### ISSUE TITLE
Differente cellTemplate for each row

### ISSUE THREAD

**Issue by nssantos** [swimlane/ngx-datatable#1012]
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Today I set the cellTamplate for each column.

**Expected behavior**
I'd like to set a specific [routerLink] for each cell in specific column for each row.

**What is the motivation / use case for changing the behavior?**
Each cell for the Name column should have a cell template with different href or different [routerLink] for each row.

**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->

* **Table version:** 0.8.x
<!-- Check whether this is still an issue in the most recent table version -->

* **Angular version:** 2.0.x
<!-- Check whether this is still an issue in the most recent Angular version -->

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
<!-- All browsers where this could be reproduced -->

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by nssantos** [comment]
I covered that using the (active) callback function. There aways the mouse enter o line, I change the template href based on the row entity I'm currently on.

**Comment by wizarrc** [comment]
@nssantos I was just in the process of typing this:

you can use `let-row="row"` to get access to the entire row data like this below:
```
<ngx-datatable-column name="Name">
      <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
            Hi: <strong>{{value}}</strong>
            <a href="{{row.anyRowVariable}}">{{row.anotherRowVariable}}</a>
      </ng-template>
</ngx-datatable-column>
```

**Comment by nssantos** [comment]
@wizarrc Thank you. Your comment prevented me to use a lot of workaround to do a simple task.
Where in the docs or in demos I can see some explanation about that?

**Comment by wizarrc** [comment]
@nssantos I just looked in the actual source code [here](https://github.com/swimlane/ngx-datatable/blob/master/src/components/body/body-cell.component.ts#L180-L190). Probably should add some documentation on that. As for demo examples, just search in here `ngx-datatable-cell-template` and you should see many demo pages.

**Comment by AmrMekkawy** [comment]
Also, [this example](https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/row-detail.component.ts) may help. It has more details about what @wizarrc mentioned in [his reply](https://github.com/swimlane/ngx-datatable/issues/1012#issuecomment-331902422)
