### ISSUE TITLE
I can't start it

### ISSUE THREAD

**Issue by Jesniphat** [swimlane/ngx-datatable#1013]
I run npm install @swimlane/ngx-datatable --save

**then put this I my module**
import { NgxDatatableModule } from '@swimlane/ngx-datatable'
**and**
imports: [
    BrowserModule,
    FormsModule,
    NgxDatatableModule
],....

**It error like this I terminal**

ERROR in /home/jesse/Projects/ang-php/node_modules/@swimlane/ngx-datatable/release/types/sort-direction.type.d.ts (2,11): In ambient enum declarations member initializer must be constant expression.
[0] /home/jesse/Projects/ang-php/node_modules/@swimlane/ngx-datatable/release/types/sort-direction.type.d.ts (3,12): In ambient enum declarations member initializer must be constant expression.

* **Table version:** "@swimlane/ngx-datatable": "^10.2.3"

* **Angular version:** 4.4.3

* **Browser:** [Chrome  ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
TypeScript version is out of date.
