### ISSUE TITLE
Error with aot build

### ISSUE THREAD

**Issue by bokzor** [swimlane/ngx-datatable#1025]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I'm using ngx-datatable in a library.
This library is used in another project. During the build I have this error :
ERROR in TypeError: Cannot read property 'provide' of undefined.
at @angular\compiler-cli\src\ngtools_impl.js:150:14

**Expected behavior**

**Reproduction of the problem**
I'm using ng-packagr to build & pack angular library.
I noticed that this bug happens when 'providers' is used in datatable.module
If the provider is set at the component level, the error disappears

**What is the motivation / use case for changing the behavior?**
Remove the error for aot build.

**Please tell us about your environment:**

* **Table version:** 0.8.x
Tried with 8 to 10

* **Angular version:** 2.0.x
4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
