### ISSUE TITLE
Default Sort Not Working / Not Documented

### ISSUE THREAD

**Issue by bhushangahire** [swimlane/ngx-datatable#1026]
Please refer #475 for the details

**Comment by bhushangahire** [comment]
This seems to be Fixed in 10.3.0. Thanks

**Comment by vkurakula** [comment]
<ngx-datatable-column [canAutoResize]="true" [flexGrow]="1" prop="year">
                    <ng-template let-column="column" ngx-datatable-header-template let-sort="sortFn">
                        <span (click)="sort()">{{ 'HOMEPAGE.YEAR' | translate }}</span>
                    </ng-template>
 </ngx-datatable-column>
in this sorting is working fine but  default hand symbal in not coming
