### ISSUE TITLE
Column with name "value" not working

### ISSUE THREAD

**Issue by saewave** [swimlane/ngx-datatable#1032]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
If column named "value" then render fail with error:
```ERROR Error: Cannot find a differ supporting object 'data1_1' of type 'string'. NgFor only supports binding to Iterables such as Arrays.```

**Expected behavior**
Should work as expected.

**Reproduction of the problem**
```
<ngx-datatable class="material "
            [rows]="csvRows" 
            [columns]="csvColumns"
            [columnMode]="'force'" 
            [headerHeight]="20" 
            [footerHeight]="20" 
            [rowHeight]="20" 
            [loadingIndicator]="loadingIndicator" 
            [limit]="10">
        </ngx-datatable>
```
And somewhere in component.ts:
```
    this.csvColumns.push({name: 'value'},{name: 'test2'});
    this.csvRows.push({'value': 'data1_1', 'test2': 'data1_2'});
    this.csvRows.push({'value': 'data2_1', 'test2': 'data2_2'});
```

**What is the motivation / use case for changing the behavior?**
This is bug and it's would be great if it will be fixed.

**Please tell us about your environment:**
MacOS 10.12.6

* **Table version:** 0.8.x
This worked under 7.x version but appears after update to latest (10.2.3) version

* **Angular version:** 2.0.x
4.3.6

* **Browser:** Safari 11.0

* **Language:** TypeScript 2.4.2

**Comment by wizarrc** [comment]
@saewave I can confirm it's a bug!

http://plnkr.co/edit/yxGGFka1DT3cLYyefNGy?p=preview

**Comment by QuentinFchx** [comment]
Duplicate of #993
