### ISSUE TITLE
aot build faild on ./node_modules/@swimlane/ngx-datatable/release/components/datatable.component.css

### ISSUE THREAD

**Issue by we125182** [swimlane/ngx-datatable#1042]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

webpack aot build failed

**Expected behavior**

success aot build

**Reproduction of the problem**

when project build with aot, error occurs like this:
![ngx-datatable](https://user-images.githubusercontent.com/17947588/31314737-3033ae4a-ac3b-11e7-8dd7-f488bf74212f.png)

**What is the motivation / use case for changing the behavior?**

aot build faild on ./node_modules/@swimlane/ngx-datatable/release/components/datatable.component.css

**Please tell us about your environment:**

* **Table version:** 10.2.3

* **Angular version:** 4.3.1

* **Browser:** all

* **Language:** typescript 2.4.2

**Comment by werts** [comment]
@we125182 hi,some thing new about this problem?i face the same

**Comment by alandroid** [comment]
`npm install --save-dev extract-text-webpack-plugin`
