### ISSUE TITLE
CellTemplating doesnt work on redrawing the ngx-datatable

### ISSUE THREAD

**Issue by DevanathanVS** [swimlane/ngx-datatable#1044]
**Hi , I am using cellTemplate for customize few columns of ngx-datatable, they work fine on page load. But when I re-render the data in table its not picking the custom ng-template respect to cellTemplate..**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
 I am using cellTemplate for customize few columns of ngx-datatable, they work fine on page load. But when I re-render the data in table its not picking the custom ng-template respect to cellTemplate.

**Expected behavior**
Retain the custom template on data refresh on Ajax calls also

**Reproduction of the problem**
I am using cellTemplate in my Column attributes like:
ngOnInit() {
    this.columns = [
     ................
      { name : "Supplier Name", prop : "supplierName" , sortable: false, cellTemplate : this.clickAction},
..................
    ];
  }

<ngx-datatable>
  ............................
</ngx-datatable>
 <ng-template #clickAction let-row="row" let-value="value"><span  class="ngxDataTableCellClick" (click) = "tableColClick.emit(row)">{{value}}</span></ng-template>
 on intial page load the custom template load while after the data change on my page action the formating is not getting applied.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 10.2.3

* **Angular version:** 4.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [TypeScript 2.4.3 and ES6]

**Comment by DevanathanVS** [comment]
I figured out the issue, its due to the attribute name I use is specific to ngx-datatable. I changed the name which i pass from the main component to the table component. We can close this issue

**Comment by crebuh** [comment]
@DevanathanVS 

I guess I've the same issue, what did you change to your code?
