### ISSUE TITLE
Adavnced Pie Chart CSS ISSUE

### ISSUE THREAD

**Issue by oruganti1289** [swimlane/ngx-datatable#1050]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

The Advanced Pie Chart data display has issue with font over lapping with other elements and the text is displayed incorrectly
**Expected behavior**

Display the text properly

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

IDE : IntelliJ , Apache or Node
* **Table version:** 4.2.x

* **Angular version:** 4.2.x

* **Browser:** [all | Chrome 60 | Firefox 55 | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript 2.3 | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Advanced pie?

**Comment by oruganti1289** [comment]
https://i.stack.imgur.com/hw8Km.png

As the picture shows the text is overlapping with other elements and the css modifications are not working

**Comment by wizarrc** [comment]
@oruganti1289 Is that an ngx-datatable project? I'm not following.

**Comment by marjan-georgiev** [comment]
Looks like this was opened in the wrong repository.

@oruganti1289 it looks like you are overriding the CSS. This is not a bug in ngx-charts.

**Comment by oruganti1289** [comment]
I didn't override any CSS, but you were correct on the wrong repository. I will open it on the charts repo.

thank you evryone.
