### ISSUE TITLE
Highlight search string breaks table

### ISSUE THREAD

**Issue by annabananana7** [swimlane/ngx-datatable#1059]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

I added a method to highlight a search string by adding a ```<span class="highlight">${match}</span>``` around the string, but it breaks my table. My table has the ability to filter, sort, and page from the server (all 3 functions are server-based), but this breaks it so that it does none of the above anymore.

**Expected behavior**

Table should highlight search string and still be able to update filter, page, and sort from the server.

**Reproduction of the problem**

Please find my code [here](https://github.com/annabananana7/ngx-datatable/blob/28a6d85bda272d7996dc52bb81463384eac6261f/demo/paging/paging-server.component.ts#L22). I added 2 buttons to highlight 'le' and clear the filter to demonstrate current behavior. Table breaks when trying to page.

**What is the motivation / use case for changing the behavior?**

Based on my team's business requirements.

**Please tell us about your environment:**

- Windows 10

- Webstorm 2017.2.4

- NPM 3.10.10

- Node 6.11.2

* **Table version:** 0.8.x

* **Angular version:** 4.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by hosseinGanjyar** [comment]
heyyyy...
Did u find any solution?
