### ISSUE TITLE
column is not aligned with the header when frozenRight enable

### ISSUE THREAD

**Issue by xmeng1** [swimlane/ngx-datatable#1078]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Column is not aligned with the header when frozenRight enable
```
this.actionColumn =  {
      cellTemplate: this.actionTpl,
      frozenRight: true,
      name: 'Action',
    };
```
![selection_053](https://user-images.githubusercontent.com/5753142/32059725-ea9b1656-ba64-11e7-8223-cc2f818ff408.png)

Meanwhile, some content of other column is not hidden in the right:
![selection_054](https://user-images.githubusercontent.com/5753142/32059823-21705ef2-ba65-11e7-831d-3584cfa06dd2.png)

**Expected behavior**

the column should be aligned with the header.
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

After debug for the DOM, after add margin-left: 15px for the column will fix the issue. I try to add this style to the `datatable.component.scss` under the class of `.datatable-row-right {
    z-index: 9;
  }`, but I found that it also applied to the header. So it doesn't work, so I think we need to find why it is not aligned.
**Please tell us about your environment:**

Fedora 24
Webstorm
* **Table version:** 10.3.0

"@swimlane/ngx-datatable": "^10.3.0",
* **Angular version:** 4.2.4

"@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 57.0.2987.133
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
    "typescript": "~2.4.0"

**Comment by xmeng1** [comment]
find duplicate with other keyword https://github.com/swimlane/ngx-datatable/issues/527

**Comment by HasannSola** [comment]
add to css file 

.datatable-row-group.datatable-row-right.ng-star-inserted{
    margin-left: 17px;
}
