### ISSUE TITLE
Angular and typescript version mismatch

### ISSUE THREAD

**Issue by slavede** [swimlane/ngx-datatable#1079]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Can't use latest ngx-datatable

**Expected behavior**

I would be able to use latest ngx-datatable

**Reproduction of the problem**

npm install @angular/compiler
npm instal @swimlane/ngx-datatable

**What is the motivation / use case for changing the behavior?**

Angular compiler can work with typescript <2.5.0, but swimlane is using 2.5.3 and above. If I don't have this installed I get warning:

```node_modules/@swimlane/ngx-datatable/release/types/column-mode.type.d.ts (2,16): In ambient enum declarations member initializer must be constant expression```

**Please tell us about your environment:**

Win 10
Visual Studio

* **Table version:** 0.8.x

10.3.0
* **Angular version:** 2.0.x

4.3.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

I had to revert to 10.0.5 to get it to work with latest (<5) angular

**Comment by RyanMilstead1** [comment]
I had the same issue this morning. Downgrading to 10.0.5 got past the compiler errors for me as well.

**Comment by slavede** [comment]
Any comments on this? I'm pretty much sure that this mismatch is a blocker for upgrading past 10.0.5 because you really shouldn't use newer version of typescript for angular 4.x, but you say you are supporting angular 4.x. To me, that's not support for that. It should really come down to rewriting this class to be able to use it with older version of typescript and then downgrade dependency to older typescript (that would match angular 4.x)

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
