### ISSUE TITLE
Compile the library with angular 4.x

### ISSUE THREAD

**Issue by isaacplmann** [swimlane/ngx-datatable#1102]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
ngx-datatable@10.5.0 will not compile in an app that uses angular 4.x

**Expected behavior**
ngx-datatable@10.5.0 _will_ compile in an app that uses angular 4.x or 5.x

**Proposed fix**
If you compile the library with angular 4.4.6, it will work in apps that use angular 4.x or 5.x.  Since ngx-datatable@10.5.0 is compiled with angular 5.0.0, it will not work in apps that use angular 4.x (only apps with angular 5.x).

**Comment by isaacplmann** [comment]
Maybe this should have been a comment on issue #1082 ...

**Comment by amcdnl** [comment]
You can use the previous version if you need 4x compatibility

**Comment by christophfriedrich** [comment]
> You can use the previous version if you need 4x compatibility
Yes, but if 10.5.0 introduces breaking changes so that it doesn't compile in projects that 10.4.0 was used in, that version should NOT have been 10.5.0 but 11.0.0. Semantic versioning FTW...

**Comment by amcdnl** [comment]
11.1.5 is compiled w/ 4.x so compat will work now.
