### ISSUE TITLE
No provider for ScrollbarHelper!

### ISSUE THREAD

**Issue by cedvdb** [swimlane/ngx-datatable#1124]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Just trying out a basic example:
```
<ngx-datatable
[rows]="products">
	<ngx-datatable-column name="Name">
		<ng-template let-value="name" ngx-datatable-cell-template>
			{{ value }}
		</ng-template>
	</ngx-datatable-column>
</ngx-datatable>
```

```
core.js:1350 ERROR Error: Uncaught (in promise): Error: StaticInjectorError[ScrollbarHelper]: 
  StaticInjectorError[ScrollbarHelper]: 
    NullInjectorError: No provider for ScrollbarHelper!

```

* **Table version:**  "^11.0.4"

* **Angular version:** ^5.0.0

* **Browser:** [all]

* **Language:** [~2.4.2]

**Comment by ramkrishnakuldeep** [comment]
Any update on this issue ?

**Comment by cedvdb** [comment]
@ramkrishnakuldeep sorry no, I ended up using something else as I was time constrained

**Comment by ramkrishnakuldeep** [comment]
@cedvdb Thanking you for your reply

**Comment by richfuns** [comment]
Any update on this issue? 
I got the same problem. 
Version:  19.0.0

`ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(BookModule)[ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper]: 
  NullInjectorError: No provider for ScrollbarHelper!
NullInjectorError: R3InjectorError(BookModule)[ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper]: 
  NullInjectorError: No provider for ScrollbarHelper!
    at NullInjector.get (:4200/vendor.js:77233)
    at R3Injector.get (:4200/vendor.js:77400)
    at R3Injector.get (:4200/vendor.js:77400)
    at R3Injector.get (:4200/vendor.js:77400)
    at NgModuleRef$1.get (:4200/vendor.js:91463)
    at R3Injector.get (:4200/vendor.js:77400)
    at NgModuleRef$1.get (:4200/vendor.js:91463)
    at Object.get (:4200/vendor.js:91177)
    at lookupTokenUsingModuleInjector (:4200/vendor.js:69706)
    at getOrCreateInjectable (:4200/vendor.js:69818)
    at resolvePromise (:4200/polyfills.js:10281)
    at resolvePromise (:4200/polyfills.js:10233)
    at :4200/polyfills.js:10343
    at ZoneDelegate.invokeTask (:4200/polyfills.js:9882)
    at Object.onInvokeTask (:4200/vendor.js:94699)
    at ZoneDelegate.invokeTask (:4200/polyfills.js:9881)
    at Zone.runTask (:4200/polyfills.js:9650)
    at drainMicroTaskQueue (:4200/polyfills.js:10052)`

**Comment by KirillKovzel** [comment]
Hey. Have the same error. I'm using this table in the shared component and in one place of using this shared component I have no errors, but in another (in the modal window) I'm getting this error.

**Comment by AlexSemenets** [comment]
I have a crutch solution for this case, just add ScrollbarHelper, DimensionsHelper, ColumnChangesService in providers in component with modal from  '@swimlane/ngx-datatable'

**Comment by mtenorio-cmp** [comment]
> I have a crutch solution for this case, just add ScrollbarHelper, DimensionsHelper, ColumnChangesService in providers in component with modal from '@swimlane/ngx-datatable'

Funciona 😎 y se tiene que agregar en app.module.ts

**Comment by heitorgiacomini** [comment]
> I have a crutch solution for this case, just add ScrollbarHelper, DimensionsHelper, ColumnChangesService in providers in component with modal from '@swimlane/ngx-datatable'

NullInjectorError: R3InjectorError(AuthorModule)[DatatableComponent -> DatatableComponent -> DatatableComponent -> DatatableComponent]:

**Comment by idsong** [comment]
@heitorgiacomini Did you solve this? I have the same problem

**Comment by benja-lp** [comment]
I solved it by adding the code in the app.module:

import { ScrollbarHelper, DimensionsHelper, ColumnChangesService } from '@swimlane/ngx-datatable'

@NgModule({
  declarations: [],
  imports: [],
  providers: [ScrollbarHelper, DimensionsHelper, ColumnChangesService  ]
})
