### ISSUE TITLE
Support selection type 'multi' and 'checkbox' combination

### ISSUE THREAD

**Issue by gabrielnemeth** [swimlane/ngx-datatable#1129]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Data table currently doesn't support combination of checkbox selection and multi selection.

**Expected behavior**

Support combination of selection types ```'multi'``` and ```'checkbox'```, for e.g. ```[selectionType]="'multi, checkbox'"```.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 11.0.x

* **Angular version:** 5.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by gabrielnemeth** [comment]
I figured it out, that I can combine custom checkbox column, with selection type multi.
```
    <ngx-datatable
            [rows]="rows"
            [columnMode]="'force'"
            [selected]="selected"
            [selectionType]="'multi'"
            (select)="onSelect($event)">
        <ngx-datatable-column
                [width]="30"
                [sortable]="false"
                [canAutoResize]="false"
                [draggable]="false"
                [resizeable]="false"
                [headerCheckboxable]="true"
                [checkboxable]="true">
        </ngx-datatable-column>
        <ngx-datatable-column name="Name"></ngx-datatable-column>
        <ngx-datatable-column name="Gender"></ngx-datatable-column>
        <ngx-datatable-column name="Company"></ngx-datatable-column>
    </ngx-datatable>
```

**Comment by DzmVasileusky** [comment]
For me this solution miss a header checkbox
