### ISSUE TITLE
Problem with templating.

### ISSUE THREAD

**Issue by mhosman** [swimlane/ngx-datatable#1131]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When I create a custom template for a specific column (let's say: Name), other columns just dissappear. This is a correct behaviour? When I just want to template one column and not the others, I need to specify all templates for each column anyway? 

* Problem is only happening when you first define columns in ngx-datatable: [columns]="[{name:'Name'},{name:'Email'}]" and then you want to apply a template for a specific column. The only solution i found is to remove the [coumns] from the ngx-datatable attribute and define a ngx-datatable-column for every column.

**Expected behavior**
Just change the template for a specific column.

**Reproduction of the problem**
```
<ngx-datatable
class="material"
[rows]="page.results"
[columns]="[{name:'Name'},{name:'Email'}]"
[columnMode]="'force'"
[headerHeight]="50"
[footerHeight]="50"
[rowHeight]="'auto'"
[externalPaging]="true"
[count]="page.totalResults"
[offset]="page.currentPage"
[limit]="limit"
(page)='loadPage($event)'>
<ngx-datatable-column name="Name">
    <ng-template let-value="value" ngx-datatable-cell-template>
        Hi: <strong>{{value}}</strong>
    </ng-template>
</ngx-datatable-column>
</ngx-datatable>
```

**Please tell us about your environment:**
Last ngx-datatable version with Angular 5.0.

**Comment by sekaiga** [comment]
i had same problem with you . then i find feature **TemplateRef**. it can just change the template for a specific column. you can try it.
demo: http://swimlane.github.io/ngx-datatable/#templateref

**Comment by ceoaliongroo** [comment]
I want to put all `ngx-datatable-column` in a external component and then load dynamic. With the idea to make the table content dynamic according a template.

Any idea, how to do it?
