### ISSUE TITLE
Add click event to table row

### ISSUE THREAD

**Issue by mustang666** [swimlane/ngx-datatable#1149]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
There is no option to configure a click event on row.

**Expected behavior**
Add a click event to table row with the possibility of associate a function, for example, to navigate to a detail page.

**Reproduction of the problem**
N/A

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
Ubuntu 16.04, Intellij Ultimate Idea 2017.2.5, angular-cli 1.5.0

* **Table version:** 11.1.3

* **Angular version:** 5.0.1

* **Browser:** Chrome Version 62.0.3202.94 (Official Build) (64-bit)

* **Language:** TypeScript 2.4.2

**Comment by amcdnl** [comment]
See `activate` event - https://swimlane.gitbooks.io/ngx-datatable/content/api/table/outputs.html#activate

**Comment by sharkoman** [comment]
very bad documentation not helping at all

**Comment by jebraieili** [comment]
very very bad documentation, not useful

**Comment by rupeshagl** [comment]
Very poor Documentation

**Comment by karansharma27** [comment]
Just use (activate)="onClick($event) property on ngx-datatable tag.

**Comment by Moulde** [comment]
This seems to change the text in the bottom of the table.
So instead of

    3 total

It will say

    1 selected / 3 total

**Comment by Parthan-Sachin** [comment]
@karansharma27 thankyou its completely working, both my 'select' and 'activate' attributes is working fine.

**Comment by NimishDavid** [comment]
How do I change the mouse pointer to a hand symbol on hovering a row?

**Comment by sansantosh** [comment]
activate is a bad choice to get the click event on a row. Use select instead. Event listening to activate will fire multiple time when you hover any row.

`(select)="onRowClicked()"`
