### ISSUE TITLE
Feature Request: Summary Row

### ISSUE THREAD

**Issue by Tempus35** [swimlane/ngx-datatable#115]
Another request:

The ability to have a row that is either in the footer or just pinned above the footer and after the body that can be hold templates like a normal row. The use case here is to allow a summary of numerical data in a column that will always be on the screen no matter the page.

**Comment by Tempus35** [comment]
A visual of this can be found here: [http://imgur.com/a/2VziI](http://imgur.com/a/2VziI).

**Comment by amcdnl** [comment]
Like this: http://demos.telerik.com/kendo-ui/grid/aggregates

**Comment by Tempus35** [comment]
Basically, would be nice of I could use a template ref in the cells in the summary row

**Comment by phillipadamson** [comment]
Hey all, I just wanted to check to see if any progress has been made on this, as this is something that would really add value to this great project.

**Comment by Tempus35** [comment]
#694

**Comment by amcdnl** [comment]
Resolved by custom footer in 8.2.0
