### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ShinDarth** [swimlane/ngx-datatable#1150]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I got many:

> ERROR TypeError: Cannot read property 'length' of undefined

and everything is broken. This happens in version `11.1.3`, but everything is fine in `11.0.4`

**Expected behavior**

should work fine

**Reproduction of the problem**
I've just updated to the latest version.

**Please tell us about your environment:**

* **Table version:**  the bug happens in 11.1.3,  but not in 11.0.4

* **Angular version:**  5.0.3

* **Browser:**  Chrome

* **Language:**  TypeScript 2.4.2

**Comment by amcdnl** [comment]
Can you provide a demo? I've saw it in the unit tests but those are passing now.

**Comment by petterhoel** [comment]
Saw same issue at work today trying to upgrade angular and datatable to latest. Hopefully I can provide a demo tomorrow or over the weekend.

**Comment by petterhoel** [comment]
@amcdnl  Did a quick test and seems it errs when initial state is an unassigned variable. This might be expected behaviour?
`  badRows: Item[]; // <- will err`
`  goodRows: Item[] = []; // <- smooth sailing`

Checked 11.1.3 & 11.1.4

**Comment by mburger81** [comment]
Yes same error for me after upgrading, it seems now `rows` property must be pre init with empty array, this wasn't before aso

**Comment by amcdnl** [comment]
Hmm...its probably cuz of all the CD bypassing I'm doing now. Just need have a default initalizer for these i suppose.

**Comment by darrenwwilliams** [comment]
Also the same error in 11.1.5 for me and no problems with 11.0.4.

**Comment by Logic-Bits** [comment]
Had the same Problem. I "npm update" and restarted VS code and it started working again. Maybe it helps somebody

**Comment by nsmithdev** [comment]
Looks like this was fixed with:
https://github.com/swimlane/ngx-datatable/commit/2739d3f3f0a19c54dd485ce51badc2b9f9262bf5

**Comment by ShinDarth** [comment]
I tried version `11.1.7` and the issue seems to be now solved
