### ISSUE TITLE
How to insert filtering in the header? 

### ISSUE THREAD

**Issue by MarineLohezic** [swimlane/ngx-datatable#1152]
I'm submitting a ...
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```
Hy, I would like to integrate the filtering input box in the header of the table. But I can't find some example. Does any one have an idea?  

**Table version:10.4.0.

 **Angular version: 4.

**Browser: all 

**Language: all

**Comment by darkurse** [comment]
Hi @MarineLohezic , you can already do this yourself by writing a custom header template. Have a look at the demos [templateref](http://swimlane.github.io/ngx-datatable/#templateref) and [inline](http://swimlane.github.io/ngx-datatable/#inline) ( If you need to customize cells as well ).
