### ISSUE TITLE
Support for Angular 4 and 5

### ISSUE THREAD

**Issue by dlabrecq** [swimlane/ngx-datatable#1153]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Currently ngx-datatable only works with Angular 5 due to how the peer dependencies are defined.

When attempting to use the latest ngx-datatable with an Angular 4 app, the build fails.

```
ERROR in Error encountered resolving symbol values statically. Could not resolve @swimlane/ngx-datatable relative to /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/app/app.module.ts., resolving symbol AppModule in /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/app/app.module.ts, resolving symbol AppModule in /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/app/app.module.ts
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src'
resolve './$$_gendir/app/app.module.ngfactory' in '/Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src'
  using description file: /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/package.json (relative path: ./src)
    using description file: /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory doesn't exist
[/Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory]
[/Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory.ts]
[/Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory.js]
[/Users/dlabrecq/Work/patternfly/repos/patternfly-ng-tests/patternfly-ng-notification/src/$$_gendir/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

```

**Expected behavior**
I would like to still use the latest ngx-datatable with an Angular 4 app, until we can upgrade to 5.

**Reproduction of the problem**
The current peer dependencies were recently changed to:

```
"peerDependencies": {
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "core-js": "^2.4.0",
    "rxjs": "^5.0.0"
  },
```

However, I believe this could be modified to still allow ngx-datatable to continue working with Angular 4 apps, as shown below. This is the same approach used by ngx-boostrap, which allows the library to be used with both Angular 4 and 5 apps -- they also have Angular 4 in their devDependencies.

```
"peerDependencies": {
    "@angular/common": ">=4.0.0 || >5.0.0",
    "@angular/compiler": ">=4.0.0 || >5.0.0",
    "@angular/core": ">=4.0.0 || >5.0.0",
    "@angular/platform-browser": ">=4.0.0 || >5.0.0",
    "@angular/platform-browser-dynamic": ">=4.0.0 || >5.0.0",
    "core-js": "^2.4.0",
    "rxjs": "^5.0.0"
  },
```

**What is the motivation / use case for changing the behavior?**
Would like to still use the latest ngx-datatable with an Angular 4 app, until we can upgrade to 5.

**Please tell us about your environment:**

* **Table version:** 0.8.x
5.0.3

* **Angular version:** 2.0.x
4.3.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by dgutride** [comment]
This would definitely help us out.

**Comment by amcdnl** [comment]
The code will work between the versions but AoT compiled code between 4 and 5 is different so changing the peer deps would not help.

We would have to make a entire different build for the 2 different versions. Is there anything specific that you can't upgrade to 5, it should be pretty seamless?

You should be able to clone the project and just change the deps to v4 and run the build and it work as a temp work around.

**Comment by dlabrecq** [comment]
It's not just the peer dependencies, but the angular deps change. We have projects that depend on our library, which cannot upgrade to Angular 5 yet. 

I have a potential solution that would not require multiple builds. This works for both Angular 4 and 5, tested with AOT. This has been implemented by ngx-boostrap and patternfly-ng.

https://github.com/swimlane/ngx-datatable/pull/1156

**Comment by elvisisking** [comment]
Our Angular 4 app wants to use ngx-datatable and would definitely like to see this fixed ASAP. Thanks.
