### ISSUE TITLE
How do we style the emptyMessage?

### ISSUE THREAD

**Issue by resting** [swimlane/ngx-datatable#1154]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

I basically need to style the empty message as `html`.
Is it possible to do it?
Using v9.3.1

**Comment by resting** [comment]
Here's how I do it for someone trying to do the same thing.

in `xx.component.ts`

```
messages = {
  emptyMessage: `
    <div>
      <img src="/pathtoimage">
      <span class="classname">No results</span>
      <p>text</p>
    </div>
  `
}
```

in `xx.component.html`

```
<ngx-datatable
 ...
 [messages]="messages"
></ngx-datatable>
```

**Comment by arturikoX** [comment]
Can we use ElementRef as emptyMessage ?

**Comment by timothylong** [comment]
@resting Your solution is helpful. However, you will run into an issue with Angular's DomSanitizer cleaning your html if you have items like a <button> element or anything that might be considered a security risk.

**Comment by julmot** [comment]
I can only agree, still looking for this.
