### ISSUE TITLE
disable sort column

### ISSUE THREAD

**Issue by nickykiet83** [swimlane/ngx-datatable#1184]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

I'm using ngx-datatable-colum

<ngx-datatable-column name="Edit" [flexGrow]="1">
        <ng-template let-row="row" let-value="value" ngx-datatable-cell-template>
          <a [routerLink]="['/admin/products/', row.$key]">Edit</a>
        </ng-template>
      </ngx-datatable-column>

**Expected behavior**

I want to disable sorting in this column? How could I do it?
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x

* **Angular version:** 5.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by uzairpm** [comment]
[sortable]="false". Ticket no longer valid. Please close.
