### ISSUE TITLE
Virtual paging demo broken

### ISSUE THREAD

**Issue by johnhamm** [swimlane/ngx-datatable#1199]
Kind of the only reason I was looking into ngx-datatable is the virtual paging, which is currently broken on your online demo page and I can't seem to get the demo working locally either.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When I click on "Paging - Virtual Server Side" demo link at https://swimlane.github.io/ngx-datatable/#virtual-paging, no rows appear and there is an error in the console:

ERROR Error: query at index -1 failed: Fenwick tree array not initialized.
    at e.query (app.js:1)
    at e.get [as scrollHeight] (app.js:1)

**Expected behavior**
I expected to see the datatable populated with rows returned from the server.

**Reproduction of the problem**
Go to https://swimlane.github.io/ngx-datatable/#virtual-paging

**What is the motivation / use case for changing the behavior?**
To make it work.

**Please tell us about your environment:**
Windows 10, Chrome

* **Table version:** 0.8.x
11.1.4

* **Angular version:** 2.0.x
Not sure what version of Angular is running on your online demo page

* **Browser:** Chrome 64.0.3282.24

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Hypercubed** [comment]
I beleive this was fixed a while back.
