### ISSUE TITLE
Pass template for columns as input property of ngx-datatable

### ISSUE THREAD

**Issue by ceoaliongroo** [swimlane/ngx-datatable#1207]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Apply template for each column only as content of `ngx-datatable` 

**Expected behavior**
Pass a templateRef of all columns  as a input property,  could be `columnTemplates` that read the content list of `DataTableColumnDirective` and recived as property.

**Reproduction of the problem**
new feature idea...

**What is the motivation / use case for changing the behavior?**
I like to make dynamic columns templates to the same table configuration.

* **Table version:** 10.4.0
* **Angular version:** 4.4.6

**Comment by cnadeau** [comment]
Isn't that what you were looking for? https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-obj.component.ts

**Comment by ceoaliongroo** [comment]
Yes, i did something similar and i used the the  `cellTemplate`property of the  `DataTableColumnDirective`

thanks
