### ISSUE TITLE
Disable table 'virtualization' and enable 'scrollbarV' make one row missing!

### ISSUE THREAD

**Issue by liwonder** [swimlane/ngx-datatable#1211]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Disable table 'virtualization' and enable 'scrollbarV' make one row missing! There will be one row missing from table than the actual data length.

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Can you make a demo to help me repo?

**Comment by hsouto** [comment]
I can confirm this behaviour. I have a rowCount of 10 (with pagesize = 10) and then I have a rowIndexes of length 9. Dunno if that is the problem - datatablebody.component on ln 528 (v 11.1.7)

**Comment by liwonder** [comment]
Sorry for that I don't have much time these days to make a demo for this issue.
But I have go through the source code it seems that it's caused  by the code below in 'body.conponent.ts':

    updateIndexes(): void {
        let first = 0;
        let last = 0;

    if (this.scrollbarV) {
      if (this.virtualization) {
        // Calculation of the first and last indexes will be based on where the
        // scrollY position would be at.  The last index would be the one
        // that shows up inside the view port the last.
        const height = parseInt(this.bodyHeight, 0);
        first = this.rowHeightsCache.getRowIndex(this.offsetY);
        last = this.rowHeightsCache.getRowIndex(height + this.offsetY) + 1;
      } else {
        // If virtual rows are not needed
        // We render all in one go
        first = 0;
        last = this.rowCount - 1;
      }
    } else {
      // The server is handling paging and will pass an array that begins with the
      // element at a specified offset.  first should always be 0 with external paging.
      if (!this.externalPaging) {
        first = Math.max(this.offset * this.pageSize, 0);
      }
      last = Math.min((first + this.pageSize), this.rowCount);
    }

    this.indexes = { first, last };
      }

'last' was assigned with 'this.rowCount - 1', this is the cause, but I am not sure why you write this line.

**Comment by joshuaharrison** [comment]
I am also having this issue. Not only is there a missing row, but the body height is calculated from the actual row count, so you end up with a white area where that last row should be.

Using above and, having changed from
`
    last = this.rowCount - 1;
`
to
`
last = this.rowCount;
`

these issues have gone away.

**Comment by akryvomaz** [comment]
Checked this solution, seems working. Created PR for this #1235

**Comment by liwonder** [comment]
@akryvomaz Thanks for your PR, I will close this issue.
