### ISSUE TITLE
Moving elements in an array

### ISSUE THREAD

**Issue by koss89** [swimlane/ngx-datatable#1213]
after update from 11.1.5 to version 11.1.7 the code with which I manually sorted the rows in the table stopped working. Ie, just the line remains in place.
Sorting carried out as follows:
`[rows]="arr"`

```
sortDown(nd: Nd) {
 let index = arr.indexOf(nd);
  if (index < arr.length - 1) {
    arr.splice(index, 1);
    index++;
    arr.splice(index, 0, nd);
  }
}
```
Actually, like the following code to change the position of an element to any position:
```
sortToIndex(element: any, index: number) {
   arr.splice(arr.indexOf(element), 1);
   arr.splice(index, 0, element);
  }
```

Ie in the data array, the changes occur but nothing changes in the table. In version 11.1.5, everything works fine when you change the position of the table changes.

**Comment by amcdnl** [comment]
You shouldn't mutate the array, you need to pass in a entirely new array with the modifications. Read this for more info: https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
