### ISSUE TITLE
TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.

### ISSUE THREAD

**Issue by arsyed04** [swimlane/ngx-datatable#1219]
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter

**Current behavior**
ERROR in node_modules/@swimlane/ngx-datatable/src/components/body/body.component.ts(406,19): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.

**Expected behavior**
No build error

**Reproduction of the problem**
ng serve or ng build

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x
11.1.5

* **Angular version:** 2.0.x
5.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.7.0-dev.20171230
ES5
Angular Cli 1.6.3

**Comment by esheleg** [comment]
Downgrade typescript to 2.6.2 solved the problem for me.
npm install typescript@2.6.2
