### ISSUE TITLE
@swimlane/ngx-datatable 11.1.7 is not working with angular 5.0.1

### ISSUE THREAD

**Issue by vjsoni** [swimlane/ngx-datatable#1230]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by gerasimovv88** [comment]
I can say nothing about an Angular 5.0.1, but @swimlane/ngx-datatable 11.1.7 pretty working without problems with an Angular ^5.0.0

**Comment by heloscream** [comment]
yes, I agree with @gerasimovv88, I have been trying Angular 4  @swimlane/ngx-datatable 11.1.7, but it doesn't work

**Comment by KyDenZ** [comment]
Same problem with Angular 5.1.0 or 5.0.0 and ngx-datatable 11.1.7. Since moving to angular 5.
I do not have rows anymore. But I have the pagination down with the page number.

**Comment by hegde5** [comment]
ngx-datatable 11.1.7 appears to be working fine with Angular 5.2.4

**Comment by petivagyok16** [comment]
Not for me. I upgraded my angular to 5.2.5 (it was released 3 hours ago) but i still cannot build a production version of my app.

Same errors as before:
<img width="1436" alt="screen shot 2018-02-14 at 9 36 30 am" src="https://user-images.githubusercontent.com/16253571/36194838-941da984-116b-11e8-8a21-69d0023d7f7b.png">

Any idea?

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
