### ISSUE TITLE
Splice item from [rows] not removing correct row 

### ISSUE THREAD

**Issue by chanm003** [swimlane/ngx-datatable#1231]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

```
 <ngx-datatable #table class="material" [rows]="filteredItems"
```
The array filteredItems contains 10 items.  If I use splice to remove element two, the ngx-datatable re-renders but it removes the bottom-most row of the table. 

**Expected behavior**

Only item two should be removed.

**Reproduction of the problem**
Upgrading to 11.1.7 introduced the issue.   Worked as expected with 11.0.4

**What is the motivation / use case for changing the behavior?**
No change.   Should exhibit same behavior as 11.0.4

**Please tell us about your environment:**

* **Table version:** 11.1.7

* **Angular version:**  5.0.0

* **Browser:** Chrome

* **Language:** TypeScript 2.6.2

**Comment by chanm003** [comment]
Looks like it might be related to #1213

**Comment by chanm003** [comment]
Closing this issue.   Fix was changing code from 
```
this.filteredItems.splice(index, 1)
```
to

```
this.filteredItems = _.reject(this.filteredItems, predicateFunc)
```

**Comment by dtarvin** [comment]
The '_.reject' only works if you are using a certain library. However, someone helped me with this. Apparently the problem is that you first have to set the array of rows to another variable and then do the slice from that variable, then reset the array of rows to the variable.

So:
deleteFilteredItem(index) {
    let temp = [...this.filteredItems];
    temp.splice(index, 1);
    this.filteredItems = temp;
}

**Comment by Kligerr** [comment]
Somehow the assigning
`let temp = [...this.filteredItems];`
**just with spread operator** is important here.
I tried it with simple assigning one array to another 
`let temp = this.filteredItems`
and it was still buggy as described above...

**Comment by mbruckner** [comment]
@Kligerr This is because using the *spread operator* that way creates a new array which gets detected using the `OnPush` change detection strategy. The array is still the same even if you temporarily assign it to a local variable.
