### ISSUE TITLE
failed to compile 

### ISSUE THREAD

**Issue by sai-murari** [swimlane/ngx-datatable#1251]
./node_modules/@swimlane/ngx-datatable/src/components/datatable.component.ts
Module build failed: Error: /home/sai/college-feedback-system/college-feedback-web/node_modules/@swimlane/ngx-datatable/src/components/datatable.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/sai/college-feedback-system/college-feedback-web/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/home/sai/college-feedback-system/college-feedback-web/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/layout/course/listcourse/listcourse.component.ts 13:28-97
 @ ./src/app/layout/course/listcourse/listcourse.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by cristianbravo** [comment]
Same issue.

**Comment by shardulP** [comment]
Same issue

**Comment by brezimenko** [comment]
Same issue

**Comment by suganyayuvaraj** [comment]
facing the same issue and couldn't compile. Any help ?
