### ISSUE TITLE
Scrollbar disappearance causes ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by kanehjeong** [swimlane/ngx-datatable#1258]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

ExpressionChangedAfterItHasBeenCheckedError is thrown on table's resize due to scrollbar disappearance

**Expected behavior**

No ExpressionChangedAfterItHasBeenCheckedError should be thrown. Exact error is:

```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '1783'. Current value: '1800'.
    at viewDebugError (core.js:9801)
    at expressionChangedAfterItHasBeenCheckedError (core.js:9779)
    at checkBindingNoChanges (core.js:9948)
    at checkNoChangesNodeDynamic (core.js:14030)
    at checkNoChangesNode (core.js:13979)
    at debugCheckNoChangesNode (core.js:14805)
    at debugCheckDirectivesFn (core.js:14707)
    at Object.eval [as updateDirectives] (DatatableComponent.html:26)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14689)
    at checkNoChangesView (core.js:13814)
```

**Reproduction of the problem**

1. Have ngx-datatable component in a view where a scrollbar exists at the highest level
2. Have scrollbar disappear (for my situation specifically, an action causes an 'overflow: hidden' to be set)
3. ExpressionChangedAfterItHasBeenCheckedError is thrown.

**What is the motivation / use case for changing the behavior?**

Removes unnecessary errors in development mode (reduce noise)

**Please tell us about your environment:**

OS: Windows 8.1 x64
IDE: Webstorm
Package manager: NPM
node 6.9.4, Angular 5.1.2, angular cli 1.6.3

* **Table version:** "^11.1.7"

* **Angular version:** "~5.1.2"

* **Browser:** Chrome (not sure about other browsers)

* **Language:** Typescript: "~2.5.3"

**Possible Fix**
I have looked into the source code and noticed it was happening due to the *_innerWidth* of the datatable.component being changed after the first detection change cycle has already fired. Not sure which exact place this is being changed as the only place I can see it is in *recalculateDims()* method which is used everywhere. 

Regardless, another tick has to happen before recalculating to notify angular of the new value. The window resizes due to the scrollbar disappearing but doesn't have the latest width. Therefore adding the below change fixes the issue:

```
/**
   * Window resize handler to update sizes.
   */
  @HostListener('window:resize')
  @throttleable(5)
  onWindowResize(): void {
    setTimeout(() => {
      this.recalculate();
    }, 0);
  }
```

**Comment by stephanecot** [comment]
Same problem here when I display a modal with click on a row.
