### ISSUE TITLE
Detail-row bug with/without ScrollbarV

### ISSUE THREAD

**Issue by petivagyok16** [swimlane/ngx-datatable#1269]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I have a problem similar to #1245. For me,  ScrollbarV causes the detail-row totally screwed up. It is tiny sometimes, sometimes just runs out from its parent boundaries. It depends on the width of the page (mobile screen or desktop).
Also having problem with pagination, because i'd like to render a paginator on the bottom of the table, but it's only possible without `[scrollbarV]`, but [in the sample app](http://swimlane.github.io/ngx-datatable/#row-details) they can be used both, but without `[scrollbarV]` details-row is buggy as we know.
<b>*UPDATE*</b>: I found out that `datatable-scroller` is bugged somehow. It has fixed `50px` width if i define my table without `[scrollbarV]="true"`.
I made a global css rule as a temporary solution. `.datatable-scroll { width: 100% !important; }`

**Expected behavior**
Enabling ScrollbarV does not make detail-row buggy, and also can be used with paginator.

**Reproduction of the problem**
![datatable-bug](https://user-images.githubusercontent.com/16253571/35624328-f990115e-068e-11e8-9560-eee31dfc692e.gif)

**What is the motivation / use case for changing the behavior?**
I want to use ngx-datatable for a responsive site that looks nice regardless of screen size.

**Please tell us about your environment:**

OSX 10.13.2, latest VSCode, npm 5.6.0, webpack, angular-cli 1.6.3.

* **Table version:** 0.8.x
11.1.7

* **Angular version:** 2.0.x
Angular 5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 63, didn't try in any other browser yet.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7, Typescript 2.6.2

**Comment by planetmalone** [comment]
Thanks! This fixes it for me.

**Comment by rikantro** [comment]
same for me, thanks @petivagyok16

**Comment by chase9** [comment]
Thank you @petivagyok16! Your width workaround worked perfectly.
