### ISSUE TITLE
 angular 5.0.0 not working with @swimlane/ngx-datatable 11.1.7 

### ISSUE THREAD

**Issue by lchittilla** [swimlane/ngx-datatable#1270]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
1.Vertical Scroll Bar does not Work.  
2. i see empty table with pagination without displaying the data.
3. Scrolling server-side does not work for me.
I think whatever i tried it dint work for me. 
 Is there are specific version i need to use. 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x
I tried with 11.1.7,11.1.4

* **Angular version:** 2.0.x
Angular 5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
2.6.1

**Comment by JoeyLi-1** [comment]
@lchittilla  In my case, this project works fine with angular 5. You just need to follow the demo and everything will work. Or at least put some code snippet, so other guys could help you.

**Comment by Matmo10** [comment]
Works fine on angular v6 beta, so it's probably works fine.

**Comment by Confusedfish** [comment]
I too am having issues having recently upgraded to 11.1.7 specifically relating to the LoadingIndicator not appearing and the table being empty when it shouldn't.

I have no problems using version 11.0.4, perhaps try that version for now?

Presumably this is related to #1230 too. If I figure out what is causing my problems then I will update this issue.
