### ISSUE TITLE
Updating [sorts] Should Trigger Sorting

### ISSUE THREAD

**Issue by rsnider19** [swimlane/ngx-datatable#1306]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
After the grid has been created, changing the value of `[sorts]` does not trigger sorting to occur.

**Expected behavior**
I would expect the grid to be sorted when `[sorts]` is updated like so:
```
<ng-template let-column="column" ngx-datatable-header-template>
    <my-header-component (sortingChange)="grid.sorts = $event">{{column.name}}</my-header-component>
</ng-template>
```

**Reproduction of the problem**
I haven't created a component for the header, but this still illustrates the problem where setting `grid.sorts` doesn't trigger sorting:
https://plnkr.co/edit/btsCZD7YJRFYIFK96X98

**What is the motivation / use case for changing the behavior?**
This would allow users to trigger sorting without needing to use `let-sort="sortFn"`

**Please tell us about your environment:**
Windows 7, Webstorm 2017.2.5, NPM, angular-cli

* **Table version:** 0.8.x
11.0.4

* **Angular version:** 2.0.x
5.2.4

* **Browser:** [**all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [**all** | TypeScript 2.5.3 | ES6/7 | ES5]

**Comment by eagor** [comment]
why is this closed?
is there a way to change table sorting programmatically?

**Comment by Asharma86** [comment]
@eagor - were you able to find a way to initiate sorting programmatically?

**Comment by eagor** [comment]
No

**Comment by Croissong** [comment]
Could this please be reopened?

**Comment by kg-neoteric** [comment]
I've just encountered the same problem. Would be nice to trigger it programmatically. Please reopen issue

**Comment by Telarin** [comment]
Was there ever a reason given as to why this was closed without a response? This seems like a pretty significant bug to me. At the very least, it would be nice to have some kind of applySort method we could call to update the table sorting after setting the sorts property programatically.
