### ISSUE TITLE
Can't select row because of padding

### ISSUE THREAD

**Issue by vink1987** [swimlane/ngx-datatable#1309]
I have a ngx datatable with [selectionType]="'single'" option. The rows have padding of 0.75rem which causes an issue. When I click on the padding area, the rows don't get selected. The rows only get selected with I click somewhere in the center of the row. Please tell me the solution or fix this if this is a bug.

Thanks.

**Comment by tommysitu** [comment]
I have the same problem too. Can anyone help?

**Comment by tommysitu** [comment]
@vineetkumar19871503, I think you can change the selection type with this input: https://swimlane.gitbooks.io/ngx-datatable/api/table/inputs.html#selectiontype 

I don't think the CSS would've changed the component's behaviour
