### ISSUE TITLE
Column bodies are misaligned after resizing columns

### ISSUE THREAD

**Issue by stewx** [swimlane/ngx-datatable#1319]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
The body of a column does not align properly after resizing the column, until you scroll horizontally. This seems to be specifically when horizontal and vertical scrolling are enabled.

**Expected behavior**

Content should be aligned properly.

**Reproduction of the problem**
The demo site shows a perfect example: https://swimlane.github.io/ngx-datatable/#horz-vert-scrolling
![screencastgif](https://user-images.githubusercontent.com/6986171/36861325-f063cc92-1d59-11e8-9381-ddb50d6f0f5e.gif)

Once you scroll horizontally, the contents will "snap" back into place where they should be.

**What is the motivation / use case for changing the behavior?**

It looks bad and is hard to read.

**Please tell us about your environment:**

N/A

* **Table version:** latest

* **Angular version:** latest

Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by stewx** [comment]
Narrowed down the offending change to df11e84f09ac0a49a8bb34b80240cfc5f70b9fcc

**Comment by stewx** [comment]
PR #1326 addresses this

**Comment by flue89** [comment]
create model: Ngx-datatable-resizer.ts

```
export class NgxDatatableResizer {

  name: string;
  grow: number;

  constructor(name: string, grow: number) {
    this.name = name;
    this.grow = grow;
  }
}

```

create helper funcion: table-resize2.ts

```
import {NgxDatatableResizer} from "../../../model/Ngx-datatable-resizer";

/**
 * @author: Mateusz Zastawny
 */

export class TableResize2 {

  private tableId: string;
  private columns: Array<NgxDatatableResizer>;
  private columnsMap = {};

  private sum: number = 0;

  constructor(tableId: string, columns: Array<NgxDatatableResizer>) {
    this.tableId = tableId;
    this.columns = columns;

    this.setMap();
  }

  private setMap(): void {
    this.columns.forEach(column => {
      this.columnsMap[column.name] = column.grow;
      this.sum = Math.round((this.sum += column.grow) * 100) / 100;
    });
  }

  public width(name: string): number {
    const maxWidth = Number(window.getComputedStyle(document.getElementById(this.tableId)).width.slice(0, -2));
    return (Math.round((((this.columnsMap[name] * 100) / this.sum) / 100) * 100) / 100) * maxWidth;
  }
}
```

use in .ts component:

```
//
public tableIdNameResizer: TableResize2 = new TableResize2('tableIdName',
    [
      new NgxDatatableResizer('name1', 0.3),
      new NgxDatatableResizer('name2', 0.4),
      new NgxDatatableResizer('name3', 0.87)
    ]);
//

```

use in .html component:

```
<ngx-datatable
        id="tableIdName"
        [columnMode]="'force'"
        >
        <ngx-datatable-column [minWidth]="30" [width]="tableIdNameResizer.width('name1')" [canAutoResize]="true" name="NAME1" prop="name1">
          <!--..-->
        </ngx-datatable-column>
        <ngx-datatable-column [minWidth]="30" [width]="tableIdNameResizer.width('name2')" [canAutoResize]="true" name="NAME2" prop="name2">
          <!--..-->
        </ngx-datatable-column>
        <!--..-->
      </ngx-datatable>
```
