### ISSUE TITLE
Buffer Items on Virtual Scroll

### ISSUE THREAD

**Issue by tskweres** [swimlane/ngx-datatable#1340]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When speed scrolling, items are white and blank before snapping into place

**Expected behavior**
Config number that defaults to 10 that puts 10 items above and below the visible view of the DOM so that there's no white space when speed scrolling

**Reproduction of the problem**
Speed scroll using virtual scrolling with a large data set, you will see lots of white space where items should be

**What is the motivation / use case for changing the behavior?**
It would be nice to not have blank items. Can we get a config number for the buffer amount of items above and below the screen?

* **Table version:** 11.x

* **Angular version:** 5.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by proguardtech** [comment]
+1

**Comment by xtianfelix** [comment]
+1

**Comment by gabrieldoty** [comment]
+1 I have a table where arrow navigation is used to traverse rows. Without a buffer of at least one row on either side, this functionality breaks :(

**Comment by Hypercubed** [comment]
For now that needs to be handled the users end.
