### ISSUE TITLE
Dialog not working after scrolling 

### ISSUE THREAD

**Issue by duyleduc** [swimlane/ngx-datatable#1348]
Bug, feature request, or proposal:
Bug

What is the expected behavior?
Page rendered correctly with passing data in parameter when clicked in a row after scrolled

What is the current behavior?
A blank page displaying after scrolled,  if I resize the windows in chrome debug console, it will be rendered.
I don't have problem if passing null value in parameter, happen only if there is an object passing in parameter.
This is the page when openned the dialog (unexpected behavior)
dialog openned
<img width="1092" alt="screen shot 2018-04-03 at 16 47 30" src="https://user-images.githubusercontent.com/6185711/38259259-dd79b108-3764-11e8-9874-12837633ad57.png">
After resizing the windows in chrome debug tool (expected behavior)
after resized
<img width="1027" alt="screen shot 2018-04-03 at 16 47 44" src="https://user-images.githubusercontent.com/6185711/38259260-dd9080fe-3764-11e8-9ac0-25ddcf732830.png">
Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0, material 5.2.2, OS: windows, mac os
Browser: Chrome

**Comment by duyleduc** [comment]
Anyone could help me please?

**Comment by duyleduc** [comment]
Issue resolved after wrapping the code of openning a dialog in zone.run()

**Comment by deeg** [comment]
If anyone is interested to use a version with scrolling running in zone, you can replace your package.json:

"@swimlane/ngx-datatable": "semanticresearch/ngx-datatable#scroll-in-zone",

The only difference from release v13 is making scrolling happen inside zone:

https://github.com/semanticresearch/ngx-datatable/commits/scroll-in-zone

**Comment by deeg** [comment]
@marjan-georgiev, I believe this should be fixed and can be closed with #1375 which was just merged.
