### ISSUE TITLE
Why does the Header disappear after reseting column array?

### ISSUE THREAD

**Issue by embryologist** [swimlane/ngx-datatable#1372]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
header disappear when resetting column array, see attached pic.
**Expected behavior**
the header should repopulate by providing column array,

**Reproduction of the problem**
by using NgRx async Pipe.

**What is the motivation / use case for changing the behavior?**
Create a dynamic and reusable Ngx-Datatable
**Please tell us about your environment:**
VSCODE, Mac OS
* **Table version:** 0.8.x
"@swimlane/ngx-datatable": "^11.2.0",

* **Angular version:** 2.0.x
"angular/cdk: 5.2.3"
"angular/cli: 1.7.3"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

I am using NgRx store to manage a search modal that has Ngx-datatable. the problem starts happening after I reset my state to the initial state. in my reducer below it happen after dispatching "CLOSE_SEARCH_MODAL" and dispatch "OPEN_SEARCH_MODAL" again. I verified that my column array is populated after I reopen my modal but yet the header is not showing.

**is it a redndering issue?**

this is my HTML markup,

```
<ngx-datatable #table class="material" [headerHeight]="50" [footerHeight]="50" [rowHeight]="'auto'" [rows]="(dbSearchStore | async).entity.data"
                                    [columns]="(dbSearchStore | async).entity.columns" [scrollbarH]="true" [limit]="2" [loadingIndicator]="(isDbSearchStoreloading | async)"
                                    [selectionType]="(dbSearchStore | async).entity.selectionType" >
                                </ngx-datatable>
```

and in my component.ts, I am using selectors to control the behavior of the data-table,

My reducers look like,

```
const initUserSearch: ISearchState = {
  isOpen: false,
  entity: {
    columns: [{ prop: null }],
    data: [],
    api: null,
    method: null,
    action: null,
    selectionType: null,
    sourcePayLoad: null,
  },
  loading: false,
  loaded: false,
  errors: null,
};

export function dbSearchReducer(
  state = initUserSearch,
  action: searchActions.UserSearchActions,
): ISearchState {
  switch (action.type) {
    case searchActions.OPEN_SEARCH_MODAL: {
      return {
        ...state,
        isOpen: true,
        loading: false,
        loaded: false,
        entity: {
          columns: action.payload.columns,
          api: action.payload.api,
          action: action.action,
          selectionType: action.payload.selectionType,
          sourcePayLoad: action.sourceAtionPayLoad,
        },
      };
    }
    case searchActions.START_SEARCH_REQUEST: {
      return {
        ...state,
        loading: true,
        loaded: false,
      };
    }
    case searchActions.FETCH_SEARCH_DATA: {
      const entity = state.entity;
      entity.data = action.payload;
      return { ...state, loading: false, loaded: true, entity: entity };
    }
    case searchActions.SEARCH_ERRORS: {
      return {
        ...state,
        loading: false,
        loaded: false,
        errors: action.payload,
      };
    }
    case searchActions.CLOSE_SEARCH_MODAL: {
      return initUserSearch;
    }

    default: {
      return state;
    }
  }
}
```

![screen shot 2018-04-15 at 01 21 06](https://user-images.githubusercontent.com/15179986/38776440-77aae050-404b-11e8-95ae-c172273e04d8.png)
![screen shot 2018-04-15 at 01 21 20](https://user-images.githubusercontent.com/15179986/38776441-7a965f2e-404b-11e8-91e5-29bf32087bee.png)

**Comment by collindutter** [comment]
@embryologist did you find a solution to this? I'm experiencing a similar problem. Thanks!

**Comment by leanribeiro** [comment]
I had the same problem
