### ISSUE TITLE
Angular 6 requires rxjs 6.1.0

### ISSUE THREAD

**Issue by Matmo10** [swimlane/ngx-datatable#1395]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Can't use Angular 6 with the datatable. The final Angular 6 is official released now.

**Expected behavior**
Should be able to use Angular 6 with the datatable.

**Reproduction of the problem**
- Follow the steps at https://update.angular.io/ to update from 5.2. to 6.0
- Once you try to run `ng update @angular/core`, you will see the following error: `Package "@swimlane/ngx-datatable" has an incompatible peer dependency to "rxjs" (requires "^5.0.0", would install "6.1.0").`

**What is the motivation / use case for changing the behavior?**
Allow usage with Angular 6

**Please tell us about your environment:**
OS X, yarn

* **Table version:** 
`"@swimlane/ngx-datatable": "^11.1.7"`

* **Angular version:**
6.0.0

**Comment by Matmo10** [comment]
Nevermind, I updated all the packages manually and got it to work.

**Comment by aog1971** [comment]
Hi, what have you updated manually?

**Comment by marjan-georgiev** [comment]
Please use ngx-datatable 12.0.0 with Angular 6.

**Comment by Matmo10** [comment]
@marjan-georgiev Does that still require `rxjs-compat`? Or have all rxjs imports been fixed?

**Comment by marjan-georgiev** [comment]
All imports have been fixed and updated to rxjs 6.1.0

**Comment by juanchofelipe** [comment]
I'm getting the same error when I run

`ng update --all`

I got:

`Package "@swimlane/ngx-datatable" has an incompatible peer dependency to "rxjs" (requires "^5.0.0", would install "6.1.0")`

Could you please explain the steps you took in order to fix it?

**Comment by Matmo10** [comment]
@juanchofelipe Try `ng update --all --force`, and then update ngx-datatable to 12.0.0 manually, or update ngx-datatable before running `ng update`

**Comment by juanchofelipe** [comment]
@Matmo10 thank you so much, after follow your instruction I was able to complete the upgrade process. However, when served the project, I got the next errors:

`ERROR in node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts(10,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.
node_modules/ng2-materialize/dist/datepicker/datepicker.directive.d.ts(6,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng2-materialize/dist/validation/error-message/error-message.component.d.ts(3,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng2-materialize/dist/validation/validation.component.d.ts(6,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng2-materialize/dist/select/select-container/select-container.component.d.ts(3,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng2-materialize/dist/input/input.directive.d.ts(9,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng2-materialize/dist/textarea/textarea.directive.d.ts(6,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/@agm/core/services/google-maps-api-wrapper.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/marker-manager.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/info-window-manager.d.ts(1,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/circle-manager.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/polygon-manager.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/polyline-manager.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/kml-layer-manager.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/data-layer-manager.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-translate/core/src/translate.loader.d.ts(1,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-translate/core/src/translate.service.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-translate/core/src/translate.directive.d.ts(2,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/common/messageservice.d.ts(1,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/messages/messages.d.ts(4,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/table/table.d.ts(8,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/table/table.d.ts(9,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/accordion/accordion.d.ts(4,10): error TS2305: Module '"C:/Ideas/Source/b2bAngular/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.`

I completed all the steps provided by the Angular Update Guide.

**Comment by Matmo10** [comment]
@juanchofelipe Make sure you have `"rxjs-compat": "^6.1.0",` somewhere in your package.json dependencies. ng-update should have added it already I think, but make sure.

**Comment by juanchofelipe** [comment]
@Matmo10 Thank you again, I had to reinstall rxjs and rxjs-compat and that fixed my problem! You rock!

**Comment by rvmladenov** [comment]
Can someone provide a list of package versions please ? ... copy/paste of the package.json will be greate. thanks

**Comment by Yogeshwar1992** [comment]
Hi ,

Did u find the solution, my versions are      
"rxjs": "^5.5.5",

    "@swimlane/ngx-datatable": "^13.0.1",

what is the compatible version for ngxdatatable for rxjsV5.5.5, i dont want to change my rxjs version.
 could u please help me out in this.

thanks :)
