### ISSUE TITLE
Angular 6 Support BehaviorSubject

### ISSUE THREAD

**Issue by danielehrhardt** [swimlane/ngx-datatable#1399]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I've updated my Project to Angular 6 RC 8 and RXJS to 6.1.0 after this Upgrade i got the following Error when i run ng serve: 
```
 ERROR in node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts(10,10): error TS2305: Module '"C:/Users/daniel.ehrhardt/Desktop/assembler/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
```

**Expected behavior**
This issue this not happen

**Reproduction of the problem**
Update the Project to the latest Angular Version and try to run ng serve

**What is the motivation / use case for changing the behavior?**
For  future  Angular Support

**Please tell us about your environment:**

* **Table version:** 0.8.x
latest

* **Angular version:** 2.0.x
6 RC 8

**Comment by danielehrhardt** [comment]
A current Workaround is to install rxjs-combat

**Comment by mateothegreat** [comment]
I think he meant npm i rxjs-compat :)

**Comment by rohitgaidhane** [comment]
even after npm i rxjs-compat prb not solve
ERROR in node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
src/app/login.service.ts(5,10): error TS2305: Module '"C:/Amrata TechWork/Restaurant-Management-System/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.

**Comment by rohitgaidhane** [comment]
its work now i also need to change import to:
import { BehaviorSubject } from 'rxjs-compat/BehaviorSubject';
