### ISSUE TITLE
scrollbarv enabled only show 1 row

### ISSUE THREAD

**Issue by desertfox123** [swimlane/ngx-datatable#1405]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Enabling scrollbarv make the datatable only show 1 rows, even after setting height for the table component.

**Expected behavior**
The datatable should show all the rows within specified table height

**Reproduction of the problem**
current table setup:
```
<ngx-datatable
				class="material"
				(page)="onPage($event)"
				[scrollbarH]="'true'"
				[scrollbarV]="'true'"
				[columnMode]="'force'"
				[headerHeight]="'auto'"
				[rowHeight]="getRowHeight"
				[rows]="rows"
				[columns]="tableColumns"
				[selected]="selected"
				(activate)="onActivate($event)">
			</ngx-datatable>
```

```
getRowHeight(row) {
	return 50;
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
MacOS High Sierra, Sublime text

* **Table version:** 0.8.x
11.3.0

* **Angular version:** 2.0.x
angular 5.2.1,
angular cli 1.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 66

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.4.2

**Comment by paritosh64ce** [comment]
Update your template. Instead of `[rowHeight]="getRowHeight"`, it should be `[rowHeight]="getRowHeight()"`

Try checking this [stackblitz](https://stackblitz.com/edit/ngx-datatable-responsive-demo-qnnrxm?file=app/demo-component.ts)

**Comment by RichardWarfield** [comment]
I am having the same issue.

The proximate cause seems to be that recalculateDims in the datatable component is getting zero height from dimensionsHelper.  This causes the math in the body component to decide only one row should be shown.

This seems to occur only when I guard display of the component with ngSwitch/ngIf.  It's as if there is a race condition where sometimes recalculateDims is being called before a height is calculated for the component.  As mentioned by @desertfox123 This occurs even when the ngx-datatable has a fixed height.

**Comment by desertfox123** [comment]
Hi, i've found the issue with mine.
It turns out that i need to specify the headerHeight and cannot be set as auto.
@RichardWarfield do you also set your headerHeight as auto?

I'm closing this issue since mine is fixed now.
