### ISSUE TITLE
ngx-datatable breaks when using multiple functionalities

### ISSUE THREAD

**Issue by cassianomon** [swimlane/ngx-datatable#1415]
If you mix functionalities of this project, they stop working, if one functionality is working, another is not.

Examples: Try to use on the  ```[scrollbarV]="true"``` together with ```[summaryRow]="enableSummary"```.

Sometimes one will work, other time scrollbarV will create a pagination even if you didn't set it to appear.

@amcdnl who is taking care of the maintenance of this project? Do you guys just accept pull requests and don't check if a new functionality is affecting another?

I can't use this in production, it's a very promising repository but it's not working at all.

**Comment by amcdnl** [comment]
A reproduction demo and more specifics of what is broken would be helpful.

cc @marjan-georgiev @Hypercubed

**Comment by cassianomon** [comment]
The steps I did for making sure that it's a bug:
> Download ngx-datatable repository
> Run ```npm install``` on it
> Run ```npm start```
> Access http://localhost:9999/#virtual-scroll
> Open demo/basic/virtual.component.ts
> Add ```[summaryRow]="enableSummary"``` and ````[summaryPosition]="summaryPosition"``` ```\\true and 'bottom'```
> The position of the summary row will fix at top and there is nothing that will change it
> If I set the height of the table to use ```[scrollbarV]="true"``` it will display a horizontal scroll of 10px, no CSS on that, just a random white space at right side of the table in a brand new project.

Gonna make a brand new angular project with it and post here this week.

**Comment by marjan-georgiev** [comment]
This is captured by https://github.com/swimlane/ngx-datatable/issues/1417. Closing this in favor of that issue. Let's continue discussion there please. @SirWojtek is currently working on a fix.

**Comment by cassianomon** [comment]
I opened this issue because it's not only Summary that is breaking, have you tried using ngx-datatable with multiple functionalities? 

Gonna make the example project this week and send here.

**Comment by marjan-georgiev** [comment]
Yes, us and many others are using the datatable in production, in different configurations.

Make sure you open separate issues for each bug you find, filling the issue template and providing as much information as possible, including demos and steps for reproduction. It's easier to keep track of them that way and will save us a lot of time.

**Comment by marjan-georgiev** [comment]
Also, our demos are part of this repository. If you think a common use case is not covered there, you are welcome to submit a PR and add demo pages and tests around it.
