### ISSUE TITLE
Wrong modified row when editing using rowIndex

### ISSUE THREAD

**Issue by carmocca** [swimlane/ngx-datatable#1430]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When a column is sorted (either ascending or descending), modifying a row as [shown in the demo](https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/row-grouping.component.ts) using the row index seems to modify other rows.

**Expected behavior**
Only the correct row comment should be modified.

**Reproduction of the problem**
Load the following component (a simplified version of row-grouping):
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'row-grouping-demo',
  template: `
    <div>
      <ngx-datatable
        class='material'
        [rows]="rows"
        [rowHeight]="40">
        <ngx-datatable-column prop="id"></ngx-datatable-column>
        <ngx-datatable-column prop="comment">
          <ng-template ngx-datatable-cell-template let-rowIndex="rowIndex" let-value="value">
            <input
              (change)="updateByIdx($event, rowIndex)"
              type="text"
              [value]="value"/>
          </ng-template>
        </ngx-datatable-column>
      </ngx-datatable>
    </div>
  `
})
export class RowGroupingComponent {
  rows = [
    { id: 'A', comment: '1' },
    { id: 'B', comment: '2' },
    { id: 'C', comment: '3' }
  ];

  updateByIdx(event, rowIndex) {
    this.rows[rowIndex]['comment'] = event.target.value;
    this.rows = [...this.rows];
  }
}
```
Steps:

1. Click on the `Comment` column header to sort in ascending order.
2. Click on the comment with id `A`. Write `5` as comment and press Enter. At this point everything is working as expected and the rows will be automatically sorted. The cursor is now modifying the comment with id `B`
3. Write `1` in the comment with id `B` and press Enter. `A` will be modified instead of `B`.

**Please tell us about your environment:**
* **OS:** macOS High Sierra 10.13.3
* **Table version:** 13.0.0
* **Angular version:** 6.0.0
* **Browser:** Chrome 66

**Comment by isaacfi** [comment]
Why did you close your issue @carmocca ? Did you find a solution? The row index is not updated after sort the table.

**Comment by carmocca** [comment]
@issaacfi I closed the issue since I am no longer working on the project which made use of this library and there was no response from the devs. As a workaround, we had to update the rows attribute using a timeout, e.g:

```
setTimeout(() => {
   this.rows = [...this.rows]; // Toggle Angular detection
}, 150);
```

Which is, of course, a huge hack.

**Comment by isaacfi** [comment]
Thanx @carmocca 

I had to sort manully as the server side sort example, and with this, the row index changed to its right value.

Regards.
