### ISSUE TITLE
[headerHeight]="false" causes entire table not to render. 

### ISSUE THREAD

**Issue by denisbetsi** [swimlane/ngx-datatable#1435]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Adding [headerHeight]="false" to table definition, causes header to disappear, although documentation states to make header be invisible, must pass falsy value.

**Expected behavior**

Should make header invisible

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

MacOS, Webstorm, NPM, node.js

* **Table version:** 13.0.0

* **Angular version:** 6.0.7

* **Browser:** [Chrome Version 66.0.3359.181 (Official Build) (64-bit) ]

* **Language:** [Typescript 2.7.2, ES7]

**Comment by ronfogel** [comment]
did you try to use `[headerHeight]="0"`?
0 is also falsy.

**Comment by denisbetsi** [comment]
I am going to close the issue, after trying 0 which did work, I tried false as value and that worked. So there must of been something else on the page which collided somehow with the component. It's okay now.
