### ISSUE TITLE
Issues with Rxjs 6.0.0

### ISSUE THREAD

**Issue by ronit123321** [swimlane/ngx-datatable#1448]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Throws an error on ng serve

ERROR in node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts(10,10): error TS2305: Module '"C:/My WorkPlace/Main/robangular/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.

**Expected behavior**

build success

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Migration to Angular 6

**Please tell us about your environment:**

Windows OS, VS code

* **Table version:** 0.8.x

11.3.2

* **Angular version:** 2.0.x

6.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by danail-vasilev** [comment]
Hi Guys,
I am having the same issue. Is Angular 6 supported by the component ?
Thanks !

**Comment by marjan-georgiev** [comment]
Need to use ngx-datatable 13 with angular 6.
