### ISSUE TITLE
Many bugs (filtering, scrolling)

### ISSUE THREAD

**Issue by hosseinGanjyar** [swimlane/ngx-datatable#1455]
- [x] bug report 
- [ ] feature request
- [ ] support request 

Why huge of bugs in this library?!!!!!
I immigration from [ngx-smart-table](https://www.npmjs.com/package/ngx-smart-table) for it's bugs, But see your library has many big bugs too. Why?

My table using these features:
- [Server-side Paging](http://swimlane.github.io/ngx-datatable/#server-paging)
- [Column Toggling](http://swimlane.github.io/ngx-datatable/#toggle)
- [Single Row Selection](http://swimlane.github.io/ngx-datatable/#single-selection)

First see my code, and next I desc problems:
```
<ngx-datatable class="bootstrap" [rows]="rows" [columns]="[{name:'id'},{name:'firstName'},{name:'lastName'},{name:'username'},{name:'locationName'}]"
        [columnMode]="'force'" [headerHeight]="50" [footerHeight]="50" [rowHeight]="'auto'" [externalPaging]="true" [count]="page.totalElements"
        [offset]="page.pageNumber" [limit]="page.size" (page)='setPage($event)' [selectionType]="'single'" (select)='onSelect($event)'
        [loadingIndicator]='loadingIndicator' [scrollbarH]="true" [scrollbarV]="null">

        <ngx-datatable-column prop="{{col.name}}" [minWidth]="100" *ngFor="let col of columns">
          <ng-template let-column="column" height="100" ngx-datatable-header-template>
            <span style="height:10px">
              <b>{{col.name}}</b>
            </span>
            <br/>
            <input type='text' id="{{col.name}}" class="form-control text-center" placeholder='Filter..' #filter/>
          </ng-template>
        </ngx-datatable-column>

      </ngx-datatable> 
````
```
@ViewChildren('filter') filter: QueryList<ElementRef>;
...
ngAfterViewInit() {
    this.filter['_results'].forEach(element => {
      const clicks = fromEvent(element.nativeElement, 'keyup');
      const result = clicks.pipe(debounceTime(1000));
      result.subscribe(data => {
        // some code
      });
    });
  }
```
Now, **bugs**:

1. When user type in searchbox then double click over text or highlight text, auto clicked over first row of table ( fire **onSelect($event)** automatic)

2.  I using `key up` for **_ViewChildren_** in **_ngAfterViewInit_** for get text of typing text in searchbox, it's ok, But after toggle column ([Column Toggling](http://swimlane.github.io/ngx-datatable/#toggle)), search not working. In other word, after render template, not working `key up` for **_ViewChildren_**.

3. If user scroll down over table, data hide then show. Why? Do call pagination server?! Do using virtual server side? What happen in background? 

**For end: I don't know why this library has 2.812 stars?!**
---
**Please tell us about your environment:**

* **Table version:** 13.0.1

* **Angular version:** 5

* **Browser:** all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Sachin124** [comment]
> **100 % working for anyone**
>     **Before doing import the** 

```
import { DatatableComponent } from '@swimlane/ngx-datatable';
ViewChild(DatatableComponent) table: DatatableComponent;
```

// Typescript  
```
   updateFilter(event) {
    const val = event.target.value.toLowerCase();
    var returnData: any;
    // filter our data
    const temp = this.temp.filter(function (d) {

      if (d.yourFirstColumnName.toLowerCase().indexOf(val) !== -1 || !val) {
        returnData = d.user_name.toLowerCase().indexOf(val) !== -1 || !val;
      } else if (d.yourSecondColumnName.toLowerCase().indexOf(val) !== -1 || !val) {
        returnData = d.notes_title.toLowerCase().indexOf(val) !== -1 || !val;

      }
      return returnData;
    });

// HTML

 <input placeholder="Search Order" (keyup)='updateFilter($event)'>
```
