### ISSUE TITLE
How to change text size in column ?

### ISSUE THREAD

**Issue by Phetz** [swimlane/ngx-datatable#1500]
i need to change text size in column bigger than text in row , i try to find in document but i dont see , i think i miss something ,Thank you

**Comment by nunos7** [comment]
Are you using some theming?

**Comment by Phetz** [comment]
i use material theme of ngx-datatable

**Comment by nunos7** [comment]
You can change the text size of the header column. If you inspect the themes/material.scss file, search for .datatable-header-cell, and change the font-size.

` .datatable-header-cell {
      text-align: left;
      padding: .9rem 1.2rem;
      font-weight: 400;
      color: rgba(0,0,0,.54);
      vertical-align: bottom;
      font-size: 12px;
      font-weight: 500;`

**Comment by Phetz** [comment]
Thank you
