### ISSUE TITLE
trying to delete a row using splice  always removes the last entry from the table.

### ISSUE THREAD

**Issue by nitinkumar8553** [swimlane/ngx-datatable#1532]
I'm submitting a  bug report

**Current behavior**
trying to to delete a random row form the table using splice method but  it's the last row which is getting removed from the table view everytime.

Expected behavior
it should remove the selected row.

Code deleting the row
if(this.filteredCampaign && this.filteredCampaign.length>0){
             this.filteredCampaign.splice(rowIndex,1);
             console.log(this.filteredCampaign)
}

Browser:
Chrome 67.0

Table version:
^11.3.2

Angular version:
5.1.0-beta.0

Browser: Chrome 
Version 68.0.3440.106 

Language:TypeScript 2.6.1

**Comment by srgreen00** [comment]
If your table rows are set to filteredDataCampaign, try updating to a new object

this.filteredCampaign.splice(rowIndex,1)
this.filteredCampaign = [...this.filteredCampaign];

**Comment by nitinkumar8553** [comment]
thanks i did the same  and it  worked yesterday itself, about to close this issue.

**Comment by DrDager** [comment]
Why i need to create a new array with rows?
```JavaScript
this.rows.splice(rowIndex, 1);
this.rows = [...this.rows];
```
I wanna use just splice? This does not work because of Change detection strategy or what?

**Comment by marjan-georgiev** [comment]
Yes, you need to pass a new object in order for the change to be detected.
