### ISSUE TITLE
color

### ISSUE THREAD

**Issue by MarisolH** [swimlane/ngx-datatable#1533]
Blue Color? Really?, when I clicked my row it turn blue, but in your documentation it is gray.
https://github.com/swimlane/ngx-datatable/blob/4bcfe3f253f3c292a60edf812c2844667fcf48f9/release/themes/material.css#L25

**Comment by srgreen00** [comment]
Blue is the color that it's set to with packaged Material style class. 

for example:
      <ngx-datatable
        class="material"

There's a trick to setting your own color in the style css that's outlined in https://github.com/swimlane/ngx-datatable/issues/738

**Comment by MarisolH** [comment]
@srgreen00 thanks so much !
