### ISSUE TITLE
Virtual scroll works only with cached rows

### ISSUE THREAD

**Issue by DmitriyIvanko** [swimlane/ngx-datatable#1556]
**I'm submitting a ...**  (check one with "x")
```
First of all, should say thank you for your really helpful tool;
[ ] bug report => search github for a similar issue or PR before submitting
[ + ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Virtual scroll works only with cached rows. Cached rows keep in the array. In my case, the number of that rows can be more than 10 million. How to not cache that rows and use the virtual scroll?  

**Expected behavior**
Just works with not cached rows (like it works in server paging);

**Reproduction of the problem**
Example of current behavior virtual scroll without cached rows: http://prntscr.com/kw9q51
Repo: https://github.com/DmitriyIvanko/ngx-datatable-example/blob/master/src/app/app.component.ts

**What is the motivation / use case for changing the behavior?**
Give user ability works with virtual scroll and not cached rows. 

**Please tell us about your environment:**
"@angular/cli": "6.2.2";

* **Table version:** 
"@swimlane/ngx-datatable": "13.1.0";

* **Angular version:** 
"@angular": "6.1.7";

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
(all browsers);

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "2.9.2";

**Comment by DmitriyIvanko** [comment]
My hack solution is simulate cached rows: For example user request take: 20 rows, skip: 50 rows, total rows: 100; Create array of 'undefined' (with length 100), and replace 20 rows starts from 50-th row;

const totalRow = 100;
const skip = 50;
const take = 20;
const serverRow = [{...}] // array of row, with length = 20;

const resultList = new Array(totalRow).fill(undefined);
resultList.splice(skip, serverRow.length, ...serverRow);
I check this solution with 10 million rows and it is works really fast; Maybe this will help someone.

**Comment by Michel73** [comment]
Do you have a working example of your solution?

**Comment by konuch** [comment]
Hey @DmitriyIvanko , do you have a working example? I'm struggling with the same situation. Thanks

**Comment by HackPoint** [comment]
@Mi

> Do you have a working example of your solution?

I have the solution with reactive behaviour
