### ISSUE TITLE
TrackByProp is not doing what is expected

### ISSUE THREAD

**Issue by hsouto** [swimlane/ngx-datatable#1558]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Looking at the library's code, the trackByProp is not doing what is expected from it.
TrackByProp is used on the construction of the trackBy function for the rows collection.
As of latest code, the trackByProp is only being attached to the row Id making something like:
return `${idx}-${this.trackByProp}`.
So in terms of the angular's trackBy it's not doing what is supposed

**Expected behavior**
We could pass a function that receives a row and an index (just like the angular trackBy function) that would let us decide by which property we would track by.

**Reproduction of the problem**
This is a code feature problem - it resides on body.component.ts @ constructor on line263

**What is the motivation / use case for changing the behavior?**
With huge data sets it will improve the performance of the table

**Please tell us about your environment:**
-

* **Table version:** 
13.1.0

* **Angular version:** 
6.1.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** 
All

**Comment by bthallion** [comment]
This is an important issue for me as well, I'm injecting new rows in the middle of the rows array (it's a 'nested' table) so the index of a given row changes. Each row has multiple chart cells, and they end up re-rendering each time I expand/collapse a row. I can open up a PR with a 'trackByFn' input property if this sounds like a reasonable change.

**Comment by yy7054wyq5** [comment]
Hope fix it

**Comment by abierbaum** [comment]
Here is a PR https://github.com/swimlane/ngx-datatable/pull/1622 that seems to fix this issue.

@marjan-georgiev Any way to get this one line change merged so we can fix this major performance issue?

**Comment by marjan-georgiev** [comment]
Merged, thanks!
