### ISSUE TITLE
Cannot compile with fullTemplateTypeCheck option on

### ISSUE THREAD

**Issue by tzoratto** [swimlane/ngx-datatable#1567]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

When turning on the fullTemplateTypeCheck option in angularCompilerOptions and having ngx-datatable as a dependency, my project won't compile in prod mode
**Expected behavior**

ngx-datatable should not prevent a build with the fullTemplateTypeCheck option turned on
**Reproduction of the problem**

Add ngx-datatable as a dependency (and instantiate a datatable), turn on the fullTemplateTypeCheck option in tsconfig.app.json and try to compile in prod mode
**What is the motivation / use case for changing the behavior?**

The fullTemplateTypeCheck option is recommended as per the Angular documentation (see https://angular.io/guide/aot-compiler) and there is currently no available option to turn off this check only for dependencies (see https://github.com/angular/angular/issues/21353) 
**Please tell us about your environment:**

* **Table version:** 

ngx-datatable 13.0.1
* **Angular version:** 

Angular 6.1.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by tzoratto** [comment]
reported errors are : 

> ERROR in node_modules/@swimlane/ngx-datatable/release/components/header/header.component.d.ts.DataTableHeaderComponent.html(11,9): : Element implicitly has an 'any' type because type '{ left: {}; center: {}; right: {}; }' has no index signature.
node_modules/@swimlane/ngx-datatable/release/components/body/body-row.component.d.ts.DataTableBodyRowComponent.html(5,7): : Element implicitly has an 'any' type because type '{ left: {}; center: {}; right: {}; }' has no index signature.

**Comment by olaf89** [comment]
I am also getting this error, could you publish the patch?

**Comment by Zarepheth** [comment]
Still seeing the same problem with Angular 7.2.15 and ngx-datatable 14.0.0

**Comment by Zarepheth** [comment]
I rolled back ngx-datatable to 13.1.0, still keeping TypeScript 7.2.15.
Building with the `--aot` switch fails with the same error.
