### ISSUE TITLE
Virtual Scroll Slower on Angular 7

### ISSUE THREAD

**Issue by SeanHub** [swimlane/ngx-datatable#1589]
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior**
Upgraded to Angular 7.0.2 and ngx-datatable 14.0.0 and our tables are very slow when scrolling (virtual scroll).

**Expected behavior**
On the previous version of Angular 6.1.1 and ngx-datatable 13.1.0 the scrolling is faster.

* **Table version:** 
14.0.0

* **Angular version:** 
7.0.2

* **Browser:**
Reproducible on Chrome 70.0.3538.77

**Comment by conradolk** [comment]
I'm getting acceptable FPS with 10 rows but when I reach 30 or 50 rows, I get like 15 FPS.

This only happenes in Chrome, Firefox works perfectly.

**Comment by aijazkhan81** [comment]
Is there any fix for this? Even the latest version of chrome is unable to handle this. Firefox is blazing fast.

**Comment by edjm1971** [comment]
@SeanHub Being that you are using scrolling and an older version but newer version than I am I have a question for you.
Are you using paging?
Are your pages correct?
I've been looking on and off into an issue with version 13.1.0 where our paging is NEVER accurate. With a record count of lets say 316 and a display limit of 10 one would expect 32 pages. We would end up with 36 pages and the discrepancy grows with the increase in return record counts.

Do you have this issue, did you have this issue? How was it resolved?
I've tried on several occasions using StackOverflow but get no answers and - votes.
