### ISSUE TITLE
Overlapping columns

### ISSUE THREAD

**Issue by Abrissirba** [swimlane/ngx-datatable#160]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When a columns have a single long word, the columns overlap.
![image](https://cloud.githubusercontent.com/assets/5156241/18946253/5acd6f44-862e-11e6-84b2-86c4d2124bbb.png)

**Expected behavior**

No overlapping

**Reproduction of the problem**

insert a row with column content that is a single very long word.

**What is the motivation / use case for changing the behavior?**

The data becomes unreadable
- **Table version:** 0.7.x
  
  
  
  0.7.3
- **Angular version:** 2.0.x
  
  
  
  2.0.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  Chrome
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  Typescript 2.0.0

**Comment by amcdnl** [comment]
This is handled automatically when you turn on vertical scrolling - https://github.com/swimlane/angular2-data-table/blob/master/src/components/datatable.scss#L57

Are you using no vertical scrolling with fixed heights?

**Comment by Abrissirba** [comment]
this is the configuration I'm using
```
{
        columnMode: ColumnMode.force,
        headerHeight: 50,
        footerHeight: 50,
        rowHeight: 'auto',
        scrollbarH: true,
        limit: 25,
        columns: []
}
```

**Comment by amcdnl** [comment]
Got it! We need to add a case when the row heights are fixed that not just apply for vertical scrolling.

**Comment by mohitnbansal** [comment]
Hi Can any one provide update on this

**Comment by rahulprakashss95** [comment]
> Hi Can any one provide update on this

This solved the problem for me

`.datatable-body-cell {
        background: white;
     }`
