### ISSUE TITLE
Global default module configuration

### ISSUE THREAD

**Issue by fantoine** [swimlane/ngx-datatable#1602]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Currently, if we want to add common settings on datatables (like localization), we have to fill them on each datatable instance.

**Expected behavior**

It could be easier and more maintainable to be able to set default settings when importing the datatable module.

**Reproduction of the problem**

For instance, we often see this kind of behavior in Angular modules:

```
NgxDatatableModule.forRoot({
    messages: {
        emptyMessage: 'Aucune donnée à afficher',
        totalMessage: 'total',
    }
})
```

**What is the motivation / use case for changing the behavior?**

Well... I think it's a wrong pattern to have to duplicate same configuration on each instance.

**Please tell us about your environment:**

Ubuntu, WebStorm, NPM...

* **Table version:** 

14.0.0

* **Angular version:** 

7.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

all

**Comment by marjan-georgiev** [comment]
Merged the PR! Will be released in 15.1.0
