### ISSUE TITLE
Disabling draggable does not remove the css-class "draggable"

### ISSUE THREAD

**Issue by PerfectPixel** [swimlane/ngx-datatable#165]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Setting `draggable` to false does not remove the `draggable` class.

**Expected behavior**
Disabling `draggable` should remove the `draggable` class, otherwise the user might get the impression that it should drag, but something is not working.

**Reproduction of the problem**
Draggable-Elements receive a red background in this example.
https://plnkr.co/edit/k6Wly6fOdsR2e2UzfjW9?p=preview

**What is the motivation / use case for changing the behavior?**
The user might get the impression that it should drag, but something is not working.

**Please tell us about your environment:**
macOS Sierra
- **Table version:** 0.7.4
- **Angular version:** 2.0.1
- **Browser:** all
- **Language:** all

**Comment by amcdnl** [comment]
Is this still happening?

**Comment by PerfectPixel** [comment]
I'll check and get back to you

**Comment by amcdnl** [comment]
Resolved in latest.

**Comment by malindakpt** [comment]
I checked this with ngx-datatable v13.0.1. But still issue is there

**Comment by frankdavidcorona** [comment]
I add this configuration to the column and work for me using version 13.1.0
Column definition:
`[draggable]="false"`
Table definition:
`[reorderable]="false"`
