### ISSUE TITLE
Bar Chart with Financial Quarter

### ISSUE THREAD

**Issue by farookshaik** [swimlane/ngx-datatable#1654]
Hello,

i need to Bar Chart with Financial Quarter, i am attaching screen shot, 

Please help..
![financial](https://user-images.githubusercontent.com/42048241/53052634-d8c9f980-3464-11e9-99f4-7cc1a9508c0b.JPG)

**Comment by andreyjkee** [comment]
@farookshaik How is that related to ngx-datatable?

**Comment by farookshaik** [comment]
You mean wants the json data?

**Comment by farookshaik** [comment]
just now I was realized, I am posting ngx datatable instead of ngx charts
