### ISSUE TITLE
project maintainance (Question)

### ISSUE THREAD

**Issue by gerhardboer** [swimlane/ngx-datatable#1661]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
There are more issues & pull-requests submitted but they are not answered or merged.
Even important ones like the accessibility pull-request have been gathering dust for a while now:
https://github.com/swimlane/ngx-datatable/pull/1506
There have also been no responses to issues or pull-requests.

**Expected behavior**
I would love an update on the planned maintainability of the project, so I have an argument to create a fork and maintain the project in house.

**Reproduction of the problem**

**Comment by WillHall** [comment]
@marjan-georgiev ⬆️

**Comment by darkurse** [comment]
@gerhardboer, please share your decision on whether to create a fork on this please.

@marjan-georgiev , if you have no longer time to maintain this project please name and give someone permission to maintain it

**Comment by yy7054wyq5** [comment]
The best way is take over project.

**Comment by marjan-georgiev** [comment]
Apologies for the delay in response everyone. My focus has been on other projects recently, without much time to dedicate to ngx-datatable. I should have more time to focus on it now.

That said, we are looking for people willing to help maintain the project. If you would like to help triaging issues, reviewing PR's and collaborating on the project's roadmap, please reach out to me directly on gitter https://gitter.im/swimlane/ngx-datatable

Thank you!

**Comment by kamlesh0606** [comment]
Any plan for Angular 9 Update ?
