### ISSUE TITLE
swimlane/ngx-datatable is active ?

### ISSUE THREAD

**Issue by kamlesh0606** [swimlane/ngx-datatable#1669]
Hi,

Please share your Repository Status .

Thanks
kamlesh

**Comment by darkurse** [comment]
I was thinking exactly the same. There are so many fixes that were never addressed it is maddening.
600+ open issues , 63+ PR stale for months  !!!!!!! That's .. sad.

So yes please share your repo status so we will now if we need to move onto something else !

**Comment by dstj** [comment]
While I whole heartedly agree and await the answer, this is a duplicate of #1661

**Comment by antch** [comment]
Sad to say, but this project appears to be dead in the water.

**Comment by bleuscyther** [comment]
:) you can dm the owner on twitter if you want to be a contributor

**Comment by marjan-georgiev** [comment]
Hi all, I left a comment on: https://github.com/swimlane/ngx-datatable/issues/1669

Closing this one. Thank you!

**Comment by bleuscyther** [comment]
Thank you for this great project, you wanted to say that link i think https://github.com/swimlane/ngx-datatable/issues/1661
