### ISSUE TITLE
Please if we can have In build functionality to add context menu, it will be helpful or if its there any share the reference. many thanks

### ISSUE THREAD

**Issue by ankitsalu** [swimlane/ngx-datatable#1673]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 

* **Angular version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
We do not provide a built-in context menu, but we emit the event so you can add one outside of it. More details here:
http://swimlane.github.io/ngx-datatable/#contextmenu
