### ISSUE TITLE
Bundle size - RXJS

### ISSUE THREAD

**Issue by hugoj-goncalves** [swimlane/ngx-datatable#1678]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Whole Rxjs gets into the final bundle.

**Expected behavior**
Only used functions should be included.

**Reproduction of the problem**

Using the getting started from angular as a base.
- ng new my-app
Simply running *npm install @swimlane/ngx-datatable* and importing the module into the *app.module.ts* like this.

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { NgxDatatableModule } from '@swimlane/ngx-datatable';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxDatatableModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Bundle analyzer without @swimlane/ngx-datatable: 

![image](https://user-images.githubusercontent.com/10927715/56402412-9558f500-6233-11e9-9701-d407984d4e0f.png)

With @swimlane/ngx-datatable:

![image](https://user-images.githubusercontent.com/10927715/56402499-e537bc00-6233-11e9-9b5c-10b3471b0868.png)

**What is the motivation / use case for changing the behavior?**

Bundle size reduction.

**Please tell us about your environment:**

Windows 10
VsCode

* **Table version:** 

@swimlane/ngx-datatable version: ^14.0.0

* **Angular version:** 

Angular version: ~7.2.0

* **Browser:** [all]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by MarkPieszak** [comment]
Just ran into this myself, I'm trying to figure out why this might be happening, as the package here isn't doing any import mistakes like `from 'rxjs/rx'` to bring in the entire library, so it must be something at the _packing_-level for swimlane.

**Comment by marjan-georgiev** [comment]
Are you seeing issues with this with the latest version of ngx-datatable (16.0.2)?

**Comment by hugoj-goncalves** [comment]
No, it's working fine with 16.0.2.
