### ISSUE TITLE
Row Detail - sort icons not visible

### ISSUE THREAD

**Issue by SruthiVala** [swimlane/ngx-datatable#1689]
I have recently started using this component. For some reason sorting icons aren't visible while sorting functionality works. 

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
sort icons are hidden

**Expected behavior**
See sorting icons

**Reproduction of the problem**
N/A

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10

* **Table version:** 
14.0.0

* **Angular version:** 
v7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [ TypeScript 3.2.4]

**Comment by KingDarBoja** [comment]
Please refer to the docs for more info about row details feature:
- [Online Demo - Row Details](http://swimlane.github.io/ngx-datatable/#row-details)
- [Source Code - Row Details](https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/row-detail.component.ts)

If you have any issue, please provide a working [stackblitz](https://stackblitz.com/) project to check your code.

Cheers!
