### ISSUE TITLE
ngx-datatable

### ISSUE THREAD

**Issue by digish777** [swimlane/ngx-datatable#1692]
I want the check boxes to be pre-selected with value from database in ngx-datatable. Any solutions?

Thanks in advance.

**Comment by bleuscyther** [comment]
You can use the [selected] attribute:
```html
<ngx-datatable
          style="width: 90%"
          class="material"
          [rows]="rows"
          [columns]="columns"
          [columnMode]="'force'"
          [headerHeight]="50"
          [footerHeight]="50"
          [rowHeight]="'auto'"
          [limit]="5"
          [selected]="selected"
          [selectionType]="'checkbox'"
          [selectAllRowsOnPage]="false"
          (select)='onSelect($event)'>
</ngx-datatable>
```
Check the source code of the doc : 

- https://github.com/swimlane/ngx-datatable/blob/master/demo/selection/selection-chkbox.component.ts

- https://github.com/swimlane/ngx-datatable/blob/master/demo/selection/selection-chkbox-template.component.ts


here is the stackblitz : 
https://stackblitz.com/edit/angular-ngx-datatable-select-checkbox

Docs:

-  [checkbox](http://swimlane.github.io/ngx-datatable/#chkbox-selection)

- [customCheckBox](http://swimlane.github.io/ngx-datatable/#chkbox-selection-template)
