### ISSUE TITLE
Not possible to manage the boolean data of a row

### ISSUE THREAD

**Issue by nobady90** [swimlane/ngx-datatable#1695]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I can't manage a simple control (if it is True or False) of a boolean row to write a given string.

**Expected behavior**
If the row in question is true, write "Active".
If the row in question is false, write "Passive".

**Reproduction of the problem**
Before opening this issue I asked for help on stackoverflow but without solving ... the problem is described here: [https://stackoverflow.com/questions/56290893/ngx-datatable-how-to-handle-a-boolean-data-of-a-row](https://stackoverflow.com/questions/56290893/ngx-datatable-how-to-handle-a-boolean-data-of-a-row)

**What is the motivation / use case for changing the behavior?**
The reason is that in the table the boolean value comes out while I must be able to insert a string value (therefore only in the visibility of the table).
Surely something escapes me ...

**Please tell us about your environment:**
"node": ">= 8.9.4",
"npm": ">= 5.6.0"

* **Table version:** 
10.4.0

* **Angular version:** 
Angular 6

* **Browser:**
All

* **Language:** "
typescript": "~3.2.4"

**Comment by KingDarBoja** [comment]
Hello @nobady90, 

Looks like you aren't properly using the documentation of ngx-datatable.
As you can check at the [Inline Template](https://swimlane.github.io/ngx-datatable/#inline) / [source code](https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-dom.component.ts) section, it is pretty easy to achieve the desired behaviour as you can see below:

![code](https://user-images.githubusercontent.com/30560560/58708682-11d80b00-837e-11e9-84af-3fafe5b77bf5.png)

In my example, `rows` is the source data array and `value` is the `status` property value of each row.
Replace the `*ngIf`statements with the boolean check like as `*ngIf="value"` and `*ngIf="!value"` and that's it!

![showcase](https://user-images.githubusercontent.com/30560560/58708797-4f3c9880-837e-11e9-881b-3fcf3f33e1c6.png)

Cheers!

**Comment by nobady90** [comment]
perfect, it worked. I missed this step. thank you!
