### ISSUE TITLE
Event (select) is not triggered when using column templates

### ISSUE THREAD

**Issue by iman-norouzi** [swimlane/ngx-datatable#1698]
I'm submitting a **bug report**

The input method (select) is not triggered when we define the columns using templates after upgrading to Angular 8.0.0 and ngx-datatable 15.0.0.
Here is my table which is not triggering "onSelect" by clicking the rows:

    <ngx-datatable
        class="material"
        [rows]="rows"
        [columnMode]="'force'"
        [headerHeight]="50"
        [footerHeight]="50"
        (select)="onSelect($event)"
        [rowHeight]="'auto'">
        <ngx-datatable-column name="Name">
          <ng-template let-column="column" ngx-datatable-header-template>
            Hello
          </ng-template>
        </ngx-datatable-column>
      </ngx-datatable>

But if we define the columns using table input attribute [columns] as below it will work.

    <ngx-datatable
        class="material"
        [rows]="rows"
        [columnMode]="'force'"
        [headerHeight]="50"
        [footerHeight]="50"
        [columns]="columns"
        (select)="onSelect($event)"
        [rowHeight]="'auto'">
      </ngx-datatable>

The (select) callback should be triggered regardless of the way we define the columns.

    OS: Ubuntu 18.04.2 LTS
    Angular Version: 8.0.0
    ngx-datatable: 15.0.0

Browsers: **Chromium 73** and **Firefox 67**.

Language: TypeScript 3.4.3

**Comment by marjan-georgiev** [comment]
Try passing the `[selectionType]` input.
Example:
```
<ngx-datatable
    class="material"
    [rows]="rows"
    [columnMode]="'force'"
    [headerHeight]="50"
    [footerHeight]="50"
    (select)="onSelect($event)"
    selectionType="single"
    [rowHeight]="'auto'">
    <ngx-datatable-column name="Name">
      <ng-template let-column="column" ngx-datatable-header-template>
        Hello
      </ng-template>
    </ngx-datatable-column>
  </ngx-datatable>        
```


Available values:
```
export enum SelectionType {
  single = 'single',
  multi = 'multi',
  multiClick = 'multiClick',
  cell = 'cell',
  checkbox = 'checkbox'
}
```

**Comment by marjan-georgiev** [comment]
Closing. Please let me know if that doesn't fix it.

**Comment by iman-norouzi** [comment]
Thanks for reply. I had [selectionType]="'single'" in my code and I just didn't include It to make the example simple. Anyway doesn't make any difference having it.

    <ngx-datatable
    class="material"
    [rows]="rows"
    [columnMode]="'force'"
    [headerHeight]="50"
    [footerHeight]="50"
    [selectionType]="'single'"
    (select)="onSelect($event)"
    [rowHeight]="'auto'">
    <ngx-datatable-column name="Name">
      <ng-template let-column="column" ngx-datatable-header-template>
        Hello
      </ng-template>
    </ngx-datatable-column>
  </ngx-datatable>

**Comment by marjan-georgiev** [comment]
Are you seeing that in 15.0.1 too?

**Comment by iman-norouzi** [comment]
Unfortunately yes! 

As I was looking into online [examples](http://swimlane.github.io/ngx-datatable/), I didn't find any example having "(select)" and Column Templates at the same time.

**Comment by iman-norouzi** [comment]
Any update for this?

**Comment by davwolf91** [comment]
Only need add
<ngx-datatable-column
[headerCheckboxable] = true
[checkboxable] = "true"
>
</  ngx-datatable-column> as other column
