### ISSUE TITLE
Virtual Paging not working after upgrade to v15

### ISSUE THREAD

**Issue by NZE** [swimlane/ngx-datatable#1702]
I m submitting this issue as the virtual paging not working after upgraded to v15 

**Current behavior**
Paging not working with scrollbarV enabled 
**Expected 
Paging should work with scrollbarV enabled
**Reproduction of the problem**
set scrollbarV=true then paging stopped working
Your online demo is not working either
http://swimlane.github.io/ngx-datatable/#virtual-paging

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Win Server 2016, Angular 8, VS Code

* **Table version:** 
15.0.0
* **Angular version:** 
Angular Version 8

* **Browser:** 
All
* **Language:** 
Type script, html

**Comment by marjan-georgiev** [comment]
@NZE thanks for catching that. Created a PR: #1704

**Comment by marjan-georgiev** [comment]
Released the fix in 15.0.2

**Comment by NZE** [comment]
Thanks guys for fixing it so quickly, well done 👍
