### ISSUE TITLE
this.table is undefined

### ISSUE THREAD

**Issue by jonclawsonMeasurabl** [swimlane/ngx-datatable#1710]
Following the demo file example https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/filter.component.ts, this.table is always undefined. 

Though it is expected to be the instance of the table created by the directive.

`import { DatatableComponent } from '@swimlane/ngx-datatable/src/components/datatable.component'`

...
  `@ViewChild(DatatableComponent, { static: false }) table: DatatableComponent`

...

`someMethod () {
   console.log(this.table) // undefined
}`

**Comment by ragauskl** [comment]
Are you logging this.table after the 'ngAfterViewInit' callback? It won't be available before that as it's a ViewChild element reference

**Comment by KingDarBoja** [comment]
As @ragauskl pointed out, you probably are calling the table template reference before the `ngAfterViewInit` lifecycle hook as stated on the official [docs](https://angular.io/api/core/ViewChild#description).

**Comment by hernanBeiza** [comment]
Get the instance of your component on ngAfterViewInit

```
import { DatatableComponent } from '**@swimlane/ngx-datatable';**
@ViewChild(DatatableComponent, { static: false }) dataTable: DatatableComponent

ngAfterViewInit() {
  //In this case I need the component instance for edit the with style inside a ngmodal issue 
  this.dataTable.element.querySelector('.datatable-scroll').setAttribute('style', 'width:100%');
}
```

**Comment by jonclawsonMeasurabl** [comment]
I don't remember exactly what I did because, I abandon this plugin for a custom build, but I think I solved my problem by changing this line to 
`@ViewChild(DatatableComponent, { static: false }) table: DatatableComponent`
to
`@ViewChild('table', { static: false }) table: DatatableComponent`
