### ISSUE TITLE
ngx-datatable-cell-template is not working

### ISSUE THREAD

**Issue by CharlesYuCH** [swimlane/ngx-datatable#1717]
This is my code: 
![image](https://user-images.githubusercontent.com/48544185/60322990-70130080-99b3-11e9-8a6a-9278ab801418.png)
And this is the result of code generation:
![image](https://user-images.githubusercontent.com/48544185/60323161-de57c300-99b3-11e9-97f6-ff8a3144d5da.png)

The project is being upgraded. From AngularJS to Angular7.
"@angular/core": "7.1.0",
"@swimlane/ngx-datatable": "^15.0.2",

**Comment by CharlesYuCH** [comment]
![image](https://user-images.githubusercontent.com/48544185/60323305-4c9c8580-99b4-11e9-9667-8b962843c49a.png)

**Comment by zbubb** [comment]
According to the change log, ngx-datatable versions 15 and above are designed for Angular 8.  Have you tried using datatable version 14, which is designed for Angular 7?

**Comment by josuetex** [comment]
@zbubb I'm with angular 8.2.1 and I have the same problem.

**Comment by CharlesYuCH** [comment]
@zbubb I found that the problem was that the ngx-datatable-cell-template was not re-rendered after the data was updated. So I add a Loading, using *ngIf to determine that it's not bound to the component until it has data. Finally the problem was solved. And thanks for your help.
