### ISSUE TITLE
8.0.1 breaks AoT: datatable.component.css not found 

### ISSUE THREAD

**Issue by theodury** [swimlane/ngx-datatable#1723]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
AOT build using angular-cli fails:

ERROR in The loader "foo/node_modules/@swimlane/ngx-datatable/release/components/datatable.component.css" didn't return a string.

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 
15.0.2

* **Angular version:** 

Angular : 8.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript : 3.4.5

**Comment by veluvj** [comment]
same issue

`
ERROR in The loader "/home/veluvijay/Documents/web__app/client-frontend/src/app/app.component.css" didn't return a string.
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
`

**Comment by veluvj** [comment]
same issue

`
ERROR in The loader "/home/veluvijay/Documents/web__app/client-frontend/src/app/app.component.css" didn't return a string.
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
`

**Comment by veluvj** [comment]
I had the same issue after updating angular7 to 8. It can be resolved by changing the version of `raw-loader` to ` 1.0.0` in package.json file and run `npm install`.

```
{
    "name": "client-frontend",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
        "ng": "ng",
        "start": "ng serve --aot",
        "build": "ng build ",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^8.2.7",
        "@angular/cdk": "^8.2.0",
        "@angular/common": "^8.2.7",
        "@angular/compiler": "^8.2.7",
        "@angular/core": "^8.2.7",
        "@angular/forms": "^8.2.7",
        "@angular/http": "^7.2.15",
        "@angular/material": "^8.2.0",
        "@angular/platform-browser": "^8.2.7",
        "@angular/platform-browser-dynamic": "^8.2.7",
        "@angular/router": "^8.2.7",
         "raw-loader": "^1.0.0",
        "rimraf": "^3.0.0",
        "style-loader": "^1.0.0",
        "to-string-loader": "^1.1.5",
        "ts-node": "~8.4.1",
        "tslint": "~5.20.0",
        "typescript": "3.5.3"
    }
}

```
