### ISSUE TITLE
[selectAllRowsOnPage] is broken.

### ISSUE THREAD

**Issue by jtran2000** [swimlane/ngx-datatable#1725]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

When a table with checkbox selection has [selectAllRowsOnPage] set to true, it does not show up. The following error appears in the Chrome console:

`DatatableComponent.html:5 ERROR TypeError: Cannot read property 'indexes' of undefined
    at DatatableComponent.get [as allRowsSelected] (datatable.component.ts:684)
    at Object.eval [as updateDirectives] (DatatableComponent.html:19)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:28133)
    at checkAndUpdateView (core.js:27529)
    at callViewAction (core.js:27770)
    at execEmbeddedViewsAction (core.js:27733)
    at checkAndUpdateView (core.js:27530)
    at callViewAction (core.js:27770)
    at execComponentViewsAction (core.js:27712)
    at checkAndUpdateView (core.js:27535)`

**Expected behavior**

The expected behavior would be that the table appears as normal and clicking the master checkbox would only select the rows visible on the current page instead of every row.

**Reproduction of the problem**

This problem can be reproduced by getting the latest version of this repository, going to the demos, finding selection-chkbox.component.ts, and changing the line
`[selectAllRowsOnPage]="false"`
to
`[selectAllRowsOnPage]="true"` .

**What is the motivation / use case for changing the behavior?**

The motivation for changing this is to allow users to configure their tables with checkboxes so that  clicking the master checkbox would only select the rows visible on the current page instead of every row.

**Please tell us about your environment:**

Windows 10, Webstorm, NPM, Node and angular-cli on WSL Ubuntu

* **Table version:** 15.0.2

* **Angular version:** 8.1.0

This is  an issue on Angular 8.1.0 and version 15.0.2 of this table. This **was not** an issue on Angular 7 and version 14 of this library. Looking through the changelog, I do not see anything that explains why [selectAllRowsOnPage] would work fine in version 14 and not version 15.0.2.

* **Browser:**  Chrome 75 | Pale Moon | Microsoft Edge 42

This bug existed in Chrome 75, Pale Moon 28, and Microsoft Edge 42. I have not tested any other browsers.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
I am working in TypeScript.

**Comment by evilstiefel** [comment]
I can reproduce this issue on our web application. It seems to be related to the changes in Angular  v8 regarding @ViewChild() and the introduced static-flag.

In our case, the directive that binds allRowsSelected to the datatable throws the same error when navigating away from a page with code like

```
<ng-template ngx-datatable-header-template let-allRowsSelected="allRowsSelected" let-selectFn="selectFn">
  <span [ngClass]="allRowsSelected ? 'fa-check-square-o' : 'fa-square-o'" (click)="selectFn.apply(!allRowsSelected)" class="fa fa-lg cursor-pointer"></span>
</ng-template>
```

If I remove the binding for allRowsSelected, it works fine (sans the functionality, ofc).

**Comment by brianlee-suplari** [comment]
Managed to fix this by removing `[selectAllRowsOnPage]` input. It may not be necessary as the checkbox behavior is the same as before.

**Comment by martinmcd1** [comment]
Any update on this? Would it be worth setting the bodyComponent static flag to false for now?

**Comment by sacgrover** [comment]
@swimlanes,
 Can you please review this pull request?
