### ISSUE TITLE
ngx-datatable width issue when open in popup second time

### ISSUE THREAD

**Issue by darpansamani** [swimlane/ngx-datatable#1729]
i have ngx-datatable and when i open it from model popup first time then it will working fine but when i open it second time after close then it will broke design and set width of header and cell 0px
![datatable_error](https://user-images.githubusercontent.com/53652520/62412038-26ed4680-b61a-11e9-85e4-e2b07e10d094.jpg)
it will work properly in local but show this design issue in staging and production
when i resize browser size then it will show perfect width of ngx-datatable
please help me to solve this issue it's on urgent basis

**Comment by darpansamani** [comment]
please help me for this issue.

**Comment by KingDarBoja** [comment]
Hello @darpansamani,

Please provide a working stackblitz in order to help you with your issue. I feel like you must manually trigger the `recalculate()` method on every model popup.

**Comment by darpansamani** [comment]
> Hello @darpansamani,
> 
> Please provide a working stackblitz in order to help you with your issue. I feel like you must manually trigger the `recalculate()` method on every model popup.

Hello, @KingDarBoja  it's done by

setTimeout(() => {
          this.restraintSupervisorESPIObservationLogTable.recalculate();
          window.dispatchEvent(new Event('resize'));
        }, 250);

add settimeout with add recalculate function and call window resize event
thanks for your reply

**Comment by KingDarBoja** [comment]
@darpansamani Glad you figure it out.

Cheers!
