### ISSUE TITLE
recalculate is still not working 

### ISSUE THREAD

**Issue by sivanargana** [swimlane/ngx-datatable#1733]
I Have Sidebar when I click on toggle sidebar will collapse but ngx datatable widths not adjust.
I tried the table.recalculate() method it's working for hover  not working click  event  how to solve this issue

**Comment by KingDarBoja** [comment]
Hello @sivanargana,

Can you provide a working stackblitz demo to check your issue? Maybe there is something wrong on you layout which doesn't let you properly trigger the recalculation logic.

Cheers!

**Comment by sivanargana** [comment]
> Hello @sivanargana,
> 
> Can you provide a working stackblitz demo to check your issue? Maybe there is something wrong on you layout which doesn't let you properly trigger the recalculation logic.
> 
> Cheers!

Hi, 
I need a horizontal scroll for the table because there are so many columns load dynamically but when I click sidebar toggle table did not adjust am getting the issue with h-scroll plz check below stackblitz demo: 
https://stackblitz.com/edit/recalculate-not-working-with-h-scrolling

**Comment by KingDarBoja** [comment]
@sivanargana I noticed the error, you should trigger the data recalculation of rows (or columns) on every click by using array destructuring as stated on the official docs, [change detection section](https://swimlane.gitbook.io/ngx-datatable/change-detection).

So in your case, no need to use recalculate, instead something like this should work:
```ts
import { Component, ViewChild, OnInit } from '@angular/core';
import { DatatableComponent } from '@swimlane/ngx-datatable';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  @ViewChild('table', { static: false }) table: DatatableComponent;
  constructor() { }
  rows = [];
  sidebar = false;
  rowsData = [
    {
      name: 'Claudine Neal',
      gender: 'female',
      company: 'Sealoud',
      c1: 'female',
      c2: 'female',
      c3: 'female',
      c4: 'female',
      c5: 'female',
      c6: 'female',
      c7: 'female',
      c8: 'female',
      c9: 'female',
    },
    {
      name: 'Beryl Rice',
      gender: 'female',
      company: 'Sealoud',
      c1: 'female',
      c2: 'female',
      c3: 'female',
      c4: 'female',
      c5: 'female',
      c6: 'female',
      c7: 'female',
      c8: 'female',
      c9: 'female',
    }
  ];

  columns = [
    { name: 'Name' },
    { name: 'Gender' },
    { name: 'Company' },
    { name: 'c1' },
    { name: 'c2' },
    { name: 'c3' },
    { name: 'c4' },
    { name: 'c5' },
    { name: 'c6' },
    { name: 'c7' },
    { name: 'c8' },
    { name: 'c9' }
  ];

  ngOnInit() {
    this.recalculateData();
  }

  recalculateData() {
    this.rows = [...this.rowsData];
  }

  toggle() {
    if (this.sidebar === false) {
      this.sidebar = true;
    } else {
      this.sidebar = false;
    }
    this.recalculateData();
    //  this.table.recalculate();
  }
}
```

Cheers!

**Comment by sivanargana** [comment]
> @sivanargana I noticed the error, you should trigger the data recalculation of rows (or columns) on every click by using array destructuring as stated on the official docs, [change detection section](https://swimlane.gitbook.io/ngx-datatable/change-detection).
> 
> So in your case, no need to use recalculate, instead something like this should work:
> 
> ```ts
> import { Component, ViewChild, OnInit } from '@angular/core';
> import { DatatableComponent } from '@swimlane/ngx-datatable';
> 
> @Component({
>   selector: 'my-app',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.css']
> })
> export class AppComponent implements OnInit {
>   @ViewChild('table', { static: false }) table: DatatableComponent;
>   constructor() { }
>   rows = [];
>   sidebar = false;
>   rowsData = [
>     {
>       name: 'Claudine Neal',
>       gender: 'female',
>       company: 'Sealoud',
>       c1: 'female',
>       c2: 'female',
>       c3: 'female',
>       c4: 'female',
>       c5: 'female',
>       c6: 'female',
>       c7: 'female',
>       c8: 'female',
>       c9: 'female',
>     },
>     {
>       name: 'Beryl Rice',
>       gender: 'female',
>       company: 'Sealoud',
>       c1: 'female',
>       c2: 'female',
>       c3: 'female',
>       c4: 'female',
>       c5: 'female',
>       c6: 'female',
>       c7: 'female',
>       c8: 'female',
>       c9: 'female',
>     }
>   ];
> 
>   columns = [
>     { name: 'Name' },
>     { name: 'Gender' },
>     { name: 'Company' },
>     { name: 'c1' },
>     { name: 'c2' },
>     { name: 'c3' },
>     { name: 'c4' },
>     { name: 'c5' },
>     { name: 'c6' },
>     { name: 'c7' },
>     { name: 'c8' },
>     { name: 'c9' }
>   ];
> 
>   ngOnInit() {
>     this.recalculateData();
>   }
> 
>   recalculateData() {
>     this.rows = [...this.rowsData];
>   }
> 
>   toggle() {
>     if (this.sidebar === false) {
>       this.sidebar = true;
>     } else {
>       this.sidebar = false;
>     }
>     this.recalculateData();
>     //  this.table.recalculate();
>   }
> }
> ```
> 
> Cheers!



> @sivanargana I noticed the error, you should trigger the data recalculation of rows (or columns) on every click by using array destructuring as stated on the official docs, [change detection section](https://swimlane.gitbook.io/ngx-datatable/change-detection).
> 
> So in your case, no need to use recalculate, instead something like this should work:
> 
> ```ts
> import { Component, ViewChild, OnInit } from '@angular/core';
> import { DatatableComponent } from '@swimlane/ngx-datatable';
> 
> @Component({
>   selector: 'my-app',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.css']
> })
> export class AppComponent implements OnInit {
>   @ViewChild('table', { static: false }) table: DatatableComponent;
>   constructor() { }
>   rows = [];
>   sidebar = false;
>   rowsData = [
>     {
>       name: 'Claudine Neal',
>       gender: 'female',
>       company: 'Sealoud',
>       c1: 'female',
>       c2: 'female',
>       c3: 'female',
>       c4: 'female',
>       c5: 'female',
>       c6: 'female',
>       c7: 'female',
>       c8: 'female',
>       c9: 'female',
>     },
>     {
>       name: 'Beryl Rice',
>       gender: 'female',
>       company: 'Sealoud',
>       c1: 'female',
>       c2: 'female',
>       c3: 'female',
>       c4: 'female',
>       c5: 'female',
>       c6: 'female',
>       c7: 'female',
>       c8: 'female',
>       c9: 'female',
>     }
>   ];
> 
>   columns = [
>     { name: 'Name' },
>     { name: 'Gender' },
>     { name: 'Company' },
>     { name: 'c1' },
>     { name: 'c2' },
>     { name: 'c3' },
>     { name: 'c4' },
>     { name: 'c5' },
>     { name: 'c6' },
>     { name: 'c7' },
>     { name: 'c8' },
>     { name: 'c9' }
>   ];
> 
>   ngOnInit() {
>     this.recalculateData();
>   }
> 
>   recalculateData() {
>     this.rows = [...this.rowsData];
>   }
> 
>   toggle() {
>     if (this.sidebar === false) {
>       this.sidebar = true;
>     } else {
>       this.sidebar = false;
>     }
>     this.recalculateData();
>     //  this.table.recalculate();
>   }
> }
> ```
> 
> Cheers!

working fine as expected thank you for your response.
