### ISSUE TITLE
404 when loading .woff files when dynamically loaded using SystemJS

### ISSUE THREAD

**Issue by metallidevils** [swimlane/ngx-datatable#1735]
Hi,

I am dynamically loading the ngx-datatable from a separately hosted angular website. The javascript downloads correctly, and the css is applied. However when trying to download the .woff file, the HTTP request is to the url of the index.html, not to the URL of where the ngx-datatable is hosted. That particular application is webpack'd with a --deploy-url.

**Comment by mike-little** [comment]
I modified release/assets/icons.css and assets/icons.css locally such that each font file is referenced on it's own line beginning with src, this gets me around this issue:

src:url("fonts/data-table.eot?#iefix") format("embedded-opentype");
src:url("fonts/data-table.woff") format("woff");
src:url("fonts/data-table.ttf") format("truetype");
src:url("fonts/data-table.svg#data-table") format("svg");

This is current github version that was causing my project experience 404 errors when these files are referenced.

 src: url('fonts/data-table.eot?#iefix') format('embedded-opentype'), url('fonts/data-table.woff') format('woff'),
    url('fonts/data-table.ttf') format('truetype'), url('fonts/data-table.svg#data-table') format('svg');

**Comment by elielia** [comment]
Same here when compiling the Angular project in production mode. While locally the "woff" is found, in production I get a 404 error only for this file, in comparison to the "ttf" files which are referenced from icons.scss as well and are in the same path.

**Comment by jarodsmk** [comment]
Also been experiencing this - @Hypercubed, any advice?

**Comment by jarodsmk** [comment]
So for me, it looks like the `woff` extension & it's mimetype weren't included in my server configuration, which propagated and threw errors in my service worker on Angular 

Seems like a small 'gotcha' since all the other mimetypes are supported by default with IIS
