### ISSUE TITLE
go to last page with scrollbarV and external paging fails

### ISSUE THREAD

**Issue by georgschroeder** [swimlane/ngx-datatable#1739]
**I'm submitting a ...** 
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When virtual server-side paging is enabled (http://swimlane.github.io/ngx-datatable/#virtual-paging) jumping to the last page using the pager will not show any data.

**Expected behavior**
The last page is shown.

**Reproduction of the problem**
You can already reproduce the problem on your own demos: 
* open the demo http://swimlane.github.io/ngx-datatable/#virtual-paging (fresh load)
* in the pager click on "go to last page" (⏯)
* look at a completely white table body

**What is the motivation / use case for changing the behavior?**
People want to see the last parts of their data.

**Please tell us about your environment:**
see http://swimlane.github.io

* **Table version:** 
15.0.2

* **Angular version:** 
8.0.0

* **Browser:**
Chrome 75.0, Firefox 60.?, ...

* **Language:**
see http://swimlane.github.io

**Comment by Hypercubed** [comment]
Fix is coming.

**Comment by OmarRobinson** [comment]
Hello, what was the fix for this issue? Is there a version number we need to update to?
