### ISSUE TITLE
Failed to find '@swimlane/ngx-datatable/release/index.css'

### ISSUE THREAD

**Issue by FrancescoBorzi** [swimlane/ngx-datatable#1741]
This error happens if I try to upgrade from version `15.0.2` to version `16.0.0`

```
ERROR in ./src/assets/scss/main.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/assets/scss/main.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '@swimlane/ngx-datatable/release/index.css'
  in [
    /home/travis/build/azerothcore/Keira3/src/assets/scss
  ]
    at resolveModule.catch.catch (/home/travis/build/azerothcore/Keira3/node_modules/postcss-import/lib/resolve-id.js:35:13)
 @ ./src/assets/scss/main.scss 1:14-257
 @ multi ./src/assets/scss/main.scss
```

- Build failure: https://travis-ci.com/azerothcore/Keira3/builds/126071234#L291
- PR: https://github.com/azerothcore/Keira3/pull/100

**Comment by dstj** [comment]
I have the same issue with `material.css` file. All css seems to have disappeared from the npm package...

.css imported
```
@import '~@swimlane/ngx-datatable/release/themes/material.css';
@import '~@swimlane/ngx-datatable/release/assets/icons.css';
```

Error:
```
./src/assets/scss/style.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/style.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '@swimlane/ngx-datatable/release/themes/material.css'
```

**Comment by marjan-georgiev** [comment]
Working on a fix

**Comment by marjan-georgiev** [comment]
Released 16.0.1. The paths of the files have changed, but they should be there:

![image](https://user-images.githubusercontent.com/8687/64374527-57167380-d024-11e9-8149-f3402ef6af4a.png)

**Comment by marjan-georgiev** [comment]
@FrancescoBorzi @dstj please let me know if you're still seeing issues.

**Comment by mhadji** [comment]
i got
 ERROR in Unexpected value 'undefined' exported by the module 'NgxDatatableModule in D:/repos/Buckhead/buckhead-web-ui/ub/ClientApp/node_modules/@swimlane/ngx-datatable/swimlane-ngx-datatable.d.ts' 
after instaling 16.0.1 and correcting the paths.

**Comment by marjan-georgiev** [comment]
@mhadji that should be fixed in 16.0.2. ng-packagr doesn't like barrel imports. 
Thanks for checking these for me.

**Comment by mhadji** [comment]
16.0.2 installed and project served and built with no problem. Thanks

**Comment by marjan-georgiev** [comment]
Great, closing this in that case. If you notice anything else, please let me know by opening a new issue.

**Comment by mchesh** [comment]
Took me a while to debug this issue, but paths to styles have changes in v16,  see changelogs [here](https://github.com/swimlane/ngx-datatable/blob/master/docs/changelog.md)

**v15.x.x and before**

        "styles": [
              "./node_modules/@swimlane/ngx-datatable/release/index.css",
              "./node_modules/@swimlane/ngx-datatable/release/themes/material.css",
              "./node_modules/@swimlane/ngx-datatable/release/assets/icons.css",
              "src/styles.css"
            ],

**After v16.x.x**

      "styles": [
              "./node_modules/@swimlane/ngx-datatable/index.css",
              "./node_modules/@swimlane/ngx-datatable/themes/material.css",
              "./node_modules/@swimlane/ngx-datatable/assets/icons.css",
              "src/styles.css"
            ],

**Comment by penihel** [comment]
please, update the docs

https://swimlane.gitbook.io/ngx-datatable/themes

**Comment by benunderw** [comment]
I am running into this error using @swimlane/ngx-datatable@16.0.3
```
ERROR in Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '../../../../node_modules/@swimlane/ngx-datatable/release/index.css'
  in [
    C:\Users\bunderwood\Projects\PN\PN.Web\App\src\pn\ldr\datatable
  ]
    at resolveModule.catch.catch (C:\Users\bunderwood\Projects\PN\PN.Web\App\node_modules\postcss-import\lib\resolve-id.js:35:13)
```

**Comment by ryandmello1198** [comment]
> Took me a while to debug this issue, but paths to styles have changes in v16, see changelogs [here](https://github.com/swimlane/ngx-datatable/blob/master/docs/changelog.md)
> 
> **v15.x.x and before**
> 
> ```
>     "styles": [
>           "./node_modules/@swimlane/ngx-datatable/release/index.css",
>           "./node_modules/@swimlane/ngx-datatable/release/themes/material.css",
>           "./node_modules/@swimlane/ngx-datatable/release/assets/icons.css",
>           "src/styles.css"
>         ],
> ```
> 
> **After v16.x.x**
> 
> ```
>   "styles": [
>           "./node_modules/@swimlane/ngx-datatable/index.css",
>           "./node_modules/@swimlane/ngx-datatable/themes/material.css",
>           "./node_modules/@swimlane/ngx-datatable/assets/icons.css",
>           "src/styles.css"
>         ],
> ```

Where should I put these new paths?

**Comment by roykhoury** [comment]
> > Took me a while to debug this issue, but paths to styles have changes in v16, see changelogs [here](https://github.com/swimlane/ngx-datatable/blob/master/docs/changelog.md)
> > **v15.x.x and before**
> > ```
> >     "styles": [
> >           "./node_modules/@swimlane/ngx-datatable/release/index.css",
> >           "./node_modules/@swimlane/ngx-datatable/release/themes/material.css",
> >           "./node_modules/@swimlane/ngx-datatable/release/assets/icons.css",
> >           "src/styles.css"
> >         ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **After v16.x.x**
> > ```
> >   "styles": [
> >           "./node_modules/@swimlane/ngx-datatable/index.css",
> >           "./node_modules/@swimlane/ngx-datatable/themes/material.css",
> >           "./node_modules/@swimlane/ngx-datatable/assets/icons.css",
> >           "src/styles.css"
> >         ],
> > ```
> 
> Where should I put these new paths?

in angular.json file.

**Comment by mhadji** [comment]
As you showed them in your style.css/style.scss in app root.Maybe i
misunderstood your question.

**Comment by edthenet** [comment]
If you want to use the import statement it is also possible to convert (save) the css files as a scss file

**Comment by Mehadmushtaq** [comment]
> Took me a while to debug this issue, but paths to styles have changes in v16, see changelogs [here](https://github.com/swimlane/ngx-datatable/blob/master/docs/changelog.md)
> 
> **v15.x.x and before**
> 
> ```
>     "styles": [
>           "./node_modules/@swimlane/ngx-datatable/release/index.css",
>           "./node_modules/@swimlane/ngx-datatable/release/themes/material.css",
>           "./node_modules/@swimlane/ngx-datatable/release/assets/icons.css",
>           "src/styles.css"
>         ],
> ```
> 
> **After v16.x.x**
> 
> ```
>   "styles": [
>           "./node_modules/@swimlane/ngx-datatable/index.css",
>           "./node_modules/@swimlane/ngx-datatable/themes/material.css",
>           "./node_modules/@swimlane/ngx-datatable/assets/icons.css",
>           "src/styles.css"
>         ],
> ```

not working for me
