### ISSUE TITLE
Unexpected value 'undefined' exported by the module 'NgxDatatableModule

### ISSUE THREAD

**Issue by javico2609** [swimlane/ngx-datatable#1742]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
ERROR in Unexpected value 'undefined' exported by the module 'NgxDatatableModule in  /frontend/node_modules/@swimlane/ngx-datatable/swimlane-ngx-datatable.d.ts'

**Expected behavior**
run my application successfully

**Reproduction of the problem**
install v16.0.1

**Please tell us about your environment:**
Yarn, WebStorm, Win10 64

* **Table version:** 
16.0.1

* **Angular version:** 
8.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google Chrome
Version 76.0.3809.132 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.4.5

**Comment by marjan-georgiev** [comment]
This was caused by ng-packagr not liking barrel imports. I removed them and release 16.0.2.

Please let me know if it fixes the issue.

**Comment by javico2609** [comment]
@marjan-georgiev  
Can't bind to 'trackByProp' since it isn't a known property of 'ngx-datatable'.
If 'ngx-datatable' is an Angular component and it has 'trackByProp' input, then verify that it is part of this module

**Comment by marjan-georgiev** [comment]
@javico2609 I can't reproduce that. Can you provide more details? A stackblitz or a github repo where this can be reproduced would be useful.
