### ISSUE TITLE
error after 16.0.2 update

### ISSUE THREAD

**Issue by blondie63** [swimlane/ngx-datatable#1743]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or 

I've a working project using ngx-datatable 15.x, after update to 16.0.2 i've this error:

[ng] ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/postcss-loader/src/index.js):
[ng] Error: Failed to find '@swimlane/ngx-datatable/release/index.css'

How can i fix ?
Thanks

**Comment by marjan-georgiev** [comment]
There is no longer a `release` folder since 16.0.0.

You should update your path to 
`@swimlane/ngx-datatable/index.css`

These are the new paths:

![image](https://user-images.githubusercontent.com/8687/64449439-30b60e00-d0e0-11e9-8b07-be9b7e85bedc.png)
