### ISSUE TITLE
Tree with multiple tree columns

### ISSUE THREAD

**Issue by shuZro** [swimlane/ngx-datatable#1744]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Expected behavior**
Ability to have multiple tree columns

**What is the motivation / use case for changing the behavior?**
Different columns with different tree columns will expand datagrid tree in different ways

I have followed this example, but can't figure out if this feature already exists.
http://swimlane.github.io/ngx-datatable/#fullscreen-tree

Thanks

**Comment by shuZro** [comment]
![image](https://user-images.githubusercontent.com/5314669/64559533-8672fc00-d314-11e9-9658-e4ee1b82a690.png)
 I would like the + to be for column PONumber

**Comment by wevertoum** [comment]
same issue...
