### ISSUE TITLE
minor outdated infos on documentation (swimlane.gitbook.io/ngx-datatable)

### ISSUE THREAD

**Issue by BePo65** [swimlane/ngx-datatable#1748]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
in the documentation 2 points are not uptodate:
1) in the topic 'Theming' the import paths change in ngx-datatable V16 (https://swimlane.gitbook.io/ngx-datatable/themeing);
the information in github is correct (in ngx-datatable/docs/introduction/themes.md)

2) the topic 'Changelog' ends with V11.3.0 (https://swimlane.gitbook.io/ngx-datatable/changelog);
the information in github is uptodate (ngx-datatable/docs/changelog.md)

**Expected behavior**
I would update the information with a pullrequest, but that is gitbook.io and I dont know how to do that.

**Reproduction of the problem**
Just visible in the documentation on gitbook.io.

**What is the motivation / use case for changing the behavior?**
-

**Please tell us about your environment:**
-
* **Table version:** 
V16.0.2
* **Angular version:** 
V8.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
->

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
-

**Comment by marjan-georgiev** [comment]
The gitbook webhook was out of sync. Should be updated now. Thanks for reporting!
