### ISSUE TITLE
select items per page

### ISSUE THREAD

**Issue by GlauberF** [swimlane/ngx-datatable#1755]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Description**
I do not know if I do not know, but I would like to have in the library a select to set how many items to show in the table, example of the image below.

![Captura de Tela_selecionar área_20190925090727](https://user-images.githubusercontent.com/11314585/65600351-58c5be00-df76-11e9-9b9b-b68d9fedd93e.png)

I would like to put this select before these fields that we already have in the library

![Captura de Tela_selecionar área_20190925092524](https://user-images.githubusercontent.com/11314585/65600424-772bb980-df76-11e9-9933-f5f0fc0bd600.png)

**Comment by rodrigojrmartinez** [comment]
Hi, check this sample https://github.com/swimlane/ngx-datatable/blob/master/src/app/paging/paging-server.component.ts

With server side rendering you can pass to the component the amount of items per row, the total count of the records to show and by doing so then the pages should be configured with the proper amount. With the offset property it seems you indicate at which page you are at. 

So, when you select a different amount of items per page then you change the value of the components property binded to the datatable and re fetch the items to show. Hope it helps!
