### ISSUE TITLE
Package description on npmjs.com and documentation states "It was built for (...) Angular >=4.0.0" but actually Angular 8 is required

### ISSUE THREAD

**Issue by TobiasSchulte** [swimlane/ngx-datatable#1771]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
See title

**Expected behavior**
Description on npmjs.com and documentation should state the actually required angular version.

**Reproduction of the problem**
Have a look at [https://www.npmjs.com/package/@swimlane/ngx-datatable](https://www.npmjs.com/package/@swimlane/ngx-datatable) or [https://swimlane.gitbook.io/ngx-datatable/](https://swimlane.gitbook.io/ngx-datatable/), see that it states "It was built for (...) Angular >=4.0.0" and try using it with angular 4, 5, 6 or 7.

**What is the motivation / use case for changing the behavior?**
Help users get the correct information about the required angular version by reading the package description on npmjs.org or the documentation.

**Please tell us about your environment:**
I think this is independent of any environment.

* **Table version:** 
All versions which don't depend on something like angular 4.0.0 or higher.

* **Angular version:** 
I think this is exactly the point of this issue.

* **Browser:** [all]

* **Language:** [all]

**Comment by Hypercubed** [comment]
Will be fixed in next release.
