### ISSUE TITLE
ngx-datatable can't be garbage collected - Memory Leak

### ISSUE THREAD

**Issue by johnhwright** [swimlane/ngx-datatable#1782]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Add table with a column
```
    <ngx-datatable [rows]="data">
      <ngx-datatable-column></ngx-datatable-column>
    </ngx-datatable>
```
Parent component can no longer be garbage collected.
![ngxdatatable](https://user-images.githubusercontent.com/11820009/69277667-8190bb00-0b95-11ea-8aa5-3c37ed58cce2.PNG)

Note that just `<ngx-datatable [rows]="data"></ngx-datatable>` does actually get collected. A column **needs** to be specified.

(Also I did see #1001 but it's been two years, I feel like this should have been a higher priority)

**Expected behavior**
The table would be get garbage collected.

**Reproduction of the problem**
If it's actually this bad just open any app where you can **navigate** away from the table and see for yourself.

**What is the motivation / use case for changing the behavior?**
It's preventing our components from being cleaned up.

**Please tell us about your environment:**
--

* **Table version:** 
16.0.2

* **Angular version:** 
8.0.3

* **Browser:** Chrome | Firefox

* **Language:** TypeScript 3.7.3

**Comment by macjohnny** [comment]
@marjan-georgiev this was fixed in https://github.com/swimlane/ngx-datatable/pull/1792 and can be closed
