### ISSUE TITLE
Row-details - bug on the official example

### ISSUE THREAD

**Issue by masscrx** [swimlane/ngx-datatable#1793]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Please expand some row and try to scroll down - rows below are not visible after scroll.
https://youtu.be/CbYeAkQdChM

**Expected behavior**
Expanding row and scrolling down should not affect displaying rows below the row with details (expanded)

**Reproduction of the problem**
Please check official example at http://swimlane.github.io/ngx-datatable/#row-details

**What is the motivation / use case for changing the behavior?**
-

**Please tell us about your environment:**
Windows 10

* **Table version:** 
16.02

* **Angular version:** 
-

* **Browser:**
Chrome 78.0.3904.108

* **Language:**
-

**Comment by marjan-georgiev** [comment]
Resolved by #1799
