### ISSUE TITLE
Wrong link to source code in documentation

### ISSUE THREAD

**Issue by jakub-astrahit** [swimlane/ngx-datatable#1812]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
The link on the Client Tree page (http://swimlane.github.io/ngx-datatable/#client-tree) is linked to this page: https://github.com/swimlane/ngx-datatable/blob/master/src/app/columns/column-flex.component.ts

**Expected behavior**
The link to the source code should use the following URL:
https://github.com/swimlane/ngx-datatable/blob/master/src/app/tree/client-tree.component.ts

I think the problem is not the link itself. It's within the demo navigation - the following URL shows a Flex column example instead of the Column tree example.

**Reproduction of the problem**
See above.

**What is the motivation / use case for changing the behavior?**
Proper documentation

**Please tell us about your environment:**
N/A

* **Table version:** 
N/A

* **Angular version:** 
N/A

* **Browser:**
N/A

* **Language:** 
N/A

**Comment by Hypercubed** [comment]
Fix in next relase.. TY.
