### ISSUE TITLE
Any plan for Angular 9 Update ?

### ISSUE THREAD

**Issue by kamlesh0606** [swimlane/ngx-datatable#1824]
**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 

* **Angular version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by blondie63** [comment]
I've used until Angular 9.0.2 but with v9.0.4 KO !!

**Comment by marcio199226** [comment]
For me it's working on 9.0.5
`
Angular CLI: 9.0.5
Node: 12.16.1
OS: linux x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.5
@angular-devkit/build-angular      0.900.5
@angular-devkit/build-optimizer    0.900.5
@angular-devkit/build-webpack      0.900.5
@angular-devkit/core               9.0.5
@angular-devkit/schematics         9.0.5
@angular/cdk                       9.1.1
@angular/flex-layout               9.0.0-beta.29
@angular/http                      7.2.7
@angular/material                  9.1.1
@angular/material-moment-adapter   9.1.1
@ngtools/webpack                   9.0.5
@schematics/angular                9.0.5
@schematics/update                 0.900.5
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
`

**Comment by blondie63** [comment]
> For me it's working on 9.0.5
> 
> ```
> Angular CLI: 9.0.5
> Node: 12.16.1
> OS: linux x64
> 
> Angular: 9.0.5
> ... animations, cli, common, compiler, compiler-cli, core
> ... elements, forms, language-service, platform-browser
> ... platform-browser-dynamic, router
> Ivy Workspace: Yes
> 
> Package                            Version
> ------------------------------------------------------------
> @angular-devkit/architect          0.900.5
> @angular-devkit/build-angular      0.900.5
> @angular-devkit/build-optimizer    0.900.5
> @angular-devkit/build-webpack      0.900.5
> @angular-devkit/core               9.0.5
> @angular-devkit/schematics         9.0.5
> @angular/cdk                       9.1.1
> @angular/flex-layout               9.0.0-beta.29
> @angular/http                      7.2.7
> @angular/material                  9.1.1
> @angular/material-moment-adapter   9.1.1
> @ngtools/webpack                   9.0.5
> @schematics/angular                9.0.5
> @schematics/update                 0.900.5
> rxjs                               6.5.4
> typescript                         3.7.5
> webpack                            4.41.2
> ```

I've tried with angular 9.0.6 and it works !
There are only the same warnings:
npm WARN @swimlane/ngx-datatable@16.0.3 requires a peer of @angular/common@<9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@16.0.3 requires a peer of @angular/core@<9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@16.0.3 requires a peer of @angular/platform-browser@<9.0.0 but none is installed. You must install peer dependencies yourself.

I hope they release a new ngx-datatable.. :)

**Comment by jacobsome** [comment]
I am getting the error as below when the angular is updated to `9.0.6`. I have used latest version of swimlane/ngx-datatable, Hopefully expecting the release. 

ERROR in node_modules/ng2-completer/src/directives/ctr-row.d.ts:1:22 - error TS2724: Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ElementRef, Renderer, OnDestroy } from "@angular/core";
                       ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5701:31
    5701 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

**Comment by blondie63** [comment]
with la Angular 9.1.0 ngx-datatable KO !! many errors :(
someone know some new updated datatable ?

**Comment by KBeDevel** [comment]
For now, with Angular 9.1.0 with enableIvy = true, compiles without problems

**Comment by Hypercubed** [comment]
Yes, should work as is.  An update with explicit support for ng9 is coming.
