### ISSUE TITLE
Wrong demo source reference link 

### ISSUE THREAD

**Issue by madhuri-bhamre-003** [swimlane/ngx-datatable#1826]
The source link in paging demo 'Scrolling no virtual' is wrong. When we  click on to the 'Source', it redirect us on 'https://github.com/swimlane/ngx-datatable/blob/master/src/app/paging/paging-server.component.ts', which is not right. It should redirect us on 'https://github.com/swimlane/ngx-datatable/blob/704d9261eb72e8d439d8a63a4f6134e6878b6966/src/app/paging/paging-scrolling-novirtualization.component.ts'.
Please confirm

**Comment by Hypercubed** [comment]
TY... will be fixed in next release.
