### ISSUE TITLE
Disappearing rows when using: RowDetail with 'auto' rowHeight, virtual scrolling, vertical scrollbar

### ISSUE THREAD

**Issue by User260220** [swimlane/ngx-datatable#1831]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When using a table with vertical scrollbar, virtual scrolling and rowdetails with [rowHeight]="'auto'"
all following rows disappear when expanding a row.
When scrollbarV is set to false the issue does not occur.

Same issue was discussed in #1657. 

**Expected behavior**
When expanding a row the following rows should stay visible  and get pushed below the rowdetail.

**Reproduction of the problem**
https://stackblitz.com/edit/angular-m7dp1m

**What is the motivation / use case for changing the behavior?**
I want to implement a table with virtual scrolling and rowdetail rowHeight adjusting to its content

**Please tell us about your environment:**
see https://stackblitz.com/edit/angular-m7dp1m

* **Table version:** 
16.0.3

* **Angular version:** 
8.2.14

* **Browser:**
Chrome 80.0.3987.122 | Firefox 74.0b7

* **Language:** 
all

**Comment by Hypercubed** [comment]
Some improvements coming to the demo.
