### ISSUE TITLE
[ngSwitch] doesn't work in angular 8.1.0 and ngx-datatable 15.0.2

### ISSUE THREAD

**Issue by diogenesneves** [swimlane/ngx-datatable#1836]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
[ngSwitch] doesn't work.

**Expected behavior**
Is there any solution to this problem?

**Reproduction of the problem**

```
<ngx-datatable-column *ngFor="let column of step.columns"  [flexGrow]=column.width name="{{column.name}}" prop="{{column.prop}}" [ngSwitch]="column.prop">
                <ng-template *ngSwitchCase="'data_faturamento'" let-rowIndex="rowIndex" let-value="value" let-row="row" ngx-datatable-cell-template>
                  {{value |  date:'dd/MM/yyyy'}}
                </ng-template>
                <ng-template ngSwitchDefault let-rowIndex="rowIndex" let-value="value" let-row="row" ngx-datatable-cell-template>
                  {{value}}
                </ng-template>
              </ngx-datatable-column>
```

**Please tell us about your environment:**
Mac Os Catalina, Visual Studio Code, Google Chrome.

* **Table version:** 
    "@swimlane/ngx-datatable": "^15.0.2",

* **Angular version:** 
Angular CLI: 8.1.0
Node: 12.13.0
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.0
@angular-devkit/build-angular      0.801.0
@angular-devkit/build-optimizer    0.801.0
@angular-devkit/build-webpack      0.801.0
@angular-devkit/core               8.1.0
@angular-devkit/schematics         8.1.0
@angular/cdk                       8.0.2
@angular/flex-layout               8.0.0-beta.26
@angular/http                      7.2.15
@angular/material                  8.0.2
@angular/material-moment-adapter   8.0.2
@ngtools/webpack                   8.1.0
@schematics/angular                8.1.0
@schematics/update                 0.801.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Siedlerchr** [comment]
16.0.3 works with 8.1 

```
   <ngx-datatable-column prop="data  [flexGrow]="1">
        <ng-template let-value="value" let-cat="row.data.metaCategory" ngx-datatable-cell-template>
          <span [ngSwitch]="cat" style="opacity: .8;">
            <ion-icon *ngSwitchCase="''F'" name="x"></ion-icon>
            <ion-icon *ngSwitchCase="C'" name="x"></ion-icon>
            <ion-icon *ngSwitchCase="'E'" name="medical"></ion-icon>
            <ion-icon *ngSwitchCase="'T'" name="build"></ion-icon>
          </span>
          {{ value }}
        </ng-template>
      </ngx-datatable-column>
```
