### ISSUE TITLE
sorting- how to get updated rows order or updated rows  after sorting

### ISSUE THREAD

**Issue by satishreddykoppella** [swimlane/ngx-datatable#1843]
1. when sorting is done, the rows order and index will change.  so here i am looking to get new updated rows after completion of sorting.

2. is there any call back which gives updated rows after sorting.

**Comment by ezzabuzaid** [comment]
I'm using `externalSorting` property alongside `sort` event, perhaps it will help you!

**Comment by Smoorfy** [comment]
try 

`this.rows = [...updatedRows];`

to trigger the changeDetection of ngx-datatable

may be it can help you!

**Comment by an2ny** [comment]
i wonder if there is any update to this issue or resolution.

**Comment by an2ny** [comment]
after looking into the source code. i found this property "_internalRows" which has the updated rows after sorting. was able to use that one

**Comment by nandhuems** [comment]
<ngx-datatable  ....  #table> 
   <ngx-datatable-column>
        {{ getRowIndex(row) }}
   </ngx-datatable-column>

 @ViewChild(DatatableComponent) table: DatatableComponent;

public getGridData() {
     console.log(this.table._internalRows)
 }

I hope this helps you.
