### ISSUE TITLE
[frozenLeft]="true" is working but text is overwritten by right hand side when scroll

### ISSUE THREAD

**Issue by ankitsalu** [swimlane/ngx-datatable#1844]
[frozenLeft]="true" is working 

but when i scroll the content, the right hand side content is coming on top of left hand side content which is fixed. 
Please find attached the image showing the problem

is there a way we can prevent the overriding of the text? 

![issue](https://user-images.githubusercontent.com/9135588/77113391-2070db00-6a01-11ea-9014-00e029e7c4fd.jpg)
n scroll

**Comment by ankitsalu** [comment]
just had to setup of the background color, and it got resolved...thanks

**Comment by ankitsalu** [comment]
just had to setup of the background color, and it got resolved...thanks

**Comment by ManolisPapaspyropoulosAUEB** [comment]
just put this in your style.css file
.datatable-row-group.datatable-row-left:hover{

  background-color: #8affd9 !important;
  backface-visibility: hidden;
  cursor: pointer;
}
