### ISSUE TITLE
Gitter is dead

### ISSUE THREAD

**Issue by zentoaku** [swimlane/ngx-datatable#1901]
**I'm submitting a ...**

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

No help is being provided on gitter.

**Expected behavior**

Help being provided by Swimlane team on gitter.

**Comment by Hypercubed** [comment]
Sorry you are having issues.  We don't always have time to support all our OS projects (we do our best).  Gitter is a forum for you to ask for support from other users.
