### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by ipod1987** [swimlane/ngx-datatable#1903]
Is possible to use this fantastic library with angular 10? Can you update the library to this new version? Thanks

**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Comment by beyondtheobservableuniverse** [comment]
![image](https://user-images.githubusercontent.com/30147726/87141452-56351a80-c2a3-11ea-8f92-02ff9e87b3f1.png)

**Comment by omnibrain** [comment]
Has anyone tried using it with Angular 10? Are there any issues?

**Comment by lohgyn** [comment]
I've tried to use it with Angular 10 (recently upgraded the Angular from version 4 to 10) as well, although it will generate the warning below:

[WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of @angular/common@~9.1.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of @angular/core@~9.1.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of @angular/platform-browser@~9.1.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of rxjs@~6.5.5 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

But so far I have yet to encounter any issues (Probably my table is too simple?).

My table is similar to the link below:
https://stackblitz.com/edit/angular-ivy-6z79qy

**Comment by hypery2k** [comment]
any change to get the references PR merged?

**Comment by hruship** [comment]
Hi It would be very helpful for me and my project if this can be updated to Angular 10. With such a great options my work would be very easy.

**Comment by celvin** [comment]
Is this one related?

https://github.com/swimlane/ngx-datatable#readme

**Comment by payalord** [comment]
This is still not fixed?

**Comment by rojasjuniore** [comment]
same problem :(

**Comment by sriharibalgam** [comment]
Update **@ngx-translate/core** lib to latest version i.,e **13.0.0** can help you to fix this issue.

Also Update **@ngx-translate/http-loader** to 6.0.0 if exists in your project.

**Comment by rojasjuniore** [comment]
the following worked for me: 

`npm uninstall  @ngx-translate/core`
`npm uninstall  @ngx-translate/http-loader `

and 

`npm i @ngx-translate/core`
`npm i  @ngx-translate/http-loader`

**Comment by argelj289** [comment]
> I've tried to use it with Angular 10 (recently upgraded the Angular from version 4 to 10) as well, although it will generate the warning below:
> 
> [WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of @angular/common@~9.1.0 but none is installed. You must install peer dependencies yourself.
> [WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of @angular/core@~9.1.0 but none is installed. You must install peer dependencies yourself.
> [WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of @angular/platform-browser@~9.1.0 but none is installed. You must install peer dependencies yourself.
> [WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of rxjs@~6.5.5 but none is installed. You must install peer dependencies yourself.
> [WARNING] npm WARN @swimlane/ngx-datatable@17.1.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
> 
> But so far I have yet to encounter any issues (Probably my table is too simple?).
> 
> My table is similar to the link below:
> https://stackblitz.com/edit/angular-ivy-6z79qy

I also get this problem even I upgraded it to its latest version

**Comment by KiranShakya** [comment]
Hasn't anybody tried v18.0.0 yet?

**Comment by Siedlerchr** [comment]
@KiranShakya  v18 is working fine with Angular 10

**Comment by joeveiga** [comment]
Version 18.0.0 provides support for ng10.
