### ISSUE TITLE
Upgrade to Angular 10.0.8

### ISSUE THREAD

**Issue by ashishtilara** [swimlane/ngx-datatable#1919]
I am seeing errors like,
![image](https://user-images.githubusercontent.com/1509613/90003940-2a5ce880-dcd8-11ea-8254-d1f362948a57.png)

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Please tell us about your environment:**

MacOS

- **Table version:**

```
"@swimlane/ngx-datatable": "^17.1.0",
```

- **Angular version:**

```
"@angular/core": "~10.0.8",
```

**Comment by nsmithdev** [comment]
https://github.com/swimlane/ngx-datatable/issues/1903

**Comment by nsmithdev** [comment]
#1903

**Comment by nsmithdev** [comment]
#1914

**Comment by hruship** [comment]
@nsmithdev Any idea when the PR can be merged. I think it would help us to decide to embed this lib to our new project.

**Comment by nsmithdev** [comment]
@hruship I'm not with the project.  Was just looking up status myself and found duplicate issue not cross linked yet.

**Comment by JamesDougherty** [comment]
FYI for anyone that makes it here. 

`Version 18.0.0 provides support for ng10.` - Per last comment on #1903

**Comment by joeveiga** [comment]
#1914
