### ISSUE TITLE
ngx-datatable-row-detail: If address is an array, how to code htlm?

### ISSUE THREAD

**Issue by happy2909** [swimlane/ngx-datatable#1935]

**Comment by ivinogradov97** [comment]
Like that?
<ngx-datatable-row-detail>
    <ng-template let-row="addressRow" let-expanded="expanded" ngx-datatable-row-detail-template>
       <div class="itable-details-row" *ngFor="let rowDetail of addressRow">
           <div class="itable-details-cell">{{rowDetail.Country}}</div>
           <div class="itable-details-cell">{{rowDetail.City}}</div>
       </div>
    </ng-template>
</ngx-datatable-row-detail>
