### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by rimena1998** [swimlane/ngx-datatable#1945]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

I am trying to add a ngx datatable in my project however I can seems to add border to the table.

![Capture](https://user-images.githubusercontent.com/48293258/99236806-1661df00-2811-11eb-8f8d-acfed705aaaf.PNG)

**Expected behavior**

I want to add border to the table so that the columns can be differentiated from one another

**Please tell us about your environment:**
 windows 10, vs code , angular

- **Angular version:**
Angular CLI: 10.0.6
Node: 12.18.4
OS: win32 x64

Angular: 10.0.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1002.0
@angular-devkit/build-optimizer   0.1002.0
@angular-devkit/build-webpack     0.1002.0
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cdk                      10.1.1
@angular/cli                      10.0.6
@angular/google-maps              10.1.3
@ngtools/webpack                  10.2.0
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.44.1

**Comment by joeveiga** [comment]
You can target any of the CSS classes documented in: https://swimlane.gitbook.io/ngx-datatable/themes#css-classes
For example:
```css
.ngx-datatable .datatable-body-cell {
  border-left: 1px solid black;
}
```
