### ISSUE TITLE
Angular 11 with Ivy not working

### ISSUE THREAD

**Issue by wanghu24** [swimlane/ngx-datatable#1947]
I'm submitting a ...** (check one with "x")

[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

Current behavior

when ng serve, got error message:

ERROR in node_modules/@swimlane/ngx-datatable/lib/ngx-datatable.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of MyOwnModule, but could not be resolved to an NgModule class.

This likely means that the library (@swimlane/ngx-datatable/lib/ngx-datatable.module) which declares NgxDatatableModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

Expected behavior
no such problem in my previou project with Angular 9

Reproduction of the problem
no speical, same code, just not working in angular 11

**What is the motivation / use case for changing the behavior?**

<!-- Describe the motivation or the concrete use case -->

Please tell us about your environment:

Win, VS code

Table version:
latest version: 18.0.0

Angular version:
11.0.2

Browser:
All

Language:
All

**Comment by joeveiga** [comment]
Please use the template when submitting an issue. Thanks.

**Comment by wanghu24** [comment]
> Please use the template when submitting an issue. Thanks.

updated

**Comment by thatcort** [comment]
Hi, wondering if there's a timeline for merging the ng11 PR and releasing a new version?

**Comment by RezaRahmati** [comment]
Would you please update us about the timeline of getting fix for this?

**Comment by vickyrathee** [comment]
@joeveiga  I see the PR #1948 is closed, but this is still an issue. Or we are yet to publish this to NPM?

![image](https://user-images.githubusercontent.com/6106479/103604650-beee0e80-4f37-11eb-9756-2c8b00a48743.png)

**Comment by joeveiga** [comment]
@vickyrathee still an issue in `v19.0.0`?

**Comment by vickyrathee** [comment]
@joeveiga Yes, I have `v19.0.0` installed just 15mins ago to test in a new project.

**Comment by vickyrathee** [comment]
Here is the Angular, Node, OS version details

![image](https://user-images.githubusercontent.com/6106479/103605521-15f4e300-4f3a-11eb-957b-a48522524982.png)

**Comment by joeveiga** [comment]
@vickyrathee thanks for the info. I'll check.

**Comment by joeveiga** [comment]
@vickyrathee I just tried it with `@angular/cli` at `11.0.2`, which was the exact version at the time when I `ng update`d the project and it works fine. It is odd that just a patch version would break it (from `.2` to `.5`). This my "downgraded" `package.json`:
```json
{
  "name": "dt-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.2",
    "@angular/common": "~11.0.2",
    "@angular/compiler": "~11.0.2",
    "@angular/core": "~11.0.2",
    "@angular/forms": "~11.0.2",
    "@angular/platform-browser": "~11.0.2",
    "@angular/platform-browser-dynamic": "~11.0.2",
    "@angular/router": "~11.0.2",
    "@swimlane/ngx-datatable": "^19.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.5",
    "@angular/cli": "~11.0.2",
    "@angular/compiler-cli": "~11.0.2",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
```
I'll bump it again to `11.0.5` in a bit.

**Comment by joeveiga** [comment]
@vickyrathee Try removing node_modules and package-lock and `npm install`ing. I just tested it again in a new project generated with `@angular/cli@11.0.5` and it works fine.

**Comment by RezaRahmati** [comment]
I just checked version `19.0.0` with angular `11.0.5` and project build is green

**Comment by vickyrathee** [comment]
@joeveiga thanks, deleting the node_modules and package lock helps. It's working now.
