### ISSUE TITLE
Add cellComponent to TableColumn

### ISSUE THREAD

**Issue by ruddenchaux** [swimlane/ngx-datatable#1967]
**I'm submitting a** 

```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
Now the column configuration on typescript not permit to use a component for a cell but permit only template.

**What is the motivation / use case for changing the behavior?**
Can be useful use a component for a cell instead that a template because the component can easy shared and reused

**Comment by joeveiga** [comment]
@ruddenchaux could you please elaborate? I'm not sure I understand. Wouldn't including your custom component in the template solve that problem?

**Comment by ruddenchaux** [comment]
@joeveiga thank for the response. Yes, your solution solve my problem. Sorry, I hadn't considered this solution.
