### ISSUE TITLE
ngx-datatable not resizing correctly inside a flex div wrapper

### ISSUE THREAD

**Issue by davoutuk** [swimlane/ngx-datatable#1971]
I am building an Angular 10 app that is using flex to layout various panels.

I have a ngx-datatable wrapped by a flex based div and I have a problem where the ngx-datatable that is notionally set to take 100% width and 100% height is not resizing as the flex wrapper resizes. 

The wrapping div has a final vertical resize that happens after the ngx-datatable has rendered and shows data.   The table does  not resize after that final vertical resize leaving a vertical gap between the bottom of the table and bottom of the wrapper div, as shown below

![image](https://user-images.githubusercontent.com/25985256/105639935-e703ca00-5e72-11eb-8806-87c0b7be8d90.png)

Any suggestions?
```

.eis-vbox {
  height: 100%;
  width: auto;
  box-sizing: border-box;
  display: flex;
  flex: auto;
  flex-direction: column;
  align-items: stretch;
  padding: 0px;
  margin: 0px;
}

.full-area-grid {
  height: 100% !important;
  width: 99% !important;
}

<div id="simpleListWrapper" #wrapper class="eis-vbox" >

  <ngx-datatable #simpleListTable id="simpleList"
    class="material striped full-area-grid"
    [rows] = "rows$ | async"
    [columns]="columns"
    [sorts]="sorts"
    [scrollbarV]="true"
    [footerHeight]="50"
    [headerHeight]="50"
    [rowHeight]="40"
    selectionType="checkbox"
    [loadingIndicator]="isloading > 0"
    [scrollbarV]="true"
    [externalPaging]="true"
    [externalSorting]="true"
    [count]="totalRows$ | async"
    [offset]="pageNumber$ | async"
    (page)="setPage($event)"
    (sort)="onSort($event)"
    (select)="onSelect($event)"
  >
  </ngx-datatable>

</div>

```

**Comment by joeveiga** [comment]
@davoutuk I noticed your container has a `display: flex; flex-direction: column;`style, however, you're setting the datatable height to 100%. Have you tried `flex: 1`instead?
