### ISSUE TITLE
Why there are multiple API calls on single scroll for Virtual server-side paging?

### ISSUE THREAD

**Issue by Pankaj-TPL** [swimlane/ngx-datatable#1980]
I am trying to implement the virtual scrolling with server-side pagination using **@swimlane/ngx-datatable** but facing issues on page events.

**Current behavior**
When I scroll on the table body then the (page) event triggers multiple times which results in multiple API calls so the loader is displayed for a long time and all the rows are flickered.

**Expected behavior**
The event for scrolling on the table body should be called only once so the API calls will get reduced and the loader, flicker issues may get resolved.

**Reproduction of the problem**
scroll in table body and observe the console to see that page event triggers multiple times on a single scroll

**Please tell us about your environment:**

- **Table version:** @swimlane/ngx-datatable: "^18.0.0"

- **Angular version:** @angular/core: "^9.0.1"

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript: "^3.9.9"

![image](https://user-images.githubusercontent.com/69451656/111104100-e683d780-8575-11eb-9274-e2193bbac039.png)
https://stackblitz.com/edit/ngx-datatable-scroll-with-limit-uxgmtt?file=app%2Fpaging%2Fmock-server-results-service.ts

**Comment by Hypercubed** [comment]
The Virtual Server-side Paging implemented in ngx-datatable does not do any type of caching.  Please see the example: https://github.com/swimlane/ngx-datatable/blob/master/src/app/paging/paging-virtual.component.ts

**Comment by Pankaj-TPL** [comment]
> The Virtual Server-side Paging implemented in ngx-datatable does not do any type of caching. Please see the example: https://github.com/swimlane/ngx-datatable/blob/master/src/app/paging/paging-virtual.component.ts

@Hypercubed I got your point but my question is, on a single scroll why the event is triggered multiple times?
