### ISSUE TITLE
Take time to Display rows in tablet

### ISSUE THREAD

**Issue by mbshingala28** [swimlane/ngx-datatable#1986]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search GitHub for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit a support request here, post on Stackoverflow or Gitter
```

**Current behavior**

In the given demo link,  when test in Tablet, it take times to render rows when scrolling in the table.
https://swimlane.github.io/ngx-datatable/#virtual-scroll

**Expected behavior**
It should not take time.

**Reproduction of the problem**

To reproduce the issue, open https://swimlane.github.io/ngx-datatable/#virtual-scroll on the tablet.
https://user-images.githubusercontent.com/58248433/113252964-2bcc3700-92e2-11eb-84c6-5561091378e2.mp4

**What is the motivation/use case for changing the behavior?**

**Please tell us about your environment:**

**Environment**:- Use a tablet that has 4 GB ram (I am using  Lenovo M-10)
![image](https://user-images.githubusercontent.com/58248433/113253496-f1af6500-92e2-11eb-86b8-627c61bab296.png)

- **Table version:**
19.0.0.0

- **Angular version:**
11.0.2

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

- **Language:** [all | TypeScript 4.0.5

**Comment by Hypercubed** [comment]
The time is explicitly added to simulate API calls.
