### ISSUE TITLE
npm install on Angular 11 - peer dependencies and not working

### ISSUE THREAD

**Issue by plecos** [swimlane/ngx-datatable#1987]
**I'm submitting a ...** 

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

I am attempting to install ngx-datatables in a project running Angular 11.

```
npm install @swimlane/ngx-datatable
```

After install I get the following warnings:

```
npm WARN @swimlane/ngx-datatable@19.0.0 requires a peer of @angular/common@^11.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@19.0.0 requires a peer of @angular/core@^11.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@19.0.0 requires a peer of @angular/platform-browser@^11.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@19.0.0 requires a peer of rxjs@^6.6.3 but none is installed. You must install peer dependencies yourself.
```

My packages.json has the following:

```
"@angular/common": "~11.2.6",
"@angular/core": "~11.2.6",
"@angular/platform-browser": "~11.2.6",
"rxjs": "~6.6.0",
```

When I add the import to app.module.ts and run my app, I get the following errors:

```
[error] Error: The target entry-point "@swimlane/ngx-datatable" has missing dependencies:
 - @angular/core
 - @angular/common
 - rxjs
 - rxjs/operators
 ```
 
So why am I having an issue?

**Expected behavior**

No warnings, and the project runs

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Would like to have a working program.

**Please tell us about your environment:**

Windows 10, Visual Studio 2019, Angular 11

Angular CLI: 11.2.6
Node: 14.16.0
OS: win32 x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6

- **Browser** Chrome

- **Language:** all

**Comment by plecos** [comment]
I updated rxjs to 6.6.7, and so that warning went away.  Still left with the other 3.

**Comment by Hypercubed** [comment]
Are you able to provide an exampkel repo?

**Comment by plecos** [comment]
@Hypercubed not sure what exactly you are asking for?

**Comment by Hypercubed** [comment]
From the description it should work.  You have the peers installed.  Do you have a full repo I can look at?

**Comment by Quangdung1996** [comment]
> I updated rxjs to 6.6.7, and so that warning went away. Still left with the other 3.

thanks you, i fixed issue it
