### ISSUE TITLE
Update Angular 12

### ISSUE THREAD

**Issue by LucasDshg** [swimlane/ngx-datatable#2008]
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter

Update for Angular 12

Npm show warnins

npm WARN @swimlane/ngx-datatable@19.0.0 requires a peer of @angular/common@^11.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@19.0.0 requires a peer of @angular/core@^11.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@19.0.0 requires a peer of @angular/platform-browser@^11.0.2 but none is installed. You must install peer dependencies yourself.

**Comment by entrymon** [comment]
Wondering if this can be done sooner as angular 12 is awesome.

**Comment by mtenorio-cmp** [comment]
🤔
```
$ npm i @swimlane/ngx-datatable

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular@3.0.0
npm ERR! Found: @angular/common@12.1.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^12.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.2" from @swimlane/ngx-datatable@19.0.0
npm ERR! node_modules/@swimlane/ngx-datatable
npm ERR!   @swimlane/ngx-datatable@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by oussema-kallel** [comment]
@mtenorio-cmp I have the same problem. Did you find how to resolve this?

**Comment by MichelZ** [comment]
#2010

**Comment by mtenorio-cmp** [comment]
@oussema-kallel 

`npm i @swimlane/ngx-datatable --force`

**Comment by oussema-kallel** [comment]
I try this but can't find swimlane/ngx-datable in nodemodule 
npm i https://github.com/swimlane/ngx-datatable#ng-12-upgrade --package-lock-only

**Comment by oussema-kallel** [comment]
@mtenorio-cmp 
`npm i @swimlane/ngx-datatable --force`
this command destroy my toolkit

**Comment by wailashraf71** [comment]
Same issue and `npm i @swimlane/ngx-datatable --force` doesn't work

**Comment by RemcoLankhorst** [comment]
@mtenorio-cmp 

I think this issue has to do with the npm version. If you run version 7 or highe, you'll get issues with upstream dependency conflicts. I use npm version 6.14.3 and it shouldn't be an issue anymore.
