### ISSUE TITLE
Sorting not working when using templates

### ISSUE THREAD

**Issue by retallicka** [swimlane/ngx-datatable#205]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
- **Current behavior**
  I am using templates as my data is not flat and I am formatting the data a bit differently in each. So I am calling functions on the data from the template.
  Clicking on the table headings gives a random order
- **Expected behavior**
  I expected the table to be sorted 
- **Reproduction of the problem**
  I made a plunkr here:
  http://plnkr.co/edit/abYiAm08Ibff9SixKoyG?p=preview
- **Table version:** 0.9.3 (most recent)

Please try the plunkr to see the problem in action. Click the table headings and see what is happening. If I preprocess the data I might be able to get around this but doing the datepipe in the component seems to slow down the table massively. So this was the nicest way I found and I am happy with it except for the sorting.

**Comment by criticalpixel** [comment]
I tried to use the same data set you have there and I cannot sort even when not using templates. When I used flat data, it sorted it no problem. I think nested data isn't sort-able right now :(

**Comment by fsaftoiu** [comment]
Hi,

Had same problem, worked around it by using a @ViewChilid to get access to the Datatable component and called state.nextSort manually.

In retrospect, I think not having sort by default when there's a header template is pretty logical since the template might want to catch the click. But this should definitely be talked about in the docs.

**Comment by retallicka** [comment]
I changed the plunkr to make the data flat since that might be another problem. Still the same behaviour

**Comment by retallicka** [comment]
@fsaftoiu I wasn't having quite the same issue as you. I was not using header templates. Only cell templates.

However, I was keen to find a workaround so I tried to use header templates and used the method you described, called state.nextSort manually. Unfortunately I got the same strange sorting as seen in the plunkr. I will try to do a bit more digging if I have time... Using 0.11.2 didn't have any improvement.

**Comment by amcdnl** [comment]
Can u retest @retallicka ?

**Comment by Anuovec** [comment]
The issue is that when you use own header template, there is no default event, that on click run sort, which is ok.

On 1.7.0 I do not see any way how to manually call sort on click.

**Comment by retallicka** [comment]
@Anuovec No that is a separate issue to this issue.
If you look at the plunkr there are no header templates. I only learned that header templates were possible because of fsaftoi's comment above. As he/she said this can be regarded as logical.

I will try to test this again with the latest version.

**Comment by amcdnl** [comment]
The event is exposed now so you can trigger the sort.
