### ISSUE TITLE
Upgrade rxjs dependency to version 7

### ISSUE THREAD

**Issue by srudin** [swimlane/ngx-datatable#2080]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Including ngx-datatable dependency requires downgrade of rxjs to v6 or usage of --legacy-peer-deps flag.

**Expected behavior**

rxjs v7 can be used with default npm install command.

**Reproduction of the problem**

Create project with rxjs v7 dependency, add ngx-datatable v20 dependency, run npm install.

**What is the motivation / use case for changing the behavior?**

Stay up to date without workarounds.

**Please tell us about your environment:**

Not important here, I think.

- **Table version:**
v20

- **Angular version:**
v13

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by ge65cer** [comment]
+1

**Comment by FlavioSantoro92** [comment]
+1

**Comment by luca-moveshelf** [comment]
+1

**Comment by aIbarrab** [comment]
+1

**Comment by darkoxv88** [comment]
+1

**Comment by gevorgav** [comment]
+1

**Comment by Mooeeezzzz** [comment]
https://www.npmjs.com/package/@boring.devs/ngx-datatable (Forked)
[stackblitz](https://stackblitz.com/edit/angular-ivy-ungshx?file=src/app/app.component.ts)

**Comment by fpfcarvalho** [comment]
+1

**Comment by maxcl10** [comment]
+1

**Comment by christophercr** [comment]
I've submitted this PR #2108, hopefully that will unblock us to move forward with Angular 13 + Ivy.

**Comment by srudin** [comment]
I think this was solved meanwhile. At least I was able to remove the legacy flag and it still works.
