### ISSUE TITLE
Summary / Total Row

### ISSUE THREAD

**Issue by AlexSpirin1990** [swimlane/ngx-datatable#216]
Can I add total row ? This line needs to show total values column.

**Comment by istiti** [comment]
Do you mean `footerHeight` option

**Comment by amcdnl** [comment]
Like a summary row?

**Comment by AlexSpirin1990** [comment]
Yes, like a summary row.

**Comment by amcdnl** [comment]
Not really possible at the moment, but something I would be happy to help you if you want to PR

**Comment by Tempus35** [comment]
Just thought I would point out this is likely the same as my request here #115

**Comment by amcdnl** [comment]
Dupe of #115
