### ISSUE TITLE
Reverse Selection Problem

### ISSUE THREAD

**Issue by marpereira** [swimlane/ngx-datatable#230]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => "searched with 'selection' keyword" nothing found
[ ] feature request
[ ] support request
```

**Current behavior**
When using MultiShift reverse selection some rows don't be selected.
On a List with 7 elements
First hit (index) | Second hit | List behavior
2 | 1 | []
2 | 0 | [0, 1]
5 | 4 | []
5 | 3 | []
5 | 2 | [2]
5 | 1 | [1, 2, 3]
5 | 0 | [0, 1, 2, 3, 4]

**Expected behavior**
First hit | Second hit | List expected
2 | 1 | [1, 2]
2 | 0 | [0, 1, 2]
5 | 4 | [4, 5]
5 | 3 | [3, 4, 5]
5 | 2 | [2, 3, 4, 5]
5 | 1 | [1, 2, 3, 4, 5]
5 | 0 | [0, 1, 2, 3, 4, 5]

**What is the motivation / use case for changing the behavior?**
I'm expecting that reverse selection does job well as normal selection

**Please tell us about your environment:**
SystemJs
- **Table version:** 0.11.2
- **Angular version:** 2.1.1
- **Browser:** [Chrome 54]
- **Language:** [TypeScript 2.0.2]

**Comment by s0x** [comment]
Hitting that issue as well. Would be great to have that fixed

**Comment by imyque** [comment]
I just updated to Table version 4.1.0 and Angular 2.3.1 and the issue still persists

**Comment by amcdnl** [comment]
Ya, I hit this the other day too. Haven't had a chance to fix it yet though.

**Comment by amcdnl** [comment]
I believe this is resolved in latest. Please reopen if that is not the case.
