### ISSUE TITLE
Server side paging prolem

### ISSUE THREAD

**Issue by honify** [swimlane/ngx-datatable#270]
Hi
Please do the steps to get the error:
1- Goto: http://swimlane.github.io/angular2-data-table/
2- Left bar Paging > Server-side
3- Click on page number 4 or 5 
4- Now, try to sort on Company

Table be empty, until you click on page 1 .

**Comment by mmrath** [comment]
IMO it does not make much sense to use client side sorting with server side paging, but there might be some genuine use cases.  
This is a bit related to #293 sorting is mixing up the indices of the array. But I think this issue can be solved without fixing #293. I will try to send a PR.

**Comment by sachinofficial** [comment]
@mmrath this even happens when you use server-side pagination with server-side pagination. Please fix this, this is a huge bug for this great library. +1 for the fix.

**Comment by PatrickHuetter** [comment]
Same problem here. Huge bug.

**Comment by pravinh-menlo** [comment]
same problem ....

**Comment by deeg** [comment]
I am also experiencing this problem. I am going to work on fixing it. I think it is safe to assume any time someone sorts, regardless of server or client paging/sorting, we always want to go back to be showing the first page.

If anyone sees issues with that, or has a different solution, please discuss.

**Comment by stefmabo** [comment]
I think that I found a workaround.
If you have to call a Web Service and load just a specific data(offset) instead of load the JSON file
You should have to add this.

**1. Init**

```
ngOnInit() {
    this.page(this.offset, this.limit);
  }
```

**2. page function:** 
```
page(offset, limit) {
    this.fetch((results) => {
      this.count = results.total; // Web service give me the total

      const start = offset * limit;
      const end = start + limit;
      const rows = [];

      for (let i = start; i < end; i++) {
        console.log(results.list[i])
        rows[i] = results.list[i - this.limit * this.offset]; //this is the "hack". result.list is the data of the web service
      }

      this.rows = rows;
    });
  }
```

**3. Call the Web Service**
Here, the Web Service support the **offset** and **limit** parameters.
```
fetch(cb) {
    this.callService.list('url', this.offset, this.limit).subscribe(
      data=> {
        cb(data);
      },
      null,
      () => {
         //TODO
      }
    );
  }
```

**4. onPage function:** 
```
onPage(event) {
    this.offset = event.offset; //here
    this.page(event.offset, event.limit);
  }
```

**Comment by chriseenberg** [comment]
Any development on this issue?
To be honest, i can't use the component until paging works - and i really like the look and the features of this component so i'd love to see it working.
