### ISSUE TITLE
Jump-to-end-of-table buttons re-enabled when scrolled past last element.

### ISSUE THREAD

**Issue by nbauernfeind** [swimlane/ngx-datatable#334]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If you scroll "past" the last element in the seamless scrolling (basic virtual demo) it re-enables the jump-to-end-of-table button.

**Expected behavior**
I would expect if you are scrolled "past" the last element that those items would be disabled. They appear to only be disabled if the last element is crossing the visible boundary.

**Reproduction of the problem**
Use the seamless paging functionality on the 100k page here: http://swimlane.github.io/angular2-data-table/#
Jump to the end of the table and the scroll near the last element.

**What is the motivation / use case for changing the behavior?**
Because it is more natural that if you're at the end of the table that navigation buttons confirm you appear to be.

**Please tell us about your environment:**
OSX

* **Table version:** 0.7.x
Current version on demo webpage.

* **Angular version:** 2.0.x
Current version on demo webpage.

* **Browser:**
Chrome: 54.0.2840.98 (64-bit)

* **Language:** N/A (I think)

**Comment by amcdnl** [comment]
Resolved in latest
