### ISSUE TITLE
Tree Grid

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-datatable#34]

**Comment by elaijuh** [comment]
Any update on this new feature?

**Comment by amcdnl** [comment]
Nothing yet, open to PRs and helping out if you wanna take it on.

**Comment by sanbornsen** [comment]
We at Red Hat found this library very useful and we wish to contribute to the Tree Grid view. Is there any update on this issue? 

These are the features we are considering to contribute to - 

* Should be able to show the tree structure in one column (Should be given as input).
* Sorting and any other existing feature should work along with that column.
* Based on a property **hasChildren** of the input object the expander icon should be shown.
* Clicking on the expander should give an event output.
* The children should be added to the array named children, an optional property of each item in the list.
* An optional input **expandChildren** will decide if the tree will be already expanded onInit. By default, it’ll be collapsed.
* The expander template can be provided by the integrator to provide flexibility.

Any suggestion is welcome.

**Comment by amcdnl** [comment]
@sanbornsen - 

1) Thats awesome that Redhat is using this library!
2) I implemented a tree grid in my Angular1 version of this table. I used a `isTreeColumn` and `relationshipProp` to determine things. https://github.com/swimlane/angular-data-table/blob/master/demos/tree.html#L103-L104 . 
3) Lets spitball the API before we start implementation. It would be helpful to create a design doc like I do for Google ... See reference: https://docs.google.com/document/d/12sksu2GHcITFBidL8nyRzIt8lnVUoGnzwQx4tXWesEw/edit?usp=sharing
4) Overall your suggestions seem sound.

**Comment by sanbornsen** [comment]
Thanks, @amcdnl. Sounds like a plan. We'll start working on that design doc.

**Comment by ashishpok** [comment]
This seems to be the only missing piece for us as well, has anything moved forward on this? Thanks for the great library - we finally might be able to be purely angular with this :)

**Comment by ashishpok** [comment]
Thanks @sanbornsen! I will give it a shot.

**Comment by ashishpok** [comment]
@sanbornsen I managed to pull it in today and first impression is good. I had one feedback/question (perhaps I am not doing this best possible way). I was looking for an easier hook to refresh child rows. Something along the lines of remove all "child" rows of parent row using treeTo/From relationships and push new rows on a successful AJAX call. 

Currently I am looping all rows to find rows matching a parent and then splicing them from the rows array first (which works ok I suppose) but doesn't seem very elegant.

**Comment by ashishpok** [comment]
@sanbornsen - couple of quick notes that might help
(1) row margin multiplier should be made configurable
(2) adding css to <label> would help. eg: like for wrapping both expander and cell template into group for styling.
Thanks!
