### ISSUE TITLE
Selectively add class/style to rows

### ISSUE THREAD

**Issue by damnko** [swimlane/ngx-datatable#348]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here
```

**What is the motivation / use case for changing the behavior?**
It would be nice to be able to style a row depending on the value of one of it's properties (column value)

**Comment by gkgithub** [comment]
we want this feature too. we couldn't able to customize the specific rows.

**Comment by s0x** [comment]
Same here. I'd really appreciate this option

**Comment by istiti** [comment]
Second it

**Comment by amcdnl** [comment]
Actually, this is possible. Can one of you guys PR it? I'd implement something like I did with `selectCheck` [reference](https://github.com/swimlane/ngx-datatable/blob/master/src/components/body/selection.component.ts#L27).

**Comment by achimha** [comment]
Would there be a way to do this using expressive markup instead of a callback handler? I can do it for cells with `<ngx-datatable-column>`, how about a `<ngx-datatable-row>` where styles could be added with standard Angular syntax?

**Comment by amcdnl** [comment]
Ya, been considering adding a row directive for this.

**Comment by tsm91** [comment]
> Ya, been considering adding a row directive for this and other stuff.

Atm i need to find a way to add an extra 1st row with predefined cells. Each cell will contain an input and will filter the given column.

There would be many use cases for this.

**Comment by amcdnl** [comment]
For that, I would make the header cell contain the filter. I've done this in my app actually.

**Comment by tsm91** [comment]
after searching the issues i did the same, needed to make the header template sortable tho

saw a lot of ppl complaining about un-sortable header templates so i reference TMP solution: https://github.com/swimlane/ngx-datatable/issues/431#issuecomment-273335200

**Comment by amcdnl** [comment]
Very nice! If you have time a demo in the docs would be cool :)

**Comment by molcik** [comment]
+1

**Comment by amcdnl** [comment]
Done in 7.0!
