### ISSUE TITLE
Vertical scrolling does not work with server side paging 

### ISSUE THREAD

**Issue by mmrath** [swimlane/ngx-datatable#349]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Page event is triggered when scrolled past visible items. With server side paging page event should be triggered when a new page is required. e.g. Page 1 has 100 records while only 10 are visible, scrolling should work only with in the 100 elements, depending on which way you scroll. If you require to see records from 101 to 200, page link 2 should be clicked to fetch records from backend. 

Included plunker has a demo, once can see how the page event is triggered in the console logs.

**Expected behavior**

Explained above

**Reproduction of the problem**

http://plnkr.co/edit/YASMF0bNYMR3mkkzKL4p?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

latest

* **Angular version:** 2.0.x

latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
In my opinion, this is actually working as desired. I believe its not necessarily the tables job to determine whether you have scrolled that offset into view or clicked the button for that matter.

It does end up kinda messy though, so I suppose we should discuss for improvement. I don't want to go down the road of this spiralling into a whole complex cache system though. Heres how I handle it internally:

```
let pageSize = pageSize * 2;
let offset = Math.floor(offset / 2);

if(!this.offsets[offset]) { 
   this.offsets[offset] = true;
   // do paging!
}
```

This is nice because I pre-cache a few pages in my scenario.

**Comment by deanproxy** [comment]
Maybe a reasonable option here is to allow disabling of paging when scrolling when using the vertical bar?  It would be nice to be able to turn off the page event if we only want users to utilize the footer paging and do not want to load anything on scroll.  Having the page event trigger anytime you scroll and not when you hit the bottom (or near bottom) of the list is a bit excessive...
