### ISSUE TITLE
AoT not outputting files after 2.3.0 upgrade

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-datatable#357]
After I updated to ng 2.3.0, the ngc is not compiling the metadata files/etc.

@Brocco - any ideas ;)

**Comment by BafS** [comment]
I had to downgrade to the 2.2 version. With angular-cli I have this error:
`building modules 3/3 modules 0 active(node:10230) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Angular2DataTableModule is not an NgModule`

**Comment by Brocco** [comment]
The recent issues I've seen/heard of regarding ngc are related to changes in TypeScript 2.1 and what metadata is being emitted. AFAIK a fix is being researched.

**Comment by BafS** [comment]
@amcdnl is it possible to create a new release (2.2.1) ? Thanks in advance !

**Comment by BafS** [comment]
Thank you, unfortunately I still have an error.

```
(node:4580) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot read property 'VisibilityDirective' of undefined, resolving symbol Angular2DataTableModule in .../node_modules/angular2-data-table/release/datatable.module.d.ts, resolving symbol Angular2DataTableModule in /.../node_modules/angular2-data-table/release/datatable.module.d.ts
```

**Comment by Brocco** [comment]
@BafS I assume you're TypeScript version is `2.1+` can you try and lower your TS version down to `~2.0.3`?

The same issues with this lib are likely affecting your app.

**Comment by BafS** [comment]
@Brocco I use typescript version 2.0.10 for my app. (in case, here is my [package.json](https://github.com/BafS/Kaudio-frontend/blob/master/package.json#L62)).

**Comment by amcdnl** [comment]
Downgraded to 2.0.x and re-releaased. Per discussions today Angular4 will be the version that supports TS 2.1.x so will have to wait for that.

**Comment by kuncevic** [comment]
I am having compilaton issues using **angular-cli: 1.0.0-beta.22-1** and angular version **2.2.3**
That is what I've got when running `ng build`:
```
Cannot read property 'VisibilityDirective' of undefined, resolving symbol Angula
r2DataTableModule in c:/Project/node_modules/angular2-data-table/release/datatable.module.d.ts,
resolving symbol Angular2DataTableModule in c:/Projects/node_modules/angular2-data-table/release/
datatable.module.d.ts
```
I had typescript `2.1.4` installed globally which I made get rid off. So I did install version `2.0.10` in to the project and then version `2.0.3` but didn't help

**Comment by wyers** [comment]
doh. 4.0.0 is the only version on npm :-(
no downgrade work around for me

**Comment by amcdnl** [comment]
You can use `angular2-data-table` in the meantime.

**Comment by wyers** [comment]
i didn't put 2+2 together and realize the project had been renamed.

**Comment by amcdnl** [comment]
See: https://github.com/swimlane/ngx-datatable/issues/377
