### ISSUE TITLE
Access body before document is ready

### ISSUE THREAD

**Issue by s0x** [swimlane/ngx-datatable#368]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
document.body is used on import of scrollbar-width.ts even though document might not be ready yet. Therefore document.body can be null, which actually leads to the following error:

Uncaught TypeError: Cannot read property 'appendChild' of null
```
getScrollBarWidth	@	main.bundle.js:30748
./src/utils/scrollbar-width.ts	@	main.bundle.js:30760
__webpack_require__	@	main.bundle.js:25854
./src/utils/index.ts	@	main.bundle.js:30336
__webpack_require__	@	main.bundle.js:25854
./src/components/datatable.component.ts	@	main.bundle.js:27478
__webpack_require__	@	main.bundle.js:25854
./src/components/index.ts	@	main.bundle.js:29216
__webpack_require__	@	main.bundle.js:25854
./src/datatable.module.ts	@	main.bundle.js:29330
__webpack_require__	@	main.bundle.js:25854
./src/index.ts	@	main.bundle.js:29962
__webpack_require__	@	main.bundle.js:25854
./src/components/body/body-cell.component.ts.c	@	main.bundle.js:25898
(anonymous function)	@	main.bundle.js:25901
```

**Expected behavior**
getScrollBarWidth should not be called before

**Reproduction of the problem**

**Please tell us about your environment:**
I'm using webpack which might have introduced an delay. Though, document should not be used before it is read.

* **Table version:** 2.2.1

* **Angular version:** 2.1.1

* **Browser:** [ Chrome | Firefox | Most probably all ]

**Comment by amcdnl** [comment]
I've never seen this, can u make a repo case?

**Comment by s0x** [comment]
Well, I found the issue: I was injecting all scripts inside the head-tag. Therefore body was not defined yet. Since angular itself has no issues to be loaded in head this module should support this as well.
Accessing the dom, or the body respectively, without checking if it is available yet should be prevented anyhow.

**Comment by amcdnl** [comment]
Resolved in latest.
