### ISSUE TITLE
Observable datasource (rxjs/flux/redux)

### ISSUE THREAD

**Issue by gregkopp** [swimlane/ngx-datatable#373]
Can an observable be used for the data source? I am just learning NG2 and implementing rxjs/Flux/Redux patterns for state management. I'd like to be able to use this module, or something like it, that can take an Observable<Widget[]> as the data source.

**Comment by deebloo** [comment]
you can use the async pipe Angular provides.

Ex:

```TS
<swui-datatable [rows]="myObservable | async"></swui-datatable>
```

**Comment by gregkopp** [comment]
I tried this, and I am getting an error.

To be clear, BEFORE I found this module, I had the observable working in a simple ngFor loop, creating table rows. So I know my state is good and ngrx is working. I then removed that table and created a static table, using ngx-datatable. The values were static in the code. I then replaces "[rows] = 'rows'" with my own observable collection, i.e. "[rows] = 'manufacturers | async'". When the content reloads, I get this error:

EXCEPTION: Error in ./DatatableComponent class DatatableComponent - inline template:28:8 caused by: Can't add property $$index, object is not extensible

Perhaps this is not a ngx-datatable issue, but I am at a loss as to what I am doing wrong.

**Comment by Codermar** [comment]
The error happens because ngrx-datastore is mutating the state of the source data. See https://github.com/swimlane/ngx-datatable/issues/253
I had to disable the StoreFreeze as a workaround. At least while you are dealing directly with components using datatables.

**Comment by gregkopp** [comment]
OK. That seemed to do the trick. I don't like the idea of disabling the storeFreeze if I end up using this in a project. I'll check out that thread, but I would hate that this would be permanent.

**Comment by fifafu** [comment]
This works, but it would be really great if this wouldn't force us to make the data mutable. The problems seems to be that an $$index is added to every object, thus ngrx crashes if StoreFreeze is enabled.

**Comment by amcdnl** [comment]
@fifafu - I suppose we could track the rows in our own internal collection?

**Comment by fifafu** [comment]
@amcdnl sounds like a good idea! Maybe I can have a closer look next week.

**Comment by amcdnl** [comment]
Awesome! Appreciate the help!

**Comment by amcdnl** [comment]
Async works now, Store freeze is being tracked as a seperate issue.

**Comment by yiweicao** [comment]
does it also work for <ngx-datatable [rows]="myObservable | async"></ngx-datatable> for angular version 2? I am using @swimlane/ngx-datatable@6.3.0 for angular 2 (not angular 4 yet).
