### ISSUE TITLE
Quickstart or Angular-CLI?

### ISSUE THREAD

**Issue by DerekdeClercq** [swimlane/ngx-datatable#374]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request => Please do not submit support request here
```

**Current behavior**

When installing as per the instructions I get dependency complaints when using the latest quickstart which pulls angular 2.3.1 and also angular-cli which pull 2.2.3(Should not work as documentation states it should be >= 2.3.0). Manage to resolve the dependencies and table seems to function correctly, but themes will not apply. Even when including material.scss as a sample. If I add a new style into material.scss and apply to a div, it shows up when I test the div. However none of the datatable styles seem to apply 
**Expected behavior**

It would be really helpful to have a short from scratch sample to get an environment going. 

**Reproduction of the problem**

clone the latest quickstart using git
npm install @swimlane/ngx-datatable
edit package.json and change the minor version number of rxjs dependancy
implement the rest of the sample as per the documentation

**What is the motivation / use case for changing the behavior?**

Don't want to change anything, the table seems awesome

**Please tell us about your environment:**

Ubuntu 16.4, Visual Studio Code, npm 3.10.10 node 7.2.1

* **Table version:** 0.7.x

4.0.0. Latest I could get

* **Angular version:** 2.0.x

2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescipit

**Comment by amcdnl** [comment]
@Brocco - this has your name all over it ;)

**Comment by hathcox** [comment]
I found my issue with angular cli!! I think it might be what you are describing too. 

I was trying to include my css file inside of the component where I was using the <ngx-datatable></ngx-datatable> tag.

This was incorrect. I needed to actually include the css file inside of my angular-cli.json, like so

`{
    "apps":[{
        "styles": [
            "../node_modules/@swimlane/ngx-datatable/release/datatable.css"
        ]
    }]
}`

**Comment by amcdnl** [comment]
CSS is included by default now.

**Comment by Phota16** [comment]
When I installed ngx-datatable as per instruction (>npm install @swimlane/ngx-datatable)  got error 
+-- UNMET PEER DEPENDENCY @angular/common@2.4.7
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.7
+-- UNMET PEER DEPENDENCY @angular/core@2.4.7
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.4.7
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.4.7
`-- @swimlane/ngx-datatable@6.3.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN @swimlane/ngx-datatable@6.3.0 requires a peer of @angular/common@^2.4.8 but none was installed.
npm WARN @swimlane/ngx-datatable@6.3.0 requires a peer of @angular/compiler@^2.4.8 but none was installed.
npm WARN @swimlane/ngx-datatable@6.3.0 requires a peer of @angular/core@^2.4.8 but none was installed.
npm WARN @swimlane/ngx-datatable@6.3.0 requires a peer of @angular/platform-browser@^2.4.8 but none was installed.
npm WARN @swimlane/ngx-datatable@6.3.0 requires a peer of @angular/platform-browser-dynamic@^2.4.8 but none was installed.

my project has been set up with
@angular/cli: 1.0.0-beta.31
node: 6.9.4
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

**Comment by amcdnl** [comment]
They are warnings not errors

**Comment by Phota16** [comment]
thank you..it worked for me.
