### ISSUE TITLE
Using translate in header

### ISSUE THREAD

**Issue by AlexKhymenko** [swimlane/ngx-datatable#376]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Thank you for your work. I'm trying to use table with translate service. I have tried

> `<ngx-datatable-column name="{{ 'global.operation' | translate}}"></ngx-datatable-column>`

 the problem is when you try to change language(it's not working) also initial load also will show what's in prop not what is name, only when you leave page and go back it will change language. Maybe i don't understand something. Have tried with custom template

Holla! {{"column.name" | translate}}

The same behavior.

**Expected behavior**
It should translate header
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x
4.0.0
* **Angular version:** 2.0.x
4.0.0.beta.0
* **Browser:** [all  ]

* **Language:** [ TypeScript 2.1.4 ]

**Comment by amcdnl** [comment]
<ngx-datatable-column [name]="global.operation | translate">

**Comment by AlexKhymenko** [comment]
Thank you very much.
