### ISSUE TITLE
Update import statement in documentation?

### ISSUE THREAD

**Issue by pchristou** [swimlane/ngx-datatable#384]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
In the documentation "Getting Started" section, the import statement of 

import { NgxDatatableModule } from 'angular2-data-table';

should read 

import { NgxDatatableModule } from '@swimlane/ngx-datatable';

**Comment by amcdnl** [comment]
Can you PR this please?

**Comment by pchristou** [comment]
@amcdnl done! Thanks
