### ISSUE TITLE
after AOT build and run "Cannot read property 'id' of undefined" at setColumnDefaults

### ISSUE THREAD

**Issue by zxshinxz** [swimlane/ngx-datatable#396]
Hi all,

Just wondering if anybody is experiencing error that I am describing here.

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
![screen shot 2016-12-27 at 4 59 43 pm](https://cloud.githubusercontent.com/assets/4936183/21494702/b362ed32-cc56-11e6-8f4c-ff0be7016900.png)

**Expected behavior**
sholud be running without error

**To reproduce the problem**
 ngc compile -> rollup bundle -> ran with gulp-webserver

**Please tell us about your environment:**

Mac 10.11.6, WebStorm, NPM 3.10.8, gulp-webserver

* **Table version:** 0.7.x
4.1.0

* **Angular version:** 2.0.x
2.3.1

* **Browser:** [Chrome]

* **Language:** [TypeScript 2.0.3]

**Comment by zxshinxz** [comment]
I have fixed problem by moving id() into setColumnDefaults() and created new ngx-datatable build. Just wondering if this is problem with my bundling setup

utils/id.ts
```
export function id() {
  return ('0000' + (Math.random() * Math.pow(36, 4) << 0).toString(36)).slice(-4);
}
```


util/column-helper.ts
```
export function setColumnDefaults(columns: any[]) {
  if(!columns) return;

  for(let column of columns) {
    if(!column.$$id) {
-->      column.$$id = ('0000' + (Math.random() * Math.pow(36, 4) << 0).toString(36)).slice(-4);   
  }

    // translate name => prop
    if(!column.prop && column.name) {
      column.prop = camelCase(column.name);
    }

    // format props if no name passed
    if(column.prop && !column.name) {
      column.name = deCamelCase(column.prop);
    }

    if(!column.hasOwnProperty('resizeable')) {
      column.resizeable = true;
```

**Comment by amcdnl** [comment]
Seems related to your build. Can you make a demo repo?

**Comment by sjonany** [comment]
I also have the same problem. Looks like util =  require('../utils') in the line below results to undefined, when I place breakpoint in the browser, leading to the error just described in the title. 
https://github.com/swimlane/ngx-datatable/blob/d348ad7fe9003925ed5aa13f3aeb5459dd69e7d2/release/utils/column-helper.js#L2

This is my rollup config, if that's helpful. http://pastebin.com/1ymv3Rw2
Not sure why rollup fails to resolve the require() statement, even with the commonjs plugin.
-- Will reply to thread if I figured it out.

**Comment by sjonany** [comment]
I discovered the problem, and have a workaround for now. But, I don't know what part of rollup causes this.

When I go to the generated rollup bundle file in dist/build.js, I see that the sequences of common js definition and require() are out of order.
---
var utils_1$1 = index$6;
....
 index$6 = createCommonJs ()
---

Since index$6 happens after the utils assignment, utils_1 will still be undefined.
When I manually move utils_1 assignment after index$6 has been defined, the error disappears.

Tried reordering rollup plugins and moved commonJs to the first plugin to run, but still same problem. This looks more like a rollup problem than this module... unless I'm missing a ngx-datatable -specific quirk that makes it not work with rollup.

**Comment by amcdnl** [comment]
Sounds like we should be able to fix. I'll tweak it but will need ur help testing.

**Comment by sjonany** [comment]
Thanks for the quick reply!
Sure, I was thinking the fix would be small changes in js files under release/utils/
If it's easy for you to send me the changed js files, I can patch them locally, rerun rollup and let you know.

**Comment by djamison** [comment]
+1 - Looks like this is still an issue in 6.1.2. Happy to help testing.

**Comment by pauldaustin** [comment]
I'm wondering if the following in column-helper.ts would fix it?

```typescript
import { camelCase} from './camelCase';
import { deCamelCase } from './deCamelCase';
import { id } from './id';
```

**Comment by pauldaustin** [comment]
The issue is that TypeScript does not allow circular dependencies. So within a module you need to reference the other files in that module using relative references rather than importing from the module.

Using the following imports in the src/utils/column-helper.ts works.

```
import { camelCase, deCamelCase } from './camel-case';
import { id } from './id';
```
