### ISSUE TITLE
Cannot select any text in any table cell

### ISSUE THREAD

**Issue by tsm91** [swimlane/ngx-datatable#397]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If i try to select the text content of a table cell by press and hold the right mouse button. It doest work. Double clicking the text content doesnt work either.

**Expected behavior**
See the text contents highlighted like this http://imgur.com/a/2Btlx

**Debug**

I realized if i do it programatically it doesnt work either.

```js
var range = document.createRange();
range.selectNodeContents(node);
window.getSelection().removeAllRanges();
window.getSelection().addRange(range);
```

When i disabled css i could select it. So this is a css issue. To be more specific it is because of these lines: https://github.com/swimlane/ngx-datatable/blob/master/src/components/datatable.scss#L101-L105

**Comment by amcdnl** [comment]
This is a specific reason for this, though I can't remember now haha. Just override this in your CSS for your particular element.

**Comment by tsm91** [comment]
@amcdnl i did that. Altho i specifically opened this issue to find out what feature will this break :D

**Comment by amcdnl** [comment]
Cool, no worries. I can't remember but I know I did it for a specific reason.

**Comment by sangeeus** [comment]
I am using ngx data table for my angular 2 development. 

My table has select box
[selected]="selected"
 [selectionType]="'cell'"

and I have removed the below code from datatable.scss. 
-webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;

But I am still facing the same issue.

**Comment by sangeeus** [comment]
fixed.
refered this link https://github.com/swimlane/ngx-datatable/issues/491

thanks
