### ISSUE TITLE
Icons indicating sort order are reversed

### ISSUE THREAD

**Issue by dae721** [swimlane/ngx-datatable#400]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
sortAscending uses icon-down, sortDescending uses icon-up

**Expected behavior**
Should be the opposite, i.e. sortAscending should use icon-up.

**Reproduction of the problem**
Click on a column header, note the icon in the column header compared to the sort order.

**What is the motivation / use case for changing the behavior?**
The sort indicators as they currently stand are confusing, at least to me. I believe the accepted convention is that ^ represents an ascending sort. Discussion here backs this up: http://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header
Also, compare to behavior in Windows File Explorer.

Seems like this will be an easy fix, just swap the two icons in cssClasses found in datatable.component.ts, and make the corresponding change in table-inputs.md.

**Comment by deeg** [comment]
@amcdnl the label says in discussion? Is this something you want to discuss, or should this change be made?

**Comment by amcdnl** [comment]
Ya, PR it if you like. I'm ok with the change :)
