### ISSUE TITLE
Multi row selection from down up

### ISSUE THREAD

**Issue by imyque** [swimlane/ngx-datatable#402]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When I activate row selection, and I select row 1, hold down shift and click row 3, all three rows get selected. But If I select row 3 then hold down shift then click row 1, only row 1 gets selected.

**Expected behavior**
If I select row 3 first, hold down shift and select row 1, all three rows should be selected.

**Reproduction of the problem**
Activate multi row selection, select row 4, hold shift and select row 1. Only row 1 and 2 will be selected.

**What is the motivation / use case for changing the behavior?**
Row selection that works the same way in both directions

**Please tell us about your environment:**
Windows 10, Node 6.9.2, NPM 3.7.5, Angular 2.2.3, Angular-cli 1.0.0-beta.22-1, Ngx-datable 4.0.0

* **Table version:** 4.0.0

* **Angular version:** 2.2.3

* **Browser:** Chrome 55.0.2883.87 m (64-bit)

* **Language:** TypeScript 2.2.0-dev.2016-12-23

**Comment by s0x** [comment]
This seems to be the same as #230

**Comment by amcdnl** [comment]
Yes, dupe :)
