### ISSUE TITLE
Column  alignment

### ISSUE THREAD

**Issue by imyque** [swimlane/ngx-datatable#403]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
No property to set text alignment for columns

**Expected behavior**
A property to determine whether the texk in  column should be left, right or center aligned

**What is the motivation / use case for changing the behavior?**
Presentation of text and numeric data on a grid, eg Price list

**Please tell us about your environment:**
All

* **Table version:** 4.0.0

* **Angular version:** 2.2.3

* **Browser:** [all ]

* **Language:** [all]

**Comment by amcdnl** [comment]
Sounds like a good change. We should add the ability to define `cssClass` on the column and it be added to the header cell and body cell elements. Can you PR that?

**Comment by imyque** [comment]
Hello amcdnl,

Thanks for agreeing with my point. Please how do I "...PR that"?

Cheers

**Comment by amcdnl** [comment]
See: https://help.github.com/articles/creating-a-pull-request/

**Comment by adrm** [comment]
I see a first PR has been merged for this functionality, but I think it shouldn't be considered complete:

- There are no docs about it yet.
- A property for `table` is similarly called `cssClasses` and means something totally different.
- It has just been implemented for column definition  as an object using the `columns` attribute, but there is not a `cssClasses` attribute for column elements.

What do you think, @amcdnl ?

**Comment by amcdnl** [comment]
Done in 8.0

**Comment by eagor** [comment]
thanks handy for addition, but how would you use it now without resorting to deprecaged `::ng-deep` ?
