### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by shlomiassaf** [swimlane/ngx-datatable#406]
Hi,

Great project! Thank you.

We want to integrate ngx-datatable in our app but we have some concerns regarding the NPM package and SCSS files.

The NPM packing is a bit blurry, there are a lot of files, the sourcecode is there along with SCSS files and their compiled CSS versions. 

Some files are in the `src` folder, some are in the `release`, its not clear what's the "official" release...

To me it looks like the packaging will get some sort of re-org in the future...

We want to relay on the SCSS files as they must be imported...

Can the SCSS files be part of the `release` folder for people using SCSS in their app?
CSS version should also be included ofcourse but it should also include SCSS...

Another thing is that the SCSS files contains vendor prefix which should be omitted and added by a vendor predixer postCSS plugin, the users of the library should consider adding or not adding them... 

Thanks, Shlomi.

**Comment by amcdnl** [comment]
Ya, I want to make it customizable and have some base styles but not force you to use them. I need to get the build to do the base css via `styleUurls` but haven't had time.

**Comment by amcdnl** [comment]
We use styleUrls now.
