### ISSUE TITLE
It seems that scrollbarV option is not working

### ISSUE THREAD

**Issue by closer27** [swimlane/ngx-datatable#427]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

```
<div>
  <ngx-datatable
    class="material"
    [rows]="itemList"
    [columnMode]="'force'"
    [headerHeight]="50"
    [footerHeight]="0"
    [rowHeight]="50"
    [scrollbarV]="true"
    [scrollbarH]="true"
    [messages]="{emptyMessage: 'no data'}">
    <ngx-datatable-column name="id" [width]="80">
    </ngx-datatable-column>
  </ngx-datatable>
</div>
```

I put the option `[scrollbarV]="true"` to ngx-datatable, vertical scroll does not appear in the table but the table's height expanded to 159200(3184*50), so the browser shut it down by force.
Strangely, the horizontal scroll did well.

**Expected behavior**

I expected vertical scroll appear in the datatable like `Horizontal and Vertical Scrolling` in the demo. Furthermore, I want to apply virtual-scroll too.

**Reproduction of the problem**

See this please, http://embed.plnkr.co/iNfzIC/
![2017-01-12 6 00 59](https://cloud.githubusercontent.com/assets/1941113/21883176/35777fee-d8f1-11e6-8efe-ff2197936e4a.png)
As you see, vertical scroll doesn't appear, but the table is expanded by itself.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

macOS 10.12.2, InteillJ, npm 3.10.3, 

* **Table version:** 4.1.0

* **Angular version:** 2.4.0

* **Browser:** safari 10.0.2, chrome 55

* **Language:** Typescript 2.0.7

**Comment by deeg** [comment]
I believe this can be closed.

[You just need to set a height on the datatable](https://plnkr.co/edit/3rmFP5ipjPutouL2cWpM?p=preview)

**Comment by amcdnl** [comment]
@deeg is correct...

**Comment by danaERadwin** [comment]
Sorry for the strange question, but where did you declare that the table is using the .datatable class?

**Comment by mayank-sahu** [comment]
@amcdnl  i'm facing vertical scroll bar issue. vertical scrollbar not working with group by. do you have any suggestions regarding this issue ?
