### ISSUE TITLE
Low performance DOM rendering

### ISSUE THREAD

**Issue by nyankov** [swimlane/ngx-datatable#428]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Poor performance DOM rendering. 25 records,  10 columns, 6 of them are templated. The browser uses too much CPU, if the scrollbarV is set to true the situation becoming even worse.

**Expected behavior**
Lighter DOM and low CPU usage

**Reproduction of the problem**
25 records, 10 columns (6 of them templated), data is paginated server side , so only the data for these 25 records is set in "rows" property.

* **Table version:** 0.7.x
4.1.0

* **Angular version:** 2.0.x
2.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.1

**Comment by amcdnl** [comment]
Is your application in production mode or dev mode?

**Comment by nyankov** [comment]
It's in dev mode

**Comment by amcdnl** [comment]
Ya, flip it to prod and it should be good.

**Comment by nyankov** [comment]
I will try it and will let you know - thank you for the quick reaction.

**Comment by nyankov** [comment]
Checked. You are correct it is working pretty fast. 

Thank you.

**Comment by Tenmak** [comment]
We should re-open this... 

Using the latest ngx-datatable version, It is causing a huge loading time...
Since we are using Angular-CLI, every time we do a single line of code, we get the 20+ seconds time of loading (While we only have 4.5~ seconds loading time without the `NgxDatatableModule` import).

And since it is not really good to continue programming in production mode,  is there any workaround or anything ? We are losing an insane amount of time because of this...

**Comment by amcdnl** [comment]
Can you give me some details about how many columns/rows you have loaded and virtual or not?

Maybe there is a way to disable debug of components at the module level.

**Comment by gryole** [comment]
I have the same issue using dev mode. Just imported NgxDatatableModule and used example from [get started](https://swimlane.gitbooks.io/ngx-datatable/introduction/getting-started.html). Loading difference is ~ 20 sec. I tried to reproduce this issue with new project (generated from angualr-cli) and difference is not significant ~ 200ms. Looks like it reproduces in larger projects.

**Comment by Tenmak** [comment]
@amcdnl I have several datatables on my app, roughly 4 tables of 5/6 columns and around 10 rows.

At first I had the `NgxDatatableModule` in a shared module, and I though that it would be better to split the shared module in several ones. So only my 4/5 components that use a table would import the module, but this changed nothing in the end. Still have 20+ seconds loading time

**Comment by ratiuandreea** [comment]
Any solution for this yet? 
I have 700 rows in the table and IE11 performance is terrible.
