### ISSUE TITLE
Sorting doesn't work if with a custom template header

### ISSUE THREAD

**Issue by PEsteves8** [swimlane/ngx-datatable#431]
If a custom template is used in a header, the columns stop being sortable. If you click the header nothing happens.

That can actually be verified in the demo itself:
http://swimlane.github.io/ngx-datatable/#
If you go to templates - inline. The first column (which is the one with a custom header) is the only one that is not sortable.

EDIT: notice there was actually an old open issue with this. Maybe it has been forgotten https://github.com/swimlane/ngx-datatable/issues/233

**Comment by tsm91** [comment]
@amcdnl any suggestions how to get sorting work?

**Comment by amcdnl** [comment]
I was trying that same approach but it wasn't working the other day. Didn't dig in too much yet though.

**Comment by amcdnl** [comment]
@tsm91 - if that works for u, then do a PR maybe i missed something

**Comment by tsm91** [comment]
@amcdnl after the project i working on is done (very soon) ill go through my notes regarding the datatable  and patch it up where needed

**Comment by kuncevic** [comment]
I am on `6.2.0` still having sorting issue with custom template header

**Comment by amcdnl** [comment]
This is resolved in latest

**Comment by burjua** [comment]
How is this closed? Sorting still doesn't work!

**Comment by winghei** [comment]
I was able to make it work by adding `ng-click="handleClick($event)" `  in the headerCellTemplate

**Comment by Ryan-Haines** [comment]
Still trying to figure out how to provide a custom comparator in the template....

Can anyone point to an obvious issue with the below code snippets? When the "Reviewed" header is clicked, it prints to console "sorting reviewed" followed by two blank lines - the row data is not being passed to the comparator!

**Template:**
```
<ngx-datatable-column name="Reviewed" [comparator]="sortReviewed">
	<ng-template let-row="row" ngx-datatable-cell-template>
		<span>{{row.numReviewed}}/{{row.numEntries}}</span>
	</ng-template>
</ngx-datatable-column>
```

**TS**
sorts by percent, then by numerator
```
sortReviewed(a: Challenge, b: Challenge): number {
	console.log('sorting reviewed');
	console.log(a);
	console.log(b);
	if(a.pctReviewed === b.pctReviewed) {
		if(a.num > b.num){
			return 1;
		} else if(a.num < b.num){
			return -1;
		} else {
			return 0;
		}
	} else if (a.pctReviewed > b.pctReviewed) {
		return 1;
	} else if (a.pctReviewed < a.pctReviewed) {
		return -1;
	}
}
```

**Comment by dougss10** [comment]
Somebody can provide a sample of sortable table using ngx-datatable-column i already tried a lot and didn't find any way to do this work.

**Comment by souzaemmanuel** [comment]
Sorting still doesn't working in client side !

**Comment by EzePerucca** [comment]
Still can´t find a way to get this working
