### ISSUE TITLE
Cannot copy cell content

### ISSUE THREAD

**Issue by Lucasvo1** [swimlane/ngx-datatable#432]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
**Current behavior**

I cannot copy text from my table, as well as the texts from the demo. That's why I don't know if it is supposed to be like that or not.  

**Expected behavior**

Ideally we should be able to copy cell content.

**Comment by amcdnl** [comment]
This is by design for selection, its a css property you can override. https://github.com/swimlane/ngx-datatable/blob/master/src/components/datatable.scss#L105

**Comment by justin1291** [comment]
@amcdnl the link is broken.
