### ISSUE TITLE
Problem with library import.

### ISSUE THREAD

**Issue by mateuszs** [swimlane/ngx-datatable#435]
**I'm submitting a ...**  
```
[ *  ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Angular does not see a module

**Expected behavior**
Angular does see a module

**Reproduction of the problem**
I have installed datatables using npm, included in my application and I receive:

 http://localhost:3000/@swimlane/ngx-datatable 404 (Not Found)

In my node_module folder I do have @swimlane/ngx-datatable folder so it seems to be installed.

> import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule, Routes } from '@angular/router';
import { HttpModule } from '@angular/http';

> import { NgxDatatableModule } from '@swimlane/ngx-datatable';

> import { AppComponent }  from './components/app.component';
import { TestLineMonitorComponent } from './components/test-line-monitor.component';
import { TabsComponent } from './components/tabs.component';
import { TestLinesTableComponent } from './components/testlines-table.component';

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Angular 2.4.3, Windows 7

* **Table version:** 0.7.x
The newest

* **Angular version:** 2.0.x
2.4.3

* **Browser:** [all ]

**Comment by PatrickHuetter** [comment]
I've the same problem. Imports in this syntax don't work (they are failing while building for prod):
import { NgxDatatableModule } from '@swimlane/ngx-datatable';

`Module not found: Error: Can't resolve '@swimlane/ngx-datatable' in '/var/www/src/app/myAppName/pages/firstpage'
`

**Comment by jfinci1** [comment]
Same problem. on Angular 2.4.6

**Comment by PatrickHuetter** [comment]
For workaround purposes i'm doing this right now within my component (its working with this, but you have to use node 6.9, using node > 6.9 it's not working this way):
`import "style-loader!@swimlane/ngx-datatable/release/material.css";`

**Comment by jfinci1** [comment]
Not really sure how to provide greater more info or a demo- doesn't seem to be possible to use latest angular in a plunkr.  For the dev's- simply npm to latest angular and you will see this

**Comment by amcdnl** [comment]
Ah yes, the CSS issues. We are working on that.

**Comment by amcdnl** [comment]
CSS issue is fixed now.

**Comment by AbdurRKhalid** [comment]
No, It has not been Fixed the Same Error

 This likely means that the library (@swimlane/ngx-datatable) which declares NgxDatatableModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer versi
on of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

Is Occuring with Angular 10, with IVY.

**Comment by RezaRahmati** [comment]
same error with angular 11

**Comment by simply-simpy** [comment]
Make sure that the selector defined in app.component matches the selector in the index.html.

Creating an angular app via the CLI provides the selector of `<app-root>` in the index.html file, while the code provided in https://swimlane.gitbook.io/ngx-datatable/getting-started `app.component.ts` uses `<app>`.

**Comment by RezaRahmati** [comment]
@simply-simpy issue with ng 11, is resolved in v19
