### ISSUE TITLE
scroll to page

### ISSUE THREAD

**Issue by istiti** [swimlane/ngx-datatable#443]
ENAHNCEMENT: I use virtual scroll, is there any solution to scroll to certain page ? goToPage(p) or go to  a certain offset of scroll ?

**Comment by amcdnl** [comment]
The pager should do this, but a new api for it would be nice :)

**Comment by istiti** [comment]
@amcdnl yes but Can I do it programatically ? how can I go to 5 page from class?

**Comment by amcdnl** [comment]
Look at this line: https://github.com/swimlane/ngx-datatable/blob/master/src/components/datatable.component.ts#L815

**Comment by deeg** [comment]
This can be done currently by grabbing ahold of the DatatableComponent and manually setting the offset.

[Take a look at an example here](https://github.com/deeg/angular2-data-table/blob/1f334cdb821a0c18649feb495f23d2d0368a8bbe/demo/basic/filter.ts#L74)

[See discussion on the topic here](https://github.com/swimlane/ngx-datatable/pull/565#issue-210368740)
