### ISSUE TITLE
Hovering table header triggers change detection

### ISSUE THREAD

**Issue by tsm91** [swimlane/ngx-datatable#445]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here
```

**Current behavior**

Hovering and moving my mouse on the header of my table (with or w/o custom header template) triggers the `getCol` (see below) method like 50-100 times.

**Expected behavior**

Not to do it :D

**Reproduction of the problem**

You use a getter function like `<ngx-datatable-column [name]=getCol(index: number, name: string)` and as a side effect do a console.log in `getCol`, check console while hovering over different areas of your datatable. Hover the header cells and voila. You get like 100+ console.log in no time.

Here is a table cell:

```ts
<ngx-datatable-column [name]="getCol(1, 'name')" [sortable]="getCol(1, 'sortable')" [prop]="getCol(1, 'prop')" [minWidth]="175" [width]="175">
  <template let-row="row" ngx-datatable-cell-template>{{ getCellValue(row, 1) }}</template>
</ngx-datatable-column>
```

Note i only see a bunch of `getCol(/([0-23])/, 'name|sortable|prop')` in the logs. `getCellValue` does not gets invoked a lot of times, only properties of `ngx-datatable-column` template.

With a table got 25+ cols, 2000 rows externally paginated (depending on the filters it can be more) I measure about 20-25 FPS while scrolling the table horizontally in prod mode on staging environment with AOT built files built with angular-cli. Which is ofc not ideal.

Any ideas how to mitigate this problem? 

I've tried adding `changeDetection: ChangeDetectionStrategy.OnPush`, to `DatatableComponent`, `DataTableHeaderComponent`, `DataTableHeaderCellComponent`, `DataTableBodyComponent` and `DataTableBodyCellComponent`. I still got a sh1tload of logs in console.

ping @amcdnl

**Comment by amcdnl** [comment]
Don't use functions in your column definitions. That will make it 1000x better since it has to run those on EVERY zone change.

**Comment by tsm91** [comment]
had 3 function calls per column, had 21 columns. it solved the problem

`<ngx-datatable-column [name]="getCol(0, 'name')" [sortable]="getCol(0, 'sortable')" [prop]="getCol(0, 'prop')" `

=>

`<ngx-datatable-column [name]="cols[0]['name']" [sortable]="cols[0]['sortable']" [prop]="cols[0]['prop']" [minWidth]="150" [width]="150">`

it still is not 60fps though, with 100 rows per page

**Comment by amcdnl** [comment]
Did you try putting it angular production mode rather than dev mode?
