### ISSUE TITLE
Column shows only empty fields after setting Table Column Options

### ISSUE THREAD

**Issue by 3HMonkey** [swimlane/ngx-datatable#448]
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If I set a table column option to 'name', the whole column will be empty.

**Expected behavior**
I want to set the table column option to 'name' to be able to sort the entries.

**Reproduction of the problem**
I followed the guide of ngx-datatable and I came to the example table. So I tried to test it with the given entries:
`
export class AppComponent {
rows = [
{ name: 'Austin', gender: 'Male', company: 'Swimlane' },
{ name: 'Dany', gender: 'Male', company: 'KFC' },
{ name: 'Molly', gender: 'Female', company: 'Burger King' },
];
columns = [
{ prop: 'name' },
{ name: 'Gender' },
{ name: 'Company' }
];
}
`
This was working like charm. Sorting was running etc. Afterwards I gave it a try by using own data.
For example: 
`[
  {
    "TAG": "DimProduct",
    "NAME": "Produkt",
    "COMM": "Produktdimension"
  },
  {
    "TAG": "DimTime",
    "NAME": "Zeit",
    "COMM": "Zeitdimension"
  },
  {
    "TAG": "DimChannel",
    "NAME": "Verkaufskanal",
    "COMM": "Verkaufskanaldimension"
  }
]`

So as you can see that the struct is nearly the same.
Then I edited the columns to fact my entries:
`
[
    { prop: 'TAG' },
    { prop: 'NAME' },
    { prop: 'COMM' }

  ]
`

This is also working fine. But what if I try to sort something? Then I need to switch one field property to 'name' instead of 'prop'. If I do this, the table shows the whole Column with empty fields. All other columns are working.

**What is the motivation / use case for changing the behavior?**
My motivation is to find a solution for this :)

**Please tell us about your environment:**
Windows 10, PHPStorm, ng, npm, Apache/XAMPP(no matter in this case), Angular2CLI

* **Table version:** 0.7.x
always latest

* **Angular version:** 2.0.x
always latest, AngularCLI

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

Really, really thank you for your time!!!

**Comment by amcdnl** [comment]
Use `prop`, `name` is only for display name. 

If no `prop` is defined it will automatically camel case name.

**Comment by ramkict** [comment]
Hi, i have a data like this
[ {Name:'Carl', Gender:'Male'}, {Name:'Dany', Gender: 'Male'}]

and i provided prop, name and both but still the table is blank.  

Please help
