### ISSUE TITLE
One column width fixed width, the rest: force

### ISSUE THREAD

**Issue by web265p3** [swimlane/ngx-datatable#449]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I need one very small field on the left side of my table. This should always have 30px width. The other columns should have "force". This does not seem to be possible right now, or am I wrong?

**Comment by amcdnl** [comment]
See: https://swimlane.gitbooks.io/ngx-datatable/api/column/inputs.html#canautoresize-boolean
