### ISSUE TITLE
Observable.js.map not found (Build warning in Webpack)

### ISSUE THREAD

**Issue by actra-gschuster** [swimlane/ngx-datatable#451]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When included by `import { NgxDatatableModule } from '@swimlane/ngx-datatable';` Webpack gives an error:
> WARNING in ./~/@swimlane/ngx-datatable/release/index.js
> Cannot find SourceMap 'Observable.js.map': Error: Can't resolve './Observable.js.map' in '/home/[...]/node_modules/@swimlane/ngx-datatable/release'

**Expected behavior**

No warning message should appear.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Arch Linux, Chromium

* **Table version:** 0.7.x

5.0.0

* **Angular version:** 2.0.x

4.0.0-beta.2

* **Browser:** [all]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.4

**Comment by achimha** [comment]
The problem is that ngx-datatable uses `Observable.map` but your application does not add the operator to `Observable`. What you need to do is

`import 'rxjs/add/operator/map';`

A cleaner solution would be if ngx-datatable did not depend on the patched `Observable` but instead import the operators as functions like this:

`import { map } from 'rxjs/operator/map';`

and then do

`map.call(observable, ....)`

**Comment by actra-gschuster** [comment]
I think you misunderstood the problem, ".map" means the JS mapping file, not the Observable operator.

**Comment by amcdnl** [comment]
This is generated dynamically by the build, not sure how I can fix this.

**Comment by actra-gschuster** [comment]
Waht build tools do you use so I can investigate a little the next days?

**Comment by amcdnl** [comment]
Look in the package.json package step.

**Comment by actra-gschuster** [comment]
Maybe you could try adding the following to config/replace.js:
```
var baseRegex = '\\s*[@#]\\s*sourceMappingURL\\s*=\\s*([^\\s]*)';
replace({
  regex: '(//' + baseRegex + '($|\n|\r\n?)|/\\*' + baseRegex + '\\s*\\*/)',
  replacement: '',
  paths: ['./release'],
  recursive: true,
  silent: false
});
```

Code is untested, I'm under stress with a client's project ^^

**Comment by Torqode** [comment]
I was getting this error when running my app's unit tests, but not during the dev or AoT builds.  I ended up adding the repo to the list of excluded folders for the source-map-loader.  Definitely not the desired course of action, but at least I can run unit tests again.

```
{
    enforce: 'pre',
    test: /\.js$/,
    use: ['source-map-loader'],
    exclude: [
    // these packages have problems with their sourcemaps
    helpers.root('node_modules/rxjs'),
    helpers.root('node_modules/@angular'),
    helpers.root('node_modules/@swimlane/ngx-datatable'),
    ]
},
```
