### ISSUE TITLE
Column size calculation fails inside a grid system, e.g. with NG2-Admin "cards"

### ISSUE THREAD

**Issue by actra-gschuster** [swimlane/ngx-datatable#452]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Table's total width is calculated with the next parent of fixed size, in my case a container with 1.900px, thus it overflows (hidden) the direct parent container "card" in a Bootstrap4 / Ng2-Admin based theme.
While debugging recalculateDims() I found that with a delay the correct width was calculated and table width matched, without it the tables overflowed.

**Expected behavior**

Tables should default to 100% of the direct parent so all columns are visible.

**Reproduction of the problem**

Going to set up a plnkr as soon as I find some spare time...

**What is the motivation / use case for changing the behavior?**

Display tables correctly.

**Please tell us about your environment:**

Arch Linux, Chromium

* **Table version:** 0.7.x

5.0.0

* **Angular version:** 2.0.x

4.0.0-beta.2

* **Browser:** [Chrome XX | probably others ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.4

**Comment by amcdnl** [comment]
Please make a demo, can't do anything with what you provided. Once you post one, I'll reopen.
