### ISSUE TITLE
Virtual scroll doesn't work if headerHeight is set to 'auto'

### ISSUE THREAD

**Issue by PEsteves8** [swimlane/ngx-datatable#453]
Since the given plunkr doesn't seem to be working and that this is easily reproducible I'll just describe it.

I have a project in which the header can get quite big. They need to always show and the table is created dynamically. I set the headerHeight to 'auto', which words, despite a few bugs.

**The problem is that doing this prevents virtual scroll from working. But setting header height to an hardcoded value, say 100. It works fine.**

By the way, by having multiline headers (large height with text wrap), the bar used to drag columns and resize them is only as tall has the text, not as the cell size.

Thanks.

**Comment by amcdnl** [comment]
I cant calculate the view port of the visible rows without having a fixed header/footer height in addition to the rows.
