### ISSUE TITLE
Programmatically set selection of a row

### ISSUE THREAD

**Issue by web265p3** [swimlane/ngx-datatable#454]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I am not quite sure if its already possible to set the selection programmatically. I already tried to access the data table component with ViewChild, but did not find any property to set. Can this already be handled?

**Expected behavior**

**Comment by amcdnl** [comment]
Update the `[selected]` array with your new selections.
