### ISSUE TITLE
css in icon.css conflicts with other libraries

### ISSUE THREAD

**Issue by nfdavenport** [swimlane/ngx-datatable#457]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

The class names or selectors used for the up and down (and likely other) icons are too generic and conflict with css used in other libraries/projects

.icon-up:before {
  content: "\65";
}
.icon-down:before {
  content: "\66";
}

**Expected behavior**
These classes should be namespaced to be specific to ngx-datatables.  So should the other libraries, but you can be the bigger man here.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Better compatibility with other ng2 libraries, projects, etc.

**Please tell us about your environment:**

* **Table version:** 0.7.x
Yes

* **Angular version:** 2.0.x
Yes

**Comment by amcdnl** [comment]
You don't have to use the icons, those are just for material base design. If you want to override, thats an option too.
