### ISSUE TITLE
inline edit autofocus

### ISSUE THREAD

**Issue by istiti** [swimlane/ngx-datatable#458]
In your demo (inline edit) when you dblclick to a column to switch to inline edit autofocus is applied correctly. but when you click (dblclick) in second row the input appear but don't receive autofocus event,  how fix? 

![inlineedit](https://cloud.githubusercontent.com/assets/2789203/22282527/46d621aa-e2dd-11e6-8925-0c6536eb3691.gif)

**Comment by amcdnl** [comment]
Not sure, didn't spend too much time on this demo just trying to show whats possible here. Its not a priority for me to implement this advanced type of inline editing.
