### ISSUE TITLE
scroll to

### ISSUE THREAD

**Issue by istiti** [swimlane/ngx-datatable#460]
ENHANCEMENT: 
I already open this issue https://github.com/swimlane/ngx-datatable/issues/443

but here is a litle bit different, many times on our virtual scroll we work wit a large set of data and actualy I have highly requirement to scroll until a certain `row.$$index ` this will be very interesting I don't know if it's possible but how can we have some method like` scrollTo(this.rows[1000])` to scroll directly to this line ?

**Comment by deeg** [comment]
This can be done currently by grabbing ahold of the DatatableComponent and manually setting the offset.

[Take a look at an example here](https://github.com/deeg/angular2-data-table/blob/1f334cdb821a0c18649feb495f23d2d0368a8bbe/demo/basic/filter.ts#L74)

[See discussion on the topic here](https://github.com/swimlane/ngx-datatable/pull/565#issue-210368740)
