### ISSUE TITLE
Resize crash on iOS Safari

### ISSUE THREAD

**Issue by achimha** [swimlane/ngx-datatable#461]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
While scrolling the page with a datatable on it, iOS 10.2 Safari, an exception is thrown when the "resize" event of the datatable is invoked but no column object is passed.

**Reproduction of the problem**
Scroll a page vertically that has a datatable on it that does not fit on the screen vertically. The datatable itself is not scrolled, the page is.

**Please tell us about your environment:**
iOS 10.2, iPhone SE simulator in Xcode.

* **Table version:** 0.7.x
6.0.0

* **Angular version:** 2.0.x
2.4.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Safari iOS 10.2

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.4

The event does not have a `column` member. A simple fix would check for that but probably it should be done where the event is emitted?

![screen shot 2017-01-26 at 11 46 32](https://cloud.githubusercontent.com/assets/6816140/22328544/211d63a2-e3bd-11e6-943f-b926e0598dc2.png)

**Comment by istiti** [comment]
same issue

**Comment by achimha** [comment]
This seems to do the job to work around the issue. Not sure it's the right thing to do though...

https://github.com/achimha/ngx-datatable/commit/0e4c678e648c4d575a7658b97e14b6bcf908ad95

**Comment by achimha** [comment]
Created a PR, please merge https://github.com/swimlane/ngx-datatable/pull/514

**Comment by amcdnl** [comment]
Merged :)
