### ISSUE TITLE
Better feedback on Checkbox selection

### ISSUE THREAD

**Issue by aMedh** [swimlane/ngx-datatable#463]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Checkbox selection:
When you check the checkbox on the header, all rows get selected in the background but not marked in the table.

**Expected behavior**

- When you check the checkbox on the header, all rows should get marked in the table.
- When you uncheck the checkbox on the header, all rows should get unmarked in the table.
- When you check the checkbox on the header and uncheck one random row, the header row should get unmarked in the table.
- When you check all the rows manually, header row should get marked in the table.

If you dont want to implement this feature, an alternative solution is acceptable:
A way to mark and unmark (visually) the header checkbox from code. This  enables implementation of all the other scenarios above.

**What is the motivation / use case for changing the behavior?**
Better control and feedback of checkbox selection.

* **Table version:** 0.7.x
5.0.0

* **Angular version:** 2.0.x
2.0.4

* **Browser:**
all

* **Language:**
all

**Comment by bheda91** [comment]
Any update on this?

**Comment by prithusah** [comment]
Would be a pretty cool feature...  any update would be apprecited guys

**Comment by arlowhite** [comment]
@amcdnl I think you can resolve this. This is how it works now.

http://swimlane.github.io/ngx-datatable/#chkbox-selection

**Comment by aMedh** [comment]
Super! Great work! Thank you!
