### ISSUE TITLE
update row

### ISSUE THREAD

**Issue by istiti** [swimlane/ngx-datatable#467]
I use last version 6 and I want update one row of my rows data..
So I fetch new row value from server and I simply apply: 
```
createNewDocument(row, currentInput){
    this.apiService.createDocument(currentInput.value.trim()).subscribe(res => {

      this.rows[row.$$index] = res[0]  // this not update my table why ?
      
    }, (err)=>{
      alert(err.json().msg)
    })
  }
```

I debug with chrome, after affectation my `this.rows[0` object is realy affected but table not show me change, why ?

**Comment by achimha** [comment]
try the following:

```
let rows = [...this.rows];
rows[index] = newValue;
this.rows = rows;
```
Always work with immutable properties in Angular 2.

**Comment by istiti** [comment]
I succeed with Object.assign() but if my solution not works with deepth object I will try yours but not sure your version worsk because of $$index this will be kost if neeValue don't have this property

**Comment by amcdnl** [comment]
Thanks! Maybe we should put this in the docs or a demo?
