### ISSUE TITLE
IterableDiffer needs one argument

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ngx-datatable#478]
node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts(409,16): error TS2314: Generic type 'IterableDiffer<V>' requires 1 type argument(s).

angular 4.0.0-beta.5
@swimlane/ngx-datatable 6.0.1

**Comment by alanpurple** [comment]
doesn't occur with 6.0.0

**Comment by amcdnl** [comment]
We don't support Angular4 yet.

**Comment by alanpurple** [comment]
@amcdnl  thx
anyway this can be modified by simply changing rowDiffer: IterableDiffer to rowDiffer:KeyValueDiffer<{}.{}>

**Comment by amcdnl** [comment]
Can you PR that?

**Comment by alanpurple** [comment]
I just did

**Comment by hellosandeep** [comment]
@amcdnl,
thanks for giving good data control **ngx-datatable**, i have used in my project, for few never feature i need to update angular 4, so when can we expect new release of  **ngx-datatable** support angular 4.

thanks.

**Comment by hellosandeep** [comment]
for the time being any one can comment // rowDiffer: IterableDiffer;
