### ISSUE TITLE
Support for multi-rows header

### ISSUE THREAD

**Issue by yuvalbl** [swimlane/ngx-datatable#485]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

No support for multi-rows header (or not documnated)

**Expected behavior**

The docs doesn't specify this. 
I would like some of the the table spread on multiple rows(see image) and still allow sorting, filtering etc.
Maybe it's already supported (just not documanted)
See my [stackoverflow question on this topic](http://stackoverflow.com/questions/42007065/is-there-an-option-for-2-rows-header-in-ngx-datatable-angular2)
![ngxdatatable_2rows_headers](https://cloud.githubusercontent.com/assets/11487010/22558226/9ccd063e-e975-11e6-835b-de8903efd2cf.jpg)

**Please tell us about your environment:**

Linux ubuntu, webstorm

* **Table version:** 0.7.x

6.0.2

* **Angular version:** 2.0.x

2.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome 56

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by yuvalbl** [comment]
@amcdnl seems like this request [already exist](https://github.com/swimlane/ngx-datatable/issues/407) with a different (lower) priority.

**Comment by olaf89** [comment]
It would be awsome

**Comment by kuncevic** [comment]
I am also wondering how would you add something like row-detail but in to header so I can expand that and apply filtering options e.g http://www.morevisibility.com/blogs/analytics/wp-content/uploads/2009/11/filters02.jpg

**Comment by macintoshplus** [comment]
HI,

Thanks for your nice work and library.
I have need create one data table with 2 headers (sortable) per column. 

Are you an idea for how to make this ?

Thanks in advance.

**Comment by amcdnl** [comment]
Closing this as dupe. Lets move the convo to the issue mentioned above.

**Comment by subodhkalika** [comment]
This could be helpful #1665
