### ISSUE TITLE
Delete buttons in columns, how to do it? 

### ISSUE THREAD

**Issue by tomaszcysewski** [swimlane/ngx-datatable#489]
**I'm submitting a ..**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
tables without buttons in columns

**Expected behavior**
deleting rows and sending something on click of button in colum

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
make it more popular

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

```

    <ngx-datatable
      class='material'
      [columns]="columns"
      [columnMode]="'force'"
      [headerHeight]="50"
      [footerHeight]="50"
      [rowHeight]="'auto'"
      [limit]="10"
      [rows]='rows'>
      <ngx-datatable-column name="Name" [width]="300"></ngx-datatable-column>
      <ngx-datatable-column name="Gender"></ngx-datatable-column>
      <ngx-datatable-column name="Age"></ngx-datatable-column>
      <ngx-datatable-column name="Options">
        <button md-raised-button color="warn">Delete</button>
      </ngx-datatable-column>
      
    </ngx-datatable>
```

Nothings happens, can somebody write code for this? I would write ngFor and so on but this table is not very customizable and I need only this feature. Thanks in advance.

**Comment by pixelsailor** [comment]
I believe the only way to do what you want is to use custom templates... https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-dom.ts

Here's a look at the HTML I'm using to add actionable buttons per item
```
<ngx-datatable-column name="Actions" sortable="false" prop="id">
    <template let-column="column" let-sort="sortFn" ngx-datatable-header-template>
        {{column.name}}
    </template>
    <template let-row="row" let-value="value" ngx-datatable-cell-template>
        <button md-icon-button (click)="blockAgents(value)" [disabled]="row['status']==='BLOCKED'">
            <i class="fa fa-ban"></i>
        </button>
        <button md-icon-button (click)="approveAgent(value)" [disabled]="row['status']==='APPROVED'">
            <i class="fa fa-check"></i>
        </button>
    </template>
</ngx-datatable-column>
```
I'm using the `prop` attribute to pass the id value through the function. Button availability is accessed via the `let-row` attribute

**Comment by marjan-georgiev** [comment]
Correct, use templates as @pixelsailor showed.

**Comment by aloysius-tim** [comment]
Hey guys,
I can't see any documentation on the customs templates ! Would be great to have one.

**Comment by Badhumvee** [comment]
Any working example plunker and document with custom template will be helpful.

**Comment by liambarnett** [comment]
+1 on the custom template documentation - can't find any documentation on embedding dropdown lists into cells.

**Comment by bhushangahire** [comment]
Can we just add the template for Action Column and have data column to work as is? I just want to keep code cleaner.

**Comment by jarodsmk** [comment]
Came across this issue thread while trying to look for a similar issue:

> I believe you can accomplish what you're looking for by using custom templates... 
> https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-dom.ts
The link is dead

Tried implementing something like:
``<ng-template #actionTmpl let-column="column" let-row="row" let-value="value">
``                    <div class="fa fa-times" (click)="doSomething()">
``                    </div>
``                </ng-template>
But the DOM seems to rerender it a couple times per second making the button unusable?
Anyone have a solution using the ng-template directive?

**Comment by vinyoliver** [comment]
Does any one ever made this work? Same problem here...

**Comment by m4limo** [comment]
@vinyoliver 
just use the ng-tamplate: 

```       
<ngx-datatable-column name="Actions" sortable="false" prop="id">
      <ng-template let-row="row" let-value="value" ngx-datatable-cell-template>

            <button md-icon-button (click)="blockAgents(value)">
              <i class="fa fa-ban"></i>
            </button>

            <button md-icon-button (click)="approveAgent(value)">
              <i class="fa fa-check"></i>
            </button>

      </ng-template>
</ngx-datatable-column>
```
`value` corresponds to the property `prop` you define in `ngx-datatable-column`, in this case `id`

hope this helps...

**Comment by vinyoliver** [comment]
thanks @m4limo i got it working!

**Comment by kevinding0218** [comment]
thanks @m4limo !, but does that mean we had to hard-code other columns in html? If I don't do that, there would only be one "Action" column in the table...

**Comment by kevinding0218** [comment]
My bad, it can still dynamically load the columns by using *ngFor

**Comment by TheSachin** [comment]
Hi here is the link for the custom templates.
[https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-obj.component.ts](https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-obj.component.ts)

**Comment by babolinGiordano** [comment]
Hello Guys,
I tried to add a new column in the end of my table and it working, but my data are gone why?
My code is 
```
<ngx-datatable class="bootstrap" [cssClasses]="cssClasses" [rows]="data" [columns]="columns" [columnMode]="'force'" [reorderable]="true"
            [headerHeight]="50" [footerHeight]="50" [rowHeight]="30" [externalSorting]="true" [externalPaging]="true" [limit]="search.page.size"
            [count]="search.page.totalElements" [offset]="search.page.pageNumber-1" (page)='doFooterPagination($event)' [selectionType]="'single'"
            (sort)="onSort($event)" (select)="onSelect($event)">

            <ngx-datatable-column name="Actions" sortable="false" prop="id">
              <ng-template let-row="row" let-value="value" ngx-datatable-cell-template>

                <button md-icon-button (click)="blockAgents(value)">
                  <i class="fa fa-ban"></i>
                </button>

              </ng-template>
            </ngx-datatable-column>

          </ngx-datatable>
```

**Comment by jarodsmk** [comment]
@babolinGiordano - is this related to having the delete button in a column? 

If not, rather create an individual issue please

**Comment by babolinGiordano** [comment]
@jarodsmk yes is related to have a delete button in new column for every rows.

**Comment by jarodsmk** [comment]
Oh OK cool - from what I can tell the ng-template you've added is overriding all of your data from displaying, could you show your 'columns' variable?

**Comment by babolinGiordano** [comment]
This is my columns variable

```
 const columns = [
      { name: this.titoloLabel, prop: 'nomeCorso', minWidth: 380, draggable: false },
      {
        name: this.dataInizioLabel, prop: 'dataInizio', cellTemplate: this.dataTpl,
        headerClass: 'custom-datatable-header', cellClass: 'custom-datatable-cell', draggable: false
      },
      {
        name: this.dataFineLabel, prop: 'dataFine', cellTemplate: this.dataTpl,
        headerClass: 'custom-datatable-header', cellClass: 'custom-datatable-cell', draggable: false
      }
    ];
    this.columns = columns;
```

**Comment by babolinGiordano** [comment]
EDIT:
IF I use this code:
```
<ngx-datatable-column *ngFor="let col of columns" [name]="col.name">
            </ngx-datatable-column>
            <ngx-datatable-column name="Actions" sortable="false" prop="id">
              <ng-template let-row="data" let-value="value" ngx-datatable-cell-template>
                <button md-icon-button>
                  <i class="fa fa-ban"></i>
                </button>
              </ng-template>
</ngx-datatable-column>

```
The 'Action' column appear but only some data are presented and I don't understand why.

![tabella](https://user-images.githubusercontent.com/383085/40429790-cbe4ea96-5ea3-11e8-8ead-dc2697441d4a.png)

**Comment by Yogeshwar1992** [comment]
any update?

**Comment by Yogeshwar1992** [comment]
@babolinGiordano ,

working perfectly, thanks, for me none of the colum details missing :)

**Comment by ryanhalley** [comment]
@babolinGiordano I had to add [prop]="col.prop" to the ngx-datatable-column, so each col knows which field to map to, where the field name does not exactly match the column name. e.g in my columns definition I have { name: 'Subject' }, { name: 'Created at', prop: 'created_at' } - only the Subject column will appear by default until you add the code change, since the prop is implied.

**Comment by dtarvin** [comment]
Does the code discussed above actually delete the row data or just hide it? I need to actually delete the row data and send that back to the server so it's deleted there also.

**Comment by larini** [comment]
So easy to make a table using html, why this is so complicated?

**Comment by biborn** [comment]
> EDIT:
> IF I use this code:
> 
> ```
> <ngx-datatable-column *ngFor="let col of columns" [name]="col.name">
>             </ngx-datatable-column>
>             <ngx-datatable-column name="Actions" sortable="false" prop="id">
>               <ng-template let-row="data" let-value="value" ngx-datatable-cell-template>
>                 <button md-icon-button>
>                   <i class="fa fa-ban"></i>
>                 </button>
>               </ng-template>
> </ngx-datatable-column>
> ```
> The 'Action' column appear but only some data are presented and I don't understand why.
> 
> ![tabella](https://user-images.githubusercontent.com/383085/40429790-cbe4ea96-5ea3-11e8-8ead-dc2697441d4a.png)

@babolinGiordano You forgot to specify the prop binding in your `<ngx-datatable-column>` like so:

`<ngx-datatable-column *ngFor="let col of columns" [name]="col.name" [prop]="col.prop"></ngx-datatable-column>`

Doing that will bring back the data for each columns on every rows.

**Comment by BMLande** [comment]
https://stackblitz.com/edit/ngx-datatable-add-extra-colom-with-action

**Comment by uds214125** [comment]
@BMLande  Thanks, saved my day

**Comment by rick-romero** [comment]
It doesn't work if you are using pipes on the Column object. :(

columns = [
    { prop: 'name' },
    { name: 'Gender', pipe: this.emulatePipe() },
    { name: 'Company', sortable: false }
  ];


  emulatePipe () {
    return {
      transform(value){
        return 'changed!';
      }
    };
  }

**Comment by nhaancs** [comment]
> https://stackblitz.com/edit/ngx-datatable-add-extra-colom-with-action

Thanks @BMLande, you save my day. 
Just a little bit correction for people come after that the following code `let-row="data"` must be updated to `let-row="row"` in case you want obtain the value of the row.

Before: 
` <ng-template let-row="data" let-value="value" ngx-datatable-cell-template>`
After:
` <ng-template let-row="row" let-value="value" ngx-datatable-cell-template>`
