### ISSUE TITLE
Text should be selectable by default

### ISSUE THREAD

**Issue by pixelsailor** [swimlane/ngx-datatable#491]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Unable to select text within the table

**Expected behavior**

User should select (and copy) text as normal browser behavior

**What is the motivation / use case for changing the behavior?**

Setting `.ngx-datatable .data-table-body-cell { user-select: none }` seems highly opinionated. As it's a simple CSS rule, it should be left up to the user. Forcing the developer to overwrite it to return default behavior is counter-intuitive.

**Comment by istiti** [comment]
+1

**Comment by rickdroio** [comment]
Is there any other way to do it instead CSS?

**Comment by istiti** [comment]
@rickdroio 
```
/* allow selection  */
:host /deep/ .datatable .datatable-body-cell{
  -webkit-user-select: initial!important;
  -moz-user-select: initial!important;
  -ms-user-select: initial!important;
  -o-user-select: initial!important;
  user-select:initial!important; }
```

**Comment by amcdnl** [comment]
There is a specific reason I did this, I can not remember though :S ....

**Comment by tzejohn** [comment]
@istiti I had to change the class from `.datatable` to `.ngx-datatable` to get it to work.

**Comment by leolorenzoluis** [comment]
@amcdnl  Is the reason because of drag and drop?

**Comment by tstackhouse** [comment]
@bheda91 It's probably related to how the table output is achieved, it is using a series of divs and other elements as opposed to an HTML `<table>` element.  I'd wager that Excel handles pasting HTML data with a table properly, is the use case you've described.

**Comment by manojkumardesai** [comment]
@tzejohn  Where did you add the styling? It doesn't seem to work for me :(
