### ISSUE TITLE
Support Columns with numeric prop values. (for simple array rows)

### ISSUE THREAD

**Issue by arlowhite** [swimlane/ngx-datatable#493]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Setting a Column prop to a numeric value results in an exception.

> TypeError: path.split is not a function
>     at Object.deepValueGetter (index.js:5627)

**Expected behavior**

Users should be able to use numeric prop values.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Some data is formatted as arrays, not a list of JSON objects. Also, this format is more efficient for large amounts of data.

**Please tell us about your environment:**

* **Table version:** 6.0.2

* **Angular version:** 2.4.5

* **Browser:** all

* **Language:** all

**Proposal**

If you don't have the time, I can work on a solution and submit a PR.
This just involves changing  `deepValueGetter`

**Comment by arlowhite** [comment]
See PR #494

**Comment by amcdnl** [comment]
Merged.
