### ISSUE TITLE
Columns cannot be resized if their label overlaps resize-handle

### ISSUE THREAD

**Issue by arlowhite** [swimlane/ngx-datatable#496]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Column resize-handle cannot be grabbed when column text overlaps it.

**Expected behavior**

Should always be able to drag resize handle.

**Reproduction of the problem**

Go to the demo: http://swimlane.github.io/ngx-datatable/#
Drag a column smaller so that the column label does not fit.
Now you cannot drag the column again!

**What is the motivation / use case for changing the behavior?**

Should always be able to resize columns.

**Please tell us about your environment:**

* **Table version:** 6.0.2

* **Angular version:** 2.4.6

* **Browser:** Chrome, Firefox

* **Language:** NA

**FIX**

Just set **z-index** on `.resize-handle`
Not sure what value you should use though.

**Comment by smoke** [comment]
I have noticed this too, way better fix would be to just put the .resize-handle element right after the content of the cell.
Having a z-index would cause more issues than it solves.
In a schematic representation (can't look the exact code right now, sorry) it is rendered like so:
```
<th><span class="resize-handler"></span><span class="header-content">Name</span></th>
```
->
```
<th><span class="header-content">Name</span><span class="resize-handler"></span></th>
```

**Comment by amcdnl** [comment]
Resizable is added at the header component here - https://github.com/swimlane/ngx-datatable/blob/master/src/components/header/header.component.ts#L22 ... which renders here https://www.screencast.com/t/BlVc1LL4Rbg

**Comment by smoke** [comment]
You may have noticed or not that I filled a pull request that fixes this https://github.com/swimlane/ngx-datatable/pull/521
