### ISSUE TITLE
Show selection count at footer

### ISSUE THREAD

**Issue by wndproc1** [swimlane/ngx-datatable#500]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If there are many rows, it is hard to identify how many rows are selected currently.

**Expected behavior**
It would be great if the currently selected row count is displayed at the footer, next by the total count.
Example:
23 selected / 340 total

**Reproduction of the problem**
N/A

**What is the motivation / use case for changing the behavior?**
See "Current behavior" and "Expected behavior" above.

**Please tell us about your environment:**
Windows7, VSCode, angular-cli, Tomcat 8.5, ...

* **Table version:** 6.0.2

* **Angular version:** 2.4.6

* **Browser:** all

* **Language:** all

**Comment by deeg** [comment]
I believe this landed and can be closed. @amcdnl
