### ISSUE TITLE
How to prevent a row form been selected (activated) ?

### ISSUE THREAD

**Issue by webmatrixxxl** [swimlane/ngx-datatable#502]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

Hello, how can I prevent a row form been selected (activated) ?

**Comment by amcdnl** [comment]
See: https://github.com/swimlane/ngx-datatable/blob/master/docs/api/table/inputs.md#selectcheck ... there is a demo for this too.

**Comment by sujithsavithryma** [comment]
I have a scenario where I don't want to select a particular row according to a condition that is able to do with selectCheck.
But selectCheck sets the selected rows to empty and losing focus from the previously selected row.
Is there any way to prevent selecting a new row and keep the already selected row in active state?.

**Comment by PietroSulis** [comment]
> I have a scenario where I don't want to select a particular row according to a condition that is able to do with selectCheck. But selectCheck sets the selected rows to empty and losing focus from the previously selected row. Is there any way to prevent selecting a new row and keep the already selected row in active state?.

I have the same problem, could you find a way to address it?

**Comment by Metalride** [comment]
Hi, I have the same scenario and I did it using the event (activate) by this way :
`onActivate(event: any): void {
    if (this.isLoading) {
      event.event.preventDefault();
      this.selected[0] = this.selectedItem;
    }
  }`
`(activate)="onActivate($event)"`

I hope this help you
Regards

**Comment by PietroSulis** [comment]
> 

Thanks for the answer but it doesn't seem to work: hovering is not gone. 
My current solution operates on the OnSelect but hovering is still present even if no rows can be selected.
Can you please post a video?
