### ISSUE TITLE
datatable-header-cell-wrapper & headerTemplate HTML layout

### ISSUE THREAD

**Issue by arlowhite** [swimlane/ngx-datatable#504]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When using column.headerTemplate, an empty `span.datatable-header-cell-wrapper` is created.

**Expected behavior**

`.datatable-header-cell-wrapper` should wrap the headerTemplate, or not be rendered.

**Reproduction of the problem**

Goto http://swimlane.github.io/ngx-datatable/#
TemplateRef example.
Inspect column.
You will see an empty span in front of template.

**What is the motivation / use case for changing the behavior?**

Simplify HTML.

**Please tell us about your environment:**

* **Table version:** 6.0.2

* **Angular version:** 2.4.7

* **Browser:** all

* **Language:** TypeScript 2.1.5

* **Relevant Code: header-cell.component.ts**
```html
    <div>
      <label
        *ngIf="isCheckboxable" 
        class="datatable-checkbox">
        <input 
          type="checkbox"
          [attr.checked]="allRowsSelected"
          (change)="select.emit(!allRowsSelected)" 
        />
      </label>
      <span class="datatable-header-cell-wrapper">
        <span
          class="datatable-header-cell-label draggable"
          *ngIf="!column.headerTemplate"
          (click)="onSort()"
          [innerHTML]="name">
        </span>
      </span>
      <template
        *ngIf="column.headerTemplate"
        [ngTemplateOutlet]="column.headerTemplate"
        [ngOutletContext]="{ 
          column: column, 
          sortDir: sortDir,
          sortFn: sortFn
        }">
      </template>
      <span
        [class]="sortClass">
      </span>
    </div>
  `,
```

**Comment by arlowhite** [comment]
`*ngIf="!column.headerTemplate"` should be moved up to `.datatable-header-cell-wrapper` span, or maybe template should be nested in `span.datatable-header-cell-wrapper`?

**Comment by amcdnl** [comment]
Ya, you are right. Can you PR that please?

**Comment by arlowhite** [comment]
Sure, I just don't know what the correct solution is as far as HTML/CSS structure.

Do you want `span.datatable-header-cell-wrapper` to wrap the template like this?
```html
<span class="datatable-header-cell-wrapper">
        <span
          class="datatable-header-cell-label draggable"
          *ngIf="!column.headerTemplate"
          (click)="onSort()"
          [innerHTML]="name">
        </span>
    <template
        *ngIf="column.headerTemplate"
        [ngTemplateOutlet]="column.headerTemplate"
        [ngOutletContext]="{ 
          column: column, 
          sortDir: sortDir,
          sortFn: sortFn
        }">
      </template>
</span>      
```

Or not render the `span.datatable-header-cell-wrapper` element at all when a headerTemplate is provided?

**Comment by amcdnl** [comment]
Ya, move the ngIf to this https://github.com/swimlane/ngx-datatable/blob/master/src/components/header/header-cell.component.ts#L21

**Comment by amcdnl** [comment]
Resolved in latest.
