### ISSUE TITLE
initial sort

### ISSUE THREAD

**Issue by yaotzin68** [swimlane/ngx-datatable#520]
Is there any way to get a initial sorting of one column? I'm running inside an ionic2 app
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The datatable is working fine, just cant make to get an initial sorting, this is my columns array
`this.columns  =
        [
          { prop: 'id'          , name:'#' , width:50 , minWidth:50},
          { prop: 'name'        , name: value['RANKING.CATEGORY'] },
          { prop: 'salesTy'     , name: value['RANKING.SALESTY']},
          { prop: 'salesLy'     , name: value['RANKING.SALESLY']},
          { prop: 'dailyInc'    , name: value['RANKING.DAILYINC']},
          { prop: 'dailyMargin' , name: value['RANKING.DAILYMAR']}
        ];`

**Expected behavior**
I want to get the table sorted by the  prop dailyMargin at the beginning by default, just work when I click

**Please tell us about your environment:**
Ionic2 app

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Resolved in latest by @marjan-georgiev
