### ISSUE TITLE
Selection lost when ngrx/store action dispatched

### ISSUE THREAD

**Issue by glendaviesnz** [swimlane/ngx-datatable#524]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I have a reasonably simple table set up getting data from ngrx/store with option to select single row. It all works as expected until I dispatch a store action in the onSelect method which causes the row to un-select in the UI. 

The selected row object still appears in the this.selected array but the selection wrappers disappear from the row - if I wrap the action dispatch in a setTimout the row selection is visible in the UI, but disappears as soon as action fired. The action isn't mutating the row data in any way. 

I have ChangeDetectionStrategy.OnPush set. 

Seems like the store.dispatch is firing some sort of onChange action in the table to cause the selection to be removed. 

Any ideas on how to best track down the cause of this?

**Expected behavior**
store.dispatch shouldn't affect row selection in UI.

**Please tell us about your environment:**
Windows, Visual Studio Code

* **Table version:** 0.7.x
6.1.2

* **Angular version:** 2.0.x
2.4.4

* **Browser:** [all ]

* **Language:** [ TypeScript 2.0 ]

**Comment by glendaviesnz** [comment]
Found a different way of structuring the component that avoids this issue so not worth investigating further at this stage.

**Comment by amcdnl** [comment]
@glendaviesnz - would you mind sharing details?

**Comment by glendaviesnz** [comment]
@amcdnl  - I was pushed for time last week, so  just decided that for the sake of the prototype app I was working on that the row selection was just transient so could be kept in component state rather than pushing to the ngrx store. If you think this is worth following up though I might have time this week to re-implement issue if you can give me some clues on best way to debug.
