### ISSUE TITLE
Perform sorting when sort icon is clicked

### ISSUE THREAD

**Issue by KiselN** [swimlane/ngx-datatable#536]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When sort icon is pressed sorting is not performed

**Expected behavior**

Sort table when sort icon is clicked

**Reproduction of the problem**

Can be seen in the official demo http://swimlane.github.io/ngx-datatable/

**What is the motivation / use case for changing the behavior?**

This is a usability issue. User generally expects that icon click will sort the table. It should behave the same way as header click

**Please tell us about your environment:**

* **Table version:** 0.7.x

6.1.2
* **Angular version:** 2.0.x

2.4.7
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

This must be an easy change so it's a matter whether you agree with me on the issue

**Comment by amcdnl** [comment]
Done :)

**Comment by sharduul** [comment]
I updated to version 6.3.0 and it was fixed. Thanks.

**Comment by jayaJai92** [comment]
Event i am facing the same issue..Could you please let me know how you people resolved this issue in ng-x datatable
