### ISSUE TITLE
i need Pager to Improvement

### ISSUE THREAD

**Issue by finalxcode** [swimlane/ngx-datatable#539]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Expected behavior**

when i use the  `ngx-datatable`, i need Pager own this ability to enter page number to jump to the page i want to go to.

**Please tell us about your environment:**
@angular/cli: 1.0.0-beta.31
node: 6.9.4
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
"@swimlane/ngx-datatable": "^6.1.2"

**Comment by amcdnl** [comment]
Please fill out the form and follow the guidelines for submitting requests.

**Comment by finalxcode** [comment]
OK

**Comment by finalxcode** [comment]
@achimha OK
