### ISSUE TITLE
pager need to  improvement support input page number to jump

### ISSUE THREAD

**Issue by finalxcode** [swimlane/ngx-datatable#547]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

      none

**Expected behavior**

     when i use the ngx-datatable, i need Pager own this ability to enter page number to jump to the page i want to go to.

**Reproduction of the problem**

      none

**What is the motivation / use case for changing the behavior?**

      i know which page i want to view data, so i just only want to input page number to jump

**Please tell us about your environment:**

     node: 6.9.4
     os: win32 x64
     nginx:1.0x

* **Table version:** 0.7.x

     "ag-grid": "^8.0.1",
     "ag-grid-ng2": "^8.0.0"

* **Angular version:** 2.0.x

     @angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "@angular/cli": "1.0.0-beta.31",
    "@angular/compiler-cli": "^2.4.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

      Chrome 56.0.2924.87 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
     TypeScript 2.0
     ES5

**Comment by amcdnl** [comment]
Interesting idea. I think we might want to make the pager customizable via a template. We won't be able to support every case like this.

**Comment by finalxcode** [comment]
Thanks very much, i really appreciate your job, when do you plan to support this new feature?

**Comment by amcdnl** [comment]
Shouldn't be too hard if you would like to PR it. Instead of rendering this: https://github.com/swimlane/ngx-datatable/blob/master/src/components/footer/footer.component.ts#L11-L28 just use ng-content to to put in the footer projectino.

**Comment by tsm91** [comment]
> Interesting idea. I think we might want to make the pager customizable via a template

it would be more useful to create a "service" for this, like `this.dtable.setPage(3)`, u dont need to anticipate internal logic, just manipulate `rows `, like `setPage(n){if(n < rows.length  / limit){..}}`

it would be nice to manipulate the table via a service, not just by tpl bindings

**Comment by finalxcode** [comment]
@amcdnl but when i use  `datatable-pager` component in my module, which is conflict with your `NgxDatatableModule`, and how to add myself input property to `datatable-pager`

**Comment by amcdnl** [comment]
Can be accomplished with custom footer in v8.2.0
