### ISSUE TITLE
externalPaging error

### ISSUE THREAD

**Issue by GuofuHuang** [swimlane/ngx-datatable#550]
Everything works find until I set externalPaging to true, I want load daata from the server. '

![screen shot 2017-02-22 at 10 03 04 am](https://cloud.githubusercontent.com/assets/10643064/23219981/239a0a84-f8e6-11e6-9578-ab7d310ddb0e.png)

Error in ./DatatableComponent class DatatableComponent - inline template:33:8 caused by: Cannot read property '0' of undefined

Have any on met this problem before, I need some help!

**Comment by amcdnl** [comment]
Please make a demo and I'll reopen and investigate
