### ISSUE TITLE
Incorrect css theme file path for ngx-datatable in docs

### ISSUE THREAD

**Issue by btinoco** [swimlane/ngx-datatable#557]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The current docs say to add the links below to your style.css to get the ngx-datatable theme styles...

@import '/node_modules/@swimlane/ngx-datatable/release/material.css';

The path does not exists and it throws an error.

**Expected behavior**
The correct path should be the one below...

@import '/node_modules/@swimlane/ngx-datatable/release/**themes**/material.css';

**Reproduction of the problem**
This path does not exists: @import '/node_modules/@swimlane/ngx-datatable/release/material.css';  add the path to your style.css and it will throw an error.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7

* **Table version:** 0.7.x
6.3.0

* **Angular version:** 2.0.x
2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by amcdnl** [comment]
Can you PR this into the docs plz?

**Comment by btinoco** [comment]
Done #564
