### ISSUE TITLE
Inconsistent active page updates when performing client-side vertical scrolling

### ISSUE THREAD

**Issue by tw3** [swimlane/ngx-datatable#559]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

The active page is updated automatically when when client-side page updates and client-side vertical scrolling are enabled.  The active page reaches an inconsistent state when scrolling up and down across page divides. This can be seen on the ngx-datatable demo page:

1) Go to http://swimlane.github.io/ngx-datatable/
2) Click "Sorting > Client-side" in the left navigation
3) Scroll down until "Netur" is barely visible.  The active page is page 2.
4) Scroll up slightly.  The active page is page 3.
5) Scroll back down slightly.  The active page is page 2.

The active page should not increase from page 2 to page 3 when scrolling up.  The active page should not decrease when scrolling down.

**Expected behavior**

The page number should be consistent.  When you scroll up the active page should either stay the same or decrease.  When you scroll down the active page should either stay the same or increase.

**Reproduction of the problem**

This can be seen on the ngx-datatable demo page:

1) Go to http://swimlane.github.io/ngx-datatable/
2) Click "Sorting > Client-side" in the left navigation
3) Scroll down until "Netur" is barely visible.  The active page is page 2.
4) Scroll up slightly.  The active page is page 3.
5) Scroll back down slightly.  The active page is page 2.

**What is the motivation / use case for changing the behavior?**

The motivation is showing a page change that is consistent with the scrolling direction.

**Please tell us about your environment:**

Win 7, PhpStorm, npm, node.

* **Table version:** 0.7.x

6.3.0

* **Angular version:** 2.0.x

2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

I am going to submit a suggested fix for this.

**Comment by tw3** [comment]
OK I'm new to the process of contributing to an open source project.  What's the best process to contribute code changes?  Fork?  Branch?  I did a branch but I'm getting a 403 error when I try to push the change.

The code change I'm trying to submit is simple.  In `src/components/body/body.component.ts` line 301 (`updatePage()`) I propose that:

`offset = Math.ceil(offset);`

(rather than `Math.floor()`) when scrolling up.

**Comment by amcdnl** [comment]
Fork and do a PR back please :)

**Comment by tsm91** [comment]
do server side sorting

i think this regression was recently introduced (in the past ~6 weeks)

back then 

, when i was checking the docs this worked fine

**Comment by tw3** [comment]
I created a pull request for the suggested change:

https://github.com/swimlane/ngx-datatable/pull/569

**Comment by deeg** [comment]
@amcdnl, I believe this landed and can be closed unless there was an issue with the fix.
