### ISSUE TITLE
dragging column results in rendering the dragged column multiple times

### ISSUE THREAD

**Issue by andrewphillipheil** [swimlane/ngx-datatable#562]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

in your demo: http://swimlane.github.io/ngx-datatable/#

before the drag: 
columns = name, gender, company

drag column "Company" from the far right to the left.  
columns are now "Company, Company, Name" - it appears that the company gets cloned and dropped over each droppable location

**Expected behavior**

No duplicate columns for dragging and dropping

**Reproduction of the problem**

http://swimlane.github.io/ngx-datatable/ - on your own website.

**What is the motivation / use case for changing the behavior?**

Dragging and droping

**Please tell us about your environment:**

Mac, Chrome

* **Table version:** 0.7.x

It's your demo

* **Angular version:** 2.0.x

It's your demo

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

It's your demo

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
It's your demo

**Comment by amcdnl** [comment]
The demo page was old, this is fixed in latest

**Comment by andrewphillipheil** [comment]
"6.3.0" is the latest right? still happening for me?

**Comment by amcdnl** [comment]
I looked on the demos, didn't see it there.
