### ISSUE TITLE
Experiencing "userPipe.transform is not a function" when adding pipe property

### ISSUE THREAD

**Issue by chriseenberg** [swimlane/ngx-datatable#567]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When adding ` columns = [{ name: 'Usage date', prop: 'localUsageDate', pipe: 'date' }]`

i get the following error `userPipe.transform is not a function.`

Am i missing something in how to use this property or is this a bug?

**Expected behavior**

I'd expect the property to be formatted as a date.

**What is the motivation / use case for changing the behavior?**

??

**Please tell us about your environment:**

MacOS Sierra - Visual studio code - angular v. 2.4.x  - "@swimlane/ngx-datatable": "^6.3.0",

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript version ~2.0.3

UPDATE:
I've made the error go away by adding userPipe as property, and adding a pipe function as the value like this -> `{ name: 'Usage date', prop: 'localUsageDate', userPipe: this.datePipeFunc }` and the function looks like this ` 
datePipeFunc: Function = (val: any) => {
        var pipe = new DatePipe('da-dk');
        return pipe.transform(val, 'medium');
    };
` though nothing happens to the value - no pipe transform.
Any pointers?

Kind regards Chris

**Comment by gerhardboer** [comment]
You need to pass in a pipe, or at least a class that acts like a pipe.

In a project i work on i just made a new class which implements the PipeTransform interface. I did not make an Angular Pipe out of it, since i don't need it in other templates (yet).
In the transform function i have the same setup as the code you have written in the update, but for my language.

Then i import that class, make a new instance and pass it to the pipe property.

**Comment by chriseenberg** [comment]
Thanks that works! Closing the issue.

**Comment by amcdnl** [comment]
@chriseenberg - can u make a PR for the docs for this?

**Comment by chriseenberg** [comment]
I'll have a go at it when i get some spare time. Quite busy at work these couple of days. :)

**Comment by mcblum** [comment]
@chriseenberg hey I'm having the same issue! From what I can tell I've followed the directions, but I'm still getting the error. My pipe looks like this:

```
import {Pipe, PipeTransform} from '@angular/core';

@Pipe({name: 'ticketingStatus'})
export class TicketingStatus implements PipeTransform {
    transform(value: boolean): string {
        switch (value) {
            case true:
                return 'Active';
            default:
                return 'Inactive';
        }
    }
}
```

I'm passing this in like so:

```
  public columns = [
        {
            name: 'Event Name',
            prop: 'name'
        },
        {
            name: 'Ticketing Active',
            prop: 'ticketing',
            pipe: TicketingStatus
        }
    ];
```

I'm not sure what I'm missing here! Any help would be greatly appreciated.

Thanks!

**Comment by jkon** [comment]
Is there a way to pass in a second parameter to the transform function? I have a custom pipe I made and I would like to be able to reuse the pipe other places, so I want to add a second parameter to the pipe's transform function. But if I do that, I can't take advantage of the second param when I pass it to the datatable columns, or at least I don't know how to. If this is possible, please let me know, thanks
