### ISSUE TITLE
How to display multi column-values in one column ?

### ISSUE THREAD

**Issue by fanttm** [swimlane/ngx-datatable#572]
**I'm submitting a ...**  
[x] support request

**Current behavior**
Now I know I can display user info as below:
```
<ngx-datatable
  ......
  <ngx-datatable-column name="Id" prop="id"></ngx-datatable-column>
  <ngx-datatable-column name="First Name" prop="first_name"></ngx-datatable-column>
  <ngx-datatable-column name="Last Name" prop="last_name"></ngx-datatable-column>
  ......
</ngx-datatable>
```

**Expected behavior**
And I hope to display as below:
`<a href="http://example.com/user/{{id}}">{{first_name}} {{last_name}}</a>`

How can I organize the code ?

**Comment by amcdnl** [comment]
Check out the demos, we show this there - https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-dom.ts#L28

**Comment by duard** [comment]
I need this too and I dont find anything about how to do this.
