### ISSUE TITLE
Sort Arrows on columns are reversed

### ISSUE THREAD

**Issue by csy9** [swimlane/ngx-datatable#574]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
**Current behavior**

Clicking on a sortable column will make an arrow indicating sort direction appear.  Right now, the 'asc' arrow points down, and the 'desc' arrow points up.

**Expected behavior**

The 'asc' arrow should point up, and the 'desc' arrow should point down.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
See: https://github.com/swimlane/ngx-datatable/issues/400
