### ISSUE TITLE
Columns duplicate when dragging to re-order more than one column away from original position

### ISSUE THREAD

**Issue by Dedac** [swimlane/ngx-datatable#576]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When dragging columns (see demos that are draggable), if you drag a column more than one column away, that column is duplicated in the grid.  If you drag it further away from its original position, you can get multiple column duplications
**Expected behavior**

columns are not duplicated on drag to re-order

**Reproduction of the problem**

http://swimlane.github.io/ngx-datatable/#
The full screen demo makes it easy to reproduce.

**What is the motivation / use case for changing the behavior?**

Users only want one of each column

**Please tell us about your environment:**

* **Table version:** 0.7.x

6.3.0

* **Angular version:** 2.0.x

Whatever you have on the demo site

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Safari

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by gerhardboer** [comment]
I have a fix for this and submitted the pull-request #563 .
I don't know why it hasn't been merged yet, maybe they want to see what Angular v4 fixes for them before they merge bigger pull-requests.

If you have this issue in a real world application (not just the demo's), maybe you could check if my changes fix the issue for you?

**Comment by Dedac** [comment]
Sorry, I didn't see the original bug after seeing that bug #562 was closed.  This is a duplicate of bug #497. 
@amcdnl, is there any reason you are not merging PR #563?

**Comment by Dedac** [comment]
If it matters this and the dynamic pinning are still problems in angular 4 rc2

**Comment by gerhardboer** [comment]
@Dedac 
it's cool. I was commenting to get more traction on my pull-request :)

**Comment by amcdnl** [comment]
Merged @gerhardboer - Please retest :)
