### ISSUE TITLE
On opening of row detail,the data which is displayed is not in grid form.

### ISSUE THREAD

**Issue by aasthas-optimus** [swimlane/ngx-datatable#577]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I'm trying to replicate the demo for the detail row example. Everything works as it should (main rows display ok, I can toggle detail rows and data is displayed under current row, etc.

**Expected behavior**
However the data which is displayed after opening of  detail row is not in columns(grid form).

**Reproduction of the problem**
Its a feature request about the data which is displayed under row detail should be displayed in grid form.

**What is the motivation / use case for changing the behavior?**
Data which is displayed under row detail should be in grid form(in columns).

**Please tell us about your environment:**

* **Table version:** 0.7.x
6.3.0

* **Angular version:** 2.0.x
2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 
all

* **Language:** 
Typescript 2.0.3

**Comment by amcdnl** [comment]
You can pass your own templates so it can be whatever you want.
