### ISSUE TITLE
Default external sort

### ISSUE THREAD

**Issue by dland512** [swimlane/ngx-datatable#578]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

**Current behavior**
I have a grid with a date/time column. My understanding is that in order to sort by that column, I must use `[externalSorting]="true"` and `(sort)="mySortingFunction()"` and provide my own custom sort, which I have done and it works fine.

The issue I'm having is that I want the default sort for the grid to be based on that date column. I tried using `[sorts]="[{ prop: 'createTime', dir: 'desc' }]"` but it has no effect.

I could probably write some code to call my sorting function manually when the grid is first loaded, but I wanted to see if the grid supports anything like that out of the box.

**Expected behavior**
It might be good for the `[sorts]` property to be able to work in conjunction with the `(sort)` property to call your external sorting method for you initially.

**Please tell us about your environment:**
macOS 10.12.3, Chrome

* **Table version:** 6.3.0

* **Angular version:** 2.4.8

**Comment by deeg** [comment]
@dland512 you don't have to use externalSorting=true unless the sorting is being done by a server request. This would be typical if you are not loading all of the data at once, but are rather using a paging scheme from the server.

If you are loading all of your data upfront, you want externalSorting = false, with a [custom comparator](https://swimlane.gitbooks.io/ngx-datatable/content/api/column/inputs.html#comparator) on the column.

That along with [the sorts input](https://swimlane.gitbooks.io/ngx-datatable/content/api/table/inputs.html#sorts) should allow you to start with a default sort.

If you are actually using external sorting, then the server should return the data already sorted by that column, and the inputs should be used to tell the table how the sort started.

@amcdnl, I believe this can be closed.

**Comment by dland512** [comment]
@deeg, thank you for the info, I will give that a shot.

**Comment by diwasUIman** [comment]
Hi,
I am new to Angular and ver new on datatables, how did you apply (sort)="mySortingFunction()". I am trying to sort number value column, but the ascending sort always takes null value in the beginning and i want them to be at the bottom.Can you help me on this?
