### ISSUE TITLE
How can I make ngx-datatable overflow visible (not scroll) ?

### ISSUE THREAD

**Issue by fanttm** [swimlane/ngx-datatable#581]
**I'm submitting a ...**  (check one with "x")
[x] support request => Please do not submit support request here

**Current behavior**
I can set datatable scroll by [scrollbarH]="true".

**Expected behavior**
I want to set datatable overflow visible.

**Comment by amcdnl** [comment]
Can you explain in more detail, perhaps just turn off scrollbarV and scrollbarH

**Comment by fanttm** [comment]
Sorry for the late reply. Need I create new issue?

I want to display table as below.
![qq 20170307102712](https://cloud.githubusercontent.com/assets/10293241/23639305/ef56a804-0321-11e7-89fd-e3a960b9e47d.png)

But I only can display as
![qq 20170307102803](https://cloud.githubusercontent.com/assets/10293241/23639313/0140a97a-0322-11e7-82fb-8e7a828118c9.png)

If I remove the property  [scrollbarH]="true", the overflow of table will be hidden.
How can I make table overflow visible, not scroll ?

**Comment by roberthelmick08** [comment]
Hi @fanttm, I think the property you want to use is ````[columnMode]="'flex'"````, which will size your columns to fit the window using the flex-grow API. So set columnMode to flex, and scrollbarH to false and let me know if that works. You may also try ````[columnMode]="'force'"```` to see if that suits your needs

*hint: don't forget the single quote inside the double quotes around flex
