### ISSUE TITLE
ng-template is not a known element

### ISSUE THREAD

**Issue by Csirme** [swimlane/ngx-datatable#584]
```
'<ngx-datatable></ngx-datatable>' Normal use
But
<ngx-datatable>
....
<ng-template></ng-template>
....
</ngx-datatable>
Error debug:

'ng-template' is not a known element.
```

**Comment by amcdnl** [comment]
Please use the bug template.

`ng-template` is Angular4. Are you using Angular4?

**Comment by Csirme** [comment]
@amcdnl 

I use the angular2.4,and what's the way to use template.where is  the angular 4???
sorry ,i code by the other computer.

**Comment by amcdnl** [comment]
In version 7.0, we upgraded the table to Angular4. If you wish to have the latest, you will need to update too.

**Comment by RawiaAhmed** [comment]
I'm having angular version 2.4.8 and ngx-datatable version 7.0.0, but still having the error
Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element

**Comment by TINITUS** [comment]
Get ngx-datatable version 6.3.0

**Comment by RawiaAhmed** [comment]
I had that version but I needed to upgrade because of an issue that is supposed to be fixed in version 7
https://github.com/swimlane/ngx-datatable/issues/559

**Comment by TINITUS** [comment]
Check the PR and update the 6.3.0 version you have with the code change introdused there. That is what I do as I am still on Angular 2.4

**Comment by balajiswaroop** [comment]
I am getting the below error.

**'ng-template' is not a known element:**

**package.json**

"primeng": "^2.0.4",
"@angular/core": "^2.4.0",

**app.module.ts**

Imported the below modules
DataTableModule,
SharedModule

Looks like its unable to find the module in which the "ng-template" directive is present.
Please help.

**Comment by TINITUS** [comment]
@balajiswaroop  You are using latest version of the ngx-datatable., which requires Angular 4. If you switch to 6.3.0 version that errror will be gone.

**Comment by savvasal** [comment]
@TINITUS how does it work to you? :-S

I just upgrade to 6.3 
`
        "@angular/common": "^2.4.0",
	"@swimlane/ngx-datatable": "^6.3.0"`        	

and it still to return the same error,

`'ng-template' is not a known element:`

Cheers
:beer:

**Comment by preservance717** [comment]
where is Angular4
