### ISSUE TITLE
How can I make table overflow visible ?

### ISSUE THREAD

**Issue by fanttm** [swimlane/ngx-datatable#585]
**I'm submitting a ...** [x] support request

**Current behavior**
Now I only can render table as below (use [scrollbarH]="true") 
(I use bootstrap.min.css and div class is "col-md-3 and col-md-9")
![qq 20170307102803](https://cloud.githubusercontent.com/assets/10293241/23639313/0140a97a-0322-11e7-82fb-8e7a828118c9.png)

**Expected behavior**

I want to render table as below in big screen (example 23 inch display).
![qq 20170307102712](https://cloud.githubusercontent.com/assets/10293241/23639305/ef56a804-0321-11e7-89fd-e3a960b9e47d.png)

If I remove the property  [scrollbarH]="true", the overflow of table will be hidden.
How can I make table overflow visible, not scroll ?

**Comment by amcdnl** [comment]
I don't understand your question. You want it to overflow but not scroll? You can achieve that with CSS unless I'm seeing this wrong.

**Comment by fanttm** [comment]
Thank you ! I know that this question is a little strange. yeh, I will achieve that with CSS.
