### ISSUE TITLE
where is the version 6.3.0's documents

### ISSUE THREAD

**Issue by Csirme** [swimlane/ngx-datatable#586]
**I'm submitting a ...**  (check one with "x")
```
the new document is 7.0 and i can't find the 6.3 document.
where, thank
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 6.3

* **Angular version:** 2.4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
the new document is 7.0 and i can't find the 6.3 document.
where, thank

**Comment by amcdnl** [comment]
The docs are part of the repo, every release we tag the repo so you can always find the docs for the version you are using there. :)
