### ISSUE TITLE
Expression has changed after it was checked

### ISSUE THREAD

**Issue by Csirme** [swimlane/ngx-datatable#587]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 6.3

* **Angular version:** 2.4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

-------------------------------------------
`
```
 <x-datatable-column>
              <ngx-datatable-column name="操作">
             <template let-value="value" let-row="row" ngx-datatable-cell-template>
                 <div>
                     <a (click)="this.editposition(row.PositionName);" style="color: #1985ac;cursor:pointer;">编辑</a><a (click)="rowclick(row);" style="color:red;margin-left: 10px;cursor: pointer;">删除</a>
                 </div>
           </template>
       <x-datatable-column>
```
-------------------------
```
 editposition(row) {
  this.modalService.open(PositionModal, { backdrop: 'static', keyboard: false });
}
```

the click function will error, debug info:
**_./DataTableBodyRowComponent class DataTableBodyRowComponent - inline template:9:8 caused by: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'._**
`

**Comment by m0squito** [comment]
@Csirme I am getting the same error. Have you resolved it?

**Comment by rogeru** [comment]
Same issue here. @Csirme, is there a fix for this since the issue has been closed?

Table version: 6.3
Angular version: 2.4.x

**Comment by ajaypatelaj** [comment]
Also facing the same issue. @Csirme, @rogeru  @m0squito  any solution you guys have found ?
