### ISSUE TITLE
mistyped "object" should be "Object" in deep-getter.d.ts

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ngx-datatable#588]
/**
 * Returns a deep object given a string. zoo['animal.type']
 * @param {Object} obj
 * @param {string} path
 */
export declare function deepValueGetter(obj: Object, path: string): Object | "";

Object should starts with capital letter as above

**Comment by amcdnl** [comment]
Can you make a PR plz?

**Comment by pensacola1989** [comment]
have you make a test before release 7.0? object should be "Object", Please fixed it soon

**Comment by litzebauer** [comment]
Looks like this is broken again

**Comment by amcdnl** [comment]
I was actually getting TSLINT telling me the opposite.
