### ISSUE TITLE
KeyValueDiffer is not generic

### ISSUE THREAD

**Issue by web265p3** [swimlane/ngx-datatable#591]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Current behavior**
After upgrading to Version 7.0.0 of this data table, I get the following error while compiling with webpack:

```
ERROR in [default] C:\Users\xxx\Documents\GitHub\Client\node_modules\@swimlane\ngx-datatable\release\components\datatable.c
omponent.d.ts:425:15
Type 'KeyValueDiffer' is not generic.
```

* **Angular version:**

My versions from package.json are:

    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",

**Comment by amcdnl** [comment]
Version 7.0 only supports Angular4. Please use 6.x branch.

**Comment by MorlaRamakrishna** [comment]
Which version is suitable for Angular 2.
