### ISSUE TITLE
Template parse errors: "let-" is only supported on template elements.

### ISSUE THREAD

**Issue by webmatrixxxl** [swimlane/ngx-datatable#592]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
https://cl.ly/210y3d1s2g1c
https://github.com/swimlane/ngx-datatable/blob/master/demo/columns/column-flex.ts As the demo si provided it should be working without error.

I need some way to set flexGrow.

**Expected behavior**
As the demo si provided it should be working without error.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.6.3

* **Angular version:** 2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.10

@angular/cli: 1.0.0-rc.0
node: 7.2.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/platform-server: 2.4.8
@angular/router: 3.4.8
@angular/compiler-cli: 2.4.8
@angular/cli: 1.0.0-rc.0

**Comment by webmatrixxxl** [comment]
As I investigate more I just have to to use <tamplate> instead of <ng-template>

**Comment by amcdnl** [comment]
The demo is for version 7 which is angular4.

**Comment by EddieBenji** [comment]
Where can I see a demo for version 6.x ? @amcdnl  ?

Thanks in advance!

**Comment by EddieBenji** [comment]
or.. what's the name of the branch/tag for version 6.3.0 of the ngx-datatable package @amcdnl ?

**Comment by EddieBenji** [comment]
Never mind, I found the tag branch (with the demos) for version 6.3.0

ICYI: https://github.com/swimlane/ngx-datatable/tree/6.3.0

**Comment by vforvasquez** [comment]
So I'm guessing if I have to use the 6.2 version and am wanting to replicate the 10K rows with scrolling demo I am just out of luck correct?
