### ISSUE TITLE
prop names with dots 

### ISSUE THREAD

**Issue by TINITUS** [swimlane/ngx-datatable#596]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When property names are with dot notation like from an elastic search :
"body.property.subproperty" the deep-getter fails to retrieve the value of the cell
**Expected behavior**

Deep-getter should have a check if obj[path] returns a value and if no then it can proceed in destructuring the path.
**Reproduction of the problem**
Provide an object with keys names in following format:
"main.property"
"main.property.subproperty"

**What is the motivation / use case for changing the behavior?**

when using the datatable with serverside Java elastic search  
**Please tell us about your environment:**

os: win32 x64
* **Table version:** 0.7.x
6.3.0
* **Angular version:** 2.0.x
@angular/cli: 1.0.0-rc.1
node: 6.9.2
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
If you do `[prop]="'foo.bar.cat'"` does it work? Can you provide a demo?

**Comment by TINITUS** [comment]
I am using columns array to set up columns as I need to provide those fromthe outside in order to create a generic grid list. That's why I haven't tested with template way of setting in columns. 
I will try to provide demo by the end of today.

**Comment by arlowhite** [comment]
Just FYI #494 changes valueGetter code a bit and renames **deep-getter.ts** to **column-prop-getters.ts**
So if #494 is merged when someone works on this, look for that file instead.

**Comment by TINITUS** [comment]
Sure, Arlowhite, I saw your PR but tnx for the notice.

**Comment by arlowhite** [comment]
My PR was just merged.  :)
So fixing this is just a few lines of code in **column-prop-getters.ts**

I will create a PR to fix this soon unless someone else says they're already working on it.

**Comment by amcdnl** [comment]
@arlowhite - did you have a chance to make this PR yet?
