### ISSUE TITLE
Rollup build instead of webpack

### ISSUE THREAD

**Issue by pauldaustin** [swimlane/ngx-datatable#599]
Quick summary: The package deployed to unpkg.com is a webpack build. Would it be possible to add a umd module build using rollup so that the package is similar to https://unpkg.com/@angular/core@2.4.8/bundles/ https://github.com/angular/angular/tree/master/packages/core?

**I'm submitting a ...**  (check one with "x")
```
[*] feature request
```

**Current behavior**
Library currently built with webpack fails when included in a rollup script.

```
'NgxDatatableModule' is not exported by node_modules/@swimlane/ngx-datatable/release/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
build/app/app.module.js (16:9)
```

**Expected behavior**
Include datatables in a rollup application

**Reproduction of the problem**
Include ngx-datatable in a rollup build

**What is the motivation / use case for changing the behavior?**
Webpack modules don't work well with other applications and require large monolithic downloads which fail on slow servers.

**Please tell us about your environment:**
Mac & Linux NPM

* **Table version:** 6.3.0

* **Angular version:** 2.4.9
2.4.

* **Browser:** all 

* **Language:** TypeScript 2.1

**Comment by amcdnl** [comment]
It does use UMD -> See: https://github.com/swimlane/ngx-datatable/blob/master/config/webpack.package.js#L39

**Comment by mgmarlow** [comment]
@amcdnl Perhaps one option is to export both the ES2015 modules and the UMD modules -- A library that I am consuming for my app does this: https://github.com/ng-lightning/ng-lightning/blob/master/gulpfile.js

**Comment by amcdnl** [comment]
Ya, after the talk at ngconf, I'm considering just rolling w/ es2015 modules.

**Comment by ronnyek** [comment]
Any updates on this one? I'm currently trying to wrap up something with ng-packagr and running into this same problem...
No name was provided for external module '@swimlane/ngx-datatable/index' in options.globals - guessing 'index'

**Comment by taras-bohdan** [comment]
@ronnyek I resolved same issue by adding:
```javascript
"externals": {
    "@swimlane/ngx-datatable": "ngxDatatable"
}
```
to `ng-package.json` based on https://github.com/dherges/ng-packagr/issues/119#issuecomment-327871092

> lib.externals is key-value pair of external dependencies of an Angular library. The key should be the import path (as used in TypeScript import {} from "" statement. The value should be the module ID for the UMD bundle.

in case of ngx-datatable UMD bundle name is `ngxDatatable` (based on https://github.com/swimlane/ngx-datatable/issues/599#issuecomment-286899739)
