### ISSUE TITLE
New set of columns added to table on every page action.

### ISSUE THREAD

**Issue by mjdikun** [swimlane/ngx-datatable#601]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I am getting a new set of duplicate columns added to the table every time I click on a new page in the table paging.
**Expected behavior**
Only have 1 set of the columns in the table.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7 64 bit.

* **Table version:** 0.7.x
0.9.3

* **Angular version:** 2.0.x
2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Can you please provide a demo?

**Comment by amcdnl** [comment]
Closing due to demo not provided and age of request.
