### ISSUE TITLE
ngx datatable for angular 2.4.x

### ISSUE THREAD

**Issue by hengkyz** [swimlane/ngx-datatable#604]
is this compatible with angular 2.4.x?

**Comment by TINITUS** [comment]
version 6.3.0 is

**Comment by hengkyz** [comment]
ok thank you i will try

**Comment by hengkyz** [comment]
Uncaught (in promise): Error: Error in :0:0 caused by: Cannot read property 'nativeElement' of undefined
i got that error
any idea?

**Comment by TINITUS** [comment]
can't tell without a demo. I personally havent got such of an error.
