### ISSUE TITLE
Support for Angular 2

### ISSUE THREAD

**Issue by rogeru** [swimlane/ngx-datatable#605]
**I'm submitting a issue to support Angular 2.**  
```
[x] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**
Error:
```
'ng-template' is not a known element
```
Since Angular 4 has renamed ng-template to template.
Refer to: https://github.com/softsimon/angular-2-dropdown-multiselect/issues/84

**Expected behavior**

**Reproduction of the problem**
Use ngx-datatable with Angular 2

**What is the motivation / use case for changing the behavior?**
While Angular 4 is still in rc I was hoping this great datatable would also be available in Angular 2.

**Please tell us about your environment:**
mac osx

* **Table version:** 0.7.x
7.0.0

* **Angular version:** 2.0.x
2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by rogeru** [comment]
Installed ngx-datatable 6.3.0 which supports Angular >=2.4.0 and all is good.

**Comment by ampolubalaji** [comment]
Thanks rogeru it works for me.

**Comment by arjayleviackerman24** [comment]
How can I install specific version of ngx-datatable. Im in angular 2 so I want to install ngx version 6.3

**Comment by rajsibi7** [comment]
Hi, am using version @swimlane/ngx-datatable": "7.2.1", works well in chrome browser, but in MAC safari its not working. Is there any fix for this ?
