### ISSUE TITLE
Drop support for Angular 2

### ISSUE THREAD

**Issue by kr3niu** [swimlane/ngx-datatable#606]
Does support for Angular 2.x has been discontinued?
Version 6.3.0 is last version and you didn't plan any bugfxing for project with still use Angular 2?

**Comment by TINITUS** [comment]
With Angular 4 comming out in a couple of weeks and probability for this to be an easy switch that probably will be the case. I too have a project started on ng2 version but will be switching to 4 once it comes out. So currently I do use the 6.3.0 datatable version and I apply fixes myself to the code. Like those for the dot props and serverside pagination.

**Comment by amcdnl** [comment]
1) Please fill out the form.
2) Given the imminent approaching date and the ease to upgrade, we have no plans to support 2.x at this moment.
