### ISSUE TITLE
Pointer mouse cursor appears for entire column header cell but only the text is clickable.

### ISSUE THREAD

**Issue by tw3** [swimlane/ngx-datatable#609]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

The "pointer" cursor appears when you hover anywhere over a column header cell.  However the only clickable/sortable area is directly over the column text.

**Expected behavior**

Make the pointer cursor accurately reflect the area that is clickable/sortable.  This means either:
a) Make the entire column cell clickable/sortable (preferred), or
b) Only show the pointer cursor when the mouse is directly over the column text

**Reproduction of the problem**

1) Go to the demo page:
    http://swimlane.github.io/ngx-datatable/
2) Click directly on the column text "Gender", the pointer cursort appears and the table sorts (good)
3) Click outside the column text "Gender" but within the Gender column, nothing happens but the pointer cursor still appears (confusing)

**What is the motivation / use case for changing the behavior?**

Improved usability

**Please tell us about your environment:**

Win 7, PhpStorm 2016.3.3

* **Table version:** 0.7.x

Latest

* **Angular version:** 2.0.x

Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Personally seen on Chrome and Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by ianhatton** [comment]
+1

**Comment by amcdnl** [comment]
Resolved in latest.
