### ISSUE TITLE
Refresh Data

### ISSUE THREAD

**Issue by misisriddle** [swimlane/ngx-datatable#619]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I added a row on my datagrid and saved it to the database but my datagrid content is not updating/updated. How do I refresh this?

**Expected behavior**

Datagrid contents will be updated with the new row.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

Angular 2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by amcdnl** [comment]
See this demo: https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/live.ts

It is live updating content, the grid will respond to result mutations. If that doesn't answer your question, let me know and i will reopen.

**Comment by murilobd** [comment]
hey @amcdnl the example you gave isn't working (http://swimlane.github.io/ngx-datatable/#live / https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/live.component.ts )

**Comment by amcdnl** [comment]
I need to push up my latest changes, trying to bunch a my changes up for this next release. Can you try in masteR?
