### ISSUE TITLE
Dead links in demo app

### ISSUE THREAD

**Issue by adammedford** [swimlane/ngx-datatable#622]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Clicking 'Source' link in header of demo app navigates to invalid url for the template demos

**Expected behavior**
Clicking link navigates to source code.

**Should be**
https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-dom.ts
https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-obj.ts
(added missing 's' in templates)

**Comment by amcdnl** [comment]
Thanks! Fixed!
