### ISSUE TITLE
Table (view) is not update when the rows is changed

### ISSUE THREAD

**Issue by youngzkyz** [swimlane/ngx-datatable#625]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I've a table which I update using a method like _editValue

 protected _editValue(index: number, value: Object){
       \\\\this.data.splice(index,1,value); same like this below
       this.data[index] = value;
 }

where

<ngx-datatable #datatable 
            class='material'
            [rows]="data"
            [columnMode]="'force'"
            [headerHeight]="40"
            [footerHeight]="50"
            [rowHeight]="40"
            [selectionType]="'single'"
            >
....
But the view (table) is not update since that I resize the window. Although the element is pushing in the array.

And But for delete and add are works fine. I've using this method
       this.data.splice(index,0,value);  -> for remove.
       this.data.push(value); -> for add.

**Expected behavior**
The view (table) and the array is updated with a changed element.

**What is the motivation / use case for changing the behavior?**
I need changed a table in real time for user interaction.

**Table version:** 6.1.2

**Angular version:** 2.4.7

**Browser:** all

**Language:** all

**Comment by ScottSpittle** [comment]
`
let myArr = [1, 2, 3];

//You have to do this when array is updated
let myNewArr = [4, 5, 6]
myArray = [...myNewArray]

//If you update a single row then do 
myArray = [...myArray]
`

**Comment by t-pankajkumar** [comment]
@ScottSpittle Still not working,
While inline editing the table rows are not getting updated.

**Comment by ScottSpittle** [comment]
@t-pankajkumar Ensure you are following this tutorial correctly https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/inline.component.ts

Without code snippets I won't be able to assist further
