### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by uroti** [swimlane/ngx-datatable#627]
Hello,
I installed ngx-datatable with this command `npm install @swimlane/ngx-datatable` but when I try to import it in `app.module.ts` and add `NgxDatatableModule` in the array `Imports` appears this error in the web console:

```
Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
        </span>
      </span>
      [ERROR ->]<ng-template
        *ngIf="column.headerTemplate"
        [ngTemplateOutlet]="column.headerTemplate""): DataTableHeaderCellComponent@20:6 ; Zone: <root> ; Task: Promise.then ; Value: Object { __zone_symbol__error: Error, fileName: Getter, lineNumber: Getter, columnNumber: Getter, message: Getter, name: Getter, stack: Getter, originalStack: Getter, zoneAwareStack: Getter, toString: createMethodProperty/props[key].value(), 5 more… } BaseError@http://localhost:4200/vendor.bundle.js:98003:9 [<root>]
SyntaxError@http://localhost:4200/vendor.bundle.js:10604:9 [<root>]
TemplateParser.prototype.parse@http://localhost:4200/vendor.bundle.js:24634:19 [<root>]
JitCompiler.prototype._compileTemplate@http://localhost:4200/vendor.bundle.js:60146:47 [<root>]
JitCompiler.prototype._compileComponents/<@http://localhost:4200/vendor.bundle.js:60029:56 [<root>]
JitCompiler.prototype._compileComponents@http://localhost:4200/vendor.bundle.js:60029:9 [<root>]
JitCompiler.prototype._compileModuleAndComponents/createResult@http://localhost:4200/vendor.bundle.js:59911:13 [<root>]
Zone.prototype.run@http://localhost:4200/polyfills.bundle.js:6369:24 [<root> => <root>]
scheduleResolveOrReject/<@http://localhost:4200/polyfills.bundle.js:6956:52 [<root>]
Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:6409:28 [<root> => <root>]
drainMicroTaskQueue@http://localhost:4200/polyfills.bundle.js:6789:25 [<root>]
  polyfills.bundle.js:6765:13
Object { __zone_symbol__error: Error, fileName: Getter, lineNumber: Getter, columnNumber: Getter, message: Getter, name: Getter, stack: Getter, originalStack: Getter, zoneAwareStack: Getter, toString: createMethodProperty/props[key].value(), 5 more… }  polyfills.bundle.js:6767:9
```
What is the problem?

Thank you

**Comment by askdesigners** [comment]
Ha I just had this error too. It looks like it's an angular version issue, but I'm not sure how to solve it. Going to look at the demo app now to see what versions of things are there...

**Comment by adammedford** [comment]
You need to upgrade to Angular 4 or downgrade to an older version of the datatable (I think something closer to version 5 would work)

Angular 4 deprecated the usage of <template> in favor of <ng-template> (but preserved backwards compatibility)

**Comment by uroti** [comment]
I'm new in Angular, which is the easier way? And how can I do it?

**Comment by adammedford** [comment]
This is pretty subjective. 

If it is a new project I'd advocate moving to Angular v4+ sooner rather than later as 3rd party libraries are already switching to it and it reduces your future breaking changes when you eventually do upgrade. 

With that said, the Angular docs haven't been updated to reflect all of the changes to Angular 4 so it might be harder to jump into (I doubt it though since not much has changed on the surface.)

You can find information about upgrading Angular 4 here: (you have to scroll way down to 4.0.0 to get close)
https://github.com/angular/angular/blob/master/CHANGELOG.md

If you choose to downgrade the Swimlane data table you're going to lose a lot of features. (I only know because this is the reason I upgraded to Angular 4 in the first place.)

**Comment by uroti** [comment]
Thank you, now it is works!

Is it possible to see the structure of the JSON file` company.json` used in the table's examples?

**Comment by adammedford** [comment]
http://swimlane.github.io/ngx-datatable/assets/data/company.json

**Comment by uroti** [comment]
Thank you!
