### ISSUE TITLE
Build error after upgrading to angular4 & ngx-datatable 7.1.0

### ISSUE THREAD

**Issue by alvinmeimoun** [swimlane/ngx-datatable#631]
Hi,

I just updated my project to angular 4 and ngx-datatable 7.1.0 but i got this error when i do ng serve

`node_modules/@swimlane/ngx-datatable/release/utils/deep-getter.d.ts (6,46): Cannot find name 'object'.`

Is it a release bug or i missed something with the update ?

**Comment by vixriihi** [comment]
update typescript to 2.2 to fix this

**Comment by alvinmeimoun** [comment]
Thanks it works, i think it was simply my browser cache because in npmjs the last version i see was 2.1.5, i opened the page from the release page on github typescript and i find that the last release is 2.2.1..

**Comment by vforvasquez** [comment]
I have a similar problem, but even after updating (to Version 2.2.1) I still have the same error along with others:

ERROR in C:/*my work path*/node_modules/@swimlane/ngx-datatable/release/utils/deep-getter.d.ts (6,46): Cannot find name 'object'.
C:/*my work path*/node_modules/@swimlane/ngx-datatable/release/utils/deep-getter.d.ts (6,69): Cannot find name 'object'.

ERROR in C:/*my work path*/node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts (425,16): Type 'KeyValueDiffer' is not generic.

I have already tried deleting, clearing cache, and re-installing. Any other ideas what might be the issue?
