### ISSUE TITLE
Build error after updating to Angular 4 and DataTable 7.1.0

### ISSUE THREAD

**Issue by vforvasquez** [swimlane/ngx-datatable#638]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
I have a similar issue to [https://github.com/swimlane/ngx-datatable/issues/631] (url) one except I get an error reading:

`/node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts (425,16): Type 'KeyValueDiffer' is not generic.`

I have updated to Typescript 2.2.1, as that was the issue with the other question. Any other ideas?

**Comment by amcdnl** [comment]
Are you on Angular2? >= 7.x is Angular4

**Comment by vforvasquez** [comment]
I updated to Angular 4 today so I believe I am. I just tried installing updates again (following these instructions - http://angularjs.blogspot.com/2017/03/angular-400-now-available.html ) . Now I'm seeing:
/@swimlane/ngx-datatable/release/components/datatable.component.d.ts (414,16): Generic type 'IterableDiffer<V>'
requires 1 type argument(s).

So I see that this is mentioned here - [https://github.com/swimlane/ngx-datatable/issues/478](other request). So I'm not really sure what happened. Should I still follow the recommendation from the other post of "simply changing rowDiffer: IterableDiffer to rowDiffer:KeyValueDiffer<{}.{}>" ?

**Comment by LaxmiNarasimha530** [comment]
i am also facing same issue any solution

**Comment by amcdnl** [comment]
Try on latest version w/ TypeScript 2.2

**Comment by chelaruc** [comment]
I have the same issue :(

Typescript: 2.2.0
<img width="81" alt="screen shot 2017-06-21 at 12 43 55" src="https://user-images.githubusercontent.com/22840626/27378072-629d6766-567f-11e7-8d15-b6df883a6ace.png">

Can you help me?
