### ISSUE TITLE
node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts

### ISSUE THREAD

**Issue by lsaballo** [swimlane/ngx-datatable#639]
After install and set up the component, I got this error TypeScript error
Type keyValueDiffer is not generic

node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts

line 425 rowDiffer: KeyValueDiffer<{},{}>

**Comment by lsaballo** [comment]
After install and set up the component, I got this error TypeScript error
Type keyValueDiffer is not generic

node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts

**Comment by amcdnl** [comment]
> 7.x is Angular4 only.
