### ISSUE TITLE
Error building after import ngx-datatable

### ISSUE THREAD

**Issue by duard** [swimlane/ngx-datatable#642]
Angular 2

ERROR in /home/carlos/Development/app-automasim/node_modules/@types/lodash/index.d.ts (19417,15): All declarations of 'WeakMap' must have identical type parameters.)

ERROR in /home/carlos/Development/app-automasim/node_modules/@swimlane/ngx-datatable/release/components/datatable.component.d.ts (425,16): Type 'KeyValueDiffer' is not generic.)
webpack: Failed to compile.

![screenshot from 2017-03-28 10-05-25](https://cloud.githubusercontent.com/assets/36894/24406248/26686602-139e-11e7-9447-ba25a9619c8d.png)

**Comment by adammedford** [comment]
Typically people will insist you follow the form provided to make sure you capture the necessary information.

Can you provide a screenshot of the import itself, possibly how you are using it? Other valuable information would be the version of Angular you are currently running (Angular 2 really only tells us it wasn't Angular 1; current Swimlane builds target Angular v4)

**Comment by duard** [comment]
Sorry,,
the problem was that I'm on Angular 2 and the npm is 7.0 + 
I change this to 6.0 and now everything works.]
Sorry man.

**Comment by adammedford** [comment]
All good, just trying to take some of the burden off the Swimlane team so they can give us more cool stuff.
