### ISSUE TITLE
HTML title attribute for column header should not be added when custom template is being used

### ISSUE THREAD

**Issue by arti040** [swimlane/ngx-datatable#643]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When you use ng2 template tag for column header, TITLE attribute is being added automatically.

**Expected behavior**
When you use ng2 template tag for column header, TITLE attribute shouldn't be added (or be configurable at least).

**Reproduction of the problem**
N-A.

**What is the motivation / use case for changing the behavior?**
This may confuse user, especially if any tooltip/popover plugin is being used within custom template.
Would be nice to have TITLE attribute in column headers configurable.

**Please tell us about your environment:**
N-A

* **Table version:** 0.7.1.1

* **Angular version:** 4.0

* **Browser:** 
All

* **Language:**
ES6/7

**Comment by amcdnl** [comment]
Good call, can you PR?

**Comment by eddy-geek** [comment]
@litzebauer is your commit above ready for PR or is it WIP?

**Comment by litzebauer** [comment]
@eddy-geek It's ready for PR
