### ISSUE TITLE
Progress bar implementation

### ISSUE THREAD

**Issue by askdesigners** [swimlane/ngx-datatable#644]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
It looks like the progress bar indicator is not fully implemented.

**Expected behavior**
It should accept a 0-1 number on an input and scale the bar's length accordingly.

**Reproduction of the problem**
Not implemented

**What is the motivation / use case for changing the behavior?**
I would like to use it. :)

**Please tell us about your environment:**
NA

* **Table version:** 6.3.0
Not in master branch anyways...

* **Angular version:** 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:**
All

**Comment by amcdnl** [comment]
The scrollbar is fully implemented per Indeterminate progress bar material design.

See: https://material.angularjs.org/latest/demo/progressLinear
