### ISSUE TITLE
Cannot find name 'object', TS dependency greater than required by Angular 4.0.0

### ISSUE THREAD

**Issue by jfinci1** [swimlane/ngx-datatable#646]
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here

Typescript does not recognize 'object' in 'deep-getter.d.ts'

The changelog mentions a requirement on > Angular 4, however Angular 4 has a TS dependency of 2.1.0.  The 'object' keyword is a feature of 2.2.0 and above.

Submitting the bug just to be clear in the changelog that there is a TS dependency greater than that required by Angular 4.0.0

* **Table version:** 0.7.x
7.1.1

* **Angular version:** 2.0.x
4.0.0

**Comment by dzena** [comment]
Are we safe to simply install TS 2.2.0?

**Comment by jfinci1** [comment]
Should be. I ran into no issues.

**Comment by amcdnl** [comment]
Yes, 2.2 is required for Angular4.

**Comment by canercandan** [comment]
I had to deal with the same issue and fixed it by upgrading those dependencies:

```diff
-    "ts-node": "~2.0.0",
+    "ts-node": "^3.0.2",
     "tslint": "~4.5.0",
-    "typescript": "~2.1.0",
-    "typings": "^2.1.0"
+    "typescript": "^2.2.2",
+    "typings": "^2.1.1"
```
