### ISSUE TITLE
Icon in header cell

### ISSUE THREAD

**Issue by Ruudn7** [swimlane/ngx-datatable#648]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

**Current behavior**
Hello, I have tried to put icon into column header cell, but I don't know how can I do it. Can anyone help me?

**Expected behavior**
There are no icon

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
**Please tell us about your environment:**
Windows 10

* **Table version:**
6.3.0

* **Angular version:**
2.4.10

* **Browser:** [all ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | ] Typescript 2.0.3

**Comment by adammedford** [comment]
The easiest way to do it is to use html in your column's name. 

For example using Font Awesome: 
```
columns = [ 
 { 
    // Prop represents the name of the property that holds this cell's value
    prop: 'description', 
    // Name represents the label for the column header.
    name: 'Description<i class="fa fa-warning"></i>'
}
]
```

The alternative is by providing a headerTemplate for the column, but it is much more involved if this is the only reason you need to do it.

**Comment by Ruudn7** [comment]
thank you very much for help Your help :)
