### ISSUE TITLE
how to replace the checkbox image

### ISSUE THREAD

**Issue by sergeu90** [swimlane/ngx-datatable#650]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
I need this for custom checkbox image 
**Current behavior**
The library generate 
```
<label class="datatable-checkbox">
        <input type="checkbox">
      </label>
```

**Expected behavior**
I want to 
```
<label class="datatable-checkbox"> </label>
<input type="checkbox">
```

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x
7.1.1

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by adammedford** [comment]
You can't currently unless you were to add a checkbox to your header template and build you own custom logic around that. 

What you're asking for falls under theming the datatable. It is much easier to change a stylesheet than it is to provide a solution that can be restructured to fit every stylesheet.

**Comment by adammedford** [comment]
If this is related to #645 you should probably close that issue as well.

**Comment by sergeu90** [comment]
> What you're asking for falls under theming the datatable. It is much easier to change a stylesheet than it is to provide a solution that can be restructured to fit every stylesheet.

@adammedford Show the code me, please.How to set a picture on the checkbox.

**Comment by adammedford** [comment]
If you link me the CSS framework you're using (Foundation/Material/Bootstrap/etc) I will fix it for you.

**Comment by sergeu90** [comment]
@adammedford  http://getbootstrap.com/getting-started/#download version 3.3.7.Thanks

**Comment by adammedford** [comment]
I don't understand what you're asking for. Bootstrap doesn't have a custom image that it uses for check boxes.

Are you using Swimlane's included Material theme? If you aren't using it then bootstrap checkboxes will appear as normal.

Also, Bootstrap's checkboxes are inside labels, not after them as you asked for.

**Comment by sergeu90** [comment]
@adammedford  I have done custom template cell and replace image how I want
