### ISSUE TITLE
Add Icon to a header cell and use Pipe in rows

### ISSUE THREAD

**Issue by Ruudn7** [swimlane/ngx-datatable#651]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here
```

**Current behavior**
Hello, I want to put icon in column header cell, and use a Pipe in row cell.

Pipe will count a length of row contain and add photo, when lenght is less then 4.
I can put icon to a header cell this way:
```

columns = [ 
 { 
    // Prop represents the name of the property that holds this cell's value
    prop: 'description', 
    // Name represents the label for the column header.
    name: 'Description<i class="fa fa-warning"></i>'
}
]
```

I found a few solutions but all of them using ng-template like this:

```
   <ngx-datatable-column name="facility" >
   	 <template let-columns="columns" ngx-datatable-cell-template>
            	{{columns}}
            </template>
       </ngx-datatable-column>
       <ngx-datatable-column name="system" >
            <template let-row="row" let-value="value" ngx-datatable-cell-template>            		{{value}}
            </template>
    </ngx-datatable-column>
```
In that way me columns declared in component:

```
	public columns=[
		{x},
		{y} ...
	]
```

were changed to a value from ngx-datable-column and icon disappears.  

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10

* **Table version:** 6.3.0

* **Angular version:** 2.4.10

* **Browser:** [all ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] Typescript 2.0.3

**Comment by adammedford** [comment]
I don't think I understand what you're saying here. Could you provide some screenshots? 


What is this supposed to do?
`<template let-columns="columns" ngx-datatable-cell-template>{{columns}} </template>`

You declare your columns on the outer ngx-datatable component. I don't think columns will populate here; I don't think Swimlane provides in in their ngx-datatable-cell-template OutletContext.

**Comment by Ruudn7** [comment]
Thank You vary much for hints, and sorry that I can't well describe my problem, also Your hint was very helpful.
