### ISSUE TITLE
How Can I add custom row dynamic before render cell

### ISSUE THREAD

**Issue by sergeu90** [swimlane/ngx-datatable#654]
I want to insert custom row when to render rows for grouping rows.Can I add program rows the conditional

**Comment by adammedford** [comment]
At best you can hack this feature together to get partial functionality. At worst it isn't possible. I have an idea of how to make this work but you either have to nest grids inside of detail rows or risk losing most of the grid functionality as a result. 

I believe this is a planned feature on the road map; not sure on any ETA.

**Comment by amcdnl** [comment]
Closing as dupe to row grouping.
