### ISSUE TITLE
Incorrect select/unselect all behavior for checkboxable column

### ISSUE THREAD

**Issue by nyankov** [swimlane/ngx-datatable#659]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Table with selectionType 'checkbox' and a column with checkboxable: true and headerCheckboxable: true.
If header checkbox is checked all rows are selected, which is fine. 
If unselect any row now,  the header checkbox stays checked.
If now click on the header check box the selection works incorrectly.

**Expected behavior**
If unselect a row the header checkbox should be unselected as well. 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Easier select/unselect all functionality

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm, IIS

* **Table version:** 0.7.x
7.1.1

* **Angular version:** 2.0.x
Angular 4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kvbhaskar7** [comment]
I am also facing the same issue. When selecting or unselecting the row header checkbox, its not selecting all the rows in the table or removing the selection. 

DEMO sample also has the same problem for reference - http://swimlane.github.io/ngx-datatable/#

**Comment by touqeershafi** [comment]
I'm getting the same problem, it's also appearing in official demo page as @kvbhaskar7 mentioned.

**Comment by tinyweasel** [comment]
I'm still having this issue with version 10.2.3, any reason it might still be happening?
