### ISSUE TITLE
Incompatible with server-side rendering

### ISSUE THREAD

**Issue by spiffyjr** [swimlane/ngx-datatable#668]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Usage of `document` throughout the project breaks server-side rendering.

e.g., `var testStyle = document.createElement('div').style;`

**Expected behavior**
Server-side rendering to build.

**Comment by amcdnl** [comment]
Pushed fixed, will be in next release.

**Comment by spiffyjr** [comment]
Excellent!
