### ISSUE TITLE
Match a row key to a col key

### ISSUE THREAD

**Issue by davidmontgom** [swimlane/ngx-datatable#670]
hedge_columns = [
           {name: 'wtf' },
           {name: 'WOW DUDE'}
      ]
  
      hedge_rows = [
    
           {
                "wtf": "Really?",
                "dude": 'omg!!!'
          }
           
      ]

...given the above...How on earth does one match a row to a column?  dude needs to map to "WOW DUDE"

Not clear from the docs dont you think?

**Comment by amcdnl** [comment]
Use `prop` ... see: https://swimlane.gitbooks.io/ngx-datatable/api/column/inputs.html#prop-string
