### ISSUE TITLE
Null text appear while add row details 

### ISSUE THREAD

**Issue by NahlaEssam** [swimlane/ngx-datatable#672]
**I'm submitting a ...**  
[x ] bug report 
[ ] feature request
[ ] support request 

**Current behavior**
While add row details it gave me null in the header On IE 

**Expected behavior** 
null text disappear in the header

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

![null error](https://cloud.githubusercontent.com/assets/7237940/24853951/f33d7670-1ddc-11e7-9901-f633d0f88fdc.PNG)

**Please tell us about your environment:**

* **Table version:** 0.7.1.1 

* **Angular version:** 4

* **Browser:** IE 11

* **Language:** TypeScript

**Comment by amcdnl** [comment]
Can you make a demo or put the code?

**Comment by adammedford** [comment]
This is IE specific; opened the current row detail demo in IE11 and reproduced. Top left corner shows 'nul' in the screenshot. 

Doesn't happen in Chrome though.

**Comment by NahlaEssam** [comment]
@amcdnl  as @adammedford  said just open the row details demo in IE 11 and you will find it

**Comment by RawiaAhmed** [comment]
@amcdnl I used the same code as in the demo here
https://github.com/swimlane/ngx-datatable/blob/master/demo/selection/selection-chkbox.component.ts
and the issue happens in IE11

**Comment by deeg** [comment]
If you do not give a column an empty name I have found that it shows null in IE.

I suggest try giving the column a name of empty string and should no longer see null. This could probably be solved in the library, but I decided just adding an empty name was less effort for me at the time.

**Comment by amcdnl** [comment]
Closing given @deeg workaround.
