### ISSUE TITLE
bug in ionic2 for videogular2

### ISSUE THREAD

**Issue by lalitdograldh** [swimlane/ngx-datatable#677]
typescript: ...wp-AngularApp/githubIonic/node_modules/videogular2/src/core/services/vg-api.d.ts, line: 1    
Cannot find type definition file for 'core-js'.                                                             
                                                                                                            
typescript: ...ngularApp/githubIonic/node_modules/videogular2/src/core/vg-media/i-playable.d.ts, line: 1    
import { EventEmitter } from '@angular/core';                                                               
import { IPlayable } from "../vg-media/i-playable";                                                         
                                                                                                            
Cannot find type definition file for 'core-js'.                                                             
                                                                                                            
import { Observable } from "rxjs/Observable";                                                               
export interface IPlayable {                                                                                
                                                                                                            
typescript: ...wp-AngularApp/githubIonic/node_modules/videogular2/src/core/services/vg-api.d.ts, line: 1    
Cannot find type definition file for 'core-js'.                                                             
                                                                                                            
typescript: ...ngularApp/githubIonic/node_modules/videogular2/src/core/vg-media/i-playable.d.ts, line: 1    
import { EventEmitter } from '@angular/core';                                                               
import { IPlayable } from "../vg-media/i-playable";                                                         
                                                                                                            
Cannot find type definition file for 'core-js'.                                                             
                                                                                                            
import { Observable } from "rxjs/Observable";                                                               
export interface IPlayable {

**Comment by amcdnl** [comment]
Fill out the form and provide examples.

**Comment by Elecash** [comment]
Just run npm install @types/core-js --save-dev
