### ISSUE TITLE
fix(doc) cellTemplate has column binding, not index

### ISSUE THREAD

**Issue by arlowhite** [swimlane/ngx-datatable#679]
**I'm submitting a ...**  (check one with "x")
```
[x] documentation bug report => search github for a similar issue or PR before submitting
```
The cell template example needs to be updated:
http://swimlane.github.io/ngx-datatable/#

Source link takes you to: https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-obj.component.ts
with this example for a cell template:
`<ng-template #editTmpl let-row="row" let-value="value" let-i="index">`

However, **index** is not a valid binding, it should be **column** instead.
**body-cell.component.ts**
```
      <ng-template
        *ngIf="column.cellTemplate"
        [ngTemplateOutlet]="column.cellTemplate"
        [ngOutletContext]="{ value: value, row: row, column: column }">
      </ng-template>
```

**Comment by amcdnl** [comment]
Fixed. Thanks!
