### ISSUE TITLE
Entire Column Header for reorderable

### ISSUE THREAD

**Issue by ronnyek** [swimlane/ngx-datatable#682]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
holding down mouse for a while, in header cell area, but not actually on the text for the header. The visuals for long press appear, and the cursor changes to cross hairs, but dragging does not work

**Expected behavior**
Columns would drag. I also think crosshairs dont appear when long pressing column header text.

**Reproduction of the problem**
http://plnkr.co/edit/vtAo2zzWFn8kFOGRH88r - just drag column without actually being immediately over the text.

**What is the motivation / use case for changing the behavior?**
Easier consumption by end users consuming this html content

**Please tell us about your environment:**

* **Table version:**
8.0

* **Angular version:**
4.0.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript2.2 angular4

**Comment by amcdnl** [comment]
We just need to remove the CSS style from this. You should only be able to drag the header text.
