### ISSUE TITLE
when import module NgxDatatableModule it gives 82 error

### ISSUE THREAD

**Issue by vipulupadhyay** [swimlane/ngx-datatable#687]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	23	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	12	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	12	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	13	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	13	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	14	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	14	
Error		Build:Unexpected token. A constructor, method, accessor, or property was expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	14	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	15	
Error		Build:',' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	20	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	21	
Error		Build:Expression expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	21	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	22	
Error		Build:Expression expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	22	
Error		Build:Expression expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	23	
Error		Build:',' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	24	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	24	
Error		Build:Expression expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	24	
Error		Build:',' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	25	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	25	
Error		Build:Expression expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	25	
Error		Build:',' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	26	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	26	
Error		Build:Expression expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	26	
Error		Build:',' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	27	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	27	
Error		Build:Expression expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	27	
Error		Build:',' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	28	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	28	
Error		Build:Declaration or statement expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-cell.component.d.ts	29	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-row.component.d.ts	11	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-row.component.d.ts	11	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-row.component.d.ts	13	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body-row.component.d.ts	13	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body.component.d.ts	25	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body.component.d.ts	25	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body.component.d.ts	44	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body.component.d.ts	44	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body.component.d.ts	54	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\body\body.component.d.ts	54	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	307	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	307	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	316	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	316	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	325	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	325	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	334	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	334	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	342	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	342	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	350	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	350	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	358	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	358	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	366	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	366	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	374	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	374	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	382	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	382	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	420	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\datatable.component.d.ts	420	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\footer\footer.component.d.ts	15	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\footer\footer.component.d.ts	15	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\footer\footer.component.d.ts	16	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\footer\footer.component.d.ts	16	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\footer\pager.component.d.ts	10	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\footer\pager.component.d.ts	10	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	14	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	14	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	15	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	15	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	16	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	16	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	17	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	17	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	18	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	18	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	19	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header-cell.component.d.ts	19	
Error		Build:'=' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header.component.d.ts	34	
Error		Build:';' expected.	WebApplication1Angular	E:\R And D\ProjectManagement\ProjectManagement\WebApplication1Angular\node_modules\@swimlane\ngx-datatable\release\components\header\header.component.d.ts	34	

installation of package im going to just import in module its give lots of error

**Comment by amcdnl** [comment]
1) Please fill out the form.
2) Please make a reproduction demo case, the error message isn't helpful :(

Once you do those, we can reopen and investigate.

**Comment by vipulupadhyay** [comment]
im just install packages NgxDatatable and just import in module it give error which one packege i have installed in my system
