### ISSUE TITLE
Failed import of module

### ISSUE THREAD

**Issue by tmburnell** [swimlane/ngx-datatable#688]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
webstore says it cant resolve NgxDatatableModule.  and the CLI fails to start

**Expected behavior**

**Reproduction of the problem**
this one will error: 
    import { NgxDatatableModule } from '@swimlane/ngx-datatable';
this one import works but had to add src:  
    import { NgxDatatableModule } from '@swimlane/ngx-datatable/src';

**What is the motivation / use case for changing the behavior?**
it would be cleaner to not have to put src

**Please tell us about your environment:**
webstorm

* **Table version:** 0.8.x
8

* **Angular version:** 2.0.x
angular4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
on build issue

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by tmburnell** [comment]
this might be related to: https://github.com/swimlane/ngx-datatable/issues/687

**Comment by arlowhite** [comment]
Angular 4.0.2, TypeScript 2.2.2, angular-cli 1.0, ngx-datatable 8.0.0 works fine for me.
What is "webstore"?

**Comment by tmburnell** [comment]
Sorry had a typo.  WebStorm.

also very odd. because i just rebuilt my job, without the src and it works now ... so I guess I will close my issue.
