### ISSUE TITLE
Configurable user-select css property

### ISSUE THREAD

**Issue by kasparsklavins** [swimlane/ngx-datatable#692]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Text is not selectable because of `user-select:none`. 

**Expected behavior**
Make user text select configurable.

**Reproduction of the problem**
See this line https://github.com/swimlane/ngx-datatable/blob/88c46dac0adc7024cc4c2e90f1ae9d5f01140809/src/components/datatable.component.scss#L105

**What is the motivation / use case for changing the behavior?**
Copying table content, for example to excel, is common in some workflows. No reason to disabling this entirely.

**Please tell us about your environment:**

* **Table version:** master. Commit #88c46dac

* **Angular version:** 4.0.x
* **Browser:** Chrome 57
* **Language:** all

**Comment by adammedford** [comment]
I think this was done to make it easier to drag column headers as I suspect some platforms might only select the text when it is enabled. But you're right, I don't think body cell needs to have it.

**Comment by amcdnl** [comment]
This has came up before and I don't remember why but it was done on purpose :S ... ill dig around and see if i can't remember why

**Comment by tamascsaba** [comment]
@amcdnl Is there any information?

**Comment by ericleb010** [comment]
I don't know where this is on the priority list, but this would be a decent nice-to-have. The header cells shouldn't need to be changed though.

**Comment by s-edlund** [comment]
Has there been a solution / workaround for this? In our app, we need to be able to select and copy text out of the table without triggering an event that's indistinguishable from a click. Selecting text (using the trackpad on my Mac) triggers an `(activate)` event of type 'click' and it's impossible to distinguish from an actual click on a row. `(select)` doesn't seem to work at all.
