### ISSUE TITLE
resize gride

### ISSUE THREAD

**Issue by MdAasim** [swimlane/ngx-datatable#697]
Hi,
     i want to resize the grid of the table after window resize , after page load if i increase the screen size of window the size of table is as per the previous size it is not increasing relatively with screen size

**Comment by enough1987** [comment]
the same problem. 
Angular 4 
datatable - 8.0.0
Which method can I use for resize width ?

**Comment by amcdnl** [comment]
Width/Height is calculated automatically during screen resize. If you need to change the container, just trigger a window resize event.

**Comment by ahmer-yasin** [comment]
how can you please give me an example

**Comment by luizhm6** [comment]
just place it in resize action 
"window.dispatchEvent(new Event('resize'));"
