### ISSUE TITLE
Important styles on icons overwrite other styles/packages with icons

### ISSUE THREAD

**Issue by seawave23** [swimlane/ngx-datatable#699]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

The following styles on icons.css overwrite other (packages') icons styles: 

`[data-icon]:before {
  font-family: "data-table" !important;
[class^="icon-"]:before,
[class*=" icon-"]:before {
  font-family: "data-table" !important;`

Please don't use important, or specify the styles better.
I'm using this datepicker and the icons there are not readable because of the settings named above:
https://github.com/kekeh/mydatepicker

**Expected behavior**
The ngx-datatable should only overwrite their own icons' font-family.

**Reproduction of the problem**
Install both packages and open the datepicker. On examining the icon in the browser, you will find the datatable's rule: "font-family: "data-table" !important;" and the icons won't show properly. This problem is also expected to appear on all other packages using icons.

**What is the motivation / use case for changing the behavior?**
Modularization/ the SOLID principles/ interference with other packages using icons

**Please tell us about your environment:**
Angular2, AngularMaterial2

* **Table version:** 8.0.0

* **Angular version:** 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mvhecke** [comment]
This can easily be solved by using a prefix for all styling related class names. I would suggest using ``datatable-icon-`` to match the names used for the components.

**Comment by seawave23** [comment]
Closed due to inactivity.
