### ISSUE TITLE
How do i add a new row ?

### ISSUE THREAD

**Issue by junaidahmed93** [swimlane/ngx-datatable#701]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Not provided adding a row functionality 

**Expected behavior**

There should be some implementation for adding a new row 

**What is the motivation / use case for changing the behavior?**

I have a use case where many different tables come from server (as JSON) and some data could be editable while user can add more data to the existing table without removing / overriding previous one.
So the requirement is to have a 'Add New Row' functionality 
Didn't find anyway to perform this functionality 

**Please tell us about your environment:**

* **Table version:** 0.8.x

Table version: 8.0.0

* **Angular version:** 2.0.x

Angular version: 2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by h4s33b** [comment]
+1

**Comment by enough1987** [comment]
this.rows.push(newRow);

 or 

this.rows.splice(this.selected[idx].$$index, 0, row);

**Comment by Iraecio** [comment]
same problem

I change the lines but the table does not change

**Comment by amcdnl** [comment]
Replace the rows or push a new one into the rows array.

If that doesn't help, can you make a demo?

**Comment by Iraecio** [comment]
this.rows.splice(row.$$index, 1);  // but dont work
-----------------------
let rows = [...this.rows];
rows.splice(row.$$index, 1);
this.rows = [...rows]; // and work update table whitout row

**Comment by murilobd** [comment]
Same here! Can't make that work!

**Comment by amcdnl** [comment]
The change detection is on push so the original row array needs to be a new instance.

```
this.rows = [...this.rows, myNewRow];
```

**Comment by murilobd** [comment]
That worked out! 

But, I found another issue... I'm using a ngx-datatable inside a material tabs component. In one tab I have the ngx-datatable and in the other tab I have a form. After I submit the form, I add a new row in the ngx-datatable and when I return to that tab, looks awful! Take a look at the image:
![image](https://user-images.githubusercontent.com/4275011/29497566-c449806a-85c0-11e7-8099-712a4da4347b.png)

**Comment by Iraecio** [comment]
What would be the problem with the image? I see a normal list with the option of removing each line and the entered normal data!

**Comment by murilobd** [comment]
Ops! I've updated images!!

**Comment by Iraecio** [comment]
Se voce estiver usando flexlayout talvez tenha que dar uma olhada em 
https://github.com/angular/flex-layout/wiki/ObservableMedia

**Comment by mustafagokkurt** [comment]
hi, I am adding from left menu 2 same row  to my datatable 
 if **Masraf Tutarı** is invalid in first row, I want only to first row to toggle but 2 row is toggling. 

i noticed two rows' $$index'no are same. 
first row $$index=1
second row $$index=1

please can help me,

![image](https://user-images.githubusercontent.com/26542096/31277836-85d9d4a0-aaab-11e7-8003-fbf9a41c776a.png)

**Comment by djpysu** [comment]
Can you please provide an accurate example of how to add a new row?  

The table won't refresh with this:

` this.rows = [...this.rows, myNewRow];`

**Comment by ashokthrymr** [comment]
> ## this.rows.splice(row.$$index, 1); // but dont work
> let rows = [...this.rows];
> rows.splice(row.$$index, 1);
> this.rows = [...rows]; // and work update table whitout row



**Check this Link may be you got the solution**
https://stackblitz.com/edit/angular-syhlgh?file=src%2Fapp%2Fapp.component.ts

**Comment by owfilip** [comment]
> That worked out!
> 
> But, I found another issue... I'm using a ngx-datatable inside a material tabs component. In one tab I have the ngx-datatable and in the other tab I have a form. After I submit the form, I add a new row in the ngx-datatable and when I return to that tab, looks awful! Take a look at the image: ![image](https://user-images.githubusercontent.com/4275011/29581306-3b5c7b32-874f-11e7-950a-c0c5e800b400.png)
> 
> After I zoom out and zoom in in chrome, everything gets back to normal! ![image](https://user-images.githubusercontent.com/4275011/29581347-5aae9196-874f-11e7-8756-684ade4b57b7.png)

[mur](https://github.com/murilobd) Did you figure out rendering issue? I have the same...
