### ISSUE TITLE
2 typescript semantic errors

### ISSUE THREAD

**Issue by tonychangcheng** [swimlane/ngx-datatable#705]
Typescript version: 2.2.1
Angular version: 4.0.0
Ngx-datatable version: 8.0.0

node_modules/@swimlane/ngx-datatable/release/components/row-detail/row-detail.directive.d.ts(10,28): error TS7006: Parameter 'row' implicitly has an 'any' type.
node_modules/@swimlane/ngx-datatable/release/components/row-detail/row-detail.directive.d.ts(10,34): error TS7006: Parameter 'index' implicitly has an 'any' type.

**Comment by amcdnl** [comment]
This should be resolved in latest.
