### ISSUE TITLE
Cannot change background color of cells

### ISSUE THREAD

**Issue by ZhanLiangUF** [swimlane/ngx-datatable#706]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

I am trying to change cells' colors based on the value. When I try to use the cellClass attribute and set a function to it. I get the following error:

Unhandled Promise rejection: Template parse errors:
Can't bind to 'cellClass' since it isn't a known property of 'ngx-datatable-column'.

**Expected behavior**

Looking at the following example - https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/css.component.ts , I should be able to change the background color of the different cells based on a conditional.

**Reproduction of the problem**

<ngx-datatable-column *ngFor="let column of columns" [prop]="column" headerClass="is-column" [cellClass]="getCellClass"> </ngx-datatable-column> 

This is my code for creating the columns, and it creates the columns perfectly fine until I try to add the cellClass attribute as shown above.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x

ngx-datatable(8.0.0)
* **Angular version:** 2.0.x

Angular v4.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

ALL
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES7

**Comment by amcdnl** [comment]
Odd, shows it here - https://github.com/swimlane/ngx-datatable/blob/master/src/components/columns/column.directive.ts#L26

**Comment by ZhanLiangUF** [comment]
Oh sorry! I just realized I actually didn't have 8.0.0. You can close this issue. Thanks for the fast reply.
