### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by Deilan** [swimlane/ngx-datatable#708]
**I'm submitting a ...**  (check one with "x")
bug report

**Current behavior**
Breakpoints ignored because generated code not found (source map problem)

**Expected behavior**
Breakpoints hit

**Reproduction of the problem**

0. Clone the repo and `npm install`
1. Add a VS Code debug launch configuration (`.vscode/launch.json`):
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:9999",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "smartStep": true,
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        }
    ]
}
```
2. `npm start`
3. Launch debugging session using the created configuration
4. Set a breakpoint somewhere in code

**What is the motivation / use case for changing the behavior?**
Allow debugging

**Please tell us about your environment:**
OS: Windows 8.1 x64
VS Code: 1.11.2
Debugger for Chrome: 3.0.1

* **Table version:** 0.8.x
The latest from the repo

* **Angular version:** 2.0.x
The latest from the repo

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 58.0.3029.81

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
The latest from the repo

**Comment by amcdnl** [comment]
This is not a library issue. Debugging works fine in other tools.

**Comment by hatung** [comment]
@Deilan
I changed this line in  \config\webpack.dev.js and it works 
 devtool: 'eval-source-map',
