### ISSUE TITLE
When rowClass() returns a string, the class is not properly added

### ISSUE THREAD

**Issue by QuentinFchx** [swimlane/ngx-datatable#710]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

When you provide a rowClass function that returns a string, the result is concatenated [without a whitespace](https://github.com/swimlane/ngx-datatable/blob/1592b6746f11beefe4d8d5a60b50b6a32e18eab4/src/components/body/body-row.component.ts#L64)

**Expected behavior**

It should add a whitespace

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x

8.1.0
* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Resolved in 9.1
