### ISSUE TITLE
(request) Pass activateFn to cell templates context

### ISSUE THREAD

**Issue by santialbo** [swimlane/ngx-datatable#718]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When using custom templates we can just show data. There's no way of, for example, being able to select or deselect with a custom checkbox column.

**Expected behavior**
It would be very useful to pass an activateFn to the context like it's done in the header for sorting (https://github.com/swimlane/ngx-datatable/blob/master/src/components/header/header-cell.component.ts#L36) so that we can have more power in the templates.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 8.2.1

* **Angular version:** 4.0.1

* **Browser:** all

* **Language:** all

**Comment by santialbo** [comment]
I can implement this myself if it's ok since it's a very straightforward and simple change.

**Comment by amcdnl** [comment]
Merged :)
