### ISSUE TITLE
Icon classes conflict with Simple Line Icons library

### ISSUE THREAD

**Issue by maxtacco** [swimlane/ngx-datatable#723]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
The current implementation uses icon classes that start with "icon-" suffix. This creates a conflict with Simple Line Icons library (http://simplelineicons.com/) 

**Expected behavior**
It would be nice to namespace datatable icon classes so that there are no potential conflicts with other libraries.  

**Reproduction of the problem**
Include Simple Line Icons library into the project and try to use any of the icons.

**Comment by Tempus35** [comment]
Just was coming on here for this issue as well. The icons.css and icons are overwriting another library I am using.

**Comment by Hypercubed** [comment]
I would like to see use us `ngx-icon-***`.

**Comment by maxtacco** [comment]
Hi @Hypercubed,
I think it would be even safer to use swimlane-ngx-icon-**

**Comment by amcdnl** [comment]
@Hypercubed - I dno't wanna add that as a dependency.

@Tempus35  - Can you PR just renaming them to `ngx-icon-`?

**Comment by marjan-georgiev** [comment]
Just wanted to mention that you have the option to override the icon classes in an input to the component

```
[cssClasses]="{
  sortAscending: 'icon-arrow-down',
  sortDescending: 'icon-arrow-up',
  pagerLeftArrow: 'icon-arrow-left',
  pagerRightArrow: 'icon-arrow-right',
  pagerPrevious: 'icon-prev',
  pagerNext: 'icon-skip'
}">
```

**Comment by gearsandcode** [comment]
PR created here > https://github.com/swimlane/ngx-datatable/pull/729

**Comment by amcdnl** [comment]
Done :)

**Comment by maxtacco** [comment]
Awesome. Thank you!
