### ISSUE TITLE
the width calculation is causing issues

### ISSUE THREAD

**Issue by LaxmiNarasimha530** [swimlane/ngx-datatable#725]
Issue is , the table column is given a width based on calculation, because of which if the text in the column is having a length greater than the width(calculated), the text is overlapping with the next sibling column. 

Please look at the attached image.\

this has nothing to do with the browser, its in all place

my system details:
angular-cli: 1.0.0-beta.28.3
node: 7.2.1
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.8

i have the latest ngx-datatable code

Thanks, pls look into this.. My recommendation would be just not to give the predefined width. it should given based on the specific requirements.

![image](https://cloud.githubusercontent.com/assets/8244164/25588720/84c4893a-2e77-11e7-9603-ea20f8f23fe1.png)

**Comment by amcdnl** [comment]
The material design applies ellipsis. This is not by default since you might want to handle this in different situations.
