### ISSUE TITLE
Make the datatable-pager directive available to the users of the library

### ISSUE THREAD

**Issue by Szabadember** [swimlane/ngx-datatable#734]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
You can create a custom footer template but you cannot use the datatable-pager directive in it. You have to create a custom pager. 

**Expected behavior**
I think it would be useful (and expected) to be able to add the datatable-pager to the template.

**Reproduction of the problem**
Create a footer template and try to add a <datatable-pager> tag to it.

**What is the motivation / use case for changing the behavior?**
Being able to use the datatable-pager

**Please tell us about your environment:**
Unrelevant

* **Table version:** 0.8.x
9.0.0

* **Angular version:** 2.0.x
4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by amcdnl** [comment]
Done! :)
