### ISSUE TITLE
Build error Angular 4 & ngx-datatable 9.1.0 & typescript 2.2.0

### ISSUE THREAD

**Issue by ankitgada** [swimlane/ngx-datatable#743]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Build error Angular 4 & ngx-datatable 9.1.0 & typescript 2.2.0. 
"
node_modules/@swimlane/ngx-datatable/release/utils/column-prop-getters.d.ts(27,4
9): error TS2304: Cannot find name 'object'.
node_modules/@swimlane/ngx-datatable/release/utils/column-prop-getters.d.ts(33,4
6): error TS2304: Cannot find name 'object'.
"

**Expected behavior**
NO build errors

**Please tell us about your environment:**
VS code on windows

* **Table version:** 0.8.x
9.1.0

* **Angular version:** 2.0.x
4.0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.0

**Comment by Isaac-Kleinman** [comment]
I'm having the same issue

**Comment by ankitgada** [comment]
i think was my bad. By looking around I came to know that this build error is due to typescript version mismatch and the version needs to be 2.2 or greater. When i checked through command line the typescript version was 2.2. . But then I realized that in package.json in the devdependencies section I had typescript as 2.1. I updated the version in package.json , ran npm install and the build error vanished. Bottom line check the typscript version everywhere.

**Comment by Isaac-Kleinman** [comment]
I only see one typescript reference and it's 2.3.2, but I'm still getting the error you posted about.

**Comment by ankitgada** [comment]
Well when I did a "tsc --version" on the command line. That showed 2.2.2 but in the package.json dev dependencies it was 2.1. Don't know what tools you are using , but u may need to look up if correct version of typescript is compiling your code.
