### ISSUE TITLE
Filter column as subheader

### ISSUE THREAD

**Issue by TeodorKolev** [swimlane/ngx-datatable#748]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Filter in demo is outside of table.

**Expected behavior**
Can filter column be added as sub header? Is that possible?

* **Angular version:** 2.0.x
4.0.3

**Comment by amcdnl** [comment]
You can use a column header template to accomplish this - https://github.com/swimlane/ngx-datatable/blob/master/demo/templates/template-dom.component.ts#L23-L25

**Comment by jmalkiewicz** [comment]
I think such an example in demo would be very helpful.
So it would like similar as in this table component:
https://valor-software.com/ng2-table/

**Comment by KeheliAdnane** [comment]
yes it would be great if we have an example of it as @jmalkiewicz ask, i tried but had no luck with it

**Comment by francisminu** [comment]
Please find a working plunker here:
https://plnkr.co/edit/2F1Jol1i9BsYYWNat42V

**Comment by jmalkiewicz** [comment]
Ok, thanks.
Could you add it to official demo page: http://swimlane.github.io/ngx-datatable/
I think it would be good to add new section 'Filtering' and place it there.

**Comment by yiquanchaoren** [comment]
> Please find a working plunker here:
https://plnkr.co/edit/2F1Jol1i9BsYYWNat42V

Hi everyone,
I am programing this problem, can we fix it by using directive method ?
Wating for your plnkr, thanks.

**Comment by sagar-sk15** [comment]
@francisminu Example not working

**Comment by francisminu** [comment]
@sagar-sk15  somebody modified the plunker and I dont see any of my code there :( Will try to create a new one.

**Comment by vundyalaavinash** [comment]
the plnkr is still not working

**Comment by sr9yar** [comment]
Maybe my example will help someone https://stackoverflow.com/a/54429466/3298637

**Comment by jonclawson** [comment]
https://codesandbox.io/s/swimlane-filter-table-lldho
