### ISSUE TITLE
What is the differentiation between limit and pageSize in (page) event ?

### ISSUE THREAD

**Issue by efriandika** [swimlane/ngx-datatable#750]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```
I use `externalPaging=true`.
What I want to ask: In the event `(page)="someMethod($event)" we will get:

* count
* limit
* pageSize
* offset

What is the differentiation between `pageSize` and `limit` ? both of them always return same value.

**Comment by amcdnl** [comment]
Good question. I'll dig in, thanks for bringing it to my attention!

**Comment by MorlaRamakrishna** [comment]
How can I set pageSize??????????????????
