### ISSUE TITLE
Expandable table does not show expand/collapse icon with latest version (9.1.0).

### ISSUE THREAD

**Issue by JosephAntoniou** [swimlane/ngx-datatable#752]
I updated to the latest version from 8.0.0 and all of a sudden the collapsable/expandable icon has disappeared.
I have reverted.

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Collapsable/Expandable icon not shown.

**Expected behavior**
Collapsable/Expandable icon displayed.

**Reproduction of the problem**
Just load the table.

**Please tell us about your environment:**
Angular 4, Firefox/Chrome/IE broswers.

* **Table version:** 9.1.0

* **Angular version:** 4.0.x

* **Browser:** [Chrome XX | Firefox XX | IE XX ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by sheiidan** [comment]
css class names were changed in the latest release. You probably need to prefix the expand/collapse css classes with "datatable-"

**Comment by JosephAntoniou** [comment]
Fixed 👍

**Comment by snandkule** [comment]
Hi can you provide example code....I used latest version in which names are already prefixed by "datatable-" but still icons are not shown.

I really want to use this data table but due to these issues, I am not able to use it.
Please help.
