### ISSUE TITLE
Steps to apply ngx-datatatble in webpack + angular2 project

### ISSUE THREAD

**Issue by bikashkumarn** [swimlane/ngx-datatable#753]
Hi All,

I tried to add ngx-datatatble in webpack + angular2 project . after adding the required import module in app.module.ts and adding this - import '@swimlane/ngx-datatable/release/index.js' in vendor.js, still i am not able to see the datattable added in my page. it shows issue below

If 'ng-template' is an Angular component, then verify that it is part of this module.
If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

Any help on this would be very helpful for me to proceed on my project.

**Comment by amcdnl** [comment]
You did not include the module in your project.

Please fill out the form in the future.

Please provide a demo and maybe i can help more.
