### ISSUE TITLE
emptyMessage not working

### ISSUE THREAD

**Issue by dharveshmydeen** [swimlane/ngx-datatable#754]
If there is no data in the list i shouls show like "No data Found"--->Message
I have tried using [emptyMessage]="''" but it is not working in angular 2.0

**Comment by amcdnl** [comment]
Please provide a demo and fill out the form. Once done, I will reopen and investigate.

**Comment by dharveshmydeen** [comment]
if there is no item in that list i have to show message like "No data found"
It is not a issue i need support

**Comment by dharveshmydeen** [comment]
In your structure you declared as  

 @Input() messages: any = {
    // Message to show when array is presented
    // but contains no values
    emptyMessage: 'No data to display',

    // Footer total message
    totalMessage: 'total',

    // Footer selected message
    selectedMessage: 'selected'
  };

But in my table if there is no list item. it will not show emptymessage in my table body

Is i enable any option for show this message...?

**Comment by Yogeshwar1992** [comment]
any update on this issue.\?

am also facing same issue.

**Comment by stevneves** [comment]
Hey guys,

I know this is an old post from last year, but I was also looking for an answer and had to figure it out by myself crawling the source code, so here's the answer in case somebody else needs it:

[messages]="{emptyMessage:'No results available.'}"

**Comment by baragondie** [comment]
You can override  the flowing messages : 
                 [messages]="{
                    emptyMessage: 'my : No data to display.',
                    totalMessage: 'my : total',
                    selectedMessage: 'my : selected'
                  }"

**Comment by ingeniero1984** [comment]
where they add this module, when importing they add this:
NgxDatatableModule.forRoot({
      messages: {
      emptyMessage: 'No hay datos disponibles',
      totalMessage: 'total',
      selectedMessage: 'selected'
      }
    }),

**Comment by argelj289** [comment]
we still have this issue and not displaying the emptyMessage when data is empty

**Comment by rathervague** [comment]
I had a similar problem with emptyMessage not displaying, it was due to [loadingIndicator]="true".
