### ISSUE TITLE
How to set a class row ?

### ISSUE THREAD

**Issue by WA-WilliamKrieg** [swimlane/ngx-datatable#755]
Hello, I don't understand how to add a class  on a row ?

I have the latest version

This is my code :

<ngx-datatable style="margin:10px 0px;" #table class="material" [autoSize]="553" [refTab]="table" [limit]="1000" [rowHeight]="20"
      [rows]="profils" [columnMode]="'force'" [scrollbarV]="true" [scrollbarH]="false" [selected]="profilSelected" [selectionType]="'single'">      
      
      <ngx-datatable-column name="nom" [width]="50">
        <ng-template let-sort="sortFn" let-column="column" ngx-datatable-header-template><span (click)="sort()">Nom</span></ng-template>
        <ng-template let-row="row" ngx-datatable-cell-template><span title="{{row.profil.nom}}">{{row.profil.nom}}</span></ng-template>

      </ngx-datatable-column>
      
      <ngx-datatable-column  name="prenom" [width]="50">
        <ng-template let-sort="sortFn" let-column="column" ngx-datatable-header-template><span (click)="sort()">Prénom</span></ng-template>
        <ng-template  let-row="row"  ngx-datatable-cell-template><span title="{{row.profil.prenom}}">{{row.profil.prenom}}</span></ng-template>
      </ngx-datatable-column>
       
      
      <ngx-datatable-column name="fonction" [width]="100">
        <ng-template let-sort="sortFn" let-column="column" ngx-datatable-header-template><span (click)="sort()">Fonction</span></ng-template>
        <ng-template  let-row="row"  ngx-datatable-cell-template><span title="{{row.profil.fonction}}">{{row.profil.fonction}}</span></ng-template>
      </ngx-datatable-column>

      
      <ngx-datatable-column name="etat" [width]="100">
        <ng-template let-sort="sortFn" let-column="column" ngx-datatable-header-template><span (click)="sort()">Etat</span></ng-template>
        <ng-template let-row="row" ngx-datatable-cell-template><span title=""></span></ng-template>
      </ngx-datatable-column>
    </ngx-datatable>

thx for your help

**Comment by amcdnl** [comment]
See: https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/css.component.ts#L54

**Comment by connectpritam** [comment]
The above GitHub link is giving 404 error.
I am also stuck on the same issue, I don't know how to add custom css to each row of the table.

**Comment by cbonitz** [comment]
Current link is https://github.com/swimlane/ngx-datatable/blob/master/src/app/basic/css.component.ts

**Comment by FauziFerdiansyah** [comment]
> Current link is https://github.com/swimlane/ngx-datatable/blob/master/src/app/basic/css.component.ts, demoed here http://swimlane.github.io/ngx-datatable/#css

save my night
