### ISSUE TITLE
Interaction of variable into datatable-footer-template

### ISSUE THREAD

**Issue by khylias** [swimlane/ngx-datatable#763]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I use the custom datatable-footer-template for add some buttons. One of them, has a `*ngIf="!myVar"`.
This variable is changing by a checkbox out of the datatable, like below : `<input type="checkbox" id="display-myvar" (change)="myFunc($event)">`
```
myFunc(event){
    const me = this;
    console.log('checkbox clicked');
    if (event.target.checked) {
      me.myVar = true;
      console.log('TRUE');
    }else{
      console.log('FALSE');
       me.myVar = false;
    }

  }
```

When I check the input, nothings it's happen. I must reload the datatable for ngIf do his job.

**Expected behavior**
I want to hide/show my button with `*ngIf="!myVar"` who is in datatable-footer-template by a checkbox out of the datatable.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 9.1.x

* **Angular version:** 4.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Can you post a demo?

**Comment by Tempus35** [comment]
First thought, the footer-template has onChangeStrategy as onPush and not being told to update.
