### ISSUE TITLE
How to resize the body component after update rows

### ISSUE THREAD

**Issue by WA-WilliamKrieg** [swimlane/ngx-datatable#767]
Hello I have a little problem, 
![select and push](https://cloud.githubusercontent.com/assets/24896153/26306300/1ebff372-3ef3-11e7-821f-569fc18ab4fc.gif)

I want update a second ngx-datatable after push an element from datatable 1 to datatable 2.
The body size of my second datatable is not update when i push my value.

An idea ?
`
@ViewChild(DatatableComponent) table: DatatableComponent;

addForSociete() {
    const pfd = [...this.profilsSelected]; //NGX-DATATBLE 1 (Selected items)
    let profils = this.profilsSL;
    for(let i = 0; i <pfd.length; i++){
      profils.push(pfd[i]);
    }
    this.profilsSL = profils;
    this.table.recalculate();
  }
`

Thx xoxo

**Comment by amcdnl** [comment]
Trigger a window resize. I'm not sure why its doing that either, it should be the total available view height. If you post a demo example showing, I will reopen and check that out.

**Comment by WA-WilliamKrieg** [comment]
It's hard for me to create a demo because my problem it's from a complexe process.
How to close my problem ? It's a very important ticket.

**Comment by siebmanb** [comment]
Solution might be here
https://github.com/swimlane/ngx-datatable/issues/193
