### ISSUE TITLE
Ability to deselect row in single select mode

### ISSUE THREAD

**Issue by nickhellmich** [swimlane/ngx-datatable#775]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Once a row is selected, it can't be deselected by using ctrl + click as with multi select.

**Expected behavior**
User can select a single row and deselect it.

**Reproduction of the problem**
http://swimlane.github.io/ngx-datatable/#single-selection

**What is the motivation / use case for changing the behavior?**
I'd like a user to be able to clear their selection without having to provide an extra button.  I have a ui where the user will load the grid per a selection in a drop down.  To proceed, they will either select a child item in the grid or just keep their option from the drop down. If the user selects something from the grid but changes their mind, they have to reset their selection by changing their selection in the drop down. Yes, this is a fairly specific use case, however the ability to deselect a single row seems reasonable and in line with the other selection modes.

* **Table version:** 7.0.0

* **Angular version:** 4.1.3

* **Browser:** [all ]

* **Language:** [TypeScript 2.3.2]

**Comment by dalelotts** [comment]
Consider having a row that says "None" or something like that, they define a selectCheck that prevents that one row from being selected. When the user clicks on it, the selection will be empty.

**Comment by dalelotts** [comment]
Actually, this feature is easy to implement yourself. 

Add this to the data table
```html
[selectCheck]="singleSelectCheck"
```
Then define the function in your class.
```typescript
  singleSelectCheck (row:any) {
     return this.selected.indexOf(row) === -1;
  }
```
One thing that is irritating about the `selectCheck` implementation is that the `this` context is bound to the `selection.component` class, not your class (Why, who knows?) so no matter what your local `selected` array is named, you must reference `this.selected`, which confuses the typescript compiler.  

@amcdnl I will be submitting a PR soon to fix much of the selection and I will include a change to not bind the filter function to `selection.component`. Is there some reason for having a different context?

**Comment by nickhellmich** [comment]
@dalelotts Thank you, that works great!  It would be nice to see this in the demo.

**Comment by amcdnl** [comment]
@dalelotts - Thanks for providing that solution! Would you mind PR'n this to the docs for others?

**Comment by chalecki** [comment]
@dalelotts thanks for solution buddy 👏 💪 !

**Comment by dalelotts** [comment]
@amcdnl Sorry, just seeing this now - sure, I can do that! Is it still needed?

@chalecki You're welcome!

**Comment by byhoratiss** [comment]
@dalelotts Thanks for the hint, I didn't realize that this could be done this way!
