### ISSUE TITLE
checkbox column doesn't work with column toggling

### ISSUE THREAD

**Issue by sarora2073** [swimlane/ngx-datatable#791]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

This is arguably a bug OR a feature request...

checkbox column doesn't appear to play well with column toggling. 

**Expected behavior**

Checkboxable columns should be fixed / retain check functionality when other columns are toggled (i.e. visibility is changed).

**Reproduction of the problem**

plnkr is here:  http://plnkr.co/edit/cBXstv?p=preview 

This code is based initially from combining the checkbox demo code (http://swimlane.github.io/ngx-datatable/#chkbox-selection) with the column toggle demo code (http://swimlane.github.io/ngx-datatable/#toggle). My initial experience was that toggling any random column would break the checkbox column (all the checkboxes disappear). As shown in the plunker, i tried making the checkbox column into a named column, but even then, toggling any other random column breaks the checkbox column, and there's no way to get the checkboxes to re-render. 

I don't see anything wrong with the column toggling code sample per se..my impression is that the solution would require an enhancement to the checkbox functionality to be able to make it survive column toggling..the checkboxes only appeared to get rendered on first initialization. If there are any workarounds that I could implement outside touching the ngx-datatable code though please do advise. thank you!

**What is the motivation / use case for changing the behavior?**

Utilize checkbox functionality and column toggling together

**Please tell us about your environment:**

Windows / Node 8.0 / npm 4.6.1
* **Table version:** 0.8.x

9.3.0
* **Angular version:** 2.0.x

4.1.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by MorlaRamakrishna** [comment]
You can achieve implementation of rows selection and  column toggling by using **multi row**
I am following like below:
```
<ngx-datatable
          style="width: 90%"
          class="material"
          [rows]="tableRows"
          [columnMode]="'force'"
          [columns]="tableColumns"
          [headerHeight]="50"
          [footerHeight]="50"
          [scrollbarV]="true"
          [scrollbarH]="true"
          [externalSorting]="true"
          [loadingIndicator]="loading"
          (sort)="onSort($event)"
          [selected]="selectedRows"
          [selectionType]="'multi'"
          (activate)="onActivate($event)"
          (select)='onSelect($event)'
          [externalPaging]="true"
          [count]="totalRows"
          [offset]="pageNum"
          [limit]="size"
          (page)='setPage($event)'>
        </ngx-datatable>
```

**Comment by sarora2073** [comment]
Hi,

Thank you very much for looking into this. I take it you are offering a workaround aside from using checkboxes? I was hoping for a way to use *checkboxable columns* with column toggling, and am aware that I can use other row selection types, but, as you may know, checkboxes offer a secondary row selection capability. e.g. i'm using (single) row selection in general to show a detail view of the selected row, but want to use checkbox selection to allow the user to select and possibly delete one or more rows, among other CRUD operations.

In the off chance that I misunderstood your response, and that you were suggesting I could in fact use checkboxable columns,  I tried using 'multi' selectionType *with a checkboxable* column like the one in the original plnkr (snippet below), and I still have the same limitation I originally reported...the checkbox column disappears upon column toggling. Any clarification / thoughts much appreciated. - S. Arora

          <ngx-datatable-column
            [width]="30"
            [sortable]="false"
            [canAutoResize]="false"
            [draggable]="false"
            [resizeable]="false"
            [headerCheckboxable]="true"
            [checkboxable]="true"
            name="checkbox">
          </ngx-datatable-column>

**Comment by sarora2073** [comment]
bump...

summary: I believe this is an open / valid issue. any advice appreciated.

**Comment by sarora2073** [comment]
update: was able to resolve this by adding updating the toggle method in the sample code:

this.columns.unshift({'name': "cb",'checkboxable': true,'headerCheckboxable': true,'width': 30}); 

I didn't realize it was going to be as easy as re-adding the checkboxable column to the columns array..i thought there was more "magic" under the hood re: the checkbox column.
