### ISSUE TITLE
Cannot read property 'toLocaleString' of undefined

### ISSUE THREAD

**Issue by Neverminder** [swimlane/ngx-datatable#793]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
An error is thrown when using the pagination:
```
Cannot read property 'toLocaleString' of undefined
    at Object.eval [as updateRenderer] (DataTableFooterComponent.html:20)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:307)
    at checkAndUpdateView (view.ts:392)
    at callViewAction (view.ts:700)
    at execEmbeddedViewsAction (view.ts:670)
    at checkAndUpdateView (view.ts:389)
    at callViewAction (view.ts:700)
    at execComponentViewsAction (view.ts:644)
    at checkAndUpdateView (view.ts:392)
    at callViewAction (view.ts:700)
```

**Expected behavior**
No errors

**Reproduction of the problem**
The problem is reproduced in this Angular Quickstart repository: https://github.com/Neverminder/quickstart

**What is the motivation / use case for changing the behavior?**
The bug makes the table unusable and breaks the whole application.

**Please tell us about your environment:**
Ubuntu 16.04, IntelliJ Ultimate 2017, npm

* **Table version:** 9.3.0
Still exists in the latest version.

* **Angular version:** 4.1.3
Yes.

* **Browser:** [all | Chrome 58 

* **Language:** TypeScript 2.3.1

**Comment by michalzfania** [comment]
also encountered with this issue..

**Comment by rahul-winner** [comment]
@Neverminder @michalzfania 

Ensure to set 'count' input if you are enabling 'externalPaging' on ngx-datatable. You may like to set 'count' to total number of row matching your qualification which is typically returned by the REST api you will be calling.

Hope it helps.

**Comment by amelnikoff** [comment]
Same problem. Count is set of course.

**Comment by sheldonyss** [comment]
For my case, the count is set but not initialized. After initializing it to 0, problem solved.

**Comment by wizarrc** [comment]
+1 for better error message

**Comment by SouengKimmeng** [comment]
+1 I also need that problems when I use page pagination on server side it seem that function run first before we get the data from the server using http. hope someone can find the solution and shared it here.thanks.

**Comment by techno2mahi** [comment]
if you are using angular , just at the constructor of the component make the total count value of the variable to 0. 

This is what that for the ngx directive parameters . You should set the variable that goes to the [offset], 

     ` [externalPaging]="true" 
      [count]="page.totalElements" 
      [offset]="page.pageNumber"
      [limit]="page.size" `

**Comment by Muhammet0617** [comment]
Bu Sorunu Çözmek İçin Sanal Sunucunuza Node +8 Kurabilirsiniz :)

**Comment by anacarol-costa** [comment]
mine is also showing similar error:

`Duplicate of react-dom.development.js:23275 Uncaught TypeError: Cannot read property 'toLocaleTimeString' of undefined`
