### ISSUE TITLE
onDomCreation lifecycle hook.

### ISSUE THREAD

**Issue by umagon** [swimlane/ngx-datatable#811]
**I'm submitting a ...**  (check one with "x")
```
[    ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[    ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

I would like to have a lifecycle hook "onDOMCreation" to include any tweaks to the rows I'm about to see.

**What is the use case for changing the behavior?**
I'm using a function on all rows to turn children objects into properties (to spread them across columns), and it takes a lot of time. I would like to do that only on the rows I'm seeing.

**Comment by amcdnl** [comment]
I do not think that is possible. Angular only provides `onAfterViewInit` which might be what your looking for.
