### ISSUE TITLE
Table's (page) emits multiple times per click on the vertical scrollbar when implemented as shown in the virtual server scrolling example

### ISSUE THREAD

**Issue by bseiller** [swimlane/ngx-datatable#814]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

When clicking on the vertical scrollbar of a datatable configured for virtual server-side paging 
as seen here
http://swimlane.github.io/ngx-datatable/#virtual-paging
https://github.com/swimlane/ngx-datatable/blob/master/demo/paging/paging-virtual.component.ts
the (page) emits multiple times per click. The same happens when dragging the scrollbar.

**Expected behavior**

Either (page) emits only once after clicking or dragging the scrollbar or the example (paging-virtual.component.ts) should be adapted either to contain a note concerning the multiple calls or code that prevents these calls to individually query the service - this might be done via a timeout/countdown that collects all calls within a certain amount of time and then submits them/the last one.

**Reproduction of the problem**
See here for the issue - the calls of 'setPage' are being logged into the console.
http://plnkr.co/edit/hcmOYgExj01h0xKtMqXy?p=preview

**What is the motivation / use case for changing the behavior?**
Activating virtual server side scrolling resulting in multiple server-calls per click on the scrollbar by default could by problematic. 

* **Table version:** 9.3.0

* **Angular version:** 4.1.3/4.2.2

* **Browser:** Chrome 58 | Firefox 49 

* **Language:** TypeScript 1.8.10

**Comment by legionairre** [comment]
I've the same problem. Any solutions?

**Comment by mgarcia23** [comment]
Me too. I have the same problem....Please help!

**Comment by Hypercubed** [comment]
ngx-datatable does not implement any caching.  You shoudl keep your own index of loaded data.  Watch this page for an updated example: https://github.com/swimlane/ngx-datatable/blob/master/src/app/paging/paging-virtual.component.ts
