### ISSUE TITLE
inline editing causes browser tab to freeze

### ISSUE THREAD

**Issue by Neverminder** [swimlane/ngx-datatable#821]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When trying a custom inline editing with specific combination of Angular Material 2 components the browser tab freezes and doesn't recover. One CPU thread is then always at 100%. Specific set of components that causes the freeze: two `md-select` and one `md-datepicker` elements. If any one of those is removed problem disappears. Outside of the table any combination of the said components does not cause this issue.

**Expected behavior**
Browser tab shouldn't freeze.

**Reproduction of the problem**
Reproduced in this repository: https://github.com/Neverminder/quickstart
Launch the application with `npm start` and click "edit" on the table

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Ubuntu 16.04, IntelliJ IDEA, npm, nginx

* **Table version:**  9.3.0

* **Angular version:** 4.2.2

* **Browser:** [all | Chrome 59 | Firefox 54 | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript 2.3.1 | ES6/7 | ES5]

**Comment by amcdnl** [comment]
I imagine its because of dirty checking.

**Comment by Neverminder** [comment]
With the latest version of Material 2 the issue is now gone.
