### ISSUE TITLE
Close the expanded / collapse row on click/expand of other row.

### ISSUE THREAD

**Issue by Muzaeed** [swimlane/ngx-datatable#829]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Step1: I have expanded one row --> toggleExpandRow(row)
![rowdetail](https://user-images.githubusercontent.com/17058984/27379373-963f01b0-5698-11e7-9e9b-ffd91101d98e.png)
Step2: I have expanded another row --> toggleExpandRow(row)
![rowdetail2](https://user-images.githubusercontent.com/17058984/27379467-f7377f42-5698-11e7-8571-01ec4f23bdb2.png)

**Expected behavior**

On expand of other row the toggled / open row should close.

**Another issue:**
There is no scroll on data-overflow in the row detail.

**What is the motivation / use case for changing the behavior?**

Since already one detail of row is displaying close the opened / toggled row on click of other row toggle.

**Please tell us about your environment:**

Linux 16.04

* **Table version:** 0.8.x

9.3.0

* **Angular version:** 2.0.x & 4.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ktriek** [comment]
As a work around you can use you can use the `rowDetail ` `collapseAllRows `method
```
 onExpandRow(row) {
    this.datatable.rowDetail.collapseAllRows();
   this.datatable.rowDetail.toggleExpandRow(row);
 }
```
```
  onCollapseRow() {
    this.datatable.rowDetail.collapseAllRows();
  } 
```

**Comment by Muzaeed** [comment]
Thanks it's working for me...! :-)

**Comment by Ravikumar087** [comment]
How to do the same for grouping ( http://swimlane.github.io/ngx-datatable/#row-grouping )? 
could you please help on this?

thanks
