### ISSUE TITLE
Issue with virtual scrolling and hitting last page button

### ISSUE THREAD

**Issue by deeg** [swimlane/ngx-datatable#830]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
* Go to the [virtual server side paging demo](http://swimlane.github.io/ngx-datatable/#virtual-paging).
* Hit the last page button in the footer
* Notice the last page is blank and does not load

**Expected behavior**
* I would expect the last page to be loaded like if you had scrolled all the way to the bottom

**Reproduction of the problem**
See demo link above

**Please tell us about your environment:**

* **Table version:** 0.8.x
9.3.0

* **Angular version:** 2.0.x
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Only checked Chrome

**Comment by andrii-oleksyshyn** [comment]
#843 Similar issue

**Comment by amcdnl** [comment]
Works for me :S - https://www.screencast.com/t/77tEqo60bMy

**Comment by leozero** [comment]
I have a similar issue, my data load at the beginning of the table, it's logic because de keys are following. When I try to fix that with a Array.splice(start, data.length, data) it crashes. Probably because the array keys not followed [0,1,2,10,11,12, ...].

The crash is generated by this error : 

**Cannot read property '0' of undefined**

On line **30** of this file **DataTableBodyComponent.html**

`        <datatable-row-wrapper
          [groupedRows]="groupedRows"
          *ngFor="let group of temp; let i = index; trackBy: rowTrackingFn;"
          [innerWidth]="innerWidth"
          [ngStyle]="getRowsStyles(group)"
          [rowDetail]="rowDetail"
          [groupHeader]="groupHeader"
          [offsetX]="offsetX"
          [detailRowHeight]="getDetailRowHeight(group[i],i)"`

It tried to get group[i] but group seems not defined

**Comment by guify** [comment]
I also see this issue. I can also get the blank page simply by scrolling too fast with the scrollbar. It seems that whenever I scroll more than one page at a time, the table is blank. I don't get any console errors.

**Comment by nevraun** [comment]
Same problem here, exactly as guify described it.

**Comment by bthallion** [comment]
Has there been any progress on this issue? I see that there are some timeout related kludges to work around this but I'd prefer to not have to go that route.

**Comment by stanleysantos** [comment]
Has there been any progress on this issue?

**Comment by stanleysantos** [comment]
> I have a similar issue, my data load at the beginning of the table, it's logic because de keys are following. When I try to fix that with a Array.splice(start, data.length, data) it crashes. Probably because the array keys not followed [0,1,2,10,11,12, ...].
> 
> The crash is generated by this error :
> 
> **Cannot read property '0' of undefined**
> 
> On line **30** of this file **DataTableBodyComponent.html**
> 
> ` <datatable-row-wrapper [groupedRows]="groupedRows" *ngFor="let group of temp; let i = index; trackBy: rowTrackingFn;" [innerWidth]="innerWidth" [ngStyle]="getRowsStyles(group)" [rowDetail]="rowDetail" [groupHeader]="groupHeader" [offsetX]="offsetX" [detailRowHeight]="getDetailRowHeight(group[i],i)"`
> 
> It tried to get group[i] but group seems not defined

Hi, i solved this issue filling data array according page data and index.

`this.loadData().subscribe(pagedData => {
      this.page = pagedData.page;

      // calc start
      const start = this.page.pageNumber * this.page.size;

      // copy rows
      let rows = [...this.rows];

      // check data array and fill with blank data, 
      // otherwise occurs 'Cannot read property '0' of undefined' error
      if (start > rows.length) {
        rows = rows.concat(rows, Array(start - rows.length ).fill({}));
      }

      // added argument pagedData.data.length to clean data and avoid memory overflow
      rows.splice(start, pagedData.data.length, ...pagedData.data);

      // set rows to our new rows
      this.rows = rows;

      // add flag for results
      this.cache[this.page.pageNumber] = true;

      this.isLoading = false;

      // Fix Bug https://github.com/swimlane/ngx-datatable/issues/843
      setTimeout(() => {
        document.getElementsByTagName('datatable-body')[0].scrollTop++;
        document.getElementsByTagName('datatable-body')[0].scrollTop--; },
      10);`

I wish this code can hel you.

**Comment by Hypercubed** [comment]
This was fixed.
