### ISSUE TITLE
Datatable not working with Angular 2 Quickstart For Visual Studio 2015 

### ISSUE THREAD

**Issue by casti004** [swimlane/ngx-datatable#832]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Apologies that I'm new to Angular and I'm sure this is a routing issue, but I'm trying to use the Angular provided Quickstart for Visual Studio here:
https://angular.io/guide/visual-studio-2015

I followed the demo to set up a simple working datatabe using npm install and the sample code but I get the following error:

index.html:18 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:57785/src/@swimlane/ngx-datatable
	Error: XHR error (404 Not Found) loading http://localhost:57785/src/@swimlane/ngx-datatable
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:57785/node_modules/zone.js/dist/zone.js:1056:39)
	    at ZoneDelegate.invokeTask (http://localhost:57785/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:57785/node_modules/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:57785/node_modules/zone.js/dist/zone.js:486:38)
	Error loading http://localhost:57785/src/@swimlane/ngx-datatable as "@swimlane/ngx-datatable" from http://localhost:57785/src/app/app.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:57785/node_modules/zone.js/dist/zone.js:1056:39)
	    at ZoneDelegate.invokeTask (http://localhost:57785/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:57785/node_modules/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:57785/node_modules/zone.js/dist/zone.js:486:38)
	Error loading http://localhost:57785/src/@swimlane/ngx-datatable as "@swimlane/ngx-datatable" from http://localhost:57785/src/app/app.module.js

**Expected behavior**
The simple demo table should show up

**Reproduction of the problem**
Download the Quickstart provided by Angular for Visual Studio 2015 and follow the steps creating the sample demo table.

**What is the motivation / use case for changing the behavior?**
I need to run the datatable from Visual Studio by clicking 'Run' or F5.

**Please tell us about your environment:**
OS Microsoft Windows 7, Visual Studio 2015

* **Table version:** 0.8.x
Latest Version

* **Angular version:** 2.0.x
Latest from Angular - 4.0.0

* **Browser:** 
all 

seen in Chrome, IE10, and Firfox

* **Language:** 
all

**Comment by Adondriel** [comment]
If you are looking for a way to create a Angular 2 project + sometype of .net backend, check out https://github.com/MarkPieszak/aspnetcore-angular2-universal. This is what i started with, and then removed a bunch of the stuff I didn't need. It is a very good base to start on. The issue with your situation being that it is not looking in `node_modules\@swimlane ...` this repo has almost all of those types of issues worked out, (you may have to remove Server Side Rendering, depending on certain things.)

**Comment by casti004** [comment]
ok, so I've figured this out. Here are the steps to get it working in Visual Studio 2015:

1. Follow all the steps to install the Angular2 - Visual Studio Quick Start here:
https://angular.io/guide/visual-studio-2015
..or from above suggested template.

2. Once you get it displaying the 'Hello Angular' page, then use NPM in the package manager to  install the grid in the proper location (npm install @swimlane/ngx-datatable)

3. Under the 'src' folder that was copied to your solution from the QuickStart, there is a systemjs.confi.js file you need to add the following inside the map object:
'@swimlane/ngx-datatable': 'npm:@swimlane/ngx-datatable/release/index.js'

in my example, the map obj looks like this:
    map: {
      // our app is within the app folder
      'app': 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      '@swimlane/ngx-datatable': 'npm:@swimlane/ngx-datatable/release/index.js'
    }

4. Rebuild and see the magic!!

**Comment by Adondriel** [comment]
What are you using to build? The current one that a lot of people use is
webpack... Not sure what you are using here.

**Comment by amcdnl** [comment]
Please make a demo project for us to debug. Once that is completed, we can reopen and discuss.
