### ISSUE TITLE
Scrolling while having row-detail open and then closing row-detail does not render the following rows.

### ISSUE THREAD

**Issue by andreykaipov** [swimlane/ngx-datatable#833]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
If a user opens up some row-details, scrolls even just a little bit in the table, and then closes the rows, the total row-detail heights will hide the following rows. Scrolling through the table again re-renders the remaining rows.

**Expected behavior**
A user should be able to see the remaining rows in the table after closing the row-details, without having to scroll.

**Reproduction of the problem**
See this gif for an example -- http://i.imgur.com/EHQ0YvX.gifv

Anybody can replicate it using the demo pages!

**What is the motivation / use case for changing the behavior?**
Improves UX and UI.

**Please tell us about your environment:**
I've replicated it on Windows and Mac.

* **Table version:** The latest release 9.3.0.

* **Angular version:** Angular 4.1.3 via the Angular CLI.

* **Browser:** I've replicated it on Chrome and Firefox.

* **Language:** TypeScript

**Comment by leozero** [comment]
I have the exact same issue, the gif show perfectly what happen

**Comment by wizarrc** [comment]
@andreykaipov I can verify the issue.

Looks like the problem is at the toggle observable handler in `body.component.ts` where it never calls `updateIndexes()` and `updateRows()`. Try changing the following:

https://github.com/swimlane/ngx-datatable/blob/master/src/components/body/body.component.ts#L226

```
ngOnInit(): void {
    if(this.rowDetail) {
      this.listener = this.rowDetail.toggle
        .subscribe(({ type, value }: { type: string, value: any }) => {
          if(type === 'row') this.toggleRowExpansion(value);
          if(type === 'all') this.toggleAllRows(value);
          
          // Refresh rows after toggle
          // Fixes #883
          this.updateIndexes();
          this.updateRows();
        });
    }
  }
```

It works in my private fork, but I changed too many things to be sure that's all that is needed to fix it.

@amcdnl can you verify this? If not, I can fork another branch and test on the current version and submit a pull request.

**Comment by leozero** [comment]
I "fixed" this issue by setting a height on the ngx-datatable container : 

`.ngx-datatable {
  height: 80vh;
}`

In my case it's not a problem to set a fixed height but it's not the best solution I think.

**Comment by rikbrowning** [comment]
Having same issue

**Comment by umagon** [comment]
I have a similar problem. In my case, when I scroll down and assign a larger array to my rows array, no rows get rendered until I scroll again.

**Comment by vibingopal** [comment]
@umagon - Please follow the configuration mentioned by @wizarrc. For me the configuration worked.

**Comment by umagon** [comment]
@vibingopal are you telling me to branch the repo, change those things in datatable-body and import from it instead of the version published in npm?

**Comment by wizarrc** [comment]
@vibingopal Thanks for confirming the fix works. I submitted a pull request with the above suggested changes.
