### ISSUE TITLE
I am unable to set Header cell style for ngx-datatable

### ISSUE THREAD

**Issue by shankar1414k** [swimlane/ngx-datatable#834]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

unable to set Header style for ngx-datatable
.datatable-header-cell{
  color :green
}

HTML
====
<ngx-datatable id ="ngxdatatable" 
          class='material'
          
          [rows]="rows" 
          [rowHeight]="20"
          [columns]="columns" 
          [columnMode]="'force'" 
          [scrollbarV]="true"
          [scrollbarH]="true"
          [headerHeight]="30"
          [footerHeight]="50"
          [limit]="35"
          (page)="onPage($event)">
                  
        </ngx-datatable>
but still style is not applied, data table still showing with default style color.

Please Help.

**Comment by andreykaipov** [comment]
Angular's default view encapsulation for components is `Emulated` to mimic a shadow DOM behavior effectively scoping a component's CSS within that component only!

To get around this, you could place that CSS into your global styles. Alternatively, you can use the `:host` and `/deep/` provided by Angular to style the `ngx-datatable`, or just change your component's view encapsulation to `ViewEncapsulation.None`. See https://angular.io/guide/component-styles for more details.

You might have to be more specific with that selector though. Something like

```
.ngx-datatable.material {
  .datatable-header {
    .datatable-header-cell {
      // your styles here
    }
  }
}
```

should work after getting around the view encapsulation.

**Comment by amcdnl** [comment]
Please try what @andreykaipov suggested.

**Comment by DevanathanVS** [comment]
I had a problem adding styles to the table. I added below in my component
**@Component({
  ....
  encapsulation: ViewEncapsulation.None,
})**
this takes my custom styling files

**Comment by Wihan** [comment]
Thanks for this, maybe this should be somewhere in the documentation, had the exact same problem. Moving my component styles to the global styles solved the problem.

**Comment by tonym99** [comment]
Any idea why I get "Cannot find name 'ViewEncapsulation'" when adding encapsulation: ViewEncapsulation.None?  I'm new to ngx-datatable coding.

**Comment by Drewdizzy** [comment]
Hi @tonym99 ,
 You have to import it first before using it

import { ViewEncapsulation } from '@angular/core';

**Comment by tonym99** [comment]
Thanks!

**Comment by andrewkiproff** [comment]
I would use caution when dealing with `ViewEncapsulation`. 

The setting of `encapsulation: ViewEncapsulation.None` will make it so that your component CSS is no longer restricted to confines of that component. i.e. It will essentially make you CSS global. This can lead to some very tricky CSS bugs and overuse negates the reason you are using a framework in the first place. Try to leverage CSS specificity as mentioned above.

**Comment by james-poulose** [comment]
> Angular's default view encapsulation for components is `Emulated` to mimic a shadow DOM behavior effectively scoping a component's CSS within that component only.
> 
> To get around this, you could place that CSS into your global styles. Alternatively, you can use the `:host` and `/deep/` selectors provided by Angular to style the `ngx-datatable`, or just change your component's view encapsulation to `ViewEncapsulation.None`. See https://angular.io/guide/component-styles for more details.
> 
> You might have to be more specific with that selector though. Something like
> 
> ```
> .ngx-datatable.material {
>   .datatable-header {
>     .datatable-header-cell {
>       // your styles here
>     }
>   }
> }
> ```
> should work after getting around the view encapsulation.

Adding `encapsulation: ViewEncapsulation.None` did the trick!
I am not going to get back my 1 hour back - but that solved many of my problems such as

1. Font color
2. Font size
3. Grid's padding
4. Grid's margin
5. all the above issues for the footer

Thanks a lot!
