### ISSUE TITLE
Select on a embedded header element triggers a select all on the table.

### ISSUE THREAD

**Issue by D0rmouse** [swimlane/ngx-datatable#840]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
We have added in input to the headers in the table (ngx-datatable-column->ng-template->input) to filter  rows based on column value. When we doubleclick it or shift-home with the cursor at the end of the text to select the input value, a select event is fired by the DataTableHeaderComponent's select handler (select.emit($event)). This in turn ends up in DatatableComponent.prototype.onHeaderSelect, which is later cleared by the next onHeaderSelect. This function adds all rows to the selected rows and the focus is lost from the input. This seems unwanted behavior, because we did not trigger a select all using the checkbox in the first column. 
This is the offending code:
`if (!allSelected) {
            (_a = this.selected).push.apply(_a, this.rows);
        }`

**Expected behavior**

We would expect a select on a custom element in the header not to trigger a select all on the table.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

This behavior prevents us from implementing desired per column row filtering.

**Please tell us about your environment:**

OS: Ubuntu Linux 14.04
IDE: IntelliJ IDEA 2017.1
NPM: 4.6.1

* **Table version:** 9.3.0

* **Angular version:** 4.2.2

* **Browser:** 
Chrome Version 59.0.3071.109 (Official Build) (64-bit)
Firefox 54.0 (64-bit) (**CRASHES**)

* **Language:** TypeScript 2.3.7

**Comment by dannyvenier** [comment]
You should probably provide a plnkr with an example to reproduce, otherwise it's just guessing.

If your input element is a child of the header, then you need to stop propagation of the double click event to the parent header which is designed to act on it.  If you do that, and your input control takes up the entire area of the header, you will have lost the ability to use the select all that was native to that column header but otherwise, the native functionality should be okay.  So use event.stopPropagation() in your own double click handler, if that's what's really going on.

**Comment by D0rmouse** [comment]
Tried that, didn't work. If you look at the code I mentioned, it seems a bit weird all rows are added to the selection on just any header select event. 
I'll try to create a plnkr this week.

**Comment by D0rmouse** [comment]
I've created a [Plunker](http://plnkr.co/edit/bfJSSlswkrYjwJABJhr6?p=preview) demonstrating the described behavior.
So first add some text to the test column filter, then double-click the text or perform some other action that selects text, like shift-arrows or shift-end/home. 
Then watch the console for select events. You'll see three select events, of which the first will select all. I would expect no select events at all here from the datatable.

**Comment by dannyvenier** [comment]
I'm not sure why you are listening for the select event from your main table configuration.  If I understand what you are trying to do from your plunker, you want a select event on the input element to trigger a handler when user completes filter entry (I moved select to your input element in plunker as below - ignore the dblclick event, I added it earlier to test stopPropagation)

When the select is triggered, you need (not sure) the list of selected rows, and the value of the filter input.  You should use ngModel to bind input field to class property but your change event should work fine.  "selected" is populated by table so you have everything you need.  You can invoke the filtering in the change handler if you want live filtering which filters as user types, or in the select handler if you only want to filter when the user completes and gestures a select.

(With the select listener in the input field, there is no selection being applied to the other columns when you have a selection gesture like doubleclick.  The event passed is not the selected array, rather it is just the selection event but you can access selected from the "this" object from within onSelect handler.) 

<ng-template let-column="column" let-sort="sortFn" ngx-datatable-header-template>
                  <span class="cursor-pointer" (click)="sort()">Test column</span>
                  <div class="header-filter">
                    <input class="" type="text" [value]="filterValues['id'] || ''"
                           placeholder="Filter..." (change)="onHeaderFilterChange($event, 'id')"
                           (dblclick)="handleDouble($event)"
                           (select)="onSelect($event)">
                  </div>
                </ng-template>

**Comment by D0rmouse** [comment]
The main select listener is just to produce the log output to demonstrate the problem (select all, select none).
Why should I stop propagation on a totally unrelated element in another column? Even if I remove the select all checkbox column the select all/select none is still performed. 
The desired functionality is to filter rows based on the value of a specific column (or columns) in that row.

I am still not, in any way, able to double click the text in the input, or select all text in the input by other means. Not even when I remove all event handling in my app. A data binding event (`ZoneTask.invoke`) will still trigger a cycle that performs the mentioned select all/select none code in `DatatableComponent.prototype.onHeaderSelect`.

**Comment by dannyvenier** [comment]
it appears the code I pasted got clipped.
In a nutshell, I removed the select from main table element, added it to the input element in template and I could capture double-clicks and drag-text selects (as select events).  I didn't try every mode of selection but it seemed to work just fine, without triggering a select all. I also tried capturing a dblclick event from the input element and that worked fine as well, so that is an option if you want to support only doubleclicks.

The reason I suggested stopping propagation from the column because the presence of the select in the main table is/was the cause of the select-all, but if you don't need the select captured in the main table for some reason, just remove it.

**Comment by D0rmouse** [comment]
I removed the select from the main table element and added it to the input in the template and the only effect it had was that not all rows are selected anymore. Double-click still loses focus.

Could you provide the working Plunker?

**Comment by dannyvenier** [comment]
http://plnkr.co/edit/jXbmUjJ6pL303sRr4mhN?p=preview
1.  listen on the input for select
2.  stopPropagation of the event because something in parent is listening and taking focus.  You just have an input element there so it will behave like one if you block other handlers.

**Comment by D0rmouse** [comment]
My God, so sure I'd tried that.. still have to wrap my head around why we need to stop propagation on an event from a completely different element than the select all header element, but I guess it's just generic handling of a select event in the DatatableComponent.
Thanks!

**Comment by dannyvenier** [comment]
Yeah, I have not dug into the bowels of the table yet.  It is definitely related to the event bubbling up to something higher in the food chain (which means stopping propagation could have side effects).  But events are so difficult to debug when using someone else's code.
