### ISSUE TITLE
row selected changed will make page lose focus

### ISSUE THREAD

**Issue by woshiyifadaguangtou** [swimlane/ngx-datatable#857]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Row selected single Mode
when i set current selected in component,Dom element will lose focus.Code like this:

`@ViewChild('byds') byds_input;
next (){
   
    let index = this.getSelectedIx();
    if( index < this.rows.length-1)
    {
      this.selected = [this.rows[index+1]];
 
    }
     this.byds_input.nativeElement.focus(); // it doesn't work !!!
                                            // if commnet 'this.selected = [this.rows[index+1]];'
                                            // 'this.byds_input.nativeElement.focus()' will work,
                                            // but i can't change selected item...
  }
`

and here is my html 
` <div style='float:left;width:100%'>
          <ngx-datatable #cbsr
            class="material striped venus-datetable"
            style="margin: 0px;float:left"
            [rows]="rows"
            [columnMode]="'force'"
            [columns]="columns"
            [headerHeight]="50"
            [footerHeight]="50"
            [rowHeight]="'auto'"
            [limit]="10"
            [selected]="selected"
            [selectionType]="'single'"
            (activate)="onActivate($event)"
            (select)='onSelect($event)'
            (focus)="onfocus($event)">
          </ngx-datatable>
        <div class='selected-column' style="float:left;width:24.8%;margin: 0px">
          <h4>Detail</h4>
          <ul>
            <li *ngFor='let sel of selected'>
              <div class="form-horizontal">
             <div class="form-group detail-col">
                <label class="col-lg-6 control-label">byds:</label>
                <div class="col-lg-6">
                  <input class="form-control" autofocus="autofocus" tabindex="1" (blur)="byds_blur($evnet)" (focus)="byds_focus($event)"  #byds [(ngModel)]="sel.byds" (keydown)="onKeyPress($event)">
                </div>
              </div>
              
           
   
             
              <div class="form-group detail-col">
                <div class="col-sm-6">
                  <button class="btn btn-primary">Save </button>
                </div>
                <div class="col-sm-6">
                  <button class="btn btn-primary" (click)="next()">NEXT</button>
                </div>
              </div>

              </div>
            </li>
            <li *ngIf="!selected.length">no selected</li>
          </ul>
          </div>
        </div>
`

 
**Expected behavior**
I want that when i put "Enter" on byds_input ,the datatable selected will move next and then byds_input will get focus again.
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.8.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by dannyvenier** [comment]
having discussed a similar issue with another issue-poster, the select event seems to be picked up by a parent element (bubbling) of some kind, which may be stealing the focus.  So you may have a race conditon trying to set focus right after a select event.  

Something you can try to confirm this is to do an event.stopPropagation() in your select handler which will prevent any further event captures.

**Comment by amcdnl** [comment]
Ya, stop prop is what you should do to prevent this. Its required to handle selection with things like keyboard events/etc.

**Comment by BearandYoon** [comment]
when type into input control, input control loss focus.

```
            <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
              <div class="url">
                <div *ngFor="let url of selectedRow.urls; let i = index;">
                  <input [(ngModel)]="selectedRow.urls[i]" >
                </div>
              </div>
            </ng-template>
```

After type one character, I lose focus. :(

**Comment by skec0912** [comment]
The same here:
<ngx-datatable-column name="Quantity">
            <ng-template let-row="row" ngx-datatable-cell-template >
                <input mdInput [(ngModel)]="row.quantity" name="Qantity" type="number">
            </ng-template>
        </ngx-datatable-column>

**Comment by Thrideep** [comment]
Hi,
any update on this issue?

**Comment by DonJuwe** [comment]
+1
