### ISSUE TITLE
Pagination Control in Footer Template

### ISSUE THREAD

**Issue by sirhcybe** [swimlane/ngx-datatable#867]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When I customize the footer with a ng-template, the pagination control does not display.

**Expected behavior**
I would like a way to place the datatable-pager component inside my ng-template so that I can display both my custom template and the default pagination controls.

**What is the motivation / use case for changing the behavior?**
I have a requirement for some custom info in the footer but I also have a requirement for pagination.

* **Table version:** 9.3.0

* **Angular version:** 4.0.x

* **Browser:** [all]

* **Language:** [all]

**Comment by Tempus35** [comment]
Look at this discussion for how to add the pager in a custom footer
https://github.com/swimlane/ngx-datatable/issues/739
