### ISSUE TITLE
Style not loading 404 error

### ISSUE THREAD

**Issue by think4ideas** [swimlane/ngx-datatable#869]
i add
 @import '~@swimlane/ngx-datatable/release/index.css';
@import '~@swimlane/ngx-datatable/release/themes/material.css';
@import '~@swimlane/ngx-datatable/release/assets/icons.css';

these code to my ionic scss file 
then  i trying build my app i get the following errror

_**Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/~@swimlane/ngx-datatable/release/themes/material.css
 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/~@swimlane/ngx-datatable/release/assets/icons.css Failed to load resource: the server responded with a status of 404 (Not Found)**_

**Comment by nrcrabbe** [comment]
Here's how I overcame this.

Add the following to package.json:
```
    "config": {
      "ionic_sass": "./config/sass.config.js"
    },
```

Create config/sass.config.js, containing:
```
var config = require('@ionic/app-scripts/config/sass.config')
config.includePaths = [
  'node_modules/ionic-angular/themes',
  'node_modules/ionicons/dist/scss',
  'node_modules/ionic-angular/fonts',
  'node_modules/@swimlane/ngx-datatable/release'
]
console.log('Added custom sass paths')
module.exports = config;
```

Add the imports like:
```
@import 'index';
@import 'themes/material';
@import 'assets/icons';
```

This approach can be used for any package styling.

**Comment by amcdnl** [comment]
This really depends on your build setup. Thanks for helping him out @nrcrabbe !
