### ISSUE TITLE
Possibility to set the table page size

### ISSUE THREAD

**Issue by ktriek** [swimlane/ngx-datatable#870]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Changing datatable's limit (page size) doesn't change anything. 

**Expected behavior**

Add possibility to set the page size  by changing the table [limit] input.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 9.3.x

* **Angular version:** 4.3.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by incinirate** [comment]
While this isn't a perfectly clean solution, this behavior can be emulated by using ViewChild to get the datatable's instance and then setting the limit directly like so..

```ts
@ViewChild(DatatableComponent)
datatable: DatatableComponent;

updateLimit(size) {
  this.datatable.limit = size;
  this.datatable.recalculatePages();
}

**Comment by amcdnl** [comment]
@incinirate - thanks for providing that example. Perhaps we should call recalc pages when u set limit.

**Comment by sgwatgit** [comment]
@amcdnl Based on this issue am I to assume binding to `[offset]` and `[limit]` does nothing?

Do I need to take the approach @incinirate shows to be able to set these values?
