### ISSUE TITLE
custom footer can't set to two rows

### ISSUE THREAD

**Issue by erickyi2006** [swimlane/ngx-datatable#871]
**I'm submitting a ...**  (check one with "x")
I am submitting a defect on custom footer. 

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
<!-- Describe how the bug manifests. -->
In my custom footer, I want to have two rows. 
First div contains two input fields 
Second div contains the summary and pagination

**Expected behavior**
<!-- Describe what the behavior would be without the bug. -->
The custom footer should render as two rows

**Reproduction of the problem**
<!-- If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/vtAo2zzWFn8kFOGRH88r). -->
```
                <ngx-datatable-footer>
                  <ng-template ngx-datatable-footer-template let-rowCount="rowCount" let-pageSize="pageSize" let-selectedCount="selectedCount"
                    let-curPage="curPage" let-offset="offset">

                    <table>
                      <tbody>
                        <tr>
                          <td>
                            <input type='text' placeholder='Search field1' (keyup)='updateFilter("field1", $event)'
                            />
                          </td>
                          <td>
                            <input type='text' placeholder='Search field2' (keyup)='updateFilter("field2", $event)'
                            />
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    <div style="display:block">
 Hello world should be in another line
                    </div>
                  </ng-template>
                </ngx-datatable-footer>

```
> 

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->
For implementation of column filters
**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->
Windows 7, vcode, ng-cli
* **Table version:** 0.8.x
<!-- Check whether this is still an issue in the most recent table version -->
Latest
* **Angular version:** 2.0.x
<!-- Check whether this is still an issue in the most recent Angular version -->
Angular : 4x
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
<!-- All browsers where this could be reproduced -->
Browser Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4

**Comment by adammedford** [comment]
Try increasing your footerHeight as it is likely too small for your footer to fit properly. Either way, this seems like a styling issue specific to your custom template, not the datatable itself.

**Comment by amcdnl** [comment]
@adammedford is right. you need to update the row height and your style.
