### ISSUE TITLE
dynamic table height

### ISSUE THREAD

**Issue by penso89** [swimlane/ngx-datatable#875]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
table not getting height from outside

**Expected behavior**
table will get an height from outside and i we will can to control over table height

**Reproduction of the problem**
i have a table that should take over part of the page,

<header>
<some element>
<another some element>
<table>(want to take rest of page)
<footer>

i want only the table scroll ant not the all site scroll.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 9.3.x

* **Angular version:** 4.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by santialbo** [comment]
You can use something like https://github.com/wnr/element-resize-detector to detect resizes and update the height of the table.

**Comment by amcdnl** [comment]
Position absolute is also a solution. Or flexbox.

**Comment by BBaysinger** [comment]
@amcdnl, Do you have a link to the example of how to use absolute positioning to fix the table height?

**Comment by BBaysinger** [comment]
@santialbo, I ran an interval on my data table, setting bodyHeight every second to 100px. It didn't matter. Every time the table was reloaded with new rows, the table height expanded further by one row. Surely there has to be some way to keep this under control.
