### ISSUE TITLE
[rowClass] support in Angular 2

### ISSUE THREAD

**Issue by vaishaliT-optimus** [swimlane/ngx-datatable#878]
**Current behavior**
rowClass input is not available in 4.2.0

**Expected behavior**
Support for rowClass input in Angular 2.

**What is the motivation / use case for changing the behavior?**
can support for rowClass input be available with previous version of datatable (4.2.0) that support angular 2. Currently rowClass input is available in newer versions of datatable and newer version support only Angular 4
* **Table version:** 4.2.0

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
We do not support Angular2 anymore. Sorry.
