### ISSUE TITLE
(select) disable (dblclick) events.

### ISSUE THREAD

**Issue by gviligvili** [swimlane/ngx-datatable#884]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
If the (select)  emitter is active (on the ngx-datatable component),
and there is (dblclick) event on a field which suppose to trigger the inline edit,
the (dblclick) function won't emit. only the (select) will emit the funciton.

**Expected behavior**
the (select) and the (dblclick) event should both emit.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
to be able to select or **deselect** a row, and also inline edit.

**Please tell us about your environment:**

windows 10, webstorm, npm.

* **Table version:** 9.3.1

* **Angular version:** 4.0.0

* **Browser:**: chrome 59

* **Language:** TypeScript 2.3.3

code : 

```
 <ngx-datatable
          class="material"
          [rows]="rows"
          [columns]="columns"
          [columnMode]="'force'"
          [headerHeight]="50"
          [footerHeight]="50"
          [rowHeight]="50"
          [sorts]="[{prop: 'points', dir: 'desc'}]"
          [selected]="selectedRows"
          [selectionType]="'single'">
          <!--(select)="onSelect($event)">-->
          

          <!-- If in edit mode, use this costum editable column-->
          <ngx-datatable-column [prop]="'points'" name="xxxxxx">
            <ng-template ngx-datatable-cell-template let-value="value" let-row="row">
            <span
              title="Double click to edit"
              (dblclick)="editing[row['destination'] + '-points'] = true"
              *ngIf="!editing[row['destination'] + '-points']">
              {{value}}
            </span>
              <input
                autofocus
                (blur)="updatePoints($event, 'points', value, row)"
                *ngIf="editing[row['destination'] + '-points']"
                type="text"
                [value]="value"
              />
            </ng-template>
          </ngx-datatable-column>
          
        </ngx-datatable>
```

**Comment by amcdnl** [comment]
You need to handle this in your custom template. The inline editing demo is purely just a demo, not something we are planning to internalize. If you stoppropagation in your template, you can handle this.
