### ISSUE TITLE
Does it support Bootstrap CSS?

### ISSUE THREAD

**Issue by PHuhn** [swimlane/ngx-datatable#886]
**I'm submitting a ...**  (check one with "x")
```
[X] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
As I see it this supports Material CSS

**Expected behavior**
Does it support Bootstrap CSS?

**Reproduction of the problem**
no problem..

**What is the motivation / use case for changing the behavior?**
You indicate that you:
Decoupled theme'ing with included Google Material theme

**Please tell us about your environment:**
Angular4 CLI using Bootstrap4 and nb-bootstrap

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.4

**Comment by amcdnl** [comment]
No but you can easily style it that way with a custom theme.

**Comment by schematical** [comment]
Anyone have a theme they would like to share?

**Comment by asadsahi** [comment]
I have seen in change log there is a bootstrap theme to include, I have added css file and applied class="bootstrap" on the table. It styles like this:

![image](https://user-images.githubusercontent.com/3470892/32144901-f91f9256-bcb7-11e7-856c-bebe57598ec9.png)


Not sure if this is correct.

**Comment by nisi1973** [comment]
Any news about this? I see the same problem.
