### ISSUE TITLE
There is no index.css file when installing

### ISSUE THREAD

**Issue by AlexRex** [swimlane/ngx-datatable#895]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
There is no `index.css` file when installing in the release folder. So when importing it in my app the build fails.

**Expected behavior**
It should be this file.

**Reproduction of the problem**
Install the library and import the CSS files as the [documentation](https://swimlane.gitbooks.io/ngx-datatable/introduction/themes.html) says.

**Please tell us about your environment:**
OS X Sierra 10.12.3. 

**Table version:** 0.8.x
"@swimlane/ngx-datatable": "^10.0.1"

**Angular version:** 2.0.x
4.0.0

**Comment by amcdnl** [comment]
Can you post the error? I don't believe the index.css is needed anymore.

**Comment by AlexRex** [comment]
Yeah, is this one: 

```console
Module not found: Error: Can't resolve '@swimlane/ngx-datatable/release/index.css' in '/Users/aletormat/Dev/smartua/frontend/src/app/components/datatable'
```

**Comment by rostalevicek** [comment]
I have the same issue. Can you please update documentation if it is not needed anymore?

**Comment by wizarrc** [comment]
`index.css` should **not** be needed as the ngx-datatable project compiles the `datatable.component.scss` file and sets the global CSS support for you. See below or [here](https://github.com/swimlane/ngx-datatable/blob/master/src/components/datatable.component.ts#L92-L93):

datatable.component.ts
```
encapsulation: ViewEncapsulation.None,
styleUrls: ['./datatable.component.scss'],
```

and [here](https://github.com/swimlane/ngx-datatable/blob/master/config/webpack.common.js#L55-L72) where webpack supplies a scss loader:

webpack.common.js
```
          test: /\.scss$/,
          use: [
            { loader: 'to-string-loader' }, 
            { loader: 'css-loader' },
            { 
              loader:'postcss-loader',
              options: {
                sourceMap: true,
                plugins: [autoprefixer]
              }
            },
            { 
              loader: 'sass-loader',
              options: {
                sourceMap: true
              }
            }
          ]
```

**Comment by wizarrc** [comment]
@amcdnl I know it's not directly related but do you know if there is a way to apply user-supplied theming (css, scss, etc) without enabling global css support aka ViewEncapsulation.None? The css applied in the project is global and requires all class names to be super long to avoid collision.

**Comment by amcdnl** [comment]
@wizarrc - I've been playing with view encapsulation lately, Angular brought out a new ::deep operator that might enable this to be easier but haven't had a chance to play w/ it much yet.

**Comment by wizarrc** [comment]
hmm, interesting. Is that related to ::shadow and /deep/ that have been deprecated in chrome because they break encapsulation? I noticed they recently added ::deep to angular and was quite confused if it's a deprecated feature in browser land.

**Comment by amcdnl** [comment]
@wizarrc - see https://twitter.com/stephenfluin/status/892766742241353728

**Comment by wizarrc** [comment]
Thanks! Sounds like ::deep is good for the foreseeable future, at least until there is something better.

**Comment by amcdnl** [comment]
Can we close this given all the info above?

**Comment by wizarrc** [comment]
@amcdnl I think this [comment](https://github.com/swimlane/ngx-datatable/commit/5b748180deb2be49c77738344ffeb4d899eb346a#commitcomment-23482131) clears up the confusion. In the 10.0.0 release, the `index.css` file was (inadvertently?) physically removed from the release folder in the repo, but not removed from the docs.

Since it's actually a breaking change that is not mentioned in the `changelog.md` file. People upgrading versions, where they previously relied on `index.css` being imported, even though it is redundant and unnecessary, are broken by just doing an `npm` update.

Options:

- Add back `index.css` to the release folder. **(easy)**

- All mentions of `index.css` be removed from the docs and update `changelog.md` to include removal of `index.css` from the project with instructions that everyone should remove it from their project upon upgrading being that it's unnecessary. **(recommended)**

**Comment by wizarrc** [comment]
A side note: `themes.md` states: 

> Out of the box, the data-table is not styled.

That simply is not true anymore, as it has a default style that can be overridden. Looks like the docs in general might need some updating.

**Comment by amcdnl** [comment]
I added it back to help prevent breaking changes. Done in 10.0.2
