### ISSUE TITLE
Uncaught illegal access - LG G4 Stock Browser

### ISSUE THREAD

**Issue by feuse8** [swimlane/ngx-datatable#905]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Uncaught illegal access when opening app with ngx-datatable on LG G4. Application does not load anymore.

**Expected behavior**
Application should load normally.

**Reproduction of the problem**
I created an app including NGX-Datatable. When trying to load the app on an LG G4 with stock Browser an uncaught illegal access exception is thrown on line:
var pre = typeof styles !== 'undefined' ? (Array.prototype.slice.call(styles).join('').match(/(moz|webkit|ms)/))[1] : undefined

The method is part of src/utils/prefixes.ts

**Comment by amcdnl** [comment]
What browser platform is that based on?

**Comment by feuse8** [comment]
Hi,

https://whichbrowser.net/ shows

You are using LG Browser on a LG G4 running Android 6.0
Mozilla/5.0 (Linux; Android 6.0; LG-H815 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.2125.102 Mobile Safari/537.36

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
