### ISSUE TITLE
Support for mouseenter event for a row

### ISSUE THREAD

**Issue by szpetny** [swimlane/ngx-datatable#909]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Mouseenter event handler available on the entire table

**Expected behavior**
Mouseenter event handler available in body-row.component.
Something like:

  @HostListener('mouseenter', ['$event'])
  onMouseenter(event: Event) {
    this.activate.emit({
        type: 'mouseenter',
        event,
        row: this.row,
        rowElement: this.element
      });
  }

**Reproduction of the problem**
Adding (mouseenter)="method()" to ngx-datatable lets handle mouseenter for the entire table, I need to for example log sth every time a row is hovered with mouse. 

**What is the motivation / use case for changing the behavior?**
It would be useful to be able to customize behavior when hovering mouse over the table records. It is a quite common use case. 

**Please tell us about your environment:**
Windows7, node v7.2.1

* **Table version:**
10.0.5

* **Angular version:** 
4.3.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Sure. Can you PR this?

**Comment by szpetny** [comment]
yes

szpetny

14 sie 2017 16:18 "Austin" <notifications@github.com> napisał(a):

**Comment by amcdnl** [comment]
Merged.
