### ISSUE TITLE
After master changes for doCheck, table not updating right

### ISSUE THREAD

**Issue by Tempus35** [swimlane/ngx-datatable#910]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I have a table in which I add rows as the user interacts with the page, I tested the newest version to find the rows did not add, at least visually until I resized the browser etc.

**Expected behavior**
Upon changes to the table data that the table is re-rendered.

**Reproduction of the problem**
Have none I can share but it seems similar to this issue describe here: [907](https://github.com/swimlane/ngx-datatable/issues/907)

* **Table version:** Newest

* **Angular version:** 5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
I changed the change detection strategy to `onpush`. If you do what I suggest here, does it work? https://github.com/swimlane/ngx-datatable/blob/master/docs/introduction/cd.md

**Comment by Tempus35** [comment]
Closing this, at the moment it is working, since you have re-added the checking but even without that the method you described in the link would work.

**Comment by amcdnl** [comment]
Ya, I decided to add it back. I don't like it but I want the table to work for ppl naturally. Its give and take
