### ISSUE TITLE
rowDetail.collapseAllRows() does not update GUI 

### ISSUE THREAD

**Issue by MarcusCalidus** [swimlane/ngx-datatable#917]
**I'm submitting a ...**  
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
rowDetail.expandAllRows() and rowDetail.collapsAllRows() do not update the GUI. The details are displayed however after one scrolls or resizes the window.

**Expected behavior**
expansion or collapsing of the rows immediately after calling the method

**Reproduction of the problem**
the described behaviour happens with Chrome 60.0.3112.101  and @swimlane/ngx-datatable@10.0.5
It can be observed in the online demo too: http://swimlane.github.io/ngx-datatable/#

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
MacOS X 10.12.6
Chrome 60.0.3112.101
@swimlane/ngx-datatable@10.0.5
angular 4.3.5
typescript 2.4.2

**Comment by Tempus35** [comment]
Sounds like it is a similar issue to the one I am having here [910](https://github.com/swimlane/ngx-datatable/issues/910). I have a table were rows are added dynamically, they do not show up on the UI till you resize, right-click etc.

**Comment by on3al** [comment]
I am also seeing the same issue

**Comment by amcdnl** [comment]
Fixed in master. Release coming in next few days.
