### ISSUE TITLE
Visibility observer leak

### ISSUE THREAD

**Issue by QuentinFchx** [swimlane/ngx-datatable#930]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

If the visibility directive is destroyed in the same thread that created it, it will leak.
Because the `runCheck` method calls an inner function through `setTimeout` without registering/cleaning it ([here](https://github.com/swimlane/ngx-datatable/blob/master/src/directives/visibility.directive.ts#L60)).

(Bonus issue: [this file](https://github.com/swimlane/ngx-datatable/blob/master/src/utils/visibility-observer.ts) is unused)

**Expected behavior**

It should not leak.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.10.1

* **Angular version:** 4.3.6

* **Browser:** [all]

* **Language:** [all]

<sub>Edit: [Oh the irony](https://github.com/swimlane/ngx-datatable/commit/d6b1239f7454aab6bb37cc507374cd811f89a50e) :bowtie: </sub>

**Comment by QuentinFchx** [comment]
@amcdnl thank you for your review! I forgot to remove the unused file in the related PR 😕

**Comment by LHLK** [comment]
Might I ask how to use this <div visibilityObserver (visible)="onVisible($event)"></div> method in order to capture the last visible row-detail child ? 
Thanks...
