### ISSUE TITLE
Custom header checkbox remains checked when uncheck any row.

### ISSUE THREAD

**Issue by mishkolesnikov** [swimlane/ngx-datatable#935]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Using custom checkbox templates click "select all" checkbox in the datatable header, then uncheck any row. Header checkbox still appears as checked.

**Expected behavior**

Header checkbox must be unchecked when at least one row would be unchecked.

**Reproduction of the problem**

Can be reproduced in online demo: http://swimlane.github.io/ngx-datatable/#chkbox-selection-template. 

* **Table version:** >10.0.3

Appears in ngx-datatable higher then 10.0.3.
Problem placed right here: https://github.com/swimlane/ngx-datatable/blob/master/src/components/header/header-cell.component.ts#L149
Template gets context object just ones, and when some props shenges, allRowsSelected for instance, cellContex object remains the same.
I think step back to v10.0.3 implementation will solve the problem. Path needed properties directly to [ngTemplateOutletContext]. here: https://github.com/swimlane/ngx-datatable/blob/master/src/components/header/header-cell.component.ts#L34
```
        [ngTemplateOutletContext]="{
          column: column,
          sortDir: sortDir,
          sortFn: sortFn,
          allRowsSelected: allRowsSelected,
          selectFn: selectFn
        }">
```

**Comment by ReneeFeng** [comment]
Have you settled it yet? @mishkolesnikov

**Comment by mishkolesnikov** [comment]
Yes, using v10.0.3.
