### ISSUE TITLE
AOT build throws error in devtools

### ISSUE THREAD

**Issue by thomasschulze** [swimlane/ngx-datatable#936]
I'm submitting a

[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter

Current behavior:
After building an application with the basic example of ngx-datatable and with AOT Compiler, the datatable doesn't show up and the following error is thrown in chrome dev-tools:
"ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined".
In development mode and when building the application JIT everything works fine.

Expected behavior:
ngx-datatable is shown and works properly.

Table version: 9.3.1, 10.1.0

Angular version:  4.3.6

Browser: [ Chrome XX | Firefox XX | IE XX ]

**Comment by tinyweasel** [comment]
For me, I was using a pipe which momentarily was passing an undefined value as an async variable hadn't been loaded. I think.
