### ISSUE TITLE
Prop definition not reflecting 

### ISSUE THREAD

**Issue by ramkict** [swimlane/ngx-datatable#942]
I am working with angular 4 and ngx-table. I am trying to build a basic table. My data has all the key in title case. I have declared columns with name and prop too. But my table is empty. The total record shows the correct count. 

My data looks like this
[{Name:"carl", Gender: "Male"}]

Column def

cols = [{prop:"Name", name:"Name"},{prop:"Gender", name:"Gender"}]

Not sure what I am missing. Please help

Thank you.

**Comment by abdulnisarpalakkal** [comment]
Please use starting letter of prop as small
cols = [{prop:"name", name:"Name"},{prop:"gender", name:"Gender"}]
