### ISSUE TITLE
expanding detail in paged table broken after scrolling

### ISSUE THREAD

**Issue by MarcusCalidus** [swimlane/ngx-datatable#944]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Scrolling a paged table after expanding a row detail throws an exception in the console. The view is rendered unresponsive afterwards

**Reproduction of the problem**
http://swimlane.github.io/ngx-datatable/#
Go to Rows->Row Detail
Expand a row and try to scroll to the bottom

**What is the motivation / use case for changing the behavior?**

* **Table version:** 
10.2.0

* **Angular version:** 
4.3.6

* **Browser:** 
latest Chrome

* **Language:**
TypeScript 2.5.1

**Comment by amcdnl** [comment]
Fixed and released. thanks for letting us know.
