### ISSUE TITLE
$$index missing in row click

### ISSUE THREAD

**Issue by Matthi0uw** [swimlane/ngx-datatable#945]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
[Demo v9.3.1](http://plnkr.co/edit/RFclwzyhTJj0O4kfUoj9?p=preview): when I click on a row, it trigger onActivate function, in row there is a property $$index
[Demo v10.2.0](http://plnkr.co/edit/OBzsECJ7uPVUbRA2ZQCg?p=preview): when I click on a row, it trigger onActivate function without $$index.

**Expected behavior**
Where can I find $$index value ?

**What is the motivation / use case for changing the behavior?**
I use $$index with pagination on server side.

**Please tell us about your environment:**

* **Table version:** 10.2.0

* **Angular version:** 2.0.x

* **Browser:** [all]

* **Language:** [TypeScript@2.4.2]

**Comment by amcdnl** [comment]
This was removed because it was actually mutating the original object. See the changelog here - https://github.com/swimlane/ngx-datatable/blob/master/docs/changelog.md#1001

See this example on how to access the rowindex - https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/inline.component.ts#L25

**Comment by Matthi0uw** [comment]
Is there any accessor of index in `ngx-datatable` mark (having `(activate)="onActivate($event)"`) ?

**Comment by djpysu** [comment]
So: You still cannot access the `rowIndex` for `onSelect()` or `onActivate()`. I think this is real important,.
