### ISSUE TITLE
Is it possible to hide the column names?

### ISSUE THREAD

**Issue by limpep** [swimlane/ngx-datatable#946]
**Expected behavior**
Hi, I was wondering if it was possible to hide the column names?

* **Table version:** 0.8.x
10.1.0

* **Angular version:** 2.0.x
4.3.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.4.2

**Comment by amcdnl** [comment]
Yes, pass a empty string for the name.

**Comment by limpep** [comment]
@amcdnl thanks dude only issue is the header is still visible :)

**Comment by wizarrc** [comment]
@limpep Did you try hiding it with css?

**Comment by limpep** [comment]
@wizarrc makes sense lol, thanks.

**Comment by lautarobock** [comment]
Hide with css and using scroll makes the conten small than the container

**Comment by sumittokkar** [comment]
Set [headerHeight]="0". Works for me.

**Comment by cesargomezh** [comment]
> headerHeight

Works for me, thank you!
