### ISSUE TITLE
null row cell value (IE issue)

### ISSUE THREAD

**Issue by amit-kadam** [swimlane/ngx-datatable#951]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
If any row cell value is null, in IE it displays 'null' text. In Chrome it displays blank.

**Expected behavior**
If row cell value is null then it should not display 'null' text in IE.

**Reproduction of the problem**
Pass null data to rows

**What is the motivation / use case for changing the behavior?**
Better user experience.

**Please tell us about your environment:
Windows, VS Code, Apache

* **Table version:** 10.0.5

* **Angular version:** 4.1.3

* **Browser:** IE 11

* **Language:** TypeScript 2.2.1

**Comment by amit-kadam** [comment]
Hi,

Anyone looking into this?

**Comment by wizarrc** [comment]
@amit-kadam I ran into this a couple months ago. I believe it is an angular template bug. That said, I think there can be some kind of workaround.

**Comment by amit-kadam** [comment]
Thanks for the updates
