### ISSUE TITLE
Checkbox selection doesn't render the checkbox anymore

### ISSUE THREAD

**Issue by monica7l** [swimlane/ngx-datatable#952]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
The checkbox column is not rendered any more.

**Expected behavior**

**Reproduction of the problem**
This can be seen also on the demo page http://swimlane.github.io/ngx-datatable/#chkbox-selection

```
 <ngx-datatable #myTable1 class="material expandable" [columnMode]="'flex'" [rows]="rows" [columns]="columns" [headerHeight]="50"
        [footerHeight]="50" [rowHeight]="40" [limit]="15" [selectionType]="'checkbox'" [selected]="selected" style="font-size: 0.9em">
        <ngx-datatable-row-detail [rowHeight]="50">
          <ng-template let-row="row" ngx-datatable-row-detail-template>
            <div style="padding-left:35px;">
            </div>
          </ng-template>
        </ngx-datatable-row-detail>
```

After upgrading to the latest version of ngx-datatable, the checkbox is not rendered any more.

**Please tell us about your environment:**

* **Table version:** 
@swimlane/ngx-datatable": "^10.2.1

* **Angular version:** 
4.0.0

* **Browser:**
Chrome 60.0.3112.101, Firefox, IE 11

* **Language:** 
  "typescript": "~2.4"

**Comment by monica7l** [comment]
Fixed by setting
input[type='checkbox'] { display: block !important; }

**Comment by monica7l** [comment]
linked to https://github.com/swimlane/ngx-datatable/issues/943

**Comment by iamchiranjeevin** [comment]
issue still persists .. checkboxes are not visible in angular 15 ngx-datatable version 20.1.0
