### ISSUE TITLE
Data manipulation feature request

### ISSUE THREAD

**Issue by ShinDarth** [swimlane/ngx-datatable#955]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```
Is there a way to manipulate the data of a column? If there's not, would it be possible to implement this feature?

I mean for example, adding an icon near the text of each row in a certain column according to the text value.

For example to automatically change this:

| Col1  |  Col 2 |
| ------------- | ------------- |
| Info | some other text |
| Info | some other text |
| Error  | ome other text  |
| Error  | ome other text  |

to this:

| Col1  |  Col 2 |
| ------------- | ------------- |
| (a nice icon here) Info | some other text |
| (a nice icon here) Info | some other text |
| (an error icon here) Error  | ome other text  |
| (an error icon here) Error  | ome other text  |

**Comment by wizarrc** [comment]
@ShinDarth That feature should already be available to you. Take a look at [cell template](https://github.com/swimlane/ngx-datatable/blob/master/docs/api/column/inputs.md#celltemplate-templateref).

Modified from [demo example](https://github.com/swimlane/ngx-datatable/blob/master/demo/columns/column-standard.component.ts):
```
<ngx-datatable
        class="material"
        [rows]="rows"
        [columnMode]="'standard'"
        [headerHeight]="50"
        [footerHeight]="50"
        [rowHeight]="'auto'">
        <ngx-datatable-column name="Name" [width]="300">
          <ng-template let-value="value" ngx-datatable-cell-template>
            <!– Icon selector –>
            <img *ngIf="value === 'Info'" src="/path/info.gif" alt="warning" height="10" width="10">
            <img *ngIf="value === 'Error'" src="/path/error.gif" alt="error" height="10" width="10">
            {{value}}
          </ng-template>
        </ngx-datatable-column>
        <ngx-datatable-column name="Gender" [width]="300">
          <ng-template let-row="row" let-value="value" ngx-datatable-cell-template>
            {{value}}
          </ng-template>
        </ngx-datatable-column>
        <ngx-datatable-column name="Age" [width]="300">
          <ng-template let-value="value" ngx-datatable-cell-template>
            {{value}}
          </ng-template>
        </ngx-datatable-column>
      </ngx-datatable>
```

**Comment by ShinDarth** [comment]
@wizarrc thanks a lot, I wasn't able to find it in the documentation. Where did you find it?

**Comment by wizarrc** [comment]
@ShinDarth The demo is provided in the repo with many variations on things you can try out. Take a look at all you can do [http://swimlane.github.io/ngx-datatable/](http://swimlane.github.io/ngx-datatable/)

**Comment by ShinDarth** [comment]
@wizarrc yes I was checking that. I think ngx-datatable is a great tool, but the documentation can be improved. I hope to have the chance to contribute to this nice project!
