### ISSUE TITLE
ngx-datatable + ng-tab having issue in tooltip view

### ISSUE THREAD

**Issue by Muzaeed** [swimlane/ngx-datatable#959]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Tooltip is displaying inside the ng-datable (datatable-body)

![screen1](https://user-images.githubusercontent.com/17058984/30120528-b67ed0d2-9346-11e7-9a27-55d048dac9ff.png)

![screen2](https://user-images.githubusercontent.com/17058984/30120632-0a5c46a8-9347-11e7-9b07-43b2fa756120.png)

**Expected behavior**
Tooltip should populate on top of table since  I have given higher z-index & additon to this the solution which got to the problem 
md-tab-group,
md-tab-body,
.mat-tab-body-wrapper,
.mat-tab-body-content
{
    overflow: visible !important;
}

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Since the table is inside md-tab it may be causing some problem.....!

**Please tell us about your environment:**
@angular/cli: 1.1.1
node: 7.10.0
os: linux x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1

* **Table version:** 0.8.x
"@swimlane/ngx-datatable": "^9.3.0"

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google Chrome
Version 58.0.3029.110 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by wizarrc** [comment]
@Muzaeed This happens because the tooltip is inside the datatable template, specifically where the overflow is set to scroll. Can add the tooltip template outside the datatable, possibly in an overlay? You would have to figure out where the row is offset yourself though.

**Comment by wizarrc** [comment]
Although it may break in the future, in the [DataTableBodyComponent](https://github.com/swimlane/ngx-datatable/blob/master/src/components/body/body.component.ts) there are 3 internal features you can use. **WARNING** This may break in any future release.

1. [DataTableBodyComponent] `getRowIndex` - If you need to figure out the row index and have access to the row object.
2. [DataTableBodyComponent] `rowHeightCache` - Call `bodyComponent.rowHeightsCache.query(idx - 1);` where `idx` is the row index.
3. [DataTableBodyComponent] `offsetY` - If you need to know the current scroll position to offset.
4. [DatatableComponent] `headerHeight` - table header height
5. Subtract 3 from the 2 and you should have your row height relative to the table's body.
6. Add 4 and 5 and that should be the offset relative to top of the data table.
7. Add overlay and adjust offset depending where overlay starts.

**Comment by Muzaeed** [comment]
Thanks a lot @wizarrc, I have added the tooltip outside ng-datatable. It's appearing on top of the table.Thanks once agin.....! :-)

**Comment by hellsm83** [comment]
@Muzaeed can you show us an example of your code? it would be helpful for other people who are at the beginning with angular2/4 and ngx-datatable

**Comment by bozzwin** [comment]
@Muzaeed Could you share with your solution??

**Comment by francisminu** [comment]
Hey!
@Muzaeed Could you please please show a plunker of how it was done. Have been checking this feature for a couple of days now. 
Thanks!

**Comment by Muzaeed** [comment]
Place the tooltip outside the ngx-data table. I have given the custom css for tooltip to come in one place, by makig it's position absolute.
