### ISSUE TITLE
Fixable Columns

### ISSUE THREAD

**Issue by Taree7734** [swimlane/ngx-datatable#962]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Currently all Columns collapse when I use horizontal scrolling.

**Expected behavior**
I want to fix one or maybe multiple columns on the left side of the table. 
i.e. the name of a dataset shown in the row. Horizontal scrolling should be available for the rest of the columns (scrollbar starting at the second column).

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
I have a set of huge data (>40 columns) where I want to see which entry belongs to a specific name

**Please tell us about your environment:**

* **Table version:** 10.2.1

* **Angular version:** 4.3.0

* **Browser:** all

* **Language:** all

**Comment by wizarrc** [comment]
@Taree7734 column pinning is available already, although it's not documented. Take a look at this [example](https://github.com/swimlane/ngx-datatable/blob/master/demo/columns/pinning.component.ts) and [demo](http://swimlane.github.io/ngx-datatable/#pinning)

@amcdnl docs could be added to:
https://github.com/swimlane/ngx-datatable/blob/master/docs/api/column/inputs.md
```
frozenLeft?: boolean;
frozenRight?: boolean;
```

**Comment by Taree7734** [comment]
@wizarrc thanks!
That is just what I was seraching for.
