### ISSUE TITLE
Dynamic client-side pagination does not work if count is not set

### ISSUE THREAD

**Issue by ShinDarth** [swimlane/ngx-datatable#963]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

Assuming that my Component class has a `limit` property which holds a number representing the amount of rows that I want to display (as a limit per page). This value can change.

**Current behavior**
If I set only: `[limit]="limit"` then the pagination will not work.

If I set: `[limit]="limit"` **and** `[count]="limit"` then the pagination **will work as expected** (so `limit` rows per page).

**Expected behavior**
`[count]` is supposed to be `The total count of all rows.` so I don't understand why I need to bind it to `limit` instead of the total amount of rows.

* **Table version:** `^10.2.1`

* **Angular version:** `^4.3.6"`

**Comment by wizarrc** [comment]
@ShinDarth Do you have [external paging](https://github.com/swimlane/ngx-datatable/blob/master/docs/api/table/inputs.md#externalpaging) turned on? External paging requires count to be set.

**Comment by wizarrc** [comment]
@ShinDarth Also, do you have [scrollbarV](https://github.com/swimlane/ngx-datatable/blob/master/docs/api/table/inputs.md#scrollbarv) set to true?

**Comment by ShinDarth** [comment]
@wizarrc I don't have `externalPaging` set. As I said, this is about client-side paging. Now that you mentioned, I tested also the server side rendering and that is not affected by this bug.

I haven't set `scrollbarV` so I'm using its default value.

**Comment by wizarrc** [comment]
@ShinDarth I can't reproduce it. http://plnkr.co/edit/2X96Y1PJKAJM3lolcy2s?p=preview

Can you show me how it doesn't work?

**Comment by ShinDarth** [comment]
in my case I assign [limit] to a variable that the user can change instead of a fixed number, just that

**Comment by wizarrc** [comment]
I am able to reproduce the problem and updated the [link](http://plnkr.co/edit/2X96Y1PJKAJM3lolcy2s?p=preview)

This is a bug for sure!

![limit](https://user-images.githubusercontent.com/8039397/30179427-59e93e72-93da-11e7-8a25-79d1f9a33e19.gif)

**Comment by wizarrc** [comment]
@ShinDarth Found the bug in the code, submitted PR, now we wait. 😀 Cheers!

**Comment by amcdnl** [comment]
Accepted and published :)

**Comment by ShinDarth** [comment]
@wizarrc @amcdnl thanks a lot!

**Comment by wizarrc** [comment]
That was quick!
