### ISSUE TITLE
Debug output in body-group-header.directive.ts

### ISSUE THREAD

**Issue by BrummbQ** [swimlane/ngx-datatable#972]
https://github.com/swimlane/ngx-datatable/blob/78aa2ab5154608a41de5d83b5ce8502a9024bbc1/src/components/body/body-group-header.directive.ts#L26

You might wanna remove it :)

**Comment by wizarrc** [comment]
@BrummbQ go ahead, you can edit a page directly in GitHub, and get credit!

**Comment by wizarrc** [comment]
https://github.com/swimlane/ngx-datatable/edit/master/src/components/body/body-group-header.directive.ts
