### ISSUE TITLE
multi select shift+click with scrollbarV bug

### ISSUE THREAD

**Issue by nickhellmich** [swimlane/ngx-datatable#974]
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter

**Current behavior**
Select a row, hold shift, scroll any distance and select another row.  Only a portion of the rows between the start row and the end row will be selected. 

**Expected behavior**
User can select a row, scroll down, shift+click another row to select all rows in between.

**Reproduction of the problem**
http://plnkr.co/edit/PuSafdl37rV5PPDe1SPm

**What is the motivation / use case for changing the behavior?**
Improve behavior of component.

**Please tell us about your environment:**
Windows

* **Table version:** 0.8.x
Current

* **Angular version:** 2.0.x
4

* **Browser:** 
Any

* **Language:** 
TypeScript

**Comment by wizarrc** [comment]
@nickhellmich selection state is only saved on the current view at this time. If you need everything to be selected, you can turn off virtual scrolling. This is clearly not the user's expectations and would call this a bug.

**Comment by wizarrc** [comment]
@amcdnl I believe to fix this would result in a breaking change as currently the onActivate event, that the selection component uses, outputs the view index and anyone relying on that number would get something they did not expect. I'm not really sure why it's outputting the view index in the first place.

**Comment by nickhellmich** [comment]
@amcdnl @wizarrc  I am running my project locally against that latest merge and the issue still exists. I can't figure out how to point the plunker to the current master branch to update my example.

**Comment by wizarrc** [comment]
@nickhellmich mhm, not seeing it at the moment, Ill see if I can recreate it when I get a chance

**Comment by kapanilas** [comment]
@amcdnl @wizarrc even i am facing the same issue. 

**Current behavior**
Select a row, hold shift, scroll any distance and select another row. Only a the rows on the view will be selected.

**Expected behavior**
User can select a row, scroll down, shift+click another row to select all rows in between.
