### ISSUE TITLE
Dynamic pagination does not work if the limit is changed and the active page is not the first

### ISSUE THREAD

**Issue by ShinDarth** [swimlane/ngx-datatable#978]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```
This bug affects both client-side and server-side pagination, I've tested on both.

**Current behavior**
If you change the `[limit]` of items per page when you are at page `1` then it works fine, but if you do the same action while being in the last page and set a higher `[limit]` then it will not work and an empty table will be shown just empty.

**Expected behavior**
The limit of the items per page should always work, regardless of which page you are currently.

**Reproduction of the problem**
Using this plunker:

http://plnkr.co/edit/2X96Y1PJKAJM3lolcy2s?p=preview

- select the limit of 5 items per page
- go to the last page (page 20)
- select the limit of 10 items per page

then the table will be empty, which is a bug.

* **Table version:** 0.8.x
10.2.3

* **Angular version:** 2.0.x
4.3.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.4.1

**Comment by ShinDarth** [comment]
@wizarrc can you take a look at this?

**Comment by wizarrc** [comment]
@ShinDarth That's cause the `offset` is too high for a higher limit, therefore showing empty.

**Comment by ShinDarth** [comment]
@amcdnl @wizarrc thanks a lot!
