### ISSUE TITLE
Set Column Fixed

### ISSUE THREAD

**Issue by nssantos** [swimlane/ngx-datatable#991]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

**Expected behavior**
The expected behavior is like its codepen: https://codepen.io/siremilomir/pen/reQRoa/

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
I'd like to have a config column, where its head will be a config button, and  when I scroll horizontally, the fixed column still remains on screen.

**Please tell us about your environment:**

* **Table version:** 0.8.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by wizarrc** [comment]
@nssantos column pinning is what you are looking for.

Demo:
http://swimlane.github.io/ngx-datatable/#pinning

Docs:
[frozenLeft](https://github.com/swimlane/ngx-datatable/blob/master/docs/api/column/inputs.md#frozenleft-boolean)
[frozenRight](https://github.com/swimlane/ngx-datatable/blob/master/docs/api/column/inputs.md#frozenright-boolean)
