### ISSUE TITLE
Table crashes when pipe returns undefined

### ISSUE THREAD

**Issue by olaf89** [swimlane/ngx-datatable#996]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Error is thrown and table is crashed.

**Expected behavior**
It does not throw error and does not crash.

**Reproduction of the problem**
When pipe returns undefined

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
npm 5.4

* **Table version:** 
Latest

* **Angular version:**
4.4.1

* **Browser:** Chrome XX 

* **Language:** TypeScript

**Comment by wizarrc** [comment]
@olaf89 hmm, are you referring to the [pipe](https://github.com/swimlane/ngx-datatable/blob/master/docs/api/column/inputs.md#pipe-pipetransform) transforms set in the column property? Also, do pipes that return undefined not throw in Angular templates? I think the pipe property set in columns should match the same behavior.

**Comment by olaf89** [comment]
Yes, i am referring to pipes on the template definition. I don't believe pipe in angular template would throw error. If it would i'm sure i would have noticed it more then once by now ;)

**Comment by olaf89** [comment]
Here is plunkr, uncomment pipe in column definition to see it fails http://plnkr.co/edit/HvNhrgc4Bc80Kdqh8w01?p=preview

**Comment by wizarrc** [comment]
@olaf89 Thanks for showing a demo verifying the functionality in the Angular code. The problem occurs when trying to sanitize user input. I created a PR making a case to not sanitize when there is nothing to sanitize.
